### ISSUE TITLE
Numeric values not allowed in output file names?

### ISSUE THREAD

**Issue by pinin4fjords** [nextflow-io/nextflow#1044]
### Expected behavior and actual behavior

Expect that it's possible to define output file names with numeric values based on e.g. different paramerisations. In fact this fails with errors like:

```
ERROR ~ Error executing process > 'test_to_tsv (1)'

Caused by:
  Nul character not allowed: test_1.tsv


 -- Check '.nextflow.log' file for details
```

### Steps to reproduce the problem

Create a dummy test file like: 

```
touch test1.csv
```

Make a workflow like:

```
TEST = Channel.fromPath( "test*.csv" )

process extract_number {

    input:
        file csvFile from TEST

    output:
        set stdout, file (csvFile) into TEST_BY_NUM

    """
       echo $csvFile | grep -o -E '[0-9]+' | tr '\\n' '\\0' 
    """
}

process test_to_tsv {

    publishDir "/nfs/production3/ma/home/jmanning/projects/scxa_worflows", mode: 'move', overwrite: true

    input:
        set val(num), file(csvFile) from TEST_BY_NUM

    output:
        set val(num), file ("test_${num}.tsv") into FINAL

    """
    cat $csvFile | sed 's/,/\t/g' > test_${num}.tsv
    """
}
```

... and execute like:

```
nextflow run test.nf
```

### Program output 

Output is:

```
N E X T F L O W  ~  version 19.01.0
Launching `test.nf` [furious_wiles] - revision: b7888bc3fc
[warm up] executor > lsf
[10/b86ba0] Submitted process > extract_number (1)
[fa/4608de] Submitted process > test_to_tsv (1)
ERROR ~ Error executing process > 'test_to_tsv (1)'

Caused by:
  Nul character not allowed: test_1.tsv


 -- Check '.nextflow.log' file for details
```

Log content is:

```
Feb-22 13:13:15.077 [main] DEBUG nextflow.cli.Launcher - $> nextflow run test.nf
Feb-22 13:13:17.677 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.01.0
Feb-22 13:13:17.778 [main] INFO  nextflow.cli.CmdRun - Launching `test.nf` [furious_wiles] - revision: b7888bc3fc
Feb-22 13:13:17.879 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/nextflow.config
Feb-22 13:13:17.880 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/nextflow.config
Feb-22 13:13:18.385 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Feb-22 13:13:22.673 [main] DEBUG nextflow.Session - Session uuid: 4c5661e2-57be-462c-9ba4-d16341f569e6
Feb-22 13:13:22.674 [main] DEBUG nextflow.Session - Run name: furious_wiles
Feb-22 13:13:22.675 [main] DEBUG nextflow.Session - Executor pool size: 32
Feb-22 13:13:22.887 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.01.0 build 5050
  Modified: 22-01-2019 11:19 UTC (11:19 BST)
  System: Linux 3.10.0-514.16.1.el7.x86_64
  Runtime: Groovy 2.5.5 on OpenJDK 64-Bit Server VM 10.0.2+13
  Encoding: UTF-8 (UTF-8)
  Process: 35914@ebi-cli-003.ebi.ac.uk [10.7.37.137]
  CPUs: 32 - Mem: 125.7 GB (1 GB) - Swap: 4 GB (3.7 GB)
Feb-22 13:13:23.178 [main] DEBUG nextflow.Session - Work-dir: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/work [nfs]
Feb-22 13:13:23.178 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/bin
Feb-22 13:13:24.085 [main] DEBUG nextflow.Session - Session start invoked
Feb-22 13:13:24.090 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Feb-22 13:13:24.090 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Feb-22 13:13:25.879 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Feb-22 13:13:26.181 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: ./; pattern: test*.csv; options: [:]
Feb-22 13:13:27.174 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: lsf
Feb-22 13:13:27.175 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'lsf'
Feb-22 13:13:27.185 [main] DEBUG nextflow.executor.Executor - Initializing executor: lsf
Feb-22 13:13:27.187 [main] INFO  nextflow.executor.Executor - [warm up] executor > lsf
Feb-22 13:13:27.279 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'lsf' > capacity: 500; pollInterval: 5s; dumpInterval: 5m 
Feb-22 13:13:27.282 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: TaskPollingMonitor
Feb-22 13:13:27.282 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: lsf)
Feb-22 13:13:27.374 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: lsf
Feb-22 13:13:27.375 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'lsf' > queue-stat-interval: 1m
Feb-22 13:13:27.779 [main] DEBUG nextflow.Session - >>> barrier register (process: extract_number)
Feb-22 13:13:27.782 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > extract_number -- maxForks: 32
Feb-22 13:13:28.574 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: lsf
Feb-22 13:13:28.574 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'lsf'
Feb-22 13:13:28.574 [main] DEBUG nextflow.executor.Executor - Initializing executor: lsf
Feb-22 13:13:28.574 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'lsf' > queue-stat-interval: 1m
Feb-22 13:13:28.576 [main] DEBUG nextflow.Session - >>> barrier register (process: test_to_tsv)
Feb-22 13:13:28.576 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > test_to_tsv -- maxForks: 32
Feb-22 13:13:28.577 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Feb-22 13:13:28.577 [main] DEBUG nextflow.Session - Session await
Feb-22 13:13:31.189 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [LSF] submitted process extract_number (1) > jobId: 1901035; workDir: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/work/10/b86ba047b858ade6193ac6dca11fb4
Feb-22 13:13:31.274 [Task submitter] INFO  nextflow.Session - [10/b86ba0] Submitted process > extract_number (1)
Feb-22 13:13:32.395 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 1901035; id: 1; name: extract_number (1); status: COMPLETED; exit: 0; error: -; workDir: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/work/10/b86ba047b858ade6193ac6dca11fb4 started: 1550841212385; exited: 2019-02-22T13:13:31.758749Z; ]
Feb-22 13:13:32.425 [Actor Thread 5] DEBUG nextflow.Session - <<< barrier arrive (process: extract_number)
Feb-22 13:13:32.888 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [LSF] submitted process test_to_tsv (1) > jobId: 1901040; workDir: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/work/fa/4608de51bde3e0783d6ebcddb3d279
Feb-22 13:13:32.888 [Task submitter] INFO  nextflow.Session - [fa/4608de] Submitted process > test_to_tsv (1)
Feb-22 13:13:37.388 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 1901040; id: 2; name: test_to_tsv (1); status: COMPLETED; exit: 0; error: -; workDir: /nfs/production3/ma/home/jmanning/projects/scxa_worflows/work/fa/4608de51bde3e0783d6ebcddb3d279 started: 1550841217381; exited: 2019-02-22T13:13:33.646166Z; ]
Feb-22 13:13:37.399 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'test_to_tsv (1)'

Caused by:
  Nul character not allowed: test_1.tsv

java.nio.file.InvalidPathException: Nul character not allowed: test_1.tsv
	at java.base/sun.nio.fs.UnixPath.checkNotNul(UnixPath.java:91)
	at java.base/sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:81)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:280)
	at java.base/java.nio.file.Path.resolve(Path.java:402)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:74)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at nextflow.processor.TaskProcessor.collectOutFiles(TaskProcessor.groovy:1373)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:167)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:192)
	at nextflow.processor.TaskProcessor.collectOutputs(TaskProcessor.groovy:1314)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:192)
	at nextflow.processor.TaskProcessor.collectOutputs(TaskProcessor.groovy:1295)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at nextflow.processor.TaskProcessor.finalizeTask(TaskProcessor.groovy:1992)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:619)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:539)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:418)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:302)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:492)
	at java.base/java.lang.Thread.run(Thread.java:844)
Feb-22 13:13:37.414 [Actor Thread 5] DEBUG nextflow.Session - <<< barrier arrive (process: test_to_tsv)
Feb-22 13:13:37.414 [main] DEBUG nextflow.Session - Session await > all process finished
Feb-22 13:13:37.472 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Nul character not allowed: test_1.tsv
Feb-22 13:13:37.574 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-22 13:13:37.574 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: lsf)
Feb-22 13:13:37.580 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=1; failedCount=1; ignoredCount=0; cachedCount=0; succeedDuration=6ms; failedDuration=7ms; cachedDuration=0ms]
Feb-22 13:13:37.593 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Feb-22 13:13:38.075 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow version: 19.01.0
* Java version: openjdk 10.0.2 2018-07-17
* Operating system: Linux

**Comment by pditommaso** [comment]
I'm not able to replicate this issue. Could  you provide a self-contained example that I can download and run?

**Comment by pinin4fjords** [comment]
Here you go: https://github.com/ebi-gene-expression-group/nextflow_test

```
nextflow run ebi-gene-expression-group/nextflow_test
```

Hope I'm not being an idiot....

**Comment by pditommaso** [comment]
ummmmmmmmh ... in the log file I've just seen this .. 

<img width="854" alt="Screenshot 2019-03-13 at 15 33 28" src="https://user-images.githubusercontent.com/816968/54287139-681a8680-45a5-11e9-962e-2e052bfcd1cb.png">

**Comment by pditommaso** [comment]
```
tr '\\n' '\\0'  
``` 

?

**Comment by pditommaso** [comment]
to summarise, there's a zero character un the stdout of the first task, which that when used to create a file name handle causes the Java API to complain (can't do much on that). 

Cleaning up the stdout as shown below, solves the problem: 

```
    input:
        set val(num), file(csvFile) from TEST_BY_NUM.map { num, file-> [num.trim(), file] }
```

**Comment by pinin4fjords** [comment]
Just getting rid of newline in the STDOUT. Both processes seem to work, test_1.tsv is produced successfully.

**Comment by pinin4fjords** [comment]
Ahh, okay, thanks for the solution

**Comment by pditommaso** [comment]
But that does not *remove* the newline, replaces it with a `0x0` character ..

**Comment by pinin4fjords** [comment]
Gotcha- sorry for the idiocy

**Comment by pditommaso** [comment]
😂
