### ISSUE TITLE
Multiple channel input exception reports a misleading channel name

### ISSUE THREAD

**Issue by lebernstein** [nextflow-io/nextflow#1079]
### Expected behavior and actual behavior

**Expected:**
value channel should be able to be used as many times as desired in multiple processes.

**Actual:**
ERROR ~ Channel `sampleName` has been used twice as an input by process `3A_samtools_sort` and process `2A_samtools_view`

### Steps to reproduce the problem

**Workflow Script File (main.nf)**
```
reference      = "hg19-chr7m-22m"
sampleFile     = "test.samples"
samtools   	   = "samtools"
bwaFlags   	   = "bwa7 mem -t 3"
alignQualityCutoff = "30"
 
ref_file     = file(reference + ".fasta")
ref_file_amb = file(reference + ".fasta.amb")
ref_file_ann = file(reference + ".fasta.ann")
ref_file_bwt = file(reference + ".fasta.bwt")
ref_file_dct = file(reference + ".dict")
ref_file_idx = file(reference + ".fasta.fai")
ref_file_pac = file(reference + ".fasta.pac")
ref_file_sa  = file(reference + ".fasta.sa")

Channel
    .fromPath(sampleFile)
    .splitCsv(header:true)
    .map{ row-> tuple(row.sampleName, row.groupId, file(row.forward), file(row.reverse)) }
    .set { input_fasta_ch }

//------------------------------------------------------------
process '1A_bwa_align' {

  input:
    file referenceFile from ref_file
    file referenceFileAmb from ref_file_amb
    file referenceFileAnn from ref_file_ann
    file referenceFileBwt from ref_file_bwt
    file referenceFilePac from ref_file_pac
    file referenceFileSa from ref_file_sa

    set sampleName, groupId, file(forward), file(reverse) from input_fasta_ch

  output:
    file "${sampleName}.Aligned.sam" into aligned_sam_ch
    val sampleName into sample_name_ch
    val groupId into group_id_ch
    
  script:
  """
      ${bwaFlags}       \
      ${referenceFile} 	\
      ${forward}        \
      ${reverse}        \
      1> "${sampleName}".Aligned.sam
  """
}

process '2A_samtools_view' {

  input:
    val sampleName from sample_name_ch
    file inFile from aligned_sam_ch

  output:
    file "${sampleName}.Q${alignQualityCutoff}.bam" into filtered_bam_ch

  script:
	"""
    ${samtools} view 				    \
      -bh 						          \
      -q ${alignQualityCutoff}	\
      -F 0x04 					        \
      ${inFile} 					      \
      1> ${sampleName}.Q${alignQualityCutoff}.bam
	"""
}

process '3A_samtools_sort' {

  input:
    val sampleName from sample_name_ch
    file fileBam from filtered_bam_ch

  output:
    file "${sampleName}.sorted.bam" into sorted_bam_ch

  script:
	"""
    ${samtools} sort					      \
      -T ${sampleName}				      \
      -o "${sampleName}.sorted.bam" \
      ${fileBam}
	"""
}
```

**Input File (test.samples)**
```
sampleName,groupId,forward,reverse
XXX,YYY,XXX_YYY_R1_001.fastq.gz,XXX_YYY_R1_001.fastq.gz
```
### Program output 

ERROR ~ Channel `sampleName` has been used twice as an input by process `3A_samtools_sort` and process `2A_samtools_view`

 -- Check script 'main4.nf' at line: 70 or see '.nextflow.log' file for more details

**Log File (.nextflow.log)**
```
Mar-15 17:10:05.220 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main4.nf
Mar-15 17:10:05.652 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.01.0
Mar-15 17:10:05.667 [main] INFO  nextflow.cli.CmdRun - Launching `main4.nf` [magical_wiles] - revision: 6b841ae6f9
Mar-15 17:10:05.768 [main] DEBUG nextflow.Session - Session uuid: e5c359c1-c56c-4c1d-b1e6-e10d9f442b56
Mar-15 17:10:05.768 [main] DEBUG nextflow.Session - Run name: magical_wiles
Mar-15 17:10:05.771 [main] DEBUG nextflow.Session - Executor pool size: 32
Mar-15 17:10:05.852 [main] DEBUG nextflow.cli.CmdRun -
  Version: 19.01.0 build 5050
  Modified: 22-01-2019 11:19 UTC
  System: Linux 3.10.0-957.1.3.el7.x86_64
  Runtime: Groovy 2.5.5 on OpenJDK 64-Bit Server VM 1.8.0_191-b12
  Encoding: UTF-8 (UTF-8)
  Process: 44526@sjlsd0019.us.qdx.com [10.72.165.134]
  CPUs: 32 - Mem: 125.7 GB (11.3 GB) - Swap: 4 GB (2.7 GB)
Mar-15 17:10:05.928 [main] DEBUG nextflow.Session - Work-dir: /home/laurence.e.bernstein/nextflow/work [xfs]
Mar-15 17:10:05.929 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/laurence.e.bernstein/nextflow/bin
Mar-15 17:10:06.182 [main] DEBUG nextflow.Session - Session start invoked
Mar-15 17:10:06.192 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Mar-15 17:10:06.193 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Mar-15 17:10:06.749 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Mar-15 17:10:07.064 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Mar-15 17:10:07.064 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-15 17:10:07.070 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-15 17:10:07.073 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Mar-15 17:10:07.081 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=32; memory=125.7 GB; capacity=32; pollInterval=100ms
; dumpInterval=5m
Mar-15 17:10:07.085 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Mar-15 17:10:07.087 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Mar-15 17:10:07.088 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Mar-15 17:10:07.147 [main] DEBUG nextflow.Session - >>> barrier register (process: 1A_bwa_align)
Mar-15 17:10:07.152 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > 1A_bwa_align -- maxForks: 32
Mar-15 17:10:07.182 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Mar-15 17:10:07.183 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-15 17:10:07.183 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-15 17:10:07.184 [main] DEBUG nextflow.Session - >>> barrier register (process: 2A_samtools_view)
Mar-15 17:10:07.184 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > 2A_samtools_view -- maxForks: 32
Mar-15 17:10:07.190 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Mar-15 17:10:07.190 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-15 17:10:07.190 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-15 17:10:07.191 [main] DEBUG nextflow.Session - >>> barrier register (process: 3A_samtools_sort)
Mar-15 17:10:07.191 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > 3A_samtools_sort -- maxForks: 32
Mar-15 17:10:07.197 [main] DEBUG nextflow.Session - Session aborted -- Cause: Channel `sampleName` has been used twice as an input by process `3A_samtools_sort` and process `2
A_samtools_view`
Mar-15 17:10:07.234 [main] DEBUG nextflow.Session - The following nodes are still active:
[process] 1A_bwa_align
  status=ACTIVE
  port 0: (value) bound ; channel: referenceFile
  port 1: (value) bound ; channel: referenceFileAmb
  port 2: (value) bound ; channel: referenceFileAnn
  port 3: (value) bound ; channel: referenceFileBwt
  port 4: (value) bound ; channel: referenceFilePac
  port 5: (value) bound ; channel: referenceFileSa
  port 6: (queue) closed; channel: -
  port 7: (cntrl) -     ; channel: $

[process] 2A_samtools_view
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: sampleName
  port 1: (queue) OPEN  ; channel: inFile
  port 2: (cntrl) -     ; channel: $

Mar-15 17:10:07.238 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Mar-15 17:10:07.241 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.dag.MultipleInputChannelException: Channel `sampleName` has been used twice as an input by process `3A_samtools_sort` and process `2A_samtools_view`
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:265)
        at nextflow.dag.DAG.inbound(DAG.groovy:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at nextflow.dag.DAG$_addVertex_closure1.doCall(DAG.groovy:129)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:427)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
        at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:89)
        at nextflow.dag.DAG.addVertex(DAG.groovy:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at nextflow.dag.DAG.addProcessNode(DAG.groovy:87)
        at nextflow.dag.NodeMarker.addProcessNode(NodeMarker.groovy:50)
        at nextflow.dag.NodeMarker$addProcessNode$1.call(Unknown Source)
        at nextflow.processor.TaskProcessor.createOperator(TaskProcessor.groovy:484)
        at nextflow.processor.TaskProcessor.run(TaskProcessor.groovy:382)
        at nextflow.processor.TaskProcessor$run.call(Unknown Source)
        at nextflow.script.BaseScript.process(BaseScript.groovy:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at _nf_script_964e9e97.run(_nf_script_964e9e97:70)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:382)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:170)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:240)
        at nextflow.cli.Launcher.run(Launcher.groovy:445)
        at nextflow.cli.Launcher.main(Launcher.groovy:622)
```

### Environment 

* Nextflow version: nextflow-19.01.0-all 
* Java version:  1.8.0_191-b12
* Operating system: Red Hat Linux 7.6

**Comment by pditommaso** [comment]
The error message is misleading it should report `sample_name_ch` not `sampleName`. 

However the `sample_name_ch` cannot as input both in `2A_samtools_view` and `3A_samtools_sort`.

ps. this restriction will be removed in upcoming version.

**Comment by haqle314** [comment]
Not sure if you're aware already or not but the error message is also misleading when using DSL 2. Given the workflow file like this
~~~nextflow
nextflow.preview.dsl = 2

process producer {
	output: stdout()
	shell: "echo Hello"
}

process consumer {
	input: file "foo"
	output: stdout()
	shell:
	"rev foo"
}

process another_consumer {
	input: file "foo"
	output: stdout()
	shell: "wc -w foo"
}

producer | consumer | view
producer | another_consumer | view
~~~
The error message says ```Process `producer` declares 1 input channel but 0 were specified```

**Comment by pditommaso** [comment]
@haqle314 this looks a different problem, could you please open a separate issue for it?

**Comment by pditommaso** [comment]
Solved. Also the use `path` instead of `file` allow the use of `:` in output file names. See https://www.nextflow.io/docs/edge/process.html#output-path.
