### ISSUE TITLE
Nextflow won't start if a proxy URL env variable contains a trailing slash 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#109]
When proxy environment variable contains a trailing slash like the following: 

    HTTP_PROXY=http://proxy.crg.es:8881/

Capsule will throw the exception shown below:

    CAPSULE EXCEPTION: For input string: "8881/" while processing attribute Allow-Snapshots: false
    java.lang.NumberFormatException: For input string: "8881/"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at capsule.SystemProxySelector.addProxyFromEnv(SystemProxySelector.java:99)
        at capsule.SystemProxySelector.init(SystemProxySelector.java:68)
        at capsule.SystemProxySelector.<init>(SystemProxySelector.java:56)
        at capsule.SystemProxySelector.<init>(SystemProxySelector.java:48)
        at capsule.DependencyManager.newRepositorySession(DependencyManager.java:202)
        at capsule.DependencyManager.getSession(DependencyManager.java:186)
        at capsule.DependencyManager.setRepos(DependencyManager.java:134)
        at MavenCapsule.setDependencyRepositories(MavenCapsule.java:267)
        at MavenCapsule.initDependencyManager(MavenCapsule.java:247)
        at MavenCapsule.getDependencyManager(MavenCapsule.java:237)
        at MavenCapsule.resolve0(MavenCapsule.java:211)
        at Capsule.resolve(Capsule.java:3356)
        at Capsule.resolve(Capsule.java:3370)
        at Capsule.buildJavaProcess(Capsule.java:2214)
        at Capsule.buildProcess0(Capsule.java:1519)
        at Capsule.buildProcess(Capsule.java:1510)
        at Capsule.buildProcess(Capsule.java:1510)
        at Capsule.buildProcess(Capsule.java:1510)
        at Capsule.prelaunch0(Capsule.java:1483)
        at Capsule.prelaunch(Capsule.java:1476)
        at CapsuleLoader.prelaunch(CapsuleLoader.java:45)
        at Capsule.prepareForLaunch(Capsule.java:1329)
        at Capsule.launch(Capsule.java:1258)
        at Capsule.main0(Capsule.java:394)
        at Capsule.main(Capsule.java:374)

**Comment by pditommaso** [comment]
This error is related to https://github.com/puniverse/capsule-maven/issues/10
