### ISSUE TITLE
make compile fails behind proxy

### ISSUE THREAD

**Issue by sb10** [nextflow-io/nextflow#1093]
### Expected behavior and actual behavior

`make compile` should download gradle and complete compilation. Presumably because I'm behind a proxy, I get a connection time out instead.

### Steps to reproduce the problem

```
export JAVA_HOME=/path/to/jdk1.8.0_60
make compile
```

### Program output 

```
Downloading https://services.gradle.org/distributions/gradle-4.10-all.zip

Exception in thread "main" java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:200)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1123)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
make: *** [compile] Error 1
```

### Environment 

* Nextflow version: commit 07c564a0ac7f62673f921b7706f0d867c1ea5a7b
* Java version: 1.8.0_60
* Operating system: Linux

### Additional context

`wget https://services.gradle.org/distributions/gradle-4.10-all.zip` works fine, going via my proxy.

I tried:

```
./gradlew -Dhttp.proxyHost=http://myproxyaddress -Dhttp.proxyPort=3128 -Dhttps.proxyHost=http://myproxyaddress -Dhttps.proxyPort=3128 compile exportClasspath
```

Which also times out. I also tried creating files `gradle.properties` and `gradle-wrapper.properties` with content:

```
#http proxy setup
systemProp.http.proxyHost=http://myproxyaddress
systemProp.http.proxyPort=3128
systemProp.http.nonProxyHosts=localhost

#https proxy setup
systemProp.https.proxyHost=http://myproxyaddress
systemProp.https.proxyPort=3128
systemProp.https.nonProxyHosts=localhost
```

But it still times out. Anything else I can try?

**Comment by pditommaso** [comment]
Weird, what if you use the _JAVA_OPTIONS var, eg: 

```
export _JAVA_OPTIONS='-Dhttp.proxyHost=http://myproxyaddress -Dhttp.proxyPort=3128 -Dhttps.proxyHost=http://myproxyaddress -Dhttps.proxyPort=3128'
make compile
```

**Comment by sb10** [comment]
It reports that it picks those options up, but still times out.

I manually installed latest gradle (v5.3.1) without problem; is there a way to get Nextflow to use that instead of trying to download its own gradle?

**Comment by pditommaso** [comment]
That's controlled by the [gradle-wrapper](https://github.com/nextflow-io/nextflow/blob/master/gradle/wrapper/gradle-wrapper.properties) file

**Comment by sb10** [comment]
I wasn't able to resolve this on the machine with the proxy, so have moved to a different machine with no proxy, which can compile without problems.
