### ISSUE TITLE
Support for Minio s3

### ISSUE THREAD

**Issue by Snapple49** [nextflow-io/nextflow#1103]
## New feature

Hey there, getting started with NextFlow and I've run into a caveat with s3. If I understand correctly, the support for reading from s3 sources requires them to be hosted on AWS, but I would like to be able to connect to buckets hosted on other s3 services such as Minio.

## Usage scenario 

One reason supporting Minio would be great is that it's an easy way to set up on-premise storage for example with local NFS setups, especially for running kubernetes clusters on your own servers. In my case we have this setup, and I wish to run NextFlow in kubernetes and to be able to easily share data from our NFS. Being able to connect to Minio buckets would make this a piece of cake.

## Suggest implementation 

Unfortunately I don't know a lot about S3 in general and how different it is to connect to generic S3 servers rather than amazon, but I feel like just providing the endpoint/bucket url and the access/secret keys should be enough. For example, Pachyderm allows setting up S3 in their helm chart with these options:

- S3 access key
- S3 secret key
- S3 bucket name
- S3 endpoint
- S3 secure
- S3 signature

I tried just creating an aws part in the nextflow config as in the documentation, 
```
aws {
  accessKey = '<Your AWS access key>'
  secretKey = '<Your AWS secret key>'
}
```
, and then providing the url to a bucket in our minio server (which is reachable from anywhere), but this resulted in the following error:
`ERROR ~ Unable to execute HTTP request: <url to bucket>.s3.amazonaws.com`

So I'm assuming some modifications would be needed to support non-amazon s3 targets

**Comment by pditommaso** [comment]
Minio *should* alredy be supported using a custom end-point. See [config setting](https://www.nextflow.io/docs/latest/config.html#config-aws) for details.

**Comment by Snapple49** [comment]
Thanks for pointing this out! I must have overlooked that section, sorry for opening this as a feature request in that case!

However, I have been trying to set it up with the custom end-point all day and I cannot get it to work, no matter what I try. I can connect to the server and bucket with the mc client from Minio so I think the endpoint itself is valid, but I keep getting one of the following errors:

`com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null; S3 Extended Request ID: null)`

or when trying with a glob pattern (`s3://<bucket-name>/*.txt`):

`java.lang.IllegalArgumentException: Key cannot be empty`

Should I open a different issue for help with this seeing as it is probably not a feature request anymore?

**Comment by pditommaso** [comment]
I fear you need to specify at least one directory level other the bucket name.

**Comment by pditommaso** [comment]
> Unfortunately I still cannot get it to work

Please report the complete error message, even better the relative `.nextflow.log` file.

**Comment by Snapple49** [comment]
Here is the .nextflow.log file content, I just ommit the s3 credentials and endpoint:

```
Apr-15 13:29:03.841 [main] DEBUG nextflow.cli.Launcher - $> nextflow run kensert.nf
Apr-15 13:29:04.028 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.01.0
Apr-15 13:29:04.047 [main] INFO  nextflow.cli.CmdRun - Launching `kensert.nf` [astonishing_kalam] - revision: 46863a52c9
Apr-15 13:29:04.090 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/farmbio/pharmbio/nextflow/nextflow-testing/nextflow.config
Apr-15 13:29:04.092 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/farmbio/pharmbio/nextflow/nextflow-testing/nextflow.config
Apr-15 13:29:04.126 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Apr-15 13:29:04.700 [main] DEBUG nextflow.Session - Session uuid: 77392e1e-326a-44b2-aefe-f677c3c5a076
Apr-15 13:29:04.700 [main] DEBUG nextflow.Session - Run name: astonishing_kalam
Apr-15 13:29:04.701 [main] DEBUG nextflow.Session - Executor pool size: 4
Apr-15 13:29:04.713 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.01.0 build 5050
  Modified: 22-01-2019 11:19 UTC (12:19 CEST)
  System: Linux 4.15.0-47-generic
  Runtime: Groovy 2.5.5 on OpenJDK 64-Bit Server VM 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12
  Encoding: UTF-8 (UTF-8)
  Process: 15026@elitebook-1030 [130.243.211.12]
  CPUs: 4 - Mem: 15.5 GB (5.7 GB) - Swap: 2 GB (2 GB)
Apr-15 13:29:04.751 [main] DEBUG nextflow.Session - Work-dir: /home/farmbio/pharmbio/nextflow/nextflow-testing/work [ext2/ext3]
Apr-15 13:29:04.752 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/farmbio/pharmbio/nextflow/nextflow-testing/bin
Apr-15 13:29:04.891 [main] DEBUG nextflow.Session - Session start invoked
Apr-15 13:29:04.896 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Apr-15 13:29:04.898 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Apr-15 13:29:05.092 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-15 13:29:05.262 [PathVisitor-1] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Apr-15 13:29:05.303 [PathVisitor-1] DEBUG nextflow.Global - Using AWS credential defined in `default` section in file: /home/farmbio/.aws/credentials
Apr-15 13:29:05.307 [PathVisitor-1] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=<key>, endpoint=<endpoint url>, protocol=HTTP, access_key=<key>}
Apr-15 13:29:05.388 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Apr-15 13:29:05.389 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Apr-15 13:29:05.402 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Apr-15 13:29:05.413 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Apr-15 13:29:05.423 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=4; memory=15.5 GB; capacity=4; pollInterval=100ms; dumpInterval=5m
Apr-15 13:29:05.432 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Apr-15 13:29:05.435 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Apr-15 13:29:05.464 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Apr-15 13:29:05.555 [main] DEBUG nextflow.Session - >>> barrier register (process: kensert_stage1)
Apr-15 13:29:05.572 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > kensert_stage1 -- maxForks: 4
Apr-15 13:29:05.662 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Apr-15 13:29:05.664 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Apr-15 13:29:05.666 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Apr-15 13:29:05.670 [main] DEBUG nextflow.Session - >>> barrier register (process: kensert_stage2)
Apr-15 13:29:05.672 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > kensert_stage2 -- maxForks: 4
Apr-15 13:29:05.692 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Apr-15 13:29:05.693 [main] DEBUG nextflow.Session - Session await
Apr-15 13:29:05.878 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /nextflow/images/; pattern: *.png; options: [:]
Apr-15 13:29:05.884 [PathVisitor-1] DEBUG nextflow.file.FileHelper - Path matcher not defined by 'S3FileSystem' file system -- using default default strategy
Apr-15 13:29:06.005 [PathVisitor-1] ERROR nextflow.Channel - Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null; S3 Extended Request ID: null)
com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null; S3 Extended Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4646)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:870)
	at com.upplication.s3fs.AmazonS3Client.listObjects(AmazonS3Client.java:104)
	at com.upplication.s3fs.util.S3ObjectSummaryLookup.lookup(S3ObjectSummaryLookup.java:117)
	at com.upplication.s3fs.S3FileSystemProvider.readAttributes(S3FileSystemProvider.java:643)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at nextflow.file.FileHelper.visitFiles(FileHelper.groovy:729)
	at nextflow.file.PathVisitor.pathImpl(PathVisitor.groovy:140)
	at nextflow.file.PathVisitor.applyGlobPattern0(PathVisitor.groovy:108)
	at nextflow.file.PathVisitor.apply(PathVisitor.groovy:68)
	at nextflow.file.PathVisitor$_applyAsync_closure1.doCall(PathVisitor.groovy:74)
	at nextflow.file.PathVisitor$_applyAsync_closure1.call(PathVisitor.groovy)
	at groovy.lang.Closure.run(Closure.java:492)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Apr-15 13:29:06.015 [PathVisitor-1] DEBUG nextflow.Session - Session aborted -- Cause: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null; S3 Extended Request ID: null)
Apr-15 13:29:06.031 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: kensert_stage1)
Apr-15 13:29:06.035 [Actor Thread 3] DEBUG nextflow.Session - <<< barrier arrive (process: kensert_stage2)
Apr-15 13:29:06.036 [main] DEBUG nextflow.Session - Session await > all process finished
Apr-15 13:29:06.051 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Apr-15 13:29:06.052 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-15 13:29:06.061 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms]
Apr-15 13:29:06.073 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Apr-15 13:29:06.078 [main] DEBUG nextflow.Session - AWS S3 uploader shutdown
Apr-15 13:29:06.116 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

Thanks for looking into it!

**Comment by pditommaso** [comment]
Check if setting the `signerOverride` help as described [here](https://github.com/nextflow-io/nextflow-s3fs/issues/13#issuecomment-465544334).

**Comment by pditommaso** [comment]
The [Minio docs](https://docs.min.io/docs/how-to-use-aws-sdk-for-java-with-minio-server.html) suggests setting`clientConfiguration.setSignerOverride("AWSS3V4SignerType")` .

**Comment by Snapple49** [comment]
Thanks, I tried adding that and also the ones suggested [here](https://github.com/elastic/elasticsearch-cloud-aws/issues/223), but it's always exactly the same error and trace as above...

**Comment by pditommaso** [comment]
Need to investigate why it's not working, but with low priority.

**Comment by pditommaso** [comment]
Closing this issue because I'm not able to replicate the issue. I've managed to connect a (local) minio instance with this nextflow.config setting: 

```
aws {
  accessKey = '<your key>'
  secretKey = '<your secret>'
  client {
     endpoint = "127.0.0.1:9000"
     protocol = 'http'
  }
}
```

**Comment by stevekm** [comment]
Note that after implementing the AWS configs shown there, I had to use a URL in the format of `s3://bucket_name/file.txt`

**Comment by jkh1** [comment]
It looks like this may only work if the minio server has enabled virtual host-style URLs (i.e. https://bucket_name.endpoint/object). Trying with a minio server that only has the default path-style URLs (i.e. https://endpoint/bucket_name/object), I get:
 `Unable to execute HTTP request: bucket_name.endpoint`
which looks like nextflow is using virtual host style by default.
Have I missed a config parameter that enables minio path-style URLs or is this not supported?

**Comment by satriobio** [comment]
try this config @jkh1 

```
aws {
    accessKey='<ACCESS>'
    secretKey='<SECRET>'
    client {
        s3PathStyleAccess = true
        endpoint = '<DOMAIN>'
        protocol = 'https'
    }
}
```
