### ISSUE TITLE
Execution of multiqc succeeds locally, but not with AWS Batch

### ISSUE THREAD

**Issue by rspreafico-vir** [nextflow-io/nextflow#1109]
## Bug report 

Executing the same RNA-seq pipeline locally (in an EC2 instance) or with AWS Batch has different behavior for multiqc.

Only in AWS Batch:

```
[0b/51b8fd] process > multiqc                     [100%] 1 of 1, failed: 1 ✔
[0b/51b8fd] NOTE: Process `multiqc` terminated for an unknown reason -- Likely it has been terminated by the external system -- Error is ignored
```

### Expected behavior and actual behavior

Expected same output from local and AWS Batch execution. I should point out that all the other tasks beautifully complete both locally and in AWS Batch.

### Steps to reproduce the problem

First, this issue should not be related to:
- the multiqc container. `ewels/multiqc:1.7` has both `bash` and `ps`, and indeed it runs fine locally.
- the size of the secondary EBS volume in the custom AMI used by AWS Batch. This has been expanded already, and indeed it handles jobs (such as STAR) that are much more storage-demanding than MultiQC.

### Program output 

MultiQC gets called this way:

```
logs = (fastqc.output | flatten()) | concat(
        trimmomatic.output[1] | flatten(),
        salmon_quant.output[1] | flatten(),
        star_align.output[2] | flatten(),
        picard_collectrnaseqmetrics.output | flatten(),
        rseqc_junction.output | flatten(),
        rseqc_bamstat.output | flatten(),
        rseqc_duplication.output | flatten()
    ) | toSortedList()

multiqc(logs)
```

The process looks like this:

```
nextflow.preview.dsl=2

containerTag = '1.7'

process multiqc {
    container 'ewels/multiqc:' + containerTag
    errorStrategy 'ignore'
    maxRetries 3
    maxErrors '-1'
    cpus 1
    memory 2.GB

    input:
    file('qc_in/sub??????/*')
    
    output:
    file('multiqc*')

    script:

    """
    multiqc \
    --interactive \
    --verbose \
    --data-dir \
    -f qc_in
    """
}
```

When executing using Batch, only two files are found in the work folder: `.command.sh` and `.command.run`. The input (`qc_in` folder) is not even staged. The log looks like this:

```
Apr-08 09:44:59.121 [AWSBatch-executor-222] INFO  nextflow.Session - [0b/51b8fd] Submitted process > multiqc
Apr-08 09:45:47.638 [Task monitor] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] Cannot read exitstatus for task: `multiqc`
java.nio.file.NoSuchFileException: /vir-nf-batch/work/0b/51b8fd75eb9c2db0dde8bdb9fb54fd/.exitcode
        at com.upplication.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:275)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at java.nio.file.Files.newBufferedReader(Files.java:2784)
        at org.codehaus.groovy.runtime.NioGroovyMethods.newReader(NioGroovyMethods.java:1400)
        at org.codehaus.groovy.runtime.NioGroovyMethods.getText(NioGroovyMethods.java:393)
        at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1859)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3797)
        at groovy.lang.DelegatingMetaClass.getProperty(DelegatingMetaClass.java:126)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:195)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassGetPropertySite.callGetProperty(PojoMetaClassGetPropertySite.java:44)
        at nextflow.cloud.aws.batch.AwsBatchTaskHandler.readExitFile(AwsBatchTaskHandler.groovy:240)
        at nextflow.cloud.aws.batch.AwsBatchTaskHandler.checkIfCompleted(AwsBatchTaskHandler.groovy:229)
        at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:601)
        at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:528)
        at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:407)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
        at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:291)
        at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.lang.Thread.run(Thread.java:745)
Apr-08 09:45:47.638 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 28; name: multiqc; status: COMPLETED; exit: -; error: -; workDir: s3://vir-nf-batch/work/0b/51b8fd75eb9c2db0dde8bdb9fb54fd]
Apr-08 09:45:47.642 [Task monitor] INFO  nextflow.processor.TaskProcessor - [0b/51b8fd] NOTE: Process `multiqc` terminated for an unknown reason -- Likely it has been terminated by the external system -- Error is ignored
```

There is also this error a little down, but I believe this is unrelated to this issue:

```
Apr-08 09:45:47.696 [main] WARN  nextflow.script.WorkflowMetadata - Failed to deliver notification email -- See the log file for details
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at nextflow.script.ExecutionStack.current(ExecutionStack.groovy:33)
        at nextflow.script.ExecutionStack.context(ExecutionStack.groovy:45)
        at nextflow.script.ExecutionStack$context$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at nextflow.NF.getBinding(NF.groovy:44)
        at nextflow.script.WorkflowMetadata.safeMailNotification(WorkflowMetadata.groovy:423)
        at nextflow.script.WorkflowMetadata.invokeOnComplete(WorkflowMetadata.groovy:377)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
        at nextflow.script.WorkflowMetadata$_closure3.doCall(WorkflowMetadata.groovy:233)
        at nextflow.script.WorkflowMetadata$_closure3.call(WorkflowMetadata.groovy)
        at nextflow.Session.shutdown0(Session.groovy:735)
        at nextflow.Session.destroy(Session.groovy:687)
        at nextflow.script.ScriptRunner.terminate(ScriptRunner.groovy:299)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:134)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:246)
        at nextflow.cli.Launcher.run(Launcher.groovy:449)
        at nextflow.cli.Launcher.main(Launcher.groovy:626)
```

### Environment 

* Nextflow version: 19.0.0.modules-draft10-SNAPSHOT (Modules work AWESOMELY!!!!)
* Java version:  1.8.0_201-b09
* Operating system: Executing from macOS laptop. The custom AMI is based on the ECS-optimized Linux AMI.

### Additional context

Not sure if this could be a concern, but some of the `file` inputs to MultiQC are whole folders (e.g. the Salmon output, due to the way the MultiQC Salmon parser works). It shouldn't matter, and indeed other tasks using whole folders as `file` input (such as Salmon and STAR indexes, which are folders) do not run into any issue.

**Comment by pditommaso** [comment]
Could you test this with the latest snapshot?

**Comment by pditommaso** [comment]
Closing this, because I'm nto able to replicate it. Feel free to reopen/comment below if needed.
