### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.SubList

### ISSUE THREAD

**Issue by lindenb** [nextflow-io/nextflow#1140]
## Bug report 

NF says: 
`Unable to resume cached task -- See log file for details

the log file contains:

```
May-03 17:16:31.466 [Actor Thread 41] WARN  nextflow.processor.TaskProcessor - [combineGVCFs0 (combine0 16 g.vcf / chr5)] Unable to resume cached task -- See log fil
e for details
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.SubList
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1228)
	at nextflow.util.InstantiationStrategy.newInstantiatorOf(SerializationHelper.groovy:266)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1049)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1058)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.create(CollectionSerializer.java:89)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:93)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:22)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:143)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:21)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.Kryo$readClassAndObject$5.call(Unknown Source)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:180)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy)
	at nextflow.util.KryoHelper$deserialize$0.call(Unknown Source)
	at nextflow.processor.TaskContext.deserialize(TaskContext.groovy:187)
	at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:162)
	at nextflow.CacheDB$getTaskEntry$1.call(Unknown Source)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:810)
	at nextflow.processor.TaskProcessor$checkCachedOutput$5.callCurrent(Unknown Source)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:695)
	at sun.reflect.GeneratedMethodAccessor339.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

the 'cached' file would have been created in **combineGVCFs0** using the following channel transformation:

This a set of GATK Combine GVCF : I've got 500 GVCF that I group per chromosomes (all_contigs is a file containing the chromosomes) and per group of params.combinegvcf_size=100 . 

```
	set contig,gvcfs from all_contigs.
			splitCsv(header: false,sep:'\t',strip:true).
			map{T->T[0]}.
                        combine(
			  all_gvcfs.
			    splitCsv(header: false,sep:'\t',strip:true).
			    map{T->T[0]}.
			    collate(params.combinegvcf_size)
                            ).map{T->[T[0],T.subList(1,T.size())]}

```

what I want : a chromosome and a list of gvcf

```
chr1,[1.gvf,2.gvcf,3.gvcf]
chr1,[4.gvf,5.gvcf,6.gvcf]
chr1,[7.gvcf]
chr2,[1.gvf,2.gvcf,3.gvcf]
chr2,[4.gvf,5.gvcf,6.gvcf]
chr2,[7.gvcf]
chr3,[1.gvf,2.gvcf,3.gvcf]
chr3,[4.gvf,5.gvcf,6.gvcf]
chr3,[7.gvcf]
```

the next process **combineGVCFs** collects all the GVCF chunks per chromosome:

```
input:
	set contig,gvcfs from combinegvcf0.groupTuple()
```

### Environment 

* Nextflow version:  custom  19.04.0
* Java version: 8
* Operating system: linux

**Comment by pditommaso** [comment]
Ugly, that `subList` returns its own List implementation. A simple workaround is to replace `T.subList(1,T.size())` with `T[1..-1]` (where `-1` stands for last element).

**Comment by lindenb** [comment]
got it, thanks Paolo !
