### ISSUE TITLE
Add support for other s3 providers than amazon

### ISSUE THREAD

**Issue by lukasjelonek** [nextflow-io/nextflow#116]
I have some data on a s3 compatible data provider and would like to access it directly from nextflow. Unfortunately it does not work via 

`file('s3://mys3provider.org/my_bucket/my_file')`

as the internal library tries to authenticate against the AWS service:

> java.io.IOException: Cannot access file: /mys3provider.org/my_bucket/my_file
>         at com.upplication.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:270)
>         at java.nio.file.Files.newInputStream(Files.java:108)
>         at java.nio.file.Files.newBufferedReader(Files.java:2677)
>         at org.codehaus.groovy.runtime.NioGroovyMethods.newReader(NioGroovyMethods.java:1306)
>         at org.codehaus.groovy.runtime.NioGroovyMethods.getText(NioGroovyMethods.java:422)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
>         at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1847)
>         at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3737)
>         at groovy.lang.DelegatingMetaClass.getProperty(DelegatingMetaClass.java:130)
>         at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:177)
>         at org.codehaus.groovy.runtime.callsite.PojoMetaClassGetPropertySite.getProperty(PojoMetaClassGetPropertySite.java:36)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
>         at s3test.run(s3test.nf:5)
>         at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:304)
>         at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:154)
>         at nextflow.cli.CmdRun.run(CmdRun.groovy:195)
>         at nextflow.cli.Launcher.run(Launcher.groovy:380)
>         at nextflow.cli.Launcher.main(Launcher.groovy:529)
> Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records.
>         at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:679)
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:350)
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:202)
>         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3037)
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:955)
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:845)
>         at com.upplication.s3fs.AmazonS3Client.getObject(AmazonS3Client.java:80)
>         at com.upplication.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:259)
>         ... 23 common frames omitted
> 

Will it be possible to add support for other s3 compatible storage solutions, either by configuring it in the nextflow config or by supplying the approriate URI?

**Comment by pditommaso** [comment]
I've added a configuration property that allows one to set a custom API endpoint. You will need to define in your `nextflow.config` file the attribute `aws.client.endpoint`. For example: 

    aws.accessKey = 'xxx'
    aws.secretKey = 'xxx'
    aws.client.endpoint = 'abc' 

This is feature is included in a snapshot version that I've just uploaded. To use your will need to launching having defined in our environment the variable `NXF_VER=0.17.4-SNAPSHOT`. For example: 

    NXF_VER=0.17.4-SNAPSHOT nextflow run ...

**Comment by pditommaso** [comment]
This is related to https://github.com/nextflow-io/nextflow-s3fs/issues/5

**Comment by lukasjelonek** [comment]
Thanks for the quick fix. Unfortunately our S3 provider does not seem to be 100% compatible with AWS. The authentication does not seem to work. 

`Mar-30 09:42:20.442 [main] ERROR nextflow.cli.Launcher - @unknown
java.io.IOException: Cannot access file: /lj_test/test.dat
        at com.upplication.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:274)
        at java.nio.file.Files.newInputStream(Files.java:108)
        at java.nio.file.Files.newBufferedReader(Files.java:2677)
        at org.codehaus.groovy.runtime.NioGroovyMethods.newReader(NioGroovyMethods.java:1306)
        at org.codehaus.groovy.runtime.NioGroovyMethods.getText(NioGroovyMethods.java:422)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1847)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3737)
        at groovy.lang.DelegatingMetaClass.getProperty(DelegatingMetaClass.java:130)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:177)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassGetPropertySite.getProperty(PojoMetaClassGetPropertySite.java:36)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
        at _nf_script_1b265d61.run($nf_script_1b265d61:3)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:315)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:155)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:195)
        at nextflow.cli.Launcher.run(Launcher.groovy:380)
        at nextflow.cli.Launcher.main(Launcher.groovy:529)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1073)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:721)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3658)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1133)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1005)
        at com.upplication.s3fs.AmazonS3Client.getObject(AmazonS3Client.java:90)
        at com.upplication.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:263)
        ... 23 common frames omitted
`

I also tried connecting by hand with the aws-java-sdk-s3 library and got the same errors as with nextflow. Using the apache jclouds library I can connect with the s3-provider, but not with the aws-s3 provider.

The next step for me is to check with the administrators if it will be possible to use the same authentication as with amazon.

**Comment by pditommaso** [comment]
OK. I will suggest to investigate the problem on your side using the `aws-java-sdk-s3` library. If you manage to have it working, please comment here or reopen this issue. Tx.
