### ISSUE TITLE
Cannot load File from nextflow.config for parsing JSON

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1160]
## Bug report 

Nextflow gives an error when trying to load a file in order to parse JSON when invoked from the `nextflow.config` file

### Steps to reproduce the problem

example JSON:

```
$ cat config.json
{
    "key1": "foo",
    "key2": "bar",
    "key4": null,
    "key5": true
}
```

It works when you try to load a JSON file from the Nextflow script:

`main.nf`: 

```
log.info('main.nf is running')

import groovy.json.JsonSlurper
def jsonSlurper = new JsonSlurper()

params.configFile = "config.json"
String configJSON = new File("${params.configFile}").text
def config = jsonSlurper.parseText(configJSON)
log.info("${config}")
```

output:

```
$ ./nextflow run main.nf
N E X T F L O W  ~  version 19.04.1
Launching `main.nf` [infallible_stallman] - revision: c7630cd40b
main.nf is running
[key1:foo, key2:bar, key4:null, key5:true]
```

However if you try to do the same from within the config file it gives an error: 

`nextflow.config`:

```
import groovy.json.JsonSlurper
def jsonSlurper = new JsonSlurper()

params.configFile = "config.json"
String configJSON = new File("${params.configFile}").text
def config = jsonSlurper.parseText(configJSON)
```

output:

```
$ ./nextflow run main.nf
N E X T F L O W  ~  version 19.04.1
Launching `main.nf` [berserk_goldberg] - revision: 1311cb241c
ERROR ~ Unable to parse config file: '/Users/kellys04/projects/nextflow-demos/parse-JSON/nextflow.config'

  Cannot cast object 'config.json' with class 'java.lang.String' to class 'java.net.URL'


 -- Check '.nextflow.log' file for details
```

log contents:

```
$ cat .nextflow.log
May-24 12:15:35.004 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
May-24 12:15:35.116 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.04.1
May-24 12:15:35.124 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [berserk_goldberg] - revision: 1311cb241c
May-24 12:15:35.139 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Users/kellys04/projects/nextflow-demos/parse-JSON/nextflow.config
May-24 12:15:35.140 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/kellys04/projects/nextflow-demos/parse-JSON/nextflow.config
May-24 12:15:35.175 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
May-24 12:15:35.630 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '/Users/kellys04/projects/nextflow-demos/parse-JSON/nextflow.config'

  Cannot cast object 'config.json' with class 'java.lang.String' to class 'java.net.URL'

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'config.json' with class 'java.lang.String' to class 'java.net.URL'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:414)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:328)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:242)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2744)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3809)
	at groovy.lang.GroovyObjectSupport.setProperty(GroovyObjectSupport.java:40)
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:213)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496)
	at _nf_config_6011b9e6.run(_nf_config_6011b9e6:4)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at org.codehaus.groovy.reflection.CachedMethod$invoke.call(Unknown Source)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:403)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:431)
	at nextflow.config.ConfigParser$parse$3.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:292)
	at nextflow.config.ConfigParser$parse$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at nextflow.config.ConfigBuilder.parse0(ConfigBuilder.groovy:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:366)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:633)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:646)
	at nextflow.script.ScriptRunner.<init>(ScriptRunner.groovy:121)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:228)
	at nextflow.cli.Launcher.run(Launcher.groovy:453)
	at nextflow.cli.Launcher.main(Launcher.groovy:630)
```

### Environment 

* Nextflow version: 19.04.1
* Java version:`java version "1.8.0_151"`
* Operating system: macOS 10.12.6, RHEL 7

### Additional context

(Add any other context about the problem here)

**Comment by stevekm** [comment]
so it turns out that `params.configFile` is a reserved variable name when used in `nextflow.config` (but not in `main.nf`), when I changed the variable to `params.configJSON`everything worked normally.
