### ISSUE TITLE
Unable to resume when passing custom groovy objects through channels

### ISSUE THREAD

**Issue by bahnk** [nextflow-io/nextflow#1252]
Hi all,

This is my first question here. So, first, I would like to thank Paolo and the nextflow community for the amazing job they are doing.

My question is about the `-lib` option we can use in order to pass custom libraries to nextflow. I use it to pass groovy objects to the processes. It works fine but for some reason nextflow is unable to resume processes involving those custom objects.

Let's say I want to create a custom `Fastq` object. I create a file `mypackage/Fastq.gy` which contains:

```groovy
package mypackage

import groovy.transform.EqualsAndHashCode

@EqualsAndHashCode(includeFields=true)
class Fastq {

	String path
	String label

	Fastq(String path, String label) {
		this.path = path
		this.label = label
	}

	String getPath() {
		return this.path
	}

	String getLabel() {
		return this.label
	}
}
```
Then I compile this code and create a `mypackage.jar` file this way:

```make
CC = groovyc
ARCH = jar
OPT = cvf
SRC = src
PACKAGE = mypackage

.PHONY: .FORCE
.FORCE:

all: jar

jar: .FORCE $(PACKAGE)/Fastq.class
	$(ARCH) $(OPT) $(PACKAGE).jar $(PACKAGE)

$(PACKAGE)/Fastq.class: .FORCE
	$(CC) -d . $(PACKAGE)/Fastq.gy
```
Here is an example `main.nf` script that just echo the path of the `Fastq` in a file:

```nextflow
import mypackage.Fastq

fastq1 = new Fastq("/path/one", "one")
fastq2 = new Fastq("/path/two", "two")
fastq3 = new Fastq("/path/two", "two")

c = Channel.from(fastq1, fastq2)

process test {

	publishDir "output"

	input:
		val f from c

	output:
		set val(f), file("*.txt") into files

	shell:

		p = f.getPath()

		"""
		echo ${f.getPath()} > ${f.getLabel()}.txt
		"""
}
```

Finally, I run nextflow this way:

```bash
#!/bin/sh

# comment this if you are not using a module system
module load Nextflow/0.32.0

nextflow run main.nf -lib mypackage.jar -resume
```
The nextflow code works fine and nextflow does understand the custom object. However, nextflow is unable to resume, and I get this:

```console
N E X T F L O W  ~  version 0.32.0
Launching `main.nf` [desperate_fermat] - revision: 8efd610501
[warm up] executor > local
WARN: [test (2)] Unable to resume cached task -- See log file for details
WARN: [test (1)] Unable to resume cached task -- See log file for details
[8c/157f95] Submitted process > test (2)
[db/a2f0de] Submitted process > test (1)
```
Do you guys have any idea about what I'm doing wrong?
It looks like the `TaskConfig` needs to know about my object in order to rebuild it.

You can find the code of this example [here](https://github.com/nextflow-io/nextflow/files/3446579/paolo.zip).

Thank you very much.

**Comment by bahnk** [comment]
Also, I tried to make my object sortable:

```groovy
package mypackage

import groovy.transform.Sortable
import groovy.transform.EqualsAndHashCode

@Sortable
@EqualsAndHashCode(includeFields=true)
class Fastq {

	String path
	String label

	Fastq(String path, String label) {
		this.path = path
		this.label = label
	}

	String getPath() {
		return this.path
	}

	String getLabel() {
		return this.label
	}
}
```
, but it still doesn't work.

**Comment by pditommaso** [comment]
Please include the `.nextflow.log` file.

**Comment by bahnk** [comment]
Hi Paolo,

Does this code work for you?

Here is the log file:

```console
Aug-05 10:39:13.870 [main] DEBUG nextflow.cli.Launcher - $> /***/***/***/***/Nextflow/0.32.0/bin/nextflow run main.nf -lib mypackage.jar -resume
Aug-05 10:39:13.976 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.32.0
Aug-05 10:39:13.985 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [ecstatic_coulomb] - revision: 8efd610501
Aug-05 10:39:14.043 [main] DEBUG nextflow.Session - Session uuid: 0703ec8e-8d82-4121-ba79-7d501ecbe4ba
Aug-05 10:39:14.043 [main] DEBUG nextflow.Session - Run name: ecstatic_coulomb
Aug-05 10:39:14.045 [main] DEBUG nextflow.Session - Executor pool size: 32
Aug-05 10:39:14.079 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 0.32.0 build 4897
  Modified: 27-09-2018 10:17 UTC (11:17 BST)
  System: Linux 3.10.0-957.1.3.el7.x86_64
  Runtime: Groovy 2.5.1 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_92-b14
  Encoding: UTF-8 (UTF-8)
  Process: 12201@***000 [10.28.4.18]
  CPUs: 32 - Mem: 251.1 GB (147 GB) - Swap: 8 GB (1.2 GB)
Aug-05 10:39:14.138 [main] DEBUG nextflow.Session - Work-dir: /***/***/***/***/***/code/nf/qc_pipeline/beta/bak/paolo/work [****]
Aug-05 10:39:14.139 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /***/***/***/***/***/code/nf/qc_pipeline/beta/bak/paolo/bin
Aug-05 10:39:14.256 [main] DEBUG nextflow.Session - Session start invoked
Aug-05 10:39:14.263 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Aug-05 10:39:14.264 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Aug-05 10:39:14.336 [main] DEBUG nextflow.script.ScriptRunner - Adding to the classpath library: /***/***/***/***/***/code/nf/qc_pipeline/beta/bak/paolo/mypackage.jar
Aug-05 10:39:14.674 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Aug-05 10:39:14.773 [main] DEBUG nextflow.processor.ProcessFactory - Discovered executor class: nextflow.executor.IgExecutor
Aug-05 10:39:14.916 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Aug-05 10:39:14.917 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Aug-05 10:39:14.921 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Aug-05 10:39:14.923 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Aug-05 10:39:14.926 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=32; memory=251.1 GB; capacity=32; pollInterval=100ms; dumpInterval=5m
Aug-05 10:39:14.930 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Aug-05 10:39:14.930 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Aug-05 10:39:14.932 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Aug-05 10:39:14.968 [main] DEBUG nextflow.Session - >>> barrier register (process: test)
Aug-05 10:39:14.970 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > test -- maxForks: 32
Aug-05 10:39:14.996 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Aug-05 10:39:14.996 [main] DEBUG nextflow.Session - Session await
Aug-05 10:39:15.082 [Actor Thread 4] DEBUG nextflow.util.CacheHelper - [WARN] Unknown hashing type: class mypackage.Fastq -- mypackage.Fastq@fa7ab09e
Aug-05 10:39:15.082 [Actor Thread 3] DEBUG nextflow.util.CacheHelper - [WARN] Unknown hashing type: class mypackage.Fastq -- mypackage.Fastq@fa7606b6
Aug-05 10:39:15.168 [Actor Thread 3] WARN  nextflow.processor.TaskProcessor - [test (1)] Unable to resume cached task -- See log file for details
com.esotericsoftware.kryo.KryoException: Unable to find class: mypackage.Fastq
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:143)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:21)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.Kryo$readClassAndObject$4.call(Unknown Source)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:185)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy)
	at nextflow.util.KryoHelper$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at nextflow.processor.TaskContext.deserialize(TaskContext.groovy:191)
	at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:166)
	at nextflow.CacheDB$getTaskEntry$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:814)
	at nextflow.processor.TaskProcessor$checkCachedOutput$3.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:699)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:540)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:62)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: mypackage.Fastq
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136)
	... 43 common frames omitted
Aug-05 10:39:15.170 [Actor Thread 4] WARN  nextflow.processor.TaskProcessor - [test (2)] Unable to resume cached task -- See log file for details
com.esotericsoftware.kryo.KryoException: Unable to find class: mypackage.Fastq
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:143)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:21)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.Kryo$readClassAndObject$4.call(Unknown Source)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:185)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy)
	at nextflow.util.KryoHelper$deserialize$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at nextflow.processor.TaskContext.deserialize(TaskContext.groovy:191)
	at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:166)
	at nextflow.CacheDB$getTaskEntry.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:814)
	at nextflow.processor.TaskProcessor$checkCachedOutput$3.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:699)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:540)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:62)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: mypackage.Fastq
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136)
	... 43 common frames omitted
Aug-05 10:39:15.223 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Aug-05 10:39:15.228 [Task submitter] INFO  nextflow.Session - [cc/d0932a] Submitted process > test (1)
Aug-05 10:39:15.244 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Aug-05 10:39:15.244 [Task submitter] INFO  nextflow.Session - [a6/77426b] Submitted process > test (2)
Aug-05 10:39:15.255 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: test (1); status: COMPLETED; exit: 0; error: -; workDir: /***/***/***/***/***/code/nf/qc_pipeline/beta/bak/paolo/work/cc/d0932a762a0b544d010eb355ff58c4]
Aug-05 10:39:15.290 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: test (2); status: COMPLETED; exit: 0; error: -; workDir: /***/***/***/***/***/code/nf/qc_pipeline/beta/bak/paolo/work/a6/77426ba0d09a3357421af814832f92]
Aug-05 10:39:15.301 [Actor Thread 5] DEBUG nextflow.Session - <<< barrier arrive (process: test)
Aug-05 10:39:15.301 [main] DEBUG nextflow.Session - Session await > all process finished
Aug-05 10:39:15.351 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Aug-05 10:39:15.352 [main] DEBUG nextflow.Session - Session await > all barriers passed
Aug-05 10:39:15.356 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=2; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=17ms; failedDuration=0ms; cachedDuration=0ms]
Aug-05 10:39:15.372 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Aug-05 10:39:15.381 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```
Thank you.

**Comment by pditommaso** [comment]
```
KryoException: Unable to find class: mypackage.Fastq
```

How are you using this class?

**Comment by bahnk** [comment]
Sorry I'm confused, what do you mean "how"?

I just run nextflow with the `-lib` option:

```bash
nextflow run main.nf -lib mypackage.jar -resume
```

**Comment by bahnk** [comment]
@pditommaso so... is that the expected behaviour? or am I doing something wrong?

**Comment by mmatthews06** [comment]
@bahnk In chat, it was apparently mentioned that you have to make your class, "Kryo friendly." Are you able to let us know if this worked, and how you tried to do it? I'm wondering if all imported classes have to be wrapped in a similar fashion.

**Comment by bahnk** [comment]
Hi @mmatthews06,

I'm sorry for the late reply, but I had no time to sort that out.

It's working for me now. What I do at the moment is putting my class in `modules/nextflow/src/main/groovy/nextflow/util` then I **recompile nextflow**. After that if I want to use my class in my nextflow script I just need to `import nextflow.util.Fastq`. Here is an example of a kryo friendly class implementation:

```groovy
package nextflow.util

import groovy.transform.Sortable
import groovy.transform.EqualsAndHashCode
import groovy.transform.CompileStatic
import org.codehaus.groovy.runtime.InvokerHelper

import com.esotericsoftware.kryo.Kryo
import com.esotericsoftware.kryo.KryoSerializable
import com.esotericsoftware.kryo.io.Input
import com.esotericsoftware.kryo.io.Output

@Sortable
@CompileStatic
@EqualsAndHashCode(includes=["path", "label"])
class Fastq implements KryoSerializable {

	String path
	String label

	private Fastq() { }

	Fastq(String path, String label) {
		this.path = path
		this.label = label
	}

	String getPath() {
		return this.path
	}

	String getLabel() {
		return this.label
	}

	@Override
	String toString() {
		return this.label + "->" + this.path
	}

	void read (Kryo kryo, Input input) {
		this.path = kryo.readObject(input, String)
		this.label = kryo.readObject(input, String)
	}

	void write (Kryo kryo, Output output) {
		kryo.writeObject(output, path)
		kryo.writeObject(output, label)
	}
}
```
The `-lib` option does not work for me because [kryo needs to register the class](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/util/SerializationHelper.groovy#L96). That's why a compilation is necessary. The code is well written because it does that automatically if the class is in `util`.

**Comment by bahnk** [comment]
I close the issue now. Thanks for you help guys :)
