### ISSUE TITLE
Multiple use of a workflow under DSL-2

### ISSUE THREAD

**Issue by pachiras** [nextflow-io/nextflow#1275]
## New feature

Hi! I'm testing DSL-2 and found one thing.

I wanted to monitor count of reads in a pipeline. So I wrote a workflow for that purpose.

```groovy
//   nf-processes/fastq.nf
process procCountReads {
    container 'centos:7.6.1810'
    input:
        set val(mFq), file(fq)
    output:
        set val(mFq), file(fq), stdout
    script:
        isPairedEnd = (fq instanceof List<?>)
        if (isPairedEnd) {
            """
            ( zcat -f ${fq[0]} | grep '^@' | wc -l ) &
            pid1=\$!
            ( zcat -f ${fq[1]} | grep '^@' | wc -l ) &
            pid2=\$!

            echo \$( wait \$pid1 )','\$( wait \$pid2 )
            """
        } else {
            """
            zcat -f ${fq} | grep '^@' | wc -l
            """
        }
}

workflow wfCountReads ( qInput ) {
    ( qInput | procCountReads )
        .map { mFq, fq, cstr ->
            if ( !("reads" in mFq) ) { mFq["reads"] = [:] }
            isPairedEnd = (fq instanceof List<?>)
            if (isPairedEnd) {
                mFq.reads +=
                    [ fq*.name*.replace(".gz",""), cstr.split(',') ]
                    .transpose()
                    .collectEntries { [ (it[0]) : (it[1] as int) ] }
            } else {
                mFq.reads +=
                    [ (fq.name.replace(".gz","")) : cstr as int ]
            }
            tuple( mFq, fq )
        }
}
```

And in the `main.nf`, I used it as follows:

```groovy
// main.nf

include wfCountReads as wfCountReads from 'nf-processes/fastq.nf'

...

workflow wfArrangeFqfiles( qInput ) {
    ( qInput | wfGetSambaFiles | wfCountReads | wfMergeFqFiles | wfSplitFqFiles )
}
```

`wfCountReads` was inserted in the middle of pipeline. It worked as I expected.

But the problem was when I inserted the workflow in two places like,
```groovy
// main.nf

include wfCountReads as wfCountReads1 from 'nf-processes/fastq.nf'
include wfCountReads as wfCountReads2 from 'nf-processes/fastq.nf'
...

workflow wfArrangeFqfiles( qInput ) {
    ( qInput | wfGetSambaFiles | wfCountReads1 | wfMergeFqFiles | wfCountReads2 | wfSplitFqFiles )
}
```
I got an error:

```
Channels cannot be used as output in more than one process or operator

 -- Check script 'nf-processes/fastq.nf' at line: 44 or see '.nextflow.log' file for more details
```

And the `.nextflow.log` says:
```
Aug-12 10:18:54.887 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.dag.MultipleOutputChannelException: Channels cannot be used as output in more than one process or operator
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:265)
    at nextflow.dag.DAG.outbound(DAG.groovy:216)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
    at nextflow.dag.DAG.addVertex(DAG.groovy:133)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
    at nextflow.dag.DAG.addProcessNode(DAG.groovy:87)
    at nextflow.dag.NodeMarker.addProcessNode(NodeMarker.groovy:50)
    at nextflow.dag.NodeMarker$addProcessNode$0.call(Unknown Source)
    at nextflow.processor.TaskProcessor.createOperator(TaskProcessor.groovy:484)
    at nextflow.processor.TaskProcessor.run(TaskProcessor.groovy:382)
    at nextflow.script.ProcessDef.run(ProcessDef.groovy:169)
    at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:36)
    at nextflow.script.ProcessDef.invoke_a(ProcessDef.groovy:126)
    at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
    at nextflow.extension.ChannelEx.or(ChannelEx.groovy:159)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
    at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:60)
    at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
    at Script_365f2370$_runScript_closure3.doCall(Script_365f2370:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    at groovy.lang.Closure.call(Closure.java:405)
    at groovy.lang.Closure.call(Closure.java:399)
    at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:179)
    at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:166)
    at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:36)
    at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
    at nextflow.extension.ChannelEx.or(ChannelEx.groovy:159)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
    at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:60)
    at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
    at Script_6842697a$_runScript_closure6.doCall(Script_6842697a:167)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    at groovy.lang.Closure.call(Closure.java:405)
    at groovy.lang.Closure.call(Closure.java:399)
    at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:179)
    at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:166)
    at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:36)
    at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
    at nextflow.extension.ChannelEx.or(ChannelEx.groovy:159)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
    at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:60)
    at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
    at Script_e8fce8e6.runScript(Script_e8fce8e6:18)
    at nextflow.script.BaseScript.run(BaseScript.groovy:151)
    at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:189)
    at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:287)
    at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:132)
    at nextflow.cli.CmdRun.run(CmdRun.groovy:246)
    at nextflow.cli.Launcher.run(Launcher.groovy:451)
    at nextflow.cli.Launcher.main(Launcher.groovy:633)
 ```

## Usage scenario 

I want to use a workflow multiple times in a pipeline.
Sorry if it is already implemented and my writing was wrong.

## Suggest implementation 

The including syntax,
```
include wfCountReads as wfCountReads1 from 'nf-processes/fastq.nf'
include wfCountReads as wfCountReads2 from 'nf-processes/fastq.nf'
```
might be somewhat lengthy.

I prefer the following:
```
include wfCountReads as wfCountReads1, wfCountReads2 from 'nf-processes/fastq.nf'
```
 
Thanks.

**Comment by pditommaso** [comment]
Thanks, this comment was inspiring. Fixed by #1276.

**Comment by pachiras** [comment]
Wow, what a rapid development! I cannot wait to try this. Thanks a lot.

**Comment by pditommaso** [comment]
It was a planned feature :)
