### ISSUE TITLE
Buffer underflow after changing name of output process file and resuming

### ISSUE THREAD

**Issue by JoseEspinosa** [nextflow-io/nextflow#134]
After modifying the output file name of a process I get this exception after resuming it:

ERROR ~ Error executing process > 'speed_to_pergola (828)' Caused by: Buffer underflow.

Stack trace:

```
Apr-15 13:37:41.545 [Actor Thread 101] ERROR nextflow.processor.TaskProcessor - Error executing process > 'speed_to_pergola (803)'

Caused by:
  Buffer underflow.

com.esotericsoftware.kryo.KryoException: Buffer underflow.
    at com.esotericsoftware.kryo.io.Input.require(Input.java:181)
    at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:355)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:109)
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
    at com.esotericsoftware.kryo.Kryo$readClassAndObject$9.call(Unknown Source)
    at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:121)
    at nextflow.util.KryoHelper$deserialize.call(Unknown Source)
    at nextflow.processor.TaskContext.read(TaskContext.groovy:213)
    at nextflow.processor.TaskContext$read$32.call(Unknown Source)
    at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:618)
    at nextflow.processor.TaskProcessor$checkCachedOutput$25.callCurrent(Unknown Source)
    at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:510)
    at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
    at nextflow.processor.ParallelTaskProcessor.invokeTask(ParallelTaskProcessor.groovy:213)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1077)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
    at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1256)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:430)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:369)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
    at ScriptED06C27BC0377A185EA6C210977107C5$_run_closure1.doCall(ScriptED06C27BC0377A185EA6C210977107C5:1)
    at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
    at groovy.lang.Closure.call(Closure.java:426)
    at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
    at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
    at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Apr-15 13:37:41.545 [Actor Thread 1] DEBUG nextflow.processor.StateObj - <get_motion> State before poison: StateObj[submitted: 1353; completed: 1344; poisoned: false; allScalar: false]
Apr-15 13:37:41.545 [Actor Thread 48] INFO  nextflow.processor.TaskProcessor - [d7/415c9f] Cached process > motion_to_pergola (860)
```

**Comment by pditommaso** [comment]
Unable to reproduce

**Comment by mes5k** [comment]
I just saw the same exception and I think it was because an output file name from process X happened to be the same as a filename from process Y.  I was able to get around this by tweaking the file name of process X.

**Comment by pditommaso** [comment]
Could you please include a test case or at least a script example?

**Comment by mes5k** [comment]
I'll see if I can create something reproducible.  My current pipeline is a bit convoluted, so I'm not sure I'll be successful.

**Comment by pditommaso** [comment]
The exception is raised because the `.command.val` is empty. The file is written at this [lines](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1681-L1684)

**Comment by pditommaso** [comment]
Serialisation/de-serialisation process changed in version 0.22.0. This issue is not valid any more.
