### ISSUE TITLE
Inconsistent workflow termination paths on errors in main script vs process def.

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1352]
## Inconsistent workflow termination paths on errors in main script vs process def. 

Workflow scripts terminate differently when encountering errors in the main script vs in process definitions.

* When you encounter/emit an error in the main script (calling error for example) then the error propagation leads to nextflow exiting without emitting the workflowComplete event to TraceObservers.
* When you encounter/emit an error in a process definition . then the error propagation leader to nextflow exiting after emitting the workflowComplete event to  TraceObservers.

### Expected behavior and actual behavior

**Expected:** All errors encountered that abort the workflow should make nextflow emit a workflowComplete event to TraceObservers that detail the errorMessage.

**Actual:** Error encountered in the main script, not process definitions, that cause the workflow to abort don't emit a workflowComplete event.

### Steps to reproduce the problem

1. Create a endpoint for the Weblog to send it's events to (I'm using https://requestbin.com)
2. Run the first script here below with weblog and notice you get a started,error and completed events from the Weblog.
3. Run the second script here below with weblog and notice you only get a started and error event.

### Environment 

* Nextflow version: 19.10.0
* Java version: 1.8
* Operating system: MacOs

### Test Scripts

**Process Error Script**
```
process ErrorProcess {
    script:    
    error "Error in process result in a completed event."
    """
    echo I encounter an error before running this
    """
}
````
**Main Script Error Script**
```
error "Error in main script doesn't result in a completed event."

process ErrorProcess {
    script:        
    """
    echo I encounter an error before running this
    """
}
```

**Comment by garpur** [comment]
@pditommaso This is a pretty irritating issue for us. Is there any progress on this issue?

**Comment by pditommaso** [comment]
Dear @garpur we try to make our best and to be as much as possible supportive with all Nextflow users. However don't forget this is open-source software that means you can use it as you wish, but there's absolutely no expectation or guaranteed timeline on features requests and bug fixes. Such kind of support it's provided through https://www.seqera.io.

**Comment by olifly** [comment]
@pditommaso - Been meaning to elaborate more on this issue, but been pre-occupied with other matters. 😦 

At the time I encountered this issue I would have liked to tackle it myself and submit a pull request, but after investigating it I deduced this would require quite alot of restructuring of code that would be best handled by the maestro himself (ie you).

I would think this problem is affecting the integration with Tower as well since the towerintegrationn is using an Observer and it seems to me this affects them all equally. 😄

**Comment by pditommaso** [comment]
Hi @olifly yes, you are right, this is the error stack trace 

```
nextflow.exception.ProcessUnrecoverableException: Error in main script doesn't result in a completed event.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at nextflow.Nextflow.error(Nextflow.groovy:262)
	at nextflow.Nextflow$error.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:231)
	at Script_525c9470.runScript(Script_525c9470:1)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:164)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:219)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:219)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:127)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:274)
	at nextflow.cli.Launcher.run(Launcher.groovy:466)
	at nextflow.cli.Launcher.main(Launcher.groovy:648)

```

Not sure yet, what's the best way to fix it .

**Comment by olifly** [comment]
@pditommaso - I had come to the conclusion that a refactoring of how errors are propagated in the main script vs in processes would be required to solve this properly. No easy task 😦
