### ISSUE TITLE
Unable to resume cached processes

### ISSUE THREAD

**Issue by husensofteng** [nextflow-io/nextflow#1358]
## Bug report 
When I re-run any pipeline with -resume option, nextflow fails to resume the cached processes. It was not the case earlier, but I am not sure what have changed, could it be something in my system or a miss configuration issue. I have tried both 18.10 and 19.04 versions and the error happens in both. Any help is highly appreciated. Thanks

### Steps to reproduce the problem

Here is the standard hello world example in test.nf:
```
#!/usr/bin/env nextflow
params.str = 'Hello world!'
process splitLetters {
    output:
    file 'chunk_*' into letters mode flatten
    """
    printf '${params.str}' | split -b 6 - chunk_
    """
}
process convertToUpper {
    input:
    file x from letters
    output:
    stdout result
    """
    rev $x
    """
}
result.subscribe {
    println it.trim()
}
```

### Program output 

`nextflow run test.nf -resume`

> N E X T F L O W  ~  version 18.10.1
> Launching `test.nf` [drunk_celsius] - revision: b7390d8379
> WARN: It appears you have never run this project before -- Option `-resume` is ignored
> [warm up] executor > local
> [2f/6b06fa] Submitted process > splitLetters
> [d8/3c755d] Submitted process > convertToUpper (1)
> [cb/0257ec] Submitted process > convertToUpper (2)
> olleH
> !dlrow
> 

Consecutive runs:
`nextflow run test.nf -resume`

> N E X T F L O W  ~  version 18.10.1
> Launching `test.nf` [elated_curran] - revision: b7390d8379
> [warm up] executor > local
**> WARN: [splitLetters] Unable to resume cached task -- See log file for details**
> [f5/8ccf3f] Submitted process > splitLetters
> [86/222752] Submitted process > convertToUpper (1)
> [36/ea9521] Submitted process > convertToUpper (2)
> olleH
> !dlrow
>  

Java exception in the log file:

> Nov-04 12:12:19.908 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
> Nov-04 12:12:19.908 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
> Nov-04 12:12:19.910 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
> Nov-04 12:12:19.977 [main] DEBUG nextflow.Session - >>> barrier register (process: splitLetters)
> Nov-04 12:12:19.980 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > splitLetters -- maxForks: 40
> Nov-04 12:12:20.035 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
> Nov-04 12:12:20.036 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
> Nov-04 12:12:20.036 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
> Nov-04 12:12:20.037 [main] DEBUG nextflow.Session - >>> barrier register (process: convertToUpper)
> Nov-04 12:12:20.037 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > convertToUpper -- maxForks: 40
> Nov-04 12:12:20.054 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
> Nov-04 12:12:20.054 [main] DEBUG nextflow.Session - Session await
> Nov-04 12:12:20.131 [Actor Thread 2] WARN  nextflow.processor.TaskProcessor - [splitLetters] Unable to resume cached task -- See log file for details
> java.lang.RuntimeException: **java.nio.channels.ClosedChannelException**
>         at com.google.common.base.Throwables.propagate(Throwables.java:240)
>         at org.iq80.leveldb.table.Table.openBlock(Table.java:83)
>         at org.iq80.leveldb.util.TableIterator.getNextBlock(TableIterator.java:102)
>         at org.iq80.leveldb.util.TableIterator.seekInternal(TableIterator.java:57)
>         at org.iq80.leveldb.util.TableIterator.seekInternal(TableIterator.java:26)
>         at org.iq80.leveldb.util.AbstractSeekingIterator.seek(AbstractSeekingIterator.java:41)
>         at org.iq80.leveldb.util.InternalTableIterator.seekInternal(InternalTableIterator.java:45)
>         at org.iq80.leveldb.util.InternalTableIterator.seekInternal(InternalTableIterator.java:25)
>         at org.iq80.leveldb.util.AbstractSeekingIterator.seek(AbstractSeekingIterator.java:41)
>         at org.iq80.leveldb.impl.Level0.get(Level0.java:103)
>         at org.iq80.leveldb.impl.Version.get(Version.java:169)
>         at org.iq80.leveldb.impl.VersionSet.get(VersionSet.java:223)
>         at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:616)
>         at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:577)
>         at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:156)
>         at nextflow.CacheDB$getTaskEntry.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
>         at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:810)
>         at nextflow.processor.TaskProcessor$checkCachedOutput$2.callCurrent(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
>         at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:536)
>         at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:58)
>         at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
>         at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
>         at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.nio.channels.ClosedChannelException: null
>         at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
>         at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:715)
>         at org.iq80.leveldb.table.FileChannelTable.read(FileChannelTable.java:96)
>         at org.iq80.leveldb.table.FileChannelTable.readBlock(FileChannelTable.java:55)
>         at org.iq80.leveldb.table.Table.openBlock(Table.java:80)
>         ... 41 common frames omitted

### Environment 

 Version: 18.10.1 build 5003
  Modified: 24-10-2018 14:03 UTC (16:03 CEST)
  System: Linux 4.15.0-62-generic
  Runtime: Groovy 2.5.3 on Java HotSpot(TM) Server VM 1.8.0_221-b11
  Encoding: UTF-8 (UTF-8)

**Comment by lindenb** [comment]
same problem for me today on my old laptop 

```
  Version: 19.10.0 build 5170
  Created: 21-10-2019 15:07 UTC (17:07 CEST)
  System: Linux 4.4.0-148-generic
  Runtime: Groovy 2.5.8 on Java HotSpot(TM) Server VM 1.8.0_172-b11
  Encoding: UTF-8 (UTF-8)
  Process: 23380@bird [127.0.1.1]
  CPUs: 4 - Mem: 15.8 GB (8.7 GB) - Swap: 16 GB (16 GB)
```

```
(...)
org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.lang.RuntimeException: java.nio.channels.ClosedChannelException
	at org.iq80.leveldb.impl.DbImpl.checkBackgroundException(DbImpl.java:421)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:584)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:577)
	at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:156)
	at nextflow.CacheDB$getTaskEntry.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:829)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:718)
(...)
Caused by: java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:721)
	at org.iq80.leveldb.table.FileChannelTable.read(FileChannelTable.java:96)
	at org.iq80.leveldb.table.FileChannelTable.readBlock(FileChannelTable.java:55)
	at org.iq80.leveldb.table.Table.openBlock(Table.java:80)
	... 18 common frames omitted
```

**Comment by pditommaso** [comment]
May be related to https://github.com/nextflow-io/nextflow/issues/842#issuecomment-567119760. Possibly solved by https://github.com/dain/leveldb/issues/96.

**Comment by pditommaso** [comment]
Using `leveldb:0.12` should solve this issue but I'm unable to replicate this problem. Could you try updating the dependency at the line below and checking if it solves the issue?

https://github.com/nextflow-io/nextflow/blob/fd13704ab1c4536583f7dfc1f44c3fcaf8f34d19/modules/nextflow/build.gradle#L34

**Comment by lindenb** [comment]
@pditommaso yes it's working on my side ! thank you.

**Comment by pditommaso** [comment]
Excellent. The updated dep will be included in the next release. Thanks for testing it!

**Comment by kemin711** [comment]
I encountered this warning message, the pipeline could not resume. It must be due to one bad line of code of mine. I include the log here to help programmers:
WARN: [transformSampleSheet (transform_ss)] Unable to resume cached task -- See log file for details
Oct-06 22:04:19.408 [Actor Thread 1] WARN  nextflow.processor.TaskProcessor - [transformSampleSheet (transform_ss)] Unable to resume cached task -- See log file for details
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): groovy.util.slurpersupport.NodeChildren
   at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1228)
   at nextflow.util.InstantiationStrategy.newInstantiatorOf(SerializationHelper.groovy:266)
   at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1049)
   at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1058)
   at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:547)
   at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:523)
   at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
   at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:143)
   at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:21)
   at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
   at com.esotericsoftware.kryo.Kryo$readClassAndObject$1.call(Unknown Source)
   at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:180)
   at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy)
   at nextflow.util.KryoHelper$deserialize.call(Unknown Source)
   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
   at nextflow.processor.TaskContext.deserialize(TaskContext.groovy:189)
   at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:162)
   at nextflow.CacheDB$getTaskEntry.call(Unknown Source)
   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
   at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:848)
   at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:737)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
   at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
   at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
   at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:572)
   at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:58)
