### ISSUE TITLE
Duration unit cannot be a negative number

### ISSUE THREAD

**Issue by srynobio** [nextflow-io/nextflow#1384]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior
The expected behavior occurred. i.e. pipleine ran all steps and `publishDir` transferred all files.  This error occurred at the end of processing for unknown reasons.
Actual behavior:
```
Nov-19 09:59:56.205 [main] DEBUG nextflow.Session - Session await > all process finished
Nov-19 09:59:56.282 [main] DEBUG nextflow.Session - Session await > all barriers passed
Nov-19 10:00:01.317 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Nov-19 10:01:01.321 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Nov-19 10:02:01.327 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Nov-19 10:02:31.675 [main] DEBUG nextflow.Session - Session aborted -- Cause: Duration unit cannot be a negative number. Expression: (duration >= 0). Values: duration = -1574027111516
Nov-19 10:02:31.822 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.AssertionError: Duration unit cannot be a negative number. Expression: (duration >= 0). Values: duration = -1574027111516
        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:417)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
        at nextflow.util.Duration.<init>(Duration.groovy:71)
        at nextflow.trace.WorkflowStats.getSucceedDuration(WorkflowStats.groovy:111)
        at nextflow.trace.WorkflowStats.toString(WorkflowStats.groovy:225)
        at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:659)
        at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:148)
        at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:547)
        at groovy.lang.GString.writeTo(GString.java:194)
        at groovy.lang.GString.toString(GString.java:151)
        at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:55)
        at nextflow.trace.StatsObserver.onFlowComplete(StatsObserver.groovy:43)
        at nextflow.Session.shutdown0(Session.groovy:749)
        at nextflow.Session.destroy(Session.groovy:689)
        at nextflow.script.ScriptRunner.terminate(ScriptRunner.groovy:297)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:134)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:246)
        at nextflow.cli.Launcher.run(Launcher.groovy:451)
        at nextflow.cli.Launcher.main(Launcher.groovy:633)
```

### Program output 

Above is log output.

### Environment 

* Nextflow version: `nextflow version 19.07.0.5106`
* Java version:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
* Operating system: `Linux`

**Comment by pditommaso** [comment]
This was very likely caused by a number overflow. Was this a veerry long run? that number is a long and therefore the max value should be `9,223,372,036,854,775,808` milliseconds that's a lot!

**Comment by srynobio** [comment]
It's strange.  The run wasn't partially long and the data was just ~30X WGS data.  Maybe it was just a strange run.  

I'll close the issue for now, and reissue if it occurs again.

**Comment by pditommaso** [comment]
I'll manage to the exception to avoid the execution to crash for now.

**Comment by pditommaso** [comment]
I've got the same stopping an execution 

```
java.lang.AssertionError: Memory unit cannot be a negative number. Expression: (value >= 0). Values: value = -73014444032
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:417)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at nextflow.util.MemoryUnit.<init>(MemoryUnit.groovy:61)
	at nextflow.util.MemoryUnit.of(MemoryUnit.groovy:172)
	at nextflow.trace.WorkflowStats.toString(WorkflowStats.groovy:255)
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:659)
	at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:148)
	at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:547)
	at groovy.lang.GString.writeTo(GString.java:194)
	at groovy.lang.GString.toString(GString.java:151)
	at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:55)
	at nextflow.trace.WorkflowStatsObserver.onFlowComplete(WorkflowStatsObserver.groovy:48)
	at nextflow.Session.notifyFlowComplete(Session.groovy:1008)
	at nextflow.Session.shutdown0(Session.groovy:662)
	at nextflow.Session.destroy(Session.groovy:606)
	at nextflow.script.ScriptRunner.terminate(ScriptRunner.groovy:228)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:128)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:257)
	at nextflow.cli.Launcher.run(Launcher.groovy:452)
	at nextflow.cli.Launcher.main(Launcher.groovy:634)
```

**Comment by pditommaso** [comment]
Actually was unrelated.
