### ISSUE TITLE
No such property stackTraceDepth error

### ISSUE THREAD

**Issue by jma1991** [nextflow-io/nextflow#1387]
### Expected behavior and actual behavior

I am trying to run an ATAC-seq pipeline by nf-core using a conda profile but the command fails and reports a Java-related MissingPropertyException error.

### Steps to reproduce the problem

```
$ nextflow run nf-core/atacseq -profile test,conda
```

### Program output 

```
N E X T F L O W  ~  version 19.10.0
Launching `nf-core/atacseq` [jolly_bernard] - revision: fa1e3f8993 [master]
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/atacseq v1.1.0
----------------------------------------------------
Run Name             : jolly_bernard
Data Type            : Paired-End
Design File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/design.csv
Genome               : Not supplied
Fasta File           : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File             : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
Mitochondrial Contig : MT
MACS2 Genome Size    : 1.2E+7
Min Consensus Reps   : 1
MACS2 Narrow Peaks   : No
MACS2 Broad Cutoff   : 0.1
Trim R1              : 0 bp
Trim R2              : 0 bp
Trim 3' R1           : 0 bp
Trim 3' R2           : 0 bp
NextSeq Trim         : 0 bp
Fingerprint Bins     : 100
Save Genome Index    : No
Max Resources        : 6 GB memory, 2 cpus, 12h time per job
Output Dir           : ./results
Launch Dir           : /home/jashmore/fast/kaji/atacseq
Working Dir          : /home/jashmore/fast/kaji/atacseq/work
Script Dir           : /home/jashmore/.nextflow/assets/nf-core/atacseq
User                 : jashmore
Config Profile       : test,conda
Config Description   : Minimal test dataset to check pipeline function
----------------------------------------------------
executor >  local (1)
[65/f742f7] process > CheckDesign (design.csv) [100%] 1 of 1 ✔
groovy.lang.MissingPropertyException: No such property: stackTraceDepth for class: nextflow.dag.MultipleInputChannelException
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
        at nextflow.dag.MultipleInputChannelException.toString(MultipleInputChannelException.groovy)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.io.PrintWriter.println(PrintWriter.java:837)
        at java.base/java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:768)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:725)
        at org.apache.commons.lang.exception.ExceptionUtils.getStackTrace(ExceptionUtils.java:896)
        at nextflow.util.LoggerHelper.findErrorLine(LoggerHelper.groovy:538)
        at nextflow.util.LoggerHelper.appendFormattedMessage(LoggerHelper.groovy:434)
        at nextflow.util.LoggerHelper.fmtEvent(LoggerHelper.groovy:414)
        at nextflow.util.LoggerHelper$CaptureAppender.append(LoggerHelper.groovy:606)
        at nextflow.util.LoggerHelper$CaptureAppender.append(LoggerHelper.groovy)
        at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.error(Logger.java:538)
        at nextflow.cli.Launcher.run(Launcher.groovy:505)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

### Environment 

* Nextflow version: 19.10.0
* Java version: JDK 11.0.5
* Operating system: Linux CentOS 6

### Additional context

I originally reported this issue to the maintainer of the ATAC-seq pipeline on the nf-core GitHub page but was asked to report it here as well: https://github.com/nf-core/atacseq/issues/64#issue-525951488

**Comment by pditommaso** [comment]
I'm unable to replicate this, however I think the real error has been shadowed by this weird exception. I've patched this code to prevent this in the future.

**Comment by jma1991** [comment]
I installed the Java 8 SDK and compiled nextflow from the latest source on Github. The error message which was revealed is the following:

```
Dec-04 11:51:09.191 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/atacseq -profile test,conda
Dec-04 11:51:09.459 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.10.0-edge
Dec-04 11:51:11.267 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jashmore/.nextflow/assets/nf-core/atacseq/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/atacseq.git
Dec-04 11:51:11.302 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jashmore/.nextflow/assets/nf-core/atacseq/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/atacseq.git
Dec-04 11:51:11.596 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jashmore/.nextflow/assets/nf-core/atacseq/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/atacseq.git
Dec-04 11:51:11.597 [main] INFO  nextflow.cli.CmdRun - Launching `nf-core/atacseq` [hungry_sax] - revision: fa1e3f8993 [master]
Dec-04 11:51:12.690 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/jashmore/.nextflow/assets/nf-core/atacseq/nextflow.config
Dec-04 11:51:12.692 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/jashmore/.nextflow/assets/nf-core/atacseq/nextflow.config
Dec-04 11:51:12.709 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `test,conda`
Dec-04 11:51:14.396 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [uppmax_devel, shh_cdag, denbi_qbic, genotoul, bigpurple, uppmax, docker, gis, ccga, shh_sdag, conda, singularity, munin, prince, czbiohub_aws, hebbe, cfc, uzh, debug, test, genouest, cbe, ccga_dx, crick, czbiohub_aws_highpriority, kraken, phoenix, awsbatch, pasteur, uct_hex, binac]
Dec-04 11:51:14.473 [main] DEBUG nextflow.extension.OperatorEx - Dataflow extension methods: branch,buffer,chain,choice,collate,collect,collectFile,combine,concat,count,countBy,countFasta,countFastq,countLines,countText,cross,distinct,filter,first,flatMap,flatten,fork,groupBy,groupTuple,ifEmpty,into,join,last,map,max,mean,merge,min,mix,phase,print,println,randomSample,reduce,separate,set,splitCsv,splitFasta,splitFastq,splitText,spread,subscribe,sum,take,tap,toDouble,toFloat,toInteger,toList,toLong,toSortedList,transpose,unique,until,view
Dec-04 11:51:14.489 [main] DEBUG nextflow.Session - Session uuid: 3e6dbc98-6a52-4c44-80e8-c9f4dda4089a
Dec-04 11:51:14.490 [main] DEBUG nextflow.Session - Run name: hungry_sax
Dec-04 11:51:14.491 [main] DEBUG nextflow.Session - Executor pool size: 64
Dec-04 11:51:14.569 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.10.0-edge build 5172
  Created: 03-12-2019 16:14 UTC (16:14 BST)
  System: Linux 2.6.32-754.18.2.el6.x86_64
  Runtime: Groovy 2.5.8 on Java HotSpot(TM) 64-Bit Server VM 11.0.5+10-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 57849@stembio19.med.ed.ac.uk [129.215.162.195]
  CPUs: 64 - Mem: 504.9 GB (63.9 GB) - Swap: 4 GB (4 GB)
Dec-04 11:51:14.629 [main] DEBUG nextflow.Session - Work-dir: /home/jashmore/fast/kaji/atacseq/work [nfs]
Dec-04 11:51:14.691 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Dec-04 11:51:14.697 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-04 11:51:15.242 [main] DEBUG nextflow.Session - Session start invoked
Dec-04 11:51:15.252 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /home/jashmore/fast/kaji/atacseq/results/pipeline_info/execution_trace.txt
Dec-04 11:51:17.858 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-04 11:51:19.977 [main] INFO  nextflow.Nextflow - -[2m--------------------------------------------------[0m-
                                        [0;32m,--.[0;30m/[0;32m,-.[0m
[0;34m        ___     __   __   __   ___     [0;32m/,-._.--~'[0m
[0;34m  |\ | |__  __ /  ` /  \ |__) |__         [0;33m}  {[0m
[0;34m  | \| |       \__, \__/ |  \ |___     [0;32m\`-._,-`-,[0m
                                        [0;32m`._,._,'[0m
[0;35m  nf-core/atacseq v1.1.0[0m
-[2m--------------------------------------------------[0m-

Dec-04 11:51:20.003 [main] INFO  nextflow.Nextflow - Run Name             : hungry_sax
Data Type            : Paired-End
Design File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/design.csv
Genome               : Not supplied
Fasta File           : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File             : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
Mitochondrial Contig : MT
MACS2 Genome Size    : 1.2E+7
Min Consensus Reps   : 1
MACS2 Narrow Peaks   : No
MACS2 Broad Cutoff   : 0.1
Trim R1              : 0 bp
Trim R2              : 0 bp
Trim 3' R1           : 0 bp
Trim 3' R2           : 0 bp
NextSeq Trim         : 0 bp
Fingerprint Bins     : 100
Save Genome Index    : No
Max Resources        : 6 GB memory, 2 cpus, 12h time per job
Output Dir           : ./results
Launch Dir           : /home/jashmore/fast/kaji/atacseq
Working Dir          : /home/jashmore/fast/kaji/atacseq/work
Script Dir           : /home/jashmore/.nextflow/assets/nf-core/atacseq
User                 : jashmore
Config Profile       : test,conda
Config Description   : Minimal test dataset to check pipeline function
Dec-04 11:51:20.005 [main] INFO  nextflow.Nextflow - -[2m--------------------------------------------------[0m-
Dec-04 11:51:20.192 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Dec-04 11:51:20.192 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Dec-04 11:51:20.204 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Dec-04 11:51:20.218 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=64; memory=504.9 GB; capacity=64; pollInterval=100ms; dumpInterval=5m
Dec-04 11:51:20.387 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > CheckDesign -- maxForks: 64; blocking: false
Dec-04 11:51:20.823 [Actor Thread 3] DEBUG n.util.BlockingThreadExecutorFactory - Thread pool name=FileTransfer; maxThreads=192; maxQueueSize=576; keepAlive=1m
Dec-04 11:51:20.842 [FileTransfer-thread-1] DEBUG nextflow.file.FilePorter - Copying foreign file https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/design.csv to work dir: /home/jashmore/fast/kaji/atacseq/work/stage/14/569d75b4e7d237fd63bc7af549d384/design.csv
Dec-04 11:51:21.138 [Actor Thread 4] INFO  nextflow.conda.CondaCache - Creating Conda env: /home/jashmore/.nextflow/assets/nf-core/atacseq/environment.yml [cache /home/jashmore/fast/kaji/atacseq/work/conda/nf-core-atacseq-1.1.0-122cbc6d9b1e4b6a246c5040c42e496b]
Dec-04 11:56:20.429 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- The following nodes are still active:
[process] CheckDesign
  status=ACTIVE
  port 0: (value) bound ; channel: design
  port 1: (cntrl) -     ; channel: $

Dec-04 12:01:20.468 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- The following nodes are still active:
[process] CheckDesign
  status=ACTIVE
  port 0: (value) bound ; channel: design
  port 1: (cntrl) -     ; channel: $

Dec-04 12:04:18.695 [Actor Thread 4] DEBUG nextflow.conda.CondaCache - Conda create complete env=/home/jashmore/.nextflow/assets/nf-core/atacseq/environment.yml path=/home/jashmore/fast/kaji/atacseq/work/conda/nf-core-atacseq-1.1.0-122cbc6d9b1e4b6a246c5040c42e496b
Dec-04 12:04:18.901 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Dec-04 12:04:18.914 [Task submitter] INFO  nextflow.Session - [14/096fd8] Submitted process > CheckDesign (design.csv)
Dec-04 12:04:25.312 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: CheckDesign (design.csv); status: COMPLETED; exit: 0; error: -; workDir: /home/jashmore/fast/kaji/atacseq/work/14/096fd8dcc183329793cf4cb25ed4ca]
Dec-04 12:04:29.100 [main] DEBUG nextflow.Session - Session aborted -- Cause: Channel `design_multiple_samples` has been used as an input by more than a process or an operator
Dec-04 12:04:29.120 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.dag.MultipleInputChannelException: Channel `design_multiple_samples` has been used as an input by more than a process or an operator
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:265)
	at nextflow.dag.DAG.inbound(DAG.groovy:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.dag.DAG.addVertex(DAG.groovy:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at nextflow.dag.DAG.addOperatorNode(DAG.groovy:100)
	at nextflow.dag.NodeMarker.addOperatorNode(NodeMarker.groovy:62)
	at nextflow.extension.OpCall.addGraphNode(OpCall.groovy:168)
	at nextflow.extension.OpCall.invoke(OpCall.groovy:158)
	at nextflow.extension.OpCall.call(OpCall.groovy:110)
	at nextflow.extension.OperatorEx.invokeExtensionMethod(OperatorEx.groovy:107)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script_2f36603e.runScript(Script_2f36603e:353)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:152)
	at nextflow.script.BaseScript.run(BaseScript.groovy:182)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:217)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:257)
	at nextflow.cli.Launcher.run(Launcher.groovy:452)
	at nextflow.cli.Launcher.main(Launcher.groovy:634)
Dec-04 12:04:29.142 [main] WARN  nextflow.util.LoggerHelper - Oops .. something wrong formatting the error stack trace | No such property: stackTraceDepth for class: nextflow.dag.MultipleInputChannelException
nextflow.dag.MultipleInputChannelException: Channel `design_multiple_samples` has been used as an input by more than a process or an operator
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:265)
	at nextflow.dag.DAG.inbound(DAG.groovy:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.dag.DAG.addVertex(DAG.groovy:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at nextflow.dag.DAG.addOperatorNode(DAG.groovy:100)
	at nextflow.dag.NodeMarker.addOperatorNode(NodeMarker.groovy:62)
	at nextflow.extension.OpCall.addGraphNode(OpCall.groovy:168)
	at nextflow.extension.OpCall.invoke(OpCall.groovy:158)
	at nextflow.extension.OpCall.call(OpCall.groovy:110)
	at nextflow.extension.OperatorEx.invokeExtensionMethod(OperatorEx.groovy:107)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script_2f36603e.runScript(Script_2f36603e:353)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:152)
	at nextflow.script.BaseScript.run(BaseScript.groovy:182)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:217)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:257)
	at nextflow.cli.Launcher.run(Launcher.groovy:452)
	at nextflow.cli.Launcher.main(Launcher.groovy:634)
```
