### ISSUE TITLE
"optional true" doesn't work with "emit"

### ISSUE THREAD

**Issue by ii-bioinfo-thomas** [nextflow-io/nextflow#1402]
### Expected behavior and actual behavior

Addition of emit should work the same way as without explicitly defining channel name. It cancels with the error that it doesn't know the variable specified after emit.

### Steps to reproduce the problem

This example works without the emit statement fine.

```
nextflow.preview.dsl=2

process opt {

  input:
  val condition

  output:
  path "TRUE" optional true, emit: path

  script:
  """
  touch ${condition}
  """
}

workflow {

  Channel.from("TRUE", "FALSE") \
  | opt

  opt.out.path \
  | view

}

```

### Program output 

```
No such variable: path
```

```
Dec-05 11:17:56.696 [main] DEBUG nextflow.cli.Launcher - $> nextflow optional.nf
Dec-05 11:17:56.793 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.10.0
Dec-05 11:17:56.806 [main] INFO  nextflow.cli.CmdRun - Launching `optional.nf` [shrivelled_lalande] - revision: f1608eb40b
Dec-05 11:17:56.893 [main] DEBUG nextflow.extension.OperatorEx - Dataflow extension methods: branch,buffer,chain,choice,collate,collect,collectFile,combine,concat,count,countBy,countFasta,countFastq,countLines,countText,cross,distinct,filter,first,flatMap,flatten,fork,groupBy,groupTuple,ifEmpty,into,join,last,map,max,mean,merge,min,mix,phase,print,println,randomSample,reduce,separate,set,splitCsv,splitFasta,splitFastq,splitText,spread,subscribe,sum,take,tap,toDouble,toFloat,toInteger,toList,toLong,toSortedList,transpose,unique,until,view
Dec-05 11:17:56.901 [main] DEBUG nextflow.Session - Session uuid: 801c4541-c327-4ebe-ae42-00f5c72a8fde
Dec-05 11:17:56.901 [main] DEBUG nextflow.Session - Run name: shrivelled_lalande
Dec-05 11:17:56.902 [main] DEBUG nextflow.Session - Executor pool size: 56
Dec-05 11:17:56.920 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.10.0 build 5170
  Created: 21-10-2019 15:07 UTC (17:07 CEST)
  System: Linux 3.10.0-693.17.1.el7.x86_64
  Runtime: Groovy 2.5.8 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13
  Encoding: UTF-8 (UTF-8)
  Process: 19312@login-03 [172.16.61.41]
  CPUs: 56 - Mem: 188.7 GB (1.6 GB) - Swap: 0 (0)
Dec-05 11:17:56.992 [main] DEBUG nextflow.Session - Work-dir: /scratch/burkard/nxf_work [nfs]
Dec-05 11:17:56.992 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /scratch/burkard/bin
Dec-05 11:17:57.008 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Dec-05 11:17:57.010 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-05 11:17:57.183 [main] DEBUG nextflow.Session - Session start invoked
Dec-05 11:17:57.705 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-05 11:17:57.715 [main] WARN  nextflow.NextflowMeta$Preview - DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
Dec-05 11:17:57.838 [main] DEBUG nextflow.Session - Session aborted -- Cause: Unknown variable 'path'
Dec-05 11:17:57.846 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: Unknown variable 'path'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:265)
	at nextflow.script.ProcessConfig.getProperty(ProcessConfig.groovy:279)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:313)
	at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:303)
	at groovy.lang.Closure.getProperty(Closure.java:288)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
	at Script_3cd029fe$_runScript_closure1.doCall(Script_3cd029fe:9)
	at Script_3cd029fe$_runScript_closure1.doCall(Script_3cd029fe)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at nextflow.script.ProcessDef.initialize(ProcessDef.groovy:103)
	at nextflow.script.ProcessDef.run(ProcessDef.groovy:158)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
	at nextflow.extension.ChannelEx.or(ChannelEx.groovy:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:61)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script_3cd029fe$_runScript_closure2$_closure4.doCall(Script_3cd029fe:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:202)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:189)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:173)
	at nextflow.script.BaseScript.run(BaseScript.groovy:182)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:217)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:257)
	at nextflow.cli.Launcher.run(Launcher.groovy:457)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

```

### Environment 

* Nextflow version: 19.10.0 
* Java version: 1.8.0_121-b13
* Operating system: Linux

**Comment by stekaz** [comment]
Is this just a syntax issue? Please try changing the output statement to:

```
output:
  path "TRUE", optional: true, emit: path
```

**Comment by ii-bioinfo-thomas** [comment]
thanks! that solved my problem!
