### ISSUE TITLE
Not such variable: process

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#141]
The following multiple `into` statements are not parsed correctly and throw the error included below:

```
process foo {
  output:
   stdout into A,B,C
   file ('x') into A,B,C 
   set ('x') into A,B,C

  """
  echo Ciao > x 
  """
}
```

Error trace:

```
groovy.lang.MissingPropertyException: No such property: process for class: _nf_script_401dc481
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
    at _nf_script_401dc481.run(_nf_script_401dc481:1)
    at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:319)
    at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:156)
    at nextflow.cli.CmdRun.run(CmdRun.groovy:195)
    at nextflow.cli.Launcher.run(Launcher.groovy:380)
    at nextflow.cli.Launcher.main(Launcher.groovy:529)
```

**Comment by pditommaso** [comment]
The process definition below:  

	process foo {
	  output: 
	  file 'x' into A,B
  	  'echo hello > x'
	}

produces the the following method call (as expected): 

    this.process(this.foo({ -> ... }))

<img width="1125" alt="good" src="https://cloud.githubusercontent.com/assets/816968/14986522/9168ce06-114c-11e6-85c5-c587cbcd1c08.png">

Instead the process below: 

	process foo {
	  output: 
	  file ('x') into A,B
  	  'echo hello > x'
	}

produces an invalid method call: 

    process.foo({ -> ... })

<img width="1125" alt="bad" src="https://cloud.githubusercontent.com/assets/816968/14986578/c9847736-114c-11e6-9d97-33106cf7d4b5.png">

This look a problem with the Groovy syntax parser.

**Comment by pditommaso** [comment]
A workaround is enclosing target channels is brackets. For example: 

```
  output:
   stdout() into (A,B,C) 
   file ('x') into (A,B,C) 
```

But the following is still failing 

```
  output:
   stdout into (A,B,C) 
```
