### ISSUE TITLE
Variable task.exitStatus throws an exception when comparing it to an integer value

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#142]
In order to replicate the issue create a `nextflow.config` file wth the following content: 

    process.errorStrategy = { task.exitStatus >= 127 ? 'retry' : 'ignore' }

Then a script file with a process definition like the following: 

	process task1 {
		errorStrategy 'ignore'
		script:
		"exit 1"
	}

The following exception is thrown: 

	groovy.lang.GroovyRuntimeException: Cannot compare groovy.util.ConfigObject with value '[:]' and java.lang.Integer with value '127'
		at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareToWithEqualityCheck(DefaultTypeTransformation.java:595)
		at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareTo(DefaultTypeTransformation.java:543)
		at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareTo(ScriptBytecodeAdapter.java:692)
		at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareGreaterThanEqual(ScriptBytecodeAdapter.java:757)
		at _nf_config_04eaa467$_run_closure4.doCall(_nf_config_04eaa467:22)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
		at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1249)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
		at nextflow.processor.ProcessConfig.invokeMethod(ProcessConfig.groovy)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:430)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:371)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
		at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
		at _nf_script_be488e52$_run_closure7.doCall(_nf_script_be488e52:149)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
		at groovy.lang.Closure.call(Closure.java:426)
		at groovy.lang.Closure.call(Closure.java:442)
		at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:241)
		at org.codehaus.groovy.runtime.dgm$757.invoke(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
		at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:76)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
		at nextflow.processor.ProcessFactory.createProcessor(ProcessFactory.groovy:222)
		at nextflow.processor.ProcessFactory.createProcessor(ProcessFactory.groovy)
		at nextflow.processor.ProcessFactory$createProcessor.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at nextflow.processor.ProcessFactory$createProcessor.call(Unknown Source)
		at nextflow.script.BaseScript.process(BaseScript.groovy:134)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
		at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
		at _nf_script_be488e52.run(_nf_script_be488e52:147)
		at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:319)
		at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:156)
		at nextflow.cli.CmdRun.run(CmdRun.groovy:195)
		at nextflow.cli.Launcher.run(Launcher.groovy:380)
		at nextflow.cli.Launcher.main(Launcher.groovy:529)

**Comment by pditommaso** [comment]
Version `0.18.2`
