### ISSUE TITLE
Google Lifesciences Executor with minimal reproducible code

### ISSUE THREAD

**Issue by daudn** [nextflow-io/nextflow#1421]
I am trying out the new `google-lifesciences` executor and can't get it to run. This is a minimal reproducible problem, all code is provided, the only external change would be adding in the service account. 

**The service account I'm using is called "uploader.json" and has the following roles**
1. Storage Admin
2. Service Usage Consumer 
3. Cloud Life Sciences Admin 

I am mentioning this because in the error logs it seems to be using the compute-engine default `230653752474-compute@developer.gserviceaccount.com` service account and not the one I have supplied via the env variable.

**The API's enabled are:**
1. Lifesciences API
2. Compute Engine API
3. Storage API
4. Genomics API

**nextflow.config**
```
process {
    executor = 'google-lifesciences'
}

google {
    project = '<project-name>'
    zone = 'europe-west2-b'
    lifeSciences.bootDiskSize = 50.GB
}

docker{
    enabled = true
}
```
**Env variables**
`NXF_MODE=google` 
`NXF_VER=19.12.0-SNAPSHOT` 
`GOOGLE_APPLICATION_CREDENTIALS=/path/to/uploader.json`

**this_workflow.nf**
```
process A{
    echo true

    container 'python:3'

    script:
    """
    echo "test"
    """
}
```

**Output**
```
Dec-12 15:03:20.120 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.12.0-SNAPSHOT
Dec-12 15:03:20.149 [main] INFO  nextflow.cli.CmdRun - Launching `this_workflow.nf` [gigantic_legentil] - revision: 9f34f59ce3
Dec-12 15:03:20.185 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/daudn/nextflow/workflows/nextflow.config
Dec-12 15:03:20.186 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/daudn/nextflow/workflows/nextflow.config
Dec-12 15:03:20.274 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Dec-12 15:03:21.554 [main] DEBUG nextflow.Session - Session uuid: f05251e2-1bce-4f2c-9734-add47a844b7f
Dec-12 15:03:21.554 [main] DEBUG nextflow.Session - Run name: gigantic_legentil
Dec-12 15:03:21.555 [main] DEBUG nextflow.Session - Executor pool size: 2
Dec-12 15:03:22.111 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.12.0-SNAPSHOT build 5175
  Created: 10-12-2019 11:42 UTC 
  System: Linux 4.9.0-9-amd64
  Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 1.8.0_232-8u232-b09-1~deb9u1-b09
  Encoding: UTF-8 (UTF-8)
  Process: 17795@nextflow [10.154.0.8]
  CPUs: 1 - Mem: 3.6 GB (2.5 GB) - Swap: 0 (0)
Dec-12 15:03:22.159 [main] DEBUG nextflow.file.FileHelper - Can't check if specified path is NFS (1): /work

Dec-12 15:03:22.160 [main] DEBUG nextflow.Session - Work-dir: gs://nextflow-text-bucket/work [null]
Dec-12 15:03:22.160 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/daudn/nextflow/workflows/bin
Dec-12 15:03:22.296 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Dec-12 15:03:22.299 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-12 15:03:22.515 [main] DEBUG nextflow.Session - Session start invoked
Dec-12 15:03:22.854 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-12 15:03:22.979 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: google-lifesciences
Dec-12 15:03:22.979 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'google-lifesciences'
Dec-12 15:03:23.001 [main] DEBUG nextflow.executor.Executor - [warm up] executor > google-lifesciences
Dec-12 15:03:23.012 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'google-lifesciences' > capacity: 1000; pollInterval: 10s; dumpInterval: 5m 
Dec-12 15:03:23.034 [main] DEBUG n.c.g.l.GoogleLifeSciencesExecutor - Google Life Science config=GoogleLifeSciencesConfig(project:<my-project>, zones:[], regions:[europe-west2], preemptible:true, remoteBinDir:null, location:europe-west2, disableBinDir:false, bootDiskSize:50 GB)
Dec-12 15:03:23.441 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > A -- maxForks: 2; blocking: false
Dec-12 15:03:23.523 [main] DEBUG nextflow.script.BaseScript - No entry workflow defined
Dec-12 15:03:23.524 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Dec-12 15:03:23.524 [main] DEBUG nextflow.Session - Session await
Dec-12 15:03:25.767 [Task submitter] WARN  n.c.g.l.GoogleLifeSciencesHelper - Invalid server response running pipeline: [actions:[[commands:[bash, -c, set -x; { cd /work/ef/95a4172af18834516ac4aea58fbd56; gsutil -m -q cp gs://nextflow-text-bucket/work/ef/95a4172af18834516ac4aea58fbd56/.command.run .; bash .command.run nxf_stage; } 2>&1 > /work/ef/95a4172af18834516ac4aea58fbd56/.command.log], containerName:nf-ef95a4172af18834516ac4aea58fbd56-stage, disableStandardErrorCapture:true, enableFuse:true, environment:[:], imageUri:google/cloud-sdk:alpine, mounts:[[disk:nf-pipeline-work, path:/work/ef/95a4172af18834516ac4aea58fbd56, readOnly:false]]], [commands:[bash, -c, { cd /work/ef/95a4172af18834516ac4aea58fbd56; bash .command.run; } 2>&1 | tee -a /work/ef/95a4172af18834516ac4aea58fbd56/.command.log], containerName:nf-ef95a4172af18834516ac4aea58fbd56-main, disableStandardErrorCapture:true, enableFuse:true, environment:[:], imageUri:python:3, mounts:[[disk:nf-pipeline-work, path:/work/ef/95a4172af18834516ac4aea58fbd56, readOnly:false]]], [alwaysRun:true, commands:[bash, -c, set -x; { cd /work/ef/95a4172af18834516ac4aea58fbd56; bash .command.run nxf_unstage; } 2>&1 | tee -a /work/ef/95a4172af18834516ac4aea58fbd56/.command.log; gsutil -m -q cp -R /work/ef/95a4172af18834516ac4aea58fbd56/.command.log gs://nextflow-text-bucket/work/ef/95a4172af18834516ac4aea58fbd56/.command.log || true; [[ $GOOGLE_LAST_EXIT_STATUS -gt 0 || $NXF_DEBUG -gt 0 ]] && { gsutil -m -q cp -R /google/ gs://nextflow-text-bucket/work/ef/95a4172af18834516ac4aea58fbd56; } || rm -rf /work/ef/95a4172af18834516ac4aea58fbd56], containerName:nf-ef95a4172af18834516ac4aea58fbd56-unstage, disableStandardErrorCapture:true, enableFuse:true, environment:[:], ignoreExitStatus:true, imageUri:google/cloud-sdk:alpine, mounts:[[disk:nf-pipeline-work, path:/work/ef/95a4172af18834516ac4aea58fbd56, readOnly:false]]]], resources:[regions:[europe-west2], virtualMachine:[bootDiskSizeGb:50, disks:[[name:nf-pipeline-work]], machineType:n1-standard-1, preemptible:true, serviceAccount:[scopes:[https://www.googleapis.com/auth/cloud-platform]]], zones:[]]]
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Error: checking service account permission: caller does not have access to act as the specified service account: \"230653752474-compute@developer.gserviceaccount.com\"",
    "reason" : "forbidden"
  } ],
  "message" : "Error: checking service account permission: caller does not have access to act as the specified service account: \"230653752474-compute@developer.gserviceaccount.com\"",
  "status" : "PERMISSION_DENIED"
}
 at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1092)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
        at nextflow.cloud.google.lifesciences.GoogleLifeSciencesHelper.runPipeline(GoogleLifeSciencesHelper.groovy:236)
        at nextflow.cloud.google.lifesciences.GoogleLifeSciencesHelper.submitPipeline(GoogleLifeSciencesHelper.groovy:150)
        at nextflow.cloud.google.lifesciences.GoogleLifeSciencesTaskHandler.submitPipeline(GoogleLifeSciencesTaskHandler.groovy:277)
        at nextflow.cloud.google.lifesciences.GoogleLifeSciencesTaskHandler.submit(GoogleLifeSciencesTaskHandler.groovy:250)
        at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:195)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:558)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:386)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1050)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1092)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.lang.Thread.run(Thread.java:748)
Dec-12 15:03:25.856 [Task submitter] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://nextflow-text-bucket/work/ef/95a4172af18834516ac4aea58fbd56/.command.log
Dec-12 15:03:25.864 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'A'

Caused by:
  Failed to submit task with name: A

Command executed:

  echo "test"

Command exit status:
  -

Command output:
  (empty)

Work dir:
  gs://nextflow-text-bucket/work/ef/95a4172af18834516ac4aea58fbd56

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Dec-12 15:03:25.881 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: Failed to submit task with name: A
Dec-12 15:03:25.926 [main] DEBUG nextflow.Session - Session await > all process finished
Dec-12 15:03:25.926 [main] DEBUG nextflow.Session - Session await > all barriers passed
Dec-12 15:03:25.983 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=1; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms]
Dec-12 15:03:26.159 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Dec-12 15:03:26.267 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

After posting on gitter, and attempting multiple times. I'm uncertain of what the issue might be. I believe it may be one of the following two problems.

**1. Service account**
It may be that Nextflow is not recognizing my service account attached. However if I set a different service account `compute-engine` which is `compute engine admin` 

I get this output immediately:
```
Caused by:
  403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "compute-engine@<my-project>.iam.gserviceaccount.com does not have storage.objects.get access to nextflow-text-bucket/work/10/521c6ad2bec00fa0a641c85de72f51.",
    "reason" : "forbidden"
  } ],
  "message" : "compute-engine@<my-project>.iam.gserviceaccount.com does not have storage.objects.get access to nextflow-text-bucket/work/10/521c6ad2bec00fa0a641c85de72f51."
}
```

So it's probably not service account. Since it throws a fit with this directly. That means the roles to my `uploader` service account are correct, and that makes me think it may not be a service account issue.

**2. com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden**

This is the main error that I can find through the logs. And this seems to start at ` nextflow.cloud.google.lifesciences.GoogleLifeSciencesHelper.runPipeline(GoogleLifeSciencesHelper.groovy:236)` so something may not be parsed correctly. 

If this problem can not be reproduced, I suppose the only problem could be my service account. But the service account worked flawlessly with previous versions of Nextflow. And the only thing that's really changed is the **executor, enabled APIs, bootDiskSize, and NXF_VER**

Any guidance would be greatly appreciated!

**Comment by pditommaso** [comment]
Unable to replicate it.

**Comment by daudn** [comment]
Just gonna leave this here to let you know. It didn't like me using my custom service account, so I made a key of the default compute engine service account, and now it's working like a charm. 

I was confused since before this I was always using a custom service account. Must be a Google Lifesciences thing. Thanks anyway, bootDisk working perfectly!

**Comment by KevinDuringWork** [comment]
Hopefully this helps anyone searching for this error: 

From: _https://cloud.google.com/iam/docs/service-accounts-actas_

> To provide this ability, grant users a role that includes the iam.serviceAccounts.actAs permission, like the Service Account User role (roles/iam.serviceAccountUser). You can grant this role on the project or on the service account. For instructions, see [Managing service account impersonation](https://cloud.google.com/iam/docs/impersonating-service-accounts).
