### ISSUE TITLE
19.12.0-edge fails to run with "UnsatisfiedLinkError: no jansi in java.library.path"

### ISSUE THREAD

**Issue by DaGaMs** [nextflow-io/nextflow#1447]
### Expected behavior and actual behavior

`nextflow` should run and show CLI options

### Steps to reproduce the problem

Run `NXF_VER=19.12.0-edge nextflow`

### Program output 

```
[benjamin@rescomp1 Code]$ NXF_VER=19.12.0-edge nextflow
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path: [/apps/eb/skylake/software/Java/11.0.2/lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib], /tmp/libjansi-64.so (Permission denied)]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:184)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:142)
	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:37)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at org.codehaus.groovy.reflection.CachedField.getProperty(CachedField.java:55)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1804)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3797)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at nextflow.cli.CliOptions.getAnsiLog(CliOptions.groovy:109)
	at nextflow.util.LoggerHelper.createConsoleAppender(LoggerHelper.groovy:237)
	at nextflow.util.LoggerHelper.setup(LoggerHelper.groovy:181)
	at nextflow.util.LoggerHelper.configureLogger(LoggerHelper.groovy:338)
	at nextflow.cli.Launcher.command(Launcher.groovy:386)
	at nextflow.cli.Launcher.main(Launcher.groovy:634)
```

### Environment 

* Nextflow version: 19.12.0-edge
* Java version: OpenJDK 11.0.2, Oracle Java 10.0.1
* Operating system: Linux

### Additional context

19.11.0-edge works fine

**Comment by pditommaso** [comment]
Ouch, I think this is a side-effect #1417

**Comment by pditommaso** [comment]
The following error message is suspect: 

```
/tmp/libjansi-64.so (Permission denied)
```

Are you using any docker/Kubernetes environment?

**Comment by DaGaMs** [comment]
Not that I'm aware of. This is a shared environment, ie the login node of a compute cluster. Maybe someone else created that?

**Comment by pditommaso** [comment]
It could, may you check?

**Comment by DaGaMs** [comment]
`NXF_ANSI_LOG=false NXF_VER=19.12.0-edge nextflow` works.

**Comment by DaGaMs** [comment]
And one more piece of information: we just figured out that this works: `TMPDIR=$HOME NXF_VER=19.12.0-edge nextflow`

It seems that libjansi sometimes insists to write a new copy of the library to the system-wide temp dir...

**Comment by pditommaso** [comment]
There's some discussion here https://github.com/java-native-access/jna/issues/985#issuecomment-403609353

**Comment by DaGaMs** [comment]
Strange, I don't understand why we didn't get the hashed library name. `USER` is set in the environment, `whoami` gives a nice unique username... There's no obvious reason why it's producing a non-hashed `libjansi-64.so`

**Comment by pditommaso** [comment]
Apparently it's not using the user name, this is the decompiled code 

```
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.regex.Pattern;

public class Library {
    static final String SLASH = System.getProperty("file.separator");
    private final String name;
    private final String version;
    private final ClassLoader classLoader;
    private boolean loaded;

    public Library(String name) {
        this(name, (String)null, (ClassLoader)null);
    }

    public Library(String name, Class<?> clazz) {
        this(name, version(clazz), clazz.getClassLoader());
    }

    public Library(String name, String version) {
        this(name, version, (ClassLoader)null);
    }

    public Library(String name, String version, ClassLoader classLoader) {
        if (name == null) {
            throw new IllegalArgumentException("name cannot be null");
        } else {
            this.name = name;
            this.version = version;
            this.classLoader = classLoader;
        }
    }

    private static String version(Class<?> clazz) {
        try {
            return clazz.getPackage().getImplementationVersion();
        } catch (Throwable var2) {
            return null;
        }
    }

    public static String getOperatingSystem() {
        String name = System.getProperty("os.name").toLowerCase().trim();
        if (name.startsWith("linux")) {
            return "linux";
        } else if (name.startsWith("mac os x")) {
            return "osx";
        } else {
            return name.startsWith("win") ? "windows" : name.replaceAll("\\W+", "_");
        }
    }

    public static String getPlatform() {
        return getOperatingSystem() + getBitModel();
    }

    public static int getBitModel() {
        String prop = System.getProperty("sun.arch.data.model");
        if (prop == null) {
            prop = System.getProperty("com.ibm.vm.bitmode");
        }

        return prop != null ? Integer.parseInt(prop) : -1;
    }

    public synchronized void load() {
        if (!this.loaded) {
            this.doLoad();
            this.loaded = true;
        }
    }

    private void doLoad() {
        String version = System.getProperty("library." + this.name + ".version");
        if (version == null) {
            version = this.version;
        }

        ArrayList<String> errors = new ArrayList();
        String customPath = System.getProperty("library." + this.name + ".path");
        if (customPath != null) {
            if (version != null && this.load(errors, this.file(customPath, this.map(this.name + "-" + version)))) {
                return;
            }

            if (this.load(errors, this.file(customPath, this.map(this.name)))) {
                return;
            }
        }

        if (version == null || !this.load(errors, this.name + getBitModel() + "-" + version)) {
            if (version == null || !this.load(errors, this.name + "-" + version)) {
                if (!this.load(errors, this.name)) {
                    if (this.classLoader != null) {
                        if (this.exractAndLoad(errors, version, customPath, this.getPlatformSpecifcResourcePath())) {
                            return;
                        }

                        if (this.exractAndLoad(errors, version, customPath, this.getOperatingSystemSpecifcResourcePath())) {
                            return;
                        }

                        if (this.exractAndLoad(errors, version, customPath, this.getResorucePath())) {
                            return;
                        }
                    }

                    throw new UnsatisfiedLinkError("Could not load library. Reasons: " + errors.toString());
                }
            }
        }
    }

    public final String getOperatingSystemSpecifcResourcePath() {
        return this.getPlatformSpecifcResourcePath(getOperatingSystem());
    }

    public final String getPlatformSpecifcResourcePath() {
        return this.getPlatformSpecifcResourcePath(getPlatform());
    }

    public final String getPlatformSpecifcResourcePath(String platform) {
        return "META-INF/native/" + platform + "/" + this.map(this.name);
    }

    public final String getResorucePath() {
        return "META-INF/native/" + this.map(this.name);
    }

    public final String getLibraryFileName() {
        return this.map(this.name);
    }

    private boolean exractAndLoad(ArrayList<String> errors, String version, String customPath, String resourcePath) {
        URL resource = this.classLoader.getResource(resourcePath);
        if (resource != null) {
            String libName = this.name + "-" + getBitModel();
            if (version != null) {
                libName = libName + "-" + version;
            }

            File target;
            if (customPath != null) {
                target = this.file(customPath, this.map(libName));
                if (this.extract(errors, resource, target) && this.load(errors, target)) {
                    return true;
                }
            }

            customPath = System.getProperty("java.io.tmpdir");
            target = this.file(customPath, this.map(libName));
            if (this.extract(errors, resource, target) && this.load(errors, target)) {
                return true;
            }
        }

        return false;
    }

    private File file(String... paths) {
        File rc = null;
        String[] arr$ = paths;
        int len$ = paths.length;

        for(int i$ = 0; i$ < len$; ++i$) {
            String path = arr$[i$];
            if (rc == null) {
                rc = new File(path);
            } else {
                rc = new File(rc, path);
            }
        }

        return rc;
    }

    private String map(String libName) {
        libName = System.mapLibraryName(libName);
        String ext = ".dylib";
        if (libName.endsWith(ext)) {
            libName = libName.substring(0, libName.length() - ext.length()) + ".jnilib";
        }

        return libName;
    }

    private boolean extract(ArrayList<String> errors, URL source, File target) {
        FileOutputStream os = null;
        InputStream is = null;
        boolean extracting = false;

        try {
            if (!target.exists() || this.isStale(source, target)) {
                is = source.openStream();
                if (is != null) {
                    byte[] buffer = new byte[4096];
                    os = new FileOutputStream(target);
                    extracting = true;

                    int read;
                    while((read = is.read(buffer)) != -1) {
                        os.write(buffer, 0, read);
                    }

                    os.close();
                    is.close();
                    this.chmod("755", target);
                }
            }

            return true;
        } catch (Throwable var11) {
            try {
                if (os != null) {
                    os.close();
                }
            } catch (IOException var10) {
            }

            try {
                if (is != null) {
                    is.close();
                }
            } catch (IOException var9) {
            }

            if (extracting && target.exists()) {
                target.delete();
            }

            errors.add(var11.getMessage());
            return false;
        }
    }

    private boolean isStale(URL source, File target) {
        if (source.getProtocol().equals("jar")) {
            try {
                String[] parts = source.getFile().split(Pattern.quote("!"));
                source = new URL(parts[0]);
            } catch (MalformedURLException var4) {
                return false;
            }
        }

        File sourceFile = null;
        if (source.getProtocol().equals("file")) {
            sourceFile = new File(source.getFile());
        }

        return sourceFile != null && sourceFile.exists() && sourceFile.lastModified() > target.lastModified();
    }

    private void chmod(String permision, File path) {
        if (!getPlatform().startsWith("windows")) {
            try {
                Runtime.getRuntime().exec(new String[]{"chmod", permision, path.getCanonicalPath()}).waitFor();
            } catch (Throwable var4) {
            }

        }
    }

    private boolean load(ArrayList<String> errors, File lib) {
        try {
            System.load(lib.getPath());
            return true;
        } catch (UnsatisfiedLinkError var4) {
            errors.add(var4.getMessage());
            return false;
        }
    }

    private boolean load(ArrayList<String> errors, String lib) {
        try {
            System.loadLibrary(lib);
            return true;
        } catch (UnsatisfiedLinkError var4) {
            errors.add(var4.getMessage());
            return false;
        }
    }
}
```

**Comment by pditommaso** [comment]
There's little it can be done on NF side. My understanding is that you have fixed changing the jansi temp lib file permission.

**Comment by s-andrews** [comment]
We've also just hit this issue with the latest nextflow-20.01.0-edge-all.

This is on a pretty stock CentOS 7 system.  To reproduce just do:

```
./nextflow-20.01.0-edge-all
```

which works and brings up the expected help file.  Now switch to a different user and try again, and it will fail.

The issue is that nextflow is writing out /tmp/libjansi-64.so into the top level of /tmp with permissions like:

```
-rwxr-xr-x 1 andrewss bioinf 48340 Feb  4 10:16 /tmp/libjansi-64.so
```

which means that this isn't usable by other users and they can't overwrite it.  Because the path is the same for all users then this causes it to fail.

If I set ```$TEMP``` to a different location I can get it to work for multiple users, but I don't really want to make such a big change to the environment to get this working.

According to the other linked thread this shouldn't be happening.  The native java code *should* write a new *directory* into ```java.io.tmpdir``` with a name containing a hash of the username, so clashes should never occur.  This doesn't happen with the bundled nextflow code and the file is written directly into tmpdir, so either that thread isn't concurrent with the version of the java library which is bundled with nextflow (but the other thread suggests this is at least 5 years old so that seems unlikely), or something else about the environment it operates in is causing this to not work in the way it is supposed to.  

Changing the permissions on the first extracted libjansi would work, but it's a pain on a cluster where every node will need to be modified, and given that /tmp will be cleaned up regularly it will need to be re-done.  Having users share libraries like this is would also be a pretty nasty security concern.

**Comment by pditommaso** [comment]
Unfortunately, NF code has no control where that lib in uncompressed. 

However, I think this is a side effect of changes introduced by #1417.  I'll rever it.

**Comment by s-andrews** [comment]
Is there an easy way to isolate the code which causes this file to be created so I can follow this up with the upstream project?  I presume it's some code which uses the JNI library, but I can't immediately see the path through which this happens.  

If I can make a simple test case outside of nextflow then I can chase it up at the appropriate level.

**Comment by pditommaso** [comment]
This this commit https://github.com/nextflow-io/nextflow/commit/11fcb0af907fb1e1fecf1f0e8fa549e2adad0ed6

**Comment by s-andrews** [comment]
Thanks!  That should do it.
