### ISSUE TITLE
nextflow initiall installation error

### ISSUE THREAD

**Issue by yan-cri** [nextflow-io/nextflow#1501]
Hi, 

After successfully install nextflow on our HPC system, I can see Java is available with version 
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

But when I tried to execute nextflow first script 'tutorial.nf', I got error message as below:

```
N E X T F L O W  ~  version 20.01.0
Launching `tutorial.nf` [stupefied_davinci] - revision: e3b475a61b
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.AnsiConsole
	at nextflow.trace.AnsiLogObserver.printAnsi(AnsiLogObserver.groovy:322)
	at nextflow.trace.AnsiLogObserver.printAnsi(AnsiLogObserver.groovy)
	at nextflow.trace.AnsiLogObserver.appendError(AnsiLogObserver.groovy:139)
	at nextflow.util.LoggerHelper$CaptureAppender.append(LoggerHelper.groovy:626)
	at nextflow.util.LoggerHelper$CaptureAppender.append(LoggerHelper.groovy)
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.error(Logger.java:538)
	at nextflow.cli.Launcher.run(Launcher.groovy:508)
	at nextflow.cli.Launcher.main(Launcher.groovy:642)
```

It seems that no other people has reported this issue before, could you please let me know what cause me to run into this issue? Thanks!

**Comment by pditommaso** [comment]
Can you trying downgrading to version `19.10.0` e.g.

```
NXF_VER=19.10.0 nextflow run tutorial.nf
```

**Comment by yan-cri** [comment]
Yes, once specifying the version 19.10.0, it runs properly. In this case, what cause this? How can I run it with version 20.01.0?

**Comment by pditommaso** [comment]
It looks that this issue is related to the jline library update. Rolling back to version `2.9`. If you want to use a NF version newer than 19.10.0 you will need to make your own custom build or wait for the upcoming release.
