### ISSUE TITLE
Support for other platforms

### ISSUE THREAD

**Issue by jrziviani** [nextflow-io/nextflow#1505]
Hello,

I'm trying to build Nextflow on **PowerPC64 little-endian** but **jansi** depends on a native library and Gradle + mavenCentral() provides it for x86 only[1]. Actually, we have jansi.jar for ppc64le (installed by the distro package manager), but I didn't find a way to use it like:
```
if platform == ppc64le
    groovyDoc '/path/to/libs/jansi.jar'
else
    groovyDoc 'org.fusesource.jansi:jansi:1.11'
endif
```

Any suggestion to make the build system more flexible for other platforms?

Thank you very much!!
```
[1] java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, /tmp/libjansi-64-6981983611386091310.so: /tmp/libjansi-64-6981983611386091310.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a Power PC 64 LE-bit platform)]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        ...
```

**Comment by jrziviani** [comment]
It might be related to https://github.com/nextflow-io/nextflow/issues/1501

**Comment by pditommaso** [comment]
What's the real need for PowerPC64 architecture?

**Comment by pditommaso** [comment]
It looks stalled. Closing.
