### ISSUE TITLE
Capsule not extracted. Unable to initialize nextflow environment

### ISSUE THREAD

**Issue by ojziff** [nextflow-io/nextflow#1518]
I am unable to run Nextflow on my HPC because of an error with Capsule extraction. This seems to be a problem with Capsule.java cache directory: https://github.com/puniverse/capsule/blob/291a54e501a32aaf0284707b8c1fbff6a566822b/capsule/src/main/java/Capsule.java#L2078 

Do you know what is causing this and how I can solve it?

Many thanks,
Oliver

**Environment**
Java 8.0.92
Nextflow 19.10.0
OS: Linux

**Error**
```
$ nextflow -Dcapsule.log=verbose info
CAPSULE: Jar: /camp/apps/eb/software/Nextflow/19.10.0/bin/nextflow-19.10.0-all
CAPSULE: Platform: linux
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: nextflow-all_19.10.0
CAPSULE: Launching app nextflow-all_19.10.0
CAPSULE: WARNING resolve [] was empty
CAPSULE: Cache directory: /camp/home/ziffo/.nextflow/capsule
CAPSULE: Creating temp file/dir /camp/home/ziffo/.nextflow/capsule/apps/nextflow-all_19.10.0/.lock
CAPSULE: Locking /camp/home/ziffo/.nextflow/capsule/apps/nextflow-all_19.10.0/.lock
CAPSULE: Extracting /camp/apps/eb/software/Nextflow/19.10.0/bin/nextflow-19.10.0-all to app cache directory /camp/home/ziffo/.nextflow/capsule/apps/nextflow-all_19.10.0
CAPSULE: IOException while creating app cache: Exception while extracting jar /camp/apps/eb/software/Nextflow/19.10.0/bin/nextflow-19.10.0-all to app cache directory /camp/home/ziffo/.nextflow/capsule/apps/nextflow-all_19.10.0
java.io.IOException: Exception while extracting jar /camp/apps/eb/software/Nextflow/19.10.0/bin/nextflow-19.10.0-all to app cache directory /camp/home/ziffo/.nextflow/capsule/apps/nextflow-all_19.10.0
	at Capsule.extractCapsule(Capsule.java:2132)
	at Capsule.buildAppCacheDir0(Capsule.java:2073)
	at Capsule.buildAppCacheDir(Capsule.java:2056)
	at Capsule.getOrCreateAppDir(Capsule.java:2004)
	at Capsule.appDir(Capsule.java:2016)
	at Capsule.simpleResolve(Capsule.java:3501)
	at Capsule.resolve00(Capsule.java:3490)
	at Capsule.resolve0(Capsule.java:3402)
	at Capsule.resolve(Capsule.java:3375)
	at Capsule.resolve00(Capsule.java:3421)
	at Capsule.resolve0(Capsule.java:3402)
	at Capsule.resolve(Capsule.java:3375)
	at Capsule.resolve(Capsule.java:3389)
	at Capsule.buildJavaProcess(Capsule.java:2228)
	at Capsule.buildProcess0(Capsule.java:1530)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.prelaunch0(Capsule.java:1494)
	at Capsule.prelaunch(Capsule.java:1487)
	at CapsuleLoader.prelaunch(CapsuleLoader.java:41)
	at Capsule.prepareForLaunch(Capsule.java:1339)
	at Capsule.launch(Capsule.java:1268)
	at Capsule.main0(Capsule.java:399)
	at Capsule.main(Capsule.java:379)
Caused by: java.io.IOException: Disk quota exceeded
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:101)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at java.nio.file.Files.copy(Files.java:2909)
	at java.nio.file.Files.copy(Files.java:3027)
	at Capsule.writeFile(Capsule.java:3918)
	at Capsule.extractJar(Capsule.java:3558)
	at Capsule.extractCapsule(Capsule.java:2130)
	... 22 more
CAPSULE: Cleanup
CAPSULE EXCEPTION: Capsule not extracted. while processing attribute App-Class-Path: [/camp/apps/eb/software/Nextflow/19.10.0/bin/nextflow-19.10.0-all, [nf-ignite-19.10.0.jar, nf-tower-19.10.0.jar, nextflow-19.10.0.jar, ivy-2.3.0.jar, nf-commons-19.10.0.jar, nf-httpfs-19.10.0.jar, groovy-nio-2.5.8.jar, groovy-templates-2.5.8.jar, groovy-xml-2.5.8.jar, groovy-json-2.5.8.jar, groovy-2.5.8.jar, jcl-over-slf4j-1.7.25.jar, jul-to-slf4j-1.7.25.jar, log4j-over-slf4j-1.7.25.jar, logback-classic-1.1.11.jar, logback-core-1.1.11.jar, gpars-1.2.1.jar, grengine-1.3.0.jar, commons-lang-2.6.jar, jcommander-1.35.jar, kryo-2.24.0.jar, leveldb-0.10.jar, org.eclipse.jgit-5.2.1.201812262042-r.jar, nxf-s3fs-1.0.7.jar, ignite-aws-2.4.0.jar, aws-java-sdk-s3-1.11.542.jar, aws-java-sdk-ec2-1.11.542.jar, aws-java-sdk-batch-1.11.542.jar, aws-java-sdk-iam-1.11.542.jar, mail-1.4.7.jar, activation-1.1.1.jar, snakeyaml-1.18.jar, jsoup-1.11.2.jar, jline-2.9.jar, ignite-slf4j-2.4.0.jar, ignite-core-2.4.0.jar, guava-21.0.jar, slf4j-api-1.7.25.jar, multiverse-core-0.7.0.jar, jsr166y-1.7.0.jar, objenesis-2.1.jar, leveldb-api-0.10.jar, jsch-0.1.54.jar, jzlib-1.1.1.jar, JavaEWAH-1.1.6.jar, aws-java-sdk-kms-1.11.542.jar, aws-java-sdk-elasticloadbalancing-1.11.75.jar, aws-java-sdk-core-1.11.542.jar, jmespath-java-1.11.542.jar, cache-api-1.0.0.jar, annotations-13.0.jar, ignite-shmem-1.0.0.jar, jackson-databind-2.6.7.2.jar, jackson-dataformat-cbor-2.6.7.jar, jackson-core-2.6.7.jar, jackson-annotations-2.6.5.jar, joda-time-2.8.1.jar, httpclient-4.5.5.jar, httpcore-4.4.9.jar, commons-codec-1.10.jar, ion-java-1.0.2.jar]]
java.lang.IllegalStateException: Capsule not extracted.
	at Capsule.appDir(Capsule.java:2025)
	at Capsule.simpleResolve(Capsule.java:3501)
	at Capsule.resolve00(Capsule.java:3490)
	at Capsule.resolve0(Capsule.java:3402)
	at Capsule.resolve(Capsule.java:3375)
	at Capsule.resolve00(Capsule.java:3421)
	at Capsule.resolve0(Capsule.java:3402)
	at Capsule.resolve(Capsule.java:3375)
	at Capsule.resolve(Capsule.java:3389)
	at Capsule.buildJavaProcess(Capsule.java:2228)
	at Capsule.buildProcess0(Capsule.java:1530)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.prelaunch0(Capsule.java:1494)
	at Capsule.prelaunch(Capsule.java:1487)
	at CapsuleLoader.prelaunch(CapsuleLoader.java:41)
	at Capsule.prepareForLaunch(Capsule.java:1339)
	at Capsule.launch(Capsule.java:1268)
	at Capsule.main0(Capsule.java:399)
	at Capsule.main(Capsule.java:379)
Unable to initialize nextflow environment
```

**Comment by pditommaso** [comment]
Oops 

```
Caused by: java.io.IOException: Disk quota exceeded
```

**Comment by drpatelh** [comment]
Yes, thats exactly it. Its because you need to soft-link `.nextflow` and `.singularity` from `working` to your `~` directory. Your `$HOME` directory on CAMP is only `5GB` by default and thats why I believe you are getting that error.

**Comment by ojziff** [comment]
Thank you both! Now its running with the soft-link.

**Comment by pditommaso** [comment]
👍
