### ISSUE TITLE
Start-up failure when moving to OpenJDK13 from 11/12, possibly related to Capsule dependency

### ISSUE THREAD

**Issue by denis-yuen** [nextflow-io/nextflow#1522]
### Expected behavior and actual behavior

Expected, can run Nextflow 19 and 20 with openjdk 11/12, would expect the same with openjdk13
```
$ /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /home/dyuen/.dockstore/libraries/nextflow-19.01.0-all config -properties
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/home/dyuen/.dockstore/libraries/nextflow-19.01.0-all) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/dyuen/.capsule/apps/nextflow-all_19.01.0/groovy-2.5.5.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
manifest.homePage=http\://tcoffee.crg.cat/apps/ampa/
manifest.mainScript=ampa.nf
manifest.description=Fast automated prediction of protein antimicrobial regions
process.container=cbcrg/ampa-nf
$ echo $?
0
```

Actual
```
$ java -jar /home/dyuen/.dockstore/libraries/nextflow-19.01.0-all config -properties
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/home/dyuen/.dockstore/libraries/nextflow-19.01.0-all) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/dyuen/.capsule/apps/nextflow-all_19.01.0/groovy-2.5.5.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR ~ Unable to parse config file: '/tmp/nextflow8938251735572763708/nextflow.config'

  Compile failed for sources FixedSetSources[name='/groovy/script/Script794364F6D840D63EAD4A96124BC157E1/_nf_config_49e8356d']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  General error during semantic analysis: Unsupported class file major version 57
  
  java.lang.IllegalArgumentException: Unsupported class file major version 57
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)
  <snip>
$ echo $?
1
$ java -jar /home/dyuen/.dockstore/libraries/nextflow-20.01.0-all config -properties
CAPSULE EXCEPTION: capsule/com/sun/jmx/mbeanserver/JmxMBeanServer while processing null null: null (for stack trace, run with -Dcapsule.log=verbose)
$ echo $?
1
```

### Steps to reproduce the problem

```
$ cat nextflow.config 
manifest {
  mainScript = 'ampa.nf'
  description = 'Fast automated prediction of protein antimicrobial regions'
  homePage = 'http://tcoffee.crg.cat/apps/ampa/'
}

process {
  container = 'cbcrg/ampa-nf'
}
```

### Environment 

* Nextflow version: 19 and 20
* Java version: 11/12 (works) and moving to 13 (fails)
* Operating system: Ubuntu

### Additional context
https://github.com/puniverse/capsule/issues/129
https://github.com/nextflow-io/nextflow/commit/6e54714b84f5bdcf3c53fffcc41a1acf34981b1f

Is it perhaps possible to workaround by launching without capsule?

**Comment by pditommaso** [comment]
Thanks for reporting this. So far, Nextflow support Java version 8 to 11 (last LTS) version.

**Comment by denis-yuen** [comment]
If it helps others, I would say that in our testing it seems like most(all?) of Nextflow does seem to work with Java 12 (OpenJDK).

**Comment by pditommaso** [comment]
True. However, there's an issue with the Ignite executor on Java 12.
