### ISSUE TITLE
publishDir throws FileAlreadyExistsException

### ISSUE THREAD

**Issue by joshamilton** [nextflow-io/nextflow#1538]
With directive 

publishDir "${params.annotated_genome_directory}/", mode: 'copy', overwrite: true

a new pipeline run should overwrite any pre-existing files, but it raises an java.nio.file.FileAlreadyExistsException. I see this has been reported and fixed in issues 163 and  283. I am writing to AWS S3.

The logfile:

Mar-20 23:46:33.032 [FileTransfer-thread-5] WARN  nextflow.processor.PublishDir - Failed to publish file: /home/ec2-user/genome_annotation/work/38/31c46b264a557c1d\
443f94b1608a3f/test001; to: /andoria.fedbio/annotated_genomes/test001 [copy] -- See log file for details
java.nio.file.FileAlreadyExistsException: /andoria.fedbio/annotated_genomes/test001/proteins.00.phr
        at com.upplication.s3fs.S3FileSystemProvider.newOutputStream(S3FileSystemProvider.java:323)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.copy(Files.java:3016)
        at nextflow.file.CopyMoveHelper.copyFile(CopyMoveHelper.java:123)
        at nextflow.file.CopyMoveHelper.access$100(CopyMoveHelper.java:42)
        at nextflow.file.CopyMoveHelper$1.visitFile(CopyMoveHelper.java:167)
        at nextflow.file.CopyMoveHelper$1.visitFile(CopyMoveHelper.java:141)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at nextflow.file.CopyMoveHelper.copyDirectory(CopyMoveHelper.java:173)
        at nextflow.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:201)
        at nextflow.file.FileHelper.copyPath(FileHelper.groovy:866)
        at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:305)
        at nextflow.processor.PublishDir.processFile(PublishDir.groovy:283)
        at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:262)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
        at nextflow.processor.PublishDir$_apply_closure1.doCall(PublishDir.groovy:235)
        at nextflow.processor.PublishDir$_apply_closure1.call(PublishDir.groovy)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

The error occurs with Nextflow version 19.10.0 build 5170 and version 20.01.0 build 5264.

**Comment by pditommaso** [comment]
Unable to replicate

```
process foo {
  publishDir 's3://nf-ci-tests/foo/', mode: 'copy', overwrite: true
  output:
  path 'file.x'
  script:
  """
  echo ciao > file.x
  """
}
```

```
nextflow run t.nf 
nextflow run t.nf 
nextflow run t.nf -resume

aws s3 ls s3://nf-ci-tests/foo/
2020-04-06 15:45:01          0 
2020-04-06 15:45:02          5 file.x 
```

**Comment by joshamilton** [comment]
@pditommaso Requesting the issue be re-opened. Please see below for additional information and a new question.

This warning appears to be due to a race condition:

My pipeline contains two processes `run_prokka` and `run_emapper` each with a separate `publishDir` command

`run_prokka`: the `publishDir` directive pushes the entire output directory to S3. This directory contains some large files that are slow to transfer.

`run_emapper`: the `publishDir` directive pushes the entire output directory to S3. This directory contains the entire output from the `run_prokka` process, plus the new emapper files. Sometimes the `run_emapper` process finishes before the files from `run_prokka` finish transferring. This causes the warning.

I have identified these work-arounds:

Use a `publishDir` directive only at the end of the workflow

Remove the overwrite: true directive from the `run_emapper` and `process_dir` directives. This will push only the new files. But if annotation files from a previous run already exist on S3, nothing will get copied.

I have tried using the `saveAs` parameter to select only the new files from the `run_emapper` process, but the output directory is defined by a Groovy variable. The `saveAs` glob syntax does not support variables in the glob pattern.

Any other work-arounds, to ensure that only new files from the `run_emapper` process get pushed to S3?

**Comment by pditommaso** [comment]
No problem to re-open but I need a test case to replicate the issue.

**Comment by zillurbmb51** [comment]
Hi, I am having the same issue. It raises an java.nio.file.FileAlreadyExistsException. Here is my code and log file.
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/6754319/nextflow.log.txt)

```
ocess merging {
publishDir params.out, mode:'copy', overwrite: true
input:
val flag from done_ch
tuple val(chrom),path(bgens) from imputed
output:
tuple val("${chrom}"),path("${chrom}.*") into merged
script:
bgen_files = bgens.collect().findAll { it.toString().endsWith('.bgen') }.sort()
gen_files = bgens.collect().findAll { it.toString().endsWith('.gen.gz') }.sort()
sample_files = bgens.collect().findAll { it.toString().endsWith('.sample') }.sort()
stat_files = bgens.collect().findAll { it.toString().endsWith('.stats') }.sort()
"""
echo "${bgen_files.join(' ')}" > "${chrom}.step10.imputed.merged.bgen.txt"
echo "${gen_files.join(' ')}" > "${chrom}.step10.imputed.merged.gen.gz.txt"
echo "${sample_files.join(' ')}" > "${chrom}.step10.imputed.merged.sample.txt"
echo "${stat_files.join(' ')}" > "${chrom}.step10.imputed.merged.snp.stats.txt"
"""
}
```
