### ISSUE TITLE
Unsatisfied link error

### ISSUE THREAD

**Issue by Colorstorm** [nextflow-io/nextflow#1541]
### Expected behavior and actual behavior

When I try to use Nextflow it is unable to initalize a nextflow enviroment and throws a java unsatisfied link error(see below)
I am running Nextflow in a conda enviroment on a linux cluster. It hasn't run before. 
I solved a java error beforehand with downgrading my java version

### Steps to reproduce the problem
Use a conda enviroment(enviroment.yml File attached)
command: `nextflow run hello`

### Program output 

```
Picked up _JAVA_OPTIONS: -Dhttp.proxyHost=172.24.2.50 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=172.24.2.50 -Dhttps.proxyPort=8080
Exception in thread "main" java.lang.UnsatisfiedLinkError: /working2/rcug_lw/miniconda3/envs/nextflow/jre/lib/amd64/libnio.so: /working2/rcug_lw/miniconda3/envs/nextflow/jre/lib/amd64/../../../lib/libnet.so: undefined symbol: JNU_ThrowByNameWithMessageAndLastError
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1843)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:573)
        at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:571)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.nio.fs.UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:571)
        at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
        at sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
        at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:46)
        at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:39)
        at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
        at sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:41)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
        at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:63)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
        at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
        at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
        at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
        at java.nio.file.Paths.get(Paths.java:84)
        at Capsule.<clinit>(Capsule.java:234)
Unable to initialize nextflow environment

```

### Environment 

* Nextflow version: 20.01.0
* Java version: 1.8.0_45
* Operating system:  Ubuntu 16.04.6
* Bash version: GNU bash, version 4.3.48(1)

### Additional context

(Add any other context about the problem here)

[enviroment.yml.zip](https://github.com/nextflow-io/nextflow/files/4368779/enviroment.yml.zip)

**Comment by pditommaso** [comment]
Provide the error output please

**Comment by Colorstorm** [comment]
Sorry, I have updated the issue

**Comment by pditommaso** [comment]
Not sure how to help, it looks some messed java installation likely due to Conda related issue. It's not a NF issue. I'll suggest contacting your sysadmins.
