### ISSUE TITLE
worflow execution aborts upon 504 from tower

### ISSUE THREAD

**Issue by idot** [nextflow-io/nextflow#1609]
##### actual:

abort of workflow execution upon 504 from tower

##### expected:

complete the workflow without tower.  having logging is nice, but its important that the workflow runs and completes without tower if there is a problem with tower

### Steps to reproduce the problem

Its impossible to reproduce without fiddling with IT/firewalls

### Program output 

```
May-19 12:52:33.174 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
May-19 12:52:33.190 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
May-19 12:52:33.500 [main] DEBUG nextflow.Session - Session start invoked
May-19 12:52:33.507 [main] DEBUG io.seqera.tower.plugin.TowerClient - Creating Tower observer -- endpoint=https://api.tower.nf; requestInterval=1s; aliveInterval=1m; maxRetries=5; backOffBase=3; backOffDelay=250
May-19 12:52:43.706 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unexpected response code 504 for request https://api.tower.nf/trace/create
        at io.seqera.tower.plugin.TowerClient.onFlowCreate(TowerClient.groovy:233)
        at nextflow.Session$_notifyFlowCreate_closure21.doCall(Session.groovy:1002)
        at nextflow.Session$_notifyFlowCreate_closure21.call(Session.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356)
        at nextflow.Session.notifyFlowCreate(Session.groovy:1002)
        at nextflow.Session.start(Session.groovy:481)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:121)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:273)
        at nextflow.cli.Launcher.run(Launcher.groovy:460)
        at nextflow.cli.Launcher.main(Launcher.groovy:642)
```

### Environment 

* Nextflow version: 20.04.1-edge build 5333
* Java version: Java HotSpot(TM) 64-Bit Server VM 1.8.0_212-b10
* Operating system: Linux 3.10.0-1062.4.3.el7.x86_64
* Bash version: (use the command 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by pditommaso** [comment]
Is this happening consistently? does it happen also with the `nextflow run hello` mini pipeline?

**Comment by idot** [comment]
I started 100 jobs of nextflow run hello at ~8:30, 8:45, 8:58 today. Maybe
you see something in your logs.

The numbers of 504 were:
12
33
34

I don't know if this a problem in our local setup, if nobody else sees this.
I noticed this the first time 2-3 days ago.

**Comment by pditommaso** [comment]
This was caused by a Tower network issue. It's ok now. Sorry for the inconvenience.
