### ISSUE TITLE
Nextflow execution aborted - java.lang.OutOfMemoryError: Java heap space submitting 30k jobs 

### ISSUE THREAD

**Issue by justinjj24** [nextflow-io/nextflow#1620]
Bug report (?)

It seems nextflow master JVM might be running out of memory when attempting to execute a workflow that spreads computation over a very large (30,000) number of parallel processes.

**nextflow.log**
```
May-28 14:23:03.441 [Actor Thread 242] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
May-28 14:23:03.518 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 167738.wlm01; id: 13; name: GenomicsDB (13); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebayes-vcf_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/16/ca41bf8a7c91bf2737a1b27caa6668 started: 1590639193178; exited: 2020-05-28T05:59:57Z; ]
May-28 14:23:52.235 [Actor Thread 242] DEBUG nextflow.Session - Session aborted -- Cause: Java heap space
May-28 14:24:55.013 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 167739.wlm01; id: 25; name: GenomicsDB (25); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebayes-vcf_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/33/1bcacaf43e4db07993a00cd64f1a04 started: 1590639193197; exited: 2020-05-28T06:01:55Z; ]
May-28 14:24:55.036 [Actor Thread 242] DEBUG nextflow.Session - The following nodes are still active:
[process] GenomicsDB
  status=ACTIVE
  port 0: (value) bound ; channel: genome
  port 1: (value) bound ; channel: genome_index
  port 2: (value) bound ; channel: genome_dict
  port 3: (queue) OPEN  ; channel: -
  port 4: (cntrl) -     ; channel: $

[process] GenotypeGVF
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (value) bound ; channel: genome
  port 2: (value) bound ; channel: genome_index
  port 3: (value) bound ; channel: genome_dict
  port 4: (cntrl) -     ; channel: $
...................
...................
May-28 14:25:53.763 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 167741.wlm01; id: 12; name: GenomicsDB (12); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebayes-vcf_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/a6/fdaa6325dd06515373b914ded3ab02 started: 1590639193249; exited: 2020-05-28T06:05:10Z; ]
May-28 14:26:20.568 [main] DEBUG nextflow.Session - Session await > all process finished
May-28 14:26:20.569 [main] DEBUG nextflow.Session - Session await > all barriers passed
May-28 14:26:53.714 [Actor Thread 238] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
        at groovyjarjarasm.asm.ByteVector.enlarge(ByteVector.java:357)
        at groovyjarjarasm.asm.ByteVector.putUTF8(ByteVector.java:250)
        at groovyjarjarasm.asm.SymbolTable.addConstantUtf8(SymbolTable.java:774)
................
................
May-28 14:27:20.941 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 167742.wlm01; id: 23; name: GenomicsDB (23); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebayes-
vcf_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/95/767b8ee9dec82dc21239faffacc20d started: 1590639193267; exited: 2020-05-28T05:59:29Z; ]
May-28 14:27:20.959 [Actor Thread 283] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
May-28 14:27:20.975 [Actor Thread 277] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
May-28 14:27:20.976 [Actor Thread 275] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
        at java.lang.String.substring(String.java:1969)
        at groovyjarjarasm.asm.Frame.getAbstractTypeFromDescriptor(Frame.java:332)
...................
...................
May-28 14:27:53.160 [Actor Thread 282] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
May-28 14:27:53.173 [Actor Thread 302] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
        at groovyjarjarasm.asm.SymbolTable.<init>(SymbolTable.java:124)
        at groovyjarjarasm.asm.ClassWriter.<init>(ClassWriter.java:238)
..................
..................
May-28 14:31:47.453 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 167750.wlm01; id: 5; name: GenomicsDB (5); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebayes-vc
f_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/4d/3e628e56c00ac37c7aaf2a85e6f565 started: 1590639806918; exited: 2020-05-28T06:14:21Z; ]
May-28 14:32:38.192 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (486)
May-28 14:32:38.211 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 167751.wlm01; id: 20; name: GenomicsDB (20); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebayes-
vcf_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/bd/72e6cc3edb20f0857fbe6a51bdf527 started: 1590640362792; exited: 2020-05-28T06:17:08Z; ]
May-28 14:42:05.676 [main] DEBUG nextflow.Session - Failed to execute shutdown hook: 
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'BatchCleanup[
' with class 'java.lang.String' to class 'java.lang.StringBuilder'
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:415)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:329)
        at org.codeha
...................
...................
May-28 14:47:52.107 [Task submitter] INFO  nextflow.Session - [35/63e67c] Submitted process > GenomicsDB (531)
May-28 14:47:52.120 [main] WARN  nextflow.trace.ReportObserver - Failed to render execution report -- see the log file for details
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)

.....................
......................  
```
### Some background information about the workflow which triggered this JVM memory consumption issue :

- we seek to perform gVCF joint-calling following GTAK4 best-practices, the central tenet of which leverage on loading all gVCF files into genomicsDB to then be efficiently read back as a whole on genome-regions slices

- the very same workflow successfully completed when the `channel` definition will results in upward of 3000 concurrent `processes` to be translated into scheduler jobs

- the workflow gets executed as jobs submitted to a PBS scheduler

- having reached some limitation in term of memory available on our HPC cluster nodes, we sought to increase the number of genome-regions slices

- the channel creation, resulting in either successfully completed 3,000 or failing to complete 30,000 identical tasks is as follows
```
idx = 1
region_list_ch = Channel
     .fromPath(calling_interval_list)
     .splitText().filter{ ! it.startsWith("@") }
     .map{ reg_list -> tuple("r" + idx++, reg_list.split('\t')[0..2]) }
Channel.from(params.sample_name_map.values())
    .flatMap { it -> tuple(file(it), file(it + ".tbi")) }
    .set { gvcfs_ch } 

region_and_gvcf_ch = region_list_ch.combine(gvcfs_ch.collect().toList() )
```
- the process which uses the channel above as input (and triggers the abortion of the nextflow execution upon seeking a scattering over 30,000+ process) is as follows
```
process GenomicsDB {
   input:
   file(genome)
   file(genome_index)
   file(genome_dict)
   set region_no, region_list, file(gvcfs) from region_and_gvcf_ch

   output: 
   // main output is a directory
   set region_no, file("ws-reg-${region_no}") into genomicsdb_ch

   script:
   //sample_name_map_str = gen_sample_map_str()
   bed_str = region_list.join("\t").replace(",", "\t").replace("-", "\t")
   """
   echo "${bed_str}" > reg-${region_no}.bed;
   # printf to avoid newline at end, which GenomicsDBImport is allergic to
   # printf '%s'
   echo "${sample_name_map_str}" > sample_map.csv
   ls -l
   gatk --java-options "-Xmx${task.memory.toGiga() -4}G -XX:ConcGCThreads=${task.cpus} -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=${task.cpus} " \
       GenomicsDBImport --batch-size 3500 --sample-name-map sample_map.csv --genomicsdb-workspace-path ws-reg-${region_no} --intervals reg-${region_no}.bed
   """
}
```
### Why we suspect the error JVM memory consumption issue is triggered at nextflow's master-level rather than tasks-level** :

- the very same workflow successfully completed when the `channel` definition will results in upward of 3000 concurrent `processes` to be translated into scheduler jobs

- nextflow seems to happily proceed and processes are submitted to the scheduler creating 100+ jobs.The first batch of submitted jobs successfully complete.

- No jobs ever report as failed neither as per `trace.txt` nor as per individual `.command.log` files

We thus suspect the error
```
...May-28 14:26:53.714 [Actor Thread 238] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
```
to be triggered by nextflow master
### How we tried but failed to remedy to this issue

- note that the node on which the nextflow master is run has >500Gb or RAM

- Suspecting the JVM memory consumption issue is triggered at nextflow's master-level rather than tasks-level, we tried to alter the amount of memory JAVA is allowed to consume altering

- - `NXT_OPTS` and `_JAVA_OPTS` in `~/.bashrc` and `nextflow.config`

- in `nextflow.config`

```
env {
  NXF_OPTS="Xms2g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError"
  NXF_DEBUG="1"
  NXF_JAVA_HOME="/data/13000026/pipeline/dev/jointvarinatcalling/java-jdk-apr1/bin"
}
```
in nextflow's `profile`
```
mail {
  smtp.host = 'localhost'
  smtp.user = 'NSCC'
}

executor {
   name = 'pbspro'
   queueSize = 500
   pollInterval = '300 sec'
   cpus = 4
   memory = '2 GB'
}

singularity {
    enabled = true
    cacheDir = '/data/users/astar/gis/rpd/containers/'
}
process.container = singularity.cacheDir + '/' + params.container
process {   
    module = 'singularity/2.5.1'
    queue = 'production'
    maxRetries = 2
    errorStrategy = { task.attempt < 2 ? 'retry' : 'finish' }
    clusterOptions = "-P 1300xxxx"
    memory = '80 GB'
    cpus = 4
}
```
- `base.config`
```
  withName:GenomicsDB {
        time = '48 h'
        cpus = 4
        memory = '80 GB'
    }
```
### Environment
```
java -version
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-linux64) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-linux64) (build 25.92-b15, mixed mode)

nextflow
version 20.01.0 build 5264
created 12-02-2020 10:14 UTC (18:14 SGST)
cite doi:10.1038/nbt.3820
http://nextflow.io

PBS scheduler
```
Thanks in advance for your help and input. Justin

**Comment by anoronh4** [comment]
Did you ever see resolution to this problem? i agree with you that it is a "master-level" problem as you put it, but i noticed that you only tried since you have 500Gb where the nextflow master is run, so you have ample room to push up the used memory. running `-Xms20g -Xmx20g` might yield better performance.
