### ISSUE TITLE
NoSuchFileException and FileAlreadyExistsException

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#1683]
I am running nextflow `20.04.1`.  I am re-running my workflow (as I iteratively add to it and debug it).

I am getting two strange errors on each execution from cached processes.  First, I am setting the following in the processes:
```
process foo {
    publishDir "$params.output_dir", mode: 'copy', overwrite: true
    ...
}
```

### NoSuchFileException

Why is it complaining about the target not existing?

```
Jul-21 20:20:23.059 [FileTransfer-thread-9] WARN  nextflow.processor.PublishDir - Failed to publish file: /path/to/source to: /path/to/target [copy] -- See log file for details
java.nio.file.NoSuchFileException: /path/to/target
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
    at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
    at java.nio.file.Files.delete(Files.java:1126)
    at nextflow.file.FileHelper.deletePath(FileHelper.groovy:901)
    at nextflow.processor.PublishDir.processFile(PublishDir.groovy:279)
    at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:259)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
    at nextflow.processor.PublishDir$_apply1_closure1.doCall(PublishDir.groovy:232)
    at nextflow.processor.PublishDir$_apply1_closure1.call(PublishDir.groovy)
    at groovy.lang.Closure.run(Closure.java:486)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

### FileAlreadyExistsException

In the directive above, I set `overwrite: true`, so why is it warning me that it already exists?

```
Jul-21 20:20:23.227 [FileTransfer-thread-1] WARN  nextflow.processor.PublishDir - Failed to publish file: /path/to/source; to: /path/to/target [copy] -- See log file for details
java.nio.file.FileAlreadyExistsException: /path/to/target
    at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)
    at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
    at nextflow.file.FileHelper.copyPath(FileHelper.groovy:875)
    at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:302)
    at nextflow.processor.PublishDir.processFile(PublishDir.groovy:280)
    at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:259)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
    at nextflow.processor.PublishDir$_apply1_closure1.doCall(PublishDir.groovy:232)
    at nextflow.processor.PublishDir$_apply1_closure1.call(PublishDir.groovy)
    at groovy.lang.Closure.run(Closure.java:486)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by pditommaso** [comment]
Maybe be related to this https://github.com/nextflow-io/nextflow/commit/5f3b69c19e70e9245aba25ca668d7905eea09cb6. Try using `20.06.0-edge`.

**Comment by nh13** [comment]
@pditommaso fixed in the latest master branch

**Comment by nh13** [comment]
@pditommaso would love a release with the fix to this included so I can install via conda.  I think the last release was May 3rd I believe, so perhaps it's time?  No worries if not.

**Comment by pditommaso** [comment]
There were two releases more and latest stable expected within the week. 

https://github.com/nextflow-io/nextflow/releases

**Comment by nh13** [comment]
Thanks! GitHub doesn’t show pre-releases as the latest “release”.  I guess it only shows “stable”.
