### ISSUE TITLE
Cannot install nextflow

### ISSUE THREAD

**Issue by yunfeiguo** [nextflow-io/nextflow#1718]
### Expected behavior and actual behavior

install latest version of nextflow

### Steps to reproduce the problem

```
curl -s https://get.nextflow.io | bash
```
### Program output 

see attachment

### Environment 

* Nextflow version: latest
* Java version: 1.8.0_92
* Operating system: Linux
* Bash version: `GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)`

### Additional context

[nf.log](https://github.com/nextflow-io/nextflow/files/5126672/nf.log)

**Comment by gradpawel** [comment]
Had similar issue and haven't resolved it. As a workaround you can download binary with *all suffix from **Releases** page https://github.com/nextflow-io/nextflow/releases and then rename it to **nextflow** and add to **PATH** if it is needed.

**Comment by pditommaso** [comment]
```
capsule.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.codehaus.groovy:groovy:pom:2.5.11 from/to central (https://repo1.maven.org/maven2/): sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
	at capsule.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at capsule.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at capsule.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at capsule.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	at capsule.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at capsule.DependencyManager.resolve0(DependencyManager.java:377)
	at capsule.DependencyManager.resolveDependencies(DependencyManager.java:314)
	at MavenCapsule.resolve0(MavenCapsule.java:224)
	at Capsule.resolve(Capsule.java:3375)
	at Capsule.resolve(Capsule.java:3389)
	at Capsule.buildJavaProcess(Capsule.java:2228)
	at Capsule.buildProcess0(Capsule.java:1530)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.prelaunch0(Capsule.java:1494)
	at Capsule.prelaunch(Capsule.java:1487)
	at CapsuleLoader.prelaunch(CapsuleLoader.java:42)
	at Capsule.prepareForLaunch(Capsule.java:1339)
	at Capsule.launch(Capsule.java:1268)
	at Capsule.main0(Capsule.java:399)
	at Capsule.main(Capsule.java:379)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
```

This a problem with SSL certificate of your Java installation (likely outdated). See #1462.
