### ISSUE TITLE
java.nio.channels.OverlappingFileLockException while running ~100 NF processes in parallel

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#1752]
## Bug report 

I've created kind of load - test with a "master" NF process which runs ~100-200 additional pipelines themselves.
Unfortunately some processes are running into this error:
```
CAPSULE EXCEPTION: null while processing attribute Allow-Snapshots: false
java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)

```

### Expected behavior and actual behavior

(Give an brief description of the expected behavior 
and actual behavior)

### Steps to reproduce the problem

run nextflow from nextflow, I guess this also depends on the underlying NFS - FS (?).

### Program output 
```
(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)
CAPSULE: Resolved artifact com.fasterxml:oss-parent:pom:23 from central (https://repo1.maven.org/maven2/, default, releases)
CAPSULE: Resolving artifact commons-codec:commons-codec:pom:1.10
CAPSULE: Resolved artifact commons-codec:commons-codec:pom:1.10 from central (https://repo1.maven.org/maven2/, default, releases)
CAPSULE: Resolving artifact org.apache.commons:commons-parent:pom:35
CAPSULE: Resolved artifact org.apache.commons:commons-parent:pom:35 from central (https://repo1.maven.org/maven2/, default, releases)
CAPSULE: Resolving artifact org.apache:apache:pom:15
CAPSULE: Resolved artifact org.apache:apache:pom:15 from central (https://repo1.maven.org/maven2/, default, releases)
CAPSULE: Cleanup
CAPSULE EXCEPTION: null while processing attribute Allow-Snapshots: false
java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1062)
        at io.takari.filemanager.internal.DefaultFileManager$LockFile.open(DefaultFileManager.java:380)
        at io.takari.filemanager.internal.DefaultFileManager$LockFile.lock(DefaultFileManager.java:313)
        at io.takari.filemanager.internal.DefaultFileManager$IndirectFileLock.lock(DefaultFileManager.java:243)
        at io.takari.filemanager.internal.DefaultFileManager$IndirectFileLock.open(DefaultFileManager.java:199)
        at io.takari.filemanager.internal.DefaultFileManager$IndirectFileLock.lock(DefaultFileManager.java:147)
        at io.takari.aether.concurrency.LockingSyncContext.acquire(LockingSyncContext.java:62)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:244)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:373)
        at capsule.DependencyManager.resolve0(DependencyManager.java:377)
        at capsule.DependencyManager.resolveDependencies(DependencyManager.java:314)
        at MavenCapsule.resolve0(MavenCapsule.java:224)
        at Capsule.resolve(Capsule.java:3375)
        at Capsule.resolve(Capsule.java:3389)
        at Capsule.buildJavaProcess(Capsule.java:2228)
        at Capsule.buildProcess0(Capsule.java:1530)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.prelaunch0(Capsule.java:1494)
        at Capsule.prelaunch(Capsule.java:1487)
        at CapsuleLoader.prelaunch(CapsuleLoader.java:42)
        at Capsule.prepareForLaunch(Capsule.java:1339)
        at Capsule.launch(Capsule.java:1268)
        at Capsule.main0(Capsule.java:399)
        at Capsule.main(Capsule.java:379)
Unable to initialize nextflow environment
```

### Environment 

* Nextflow version: nextflow_20.07.1
* Java version: $ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
* Operating system: Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

I might have to delay each launch of "inner" Nextflow pipelines.....
Overall capsule processing during startup seems to be very slow.

**Comment by tbugfinder** [comment]
After switching to NFSv4.1 using `NXF_HOME` setting I also run into this error.

**Comment by tbugfinder** [comment]
I've added a random wait before "inner" nextflow launches.
```
sleep \$[ ( \$RANDOM % 88 )  + 1 ]s
```

**Comment by tbugfinder** [comment]
Unfortunately, still I'm running into this kind of "race-condition" when multiple nextflow processes try to run the same nextflow init function....
