### ISSUE TITLE
Unable to make tap() operator work in DSL2

### ISSUE THREAD

**Issue by dweemx** [nextflow-io/nextflow#1766]
### Expected behavior and actual behavior

Trying to make `tap` operator work with DSL2.

#### Trial 1

```
nextflow.preview.dsl=2
log1 = Channel.create().view { "Log 1: $it" }
Channel
    .from ( 'a', 'b', 'c' )
        .tap( log1 )
```
But Channel.create() seems to be deprecated for NXF DLS2:

```
Channel `create` method is not supported any more
```

#### Trial 2
...with `Channel.empty()`

```
nextflow.preview.dsl=2
log1 = Channel.empty().view { "Log 1: $it" }
Channel
    .from ( 'a', 'b', 'c' )
        .tap( log1 )
```
In this case I get:
```
Invalid method `tap` invocation with arguments:  on OperatorEx type
```

### Program output 

This `.nextflow.log` output is from trial 2
```
$ cat .nextflow.log
Oct-19 19:50:22.751 [main] DEBUG nextflow.cli.Launcher - $> nextflow run test_tap.nf
Oct-19 19:50:22.990 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.04.1
Oct-19 19:50:23.017 [main] INFO  nextflow.cli.CmdRun - Launching `test_tap.nf` [elegant_noyce] - revision: a748d99c68
Oct-19 19:50:23.281 [main] DEBUG nextflow.Session - Session uuid: 1a677370-3cbc-4cec-8ed7-ab06eb3acb43
Oct-19 19:50:23.281 [main] DEBUG nextflow.Session - Run name: elegant_noyce
Oct-19 19:50:23.282 [main] DEBUG nextflow.Session - Executor pool size: 35
Oct-19 19:50:23.321 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 20.04.1 build 5335
  Created: 03-05-2020 19:37 UTC (21:37 CEST)
  System: Linux 3.10.0-1127.18.2.el7.x86_64
  Runtime: Groovy 2.5.8 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_221-b11
  Encoding: UTF-8 (ANSI_X3.4-1968)
  Process: 32651@r23i27n22 [10.118.230.158]
  CPUs: 35 - Mem: 755.6 GB (584.2 GB) - Swap: 2 GB (2 GB)
Oct-19 19:50:23.492 [main] DEBUG nextflow.Session - Work-dir: ~/nxf/tests/work [gpfs]
Oct-19 19:50:23.493 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: ~/nxf/tests/bin
Oct-19 19:50:23.589 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Oct-19 19:50:23.602 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Oct-19 19:50:23.889 [main] DEBUG nextflow.Session - Session start invoked
Oct-19 19:50:24.573 [main] WARN  nextflow.NextflowMeta$Preview - DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
Oct-19 19:50:24.576 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Oct-19 19:50:24.705 [main] DEBUG nextflow.Session - Session aborted -- Cause: No signature of method: nextflow.extension.OperatorEx.tap() is applicable for argument types: () values: []
Possible solutions: tap(groovy.lang.Closure), tap(groovyx.gpars.dataflow.DataflowReadChannel, groovy.lang.Closure), tap(groovyx.gpars.dataflow.DataflowReadChannel, groovyx.gpars.dataflow.DataflowWriteChannel), map(groovyx.gpars.dataflow.DataflowReadChannel, groovy.lang.Closure), max(groovyx.gpars.dataflow.DataflowReadChannel), max(groovyx.gpars.dataflow.DataflowReadChannel, java.util.Comparator)
Oct-19 19:50:24.744 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] view

Oct-19 19:50:24.752 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingMethodException: No signature of method: nextflow.extension.OperatorEx.tap() is applicable for argument types: () values: []
Possible solutions: tap(groovy.lang.Closure), tap(groovyx.gpars.dataflow.DataflowReadChannel, groovy.lang.Closure), tap(groovyx.gpars.dataflow.DataflowReadChannel, groovyx.gpars.dataflow.DataflowWriteChannel), map(groovyx.gpars.dataflow.DataflowReadChannel, groovy.lang.Closure), max(groovyx.gpars.dataflow.DataflowReadChannel), max(groovyx.gpars.dataflow.DataflowReadChannel, java.util.Comparator)
	at nextflow.extension.OpCall.getMethod0(OpCall.groovy:303)
	at nextflow.extension.OpCall.invoke1(OpCall.groovy:308)
	at nextflow.extension.OpCall.invoke0(OpCall.groovy:296)
	at nextflow.extension.OpCall.invoke(OpCall.groovy:156)
	at nextflow.extension.OpCall.call(OpCall.groovy:110)
	at nextflow.extension.OperatorEx.invokeExtensionMethod(OperatorEx.groovy:107)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script_a891b704.runScript(Script_a891b704:38)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:159)
	at nextflow.script.BaseScript.run(BaseScript.groovy:189)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:225)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:273)
	at nextflow.cli.Launcher.run(Launcher.groovy:460)
	at nextflow.cli.Launcher.main(Launcher.groovy:642)
```

### Environment 

* Nextflow version: `20.04.1`
* Java version: `1.8.0_221`
* Operating system: `CentOS`
* Bash version: `GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)`

### Additional context

None

**Comment by pditommaso** [comment]
This not how it's intended to be used the `tap` operator. I guess you want to do is: 

```
Channel .of ( 'a', 'b', 'c' )
        .tap { log1 }
        .view {  "Log 2: $it" }

log1.view { "Log 1: $it" }
```

(this is irrespective of DSL2)

**Comment by dweemx** [comment]
Yes great! the ouptut of this code block is exactly what I was looking for.

Nevertheless, since I took my code blocks from the docs, I think the docs should be updated because this piece does not work in DSL1 (neither in DSL2):
```
log1 = Channel.create().view { "Log 2: $it" }
log2 = Channel.create().view { "Log 2: $it" }
Channel
    .from ( 'a', 'b', 'c' )
        .tap( log1 )
        .map { it * 2 }
        .tap( log2 )
        .view { "Result: $it" }
```
and fails with:
```
Channel `log1` has been used as an output by more than a process or an operator
```

But this one work in DSL1 but not in DSL2:
```
log1 = Channel.create()
log2 = Channel.create()
Channel
    .from ( 'a', 'b', 'c' )
        .tap( log1 )
        .map { it * 2 }
        .tap( log2 )
        .view { "Result: $it" }
log1.view { "Log 1: $it" }
log2.view { "Log 2: $it" }
```

**Comment by pditommaso** [comment]
In DSL2 `create` is not supported anymore 

https://github.com/nextflow-io/nextflow/blob/e94e6877c2dc9bed983e873b62e302a08843c891/modules/nextflow/src/main/groovy/nextflow/Channel.groovy#L76-L81


You need to replace it with the syntax shown above.

**Comment by dweemx** [comment]
I didn't noticed you used `.tap {}` in your suggested solution. Actually, I would like to use the tap operator like this:
```
log1 = Channel.empty()
Channel .of ( 'a', 'b', 'c' )
        .tap ( log1 )
        .view {  "Log 2: $it" }
log1.view { "Log 1: $it" }
```

instead of creating a new `log1` channel implicitly (like you suggested)
```
Channel .of ( 'a', 'b', 'c' )
        .tap { log1 }
        .view {  "Log 2: $it" }

log1.view { "Log 1: $it" }
```

The docs suggest that the first one should be possible

**Comment by pditommaso** [comment]
Thanks for pointing this out, I'll update the docs

**Comment by dweemx** [comment]
This piece works in DSL1:
```
log1 = Channel.create()
Channel.from ( 'a', 'b', 'c' )
       .tap ( log1 )
       .view {  "Log 2: $it" }
log1.view { "Log 1: $it" }
```
Is there a work around in DSL2 without having the `log1` channel being created implicitly (i.e. using `.tap {}`) ?

**Comment by pditommaso** [comment]
Nothing that I can think of. Why `.tap {}` is not a viable solution?

**Comment by dweemx** [comment]
Not in my case since `.tap {}` is re-creating a channel. 
I'd like to create a `Channel` before hand and pass this channel to a workflow that would add new items to it and that I would not need to pass it back. If I'd use `.tap {}`, it's creating implicitly a new channel were it adds the items.
In my case I would already have this channel created hence this would be solved by `.tap()` (based on the documentation) but unfortunately doesn't work in `DSL2`.

**Comment by DaGaMs** [comment]
I just ran into the same problem. I tried to recreate the "feedback loop" pattern from the [Nextflow patterns](https://nextflow-io.github.io/patterns/index.html#_feedback_loop) documentation. The idea is that I have a process that needs to be run multiple times, until some condition is reached. I would mix the output of the process back into its input. The only way I could think of doing this in DSL2 is with `tap()` (as opposed to `tap{}`), something like this:

```groovy
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

workflow {
	main:
		feedback = Channel.of()
		condition = {it[1].length() > 10}
		input = Channel.of([0, "a", ""], [0, "b", ""], [0, "c", ""], [0, "d", ""]).mix(feedback.until(condition))

		input \
		 | makeLonger \
		 | tap (feedback) \
		 | groupTuple(by: 1, sort: {a, b -> b[0] <=> a[0]}) \
		 | view
}

process makeLonger {
	input: tuple val(iteration), val(identifier), val(string)
	output: tuple val("${iteration+1}"), val(identifier), env(FOO)
	script:
	"""
	chars=abcdedfghijklmnopqrstuvwxzy0123456789
	FOO="$string" # start from previous iteration
	for i in `seq 1 \$((RANDOM % 10))` ; do
    FOO="\$FOO\${chars:RANDOM%\${#chars}:1}" # make a random string
	done
	export FOO
	"""
}
```

**Comment by marcodelapierre** [comment]
I have a similar user case, i.e. trying to setup a Feedback Loop pattern using DSL 2

**Comment by yqshao** [comment]
Hi, I'm looking at something similar. After some strugle I mange to make something like the [feeedback-loop](https://github.com/nextflow-io/patterns/blob/1f7477b7181d76a7347bbe5398f9d0ea4d01ad46/feedback-loop.nf) 
exmaple to work with DSL2. 

```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl=2

import nextflow.extension.CH
import static nextflow.extension.DataflowHelper.newOperator
import groovyx.gpars.dataflow.operator.ChainWithClosure
import groovyx.gpars.dataflow.operator.CopyChannelsClosure

def attach(source, target) {
    newOperator([source.createReadChannel()], [target],
                new ChainWithClosure(new CopyChannelsClosure()))
}

process foo {
    input:
      path x
    output:
      path 'foo.txt'
    script:
    """
    cat $x > foo.txt
    """
}

process bar {
    input:
      path x
    output:
      path 'bar.txt', emit: feedback
      path 'bar.txt', emit: result
    script:
    """
    cat $x > bar.txt
    echo World >> bar.txt
    """
}


params.input = "$baseDir/data/hello.txt"
workflow {
    condition = { it.readLines().size()>3 }
    feedback_ch = CH.create()
    input_ch = Channel.fromPath(params.input, checkIfExists:true)
                      .mix( feedback_ch.until(condition) )
    foo_ch = foo(input_ch)
    bar_ch = bar(foo_ch)
    attach(bar_ch.feedback, feedback_ch)
    bar_ch.result.last().view { "Result:\n${it.text.indent(' ')}" }
}
```

What I find to be the obstacles (as far as I understood it) to a feedback workflow is 
1. the removal of `Channel.create()`
2. the `.tap()` operation checks the classes of source and target which prevents `DataflowStreamReadAdaptor` to be copied to `DataflowBroadcast`(therefore I naively copied out the `apply` part of `TapOp` and copied the channels manually).

As I'm essentially new to Groovy/Nextflow scripting, I'm not sure whether the solution makes sense at all. And I have yet to test wether it works if I am to compose some sub-workflow with this pattern, but this seems useful to some. I'd like to know if this is something to be included into the nextflow core (and in that case, wether a PR on this is welcomed).
