### ISSUE TITLE
publishDir to S3 bucket with server-side encryption fails even with aws.client.storageEncryption = 'AES256'

### ISSUE THREAD

**Issue by hillan141** [nextflow-io/nextflow#1830]
## Bug report 

Hi,
publishDir to S3 bucket with server-side encryption fails even with aws.client.storageEncryption = 'AES256'
Any pointers or help appreciated.

### Expected behavior and actual behavior

Expected: when publishDir is a S3 prefix on a bucket with server-side encryption, publication of file should succeed.  Instead, I receive a 403 forbidden error code from AWS client code.

### Steps to reproduce the problem

nextflow.config:
```
env.NXF_WORK = '/tmp/nxf-work'
workDir = '/tmp/nxf-work'

// AWS S3 bucket requires server-side encryption 
aws.client.storageEncryption = 'AES256'
```

test_aws_upload.nf:
```
process aws_upload {
    publishDir "${params.output_prefix}", mode: 'copy', overwrite: true
    output:
        file 'foo.txt'
    script:
    """
    echo 'hello aws' > foo.txt
    """
}
```

### Program output 

```
# Success for publishDir to a local filesystem
$ nextflow run test_aws_upload.nf --output_prefix /tmp/aws-test
N E X T F L O W  ~  version 20.10.0
Launching `test_aws_upload.nf` [dreamy_poitras] - revision: 48ef5ee196
executor >  local (1)
[dd/612eeb] process > aws_upload [100%] 1 of 1 ✔

# Try S3 bucket with server-side encryption
$ S3_BUCKET=s3://<snipped>

# Successful upload with AWS CLI aws s3 cp --sse AES256 ...
$ aws s3 cp --sse AES256 foo.txt $S3_BUCKET/
upload: foo.txt to s3://<snipped>/foo.txt

# Failure of publishDir to same bucket
$ nextflow run test_aws_upload.nf --output_prefix $S3_BUCKET
N E X T F L O W  ~  version 20.10.0
Launching `test_aws_upload.nf` [tender_koch] - revision: 48ef5ee196
executor >  local (1)
[65/c53b08] process > aws_upload [  0%] 0 of 1
Error executing process > 'aws_upload'

Caused by:
  Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: F9BFBA6F58655F15; S3 Extended Request ID: WSt/X/xfHktukVflQC7mkD8FeY7sHF6P4CEA3g3rSS/kgy/A69ZnGEL3aSufkloC1iH+LgDrFcA=)
```

Nextflow.log attached.
[nextflow_log.txt](https://github.com/nextflow-io/nextflow/files/5676916/nextflow_log.txt)

### Environment 

* Nextflow version: 20.10.0
* Java version: 1.8.0
* Operating system: Linux
* Bash version: 4.4.20

### Additional context

I understood from previous issue threads that AES256 server-side encryption is supported.  Any suggestions to debug?

**Comment by pditommaso** [comment]
For reference this happens when AES security is enforced with a rule like the following 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "S3xDataMustBeEncryptedAtRest",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": [
                "arn:aws:s3:::nf-aes-test",
                "arn:aws:s3:::nf-aes-test/*"
            ],
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": "AES256"
                }
            }
        }
    ]
}
```

**Comment by pditommaso** [comment]
Related error stack trace 

```
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: WBVY99RS3QTS45QV; S3 Extended Request ID: J5AauC9stxOvrSkj2aJ0shvTV9j81pn5HsIzKpZtnsc2AXorvudH9TBuxA++X1LQjpbardrhy9c=)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:389)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5793)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1786)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1746)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1687)
	at com.upplication.s3fs.AmazonS3Client.putObject(AmazonS3Client.java:120)
	at com.upplication.s3fs.S3FileSystemProvider.createDirectory(S3FileSystemProvider.java:470)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at nextflow.processor.PublishDir.makeDirs(PublishDir.groovy:324)
	at nextflow.processor.PublishDir.createPublishDir(PublishDir.groovy:315)
	at nextflow.processor.PublishDir.apply0(PublishDir.groovy:160)
	at nextflow.processor.PublishDir.apply(PublishDir.groovy:210)
	at nextflow.processor.PublishDir$apply.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.processor.TaskProcessor.publishOutputs0(TaskProcessor.groovy:1271)
	at nextflow.processor.TaskProcessor.publishOutputs(TaskProcessor.groovy:1246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.finalizeTask0(TaskProcessor.groovy:2132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.finalizeTask(TaskProcessor.groovy:2103)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:614)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:530)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.lang.Thread.run(Thread.java:748)
```
