### ISSUE TITLE
Nextflow has thread deadlock staging large files using an S3 working directory 

### ISSUE THREAD

**Issue by kainosgelhpc** [nextflow-io/nextflow#1872]
## Bug report 

Running Nextflow with an S3 working directory with large files takes a long time due to a thread deadlock in Nextflow

### Expected behavior and actual behavior

With an S3 working directory the job runs in 3 hours. With a locak working directory 35 minutes.

### Steps to reproduce the problem

Run a Nextflow job that stages large files (our test case has 12x 15GB files) from S3 with an S3 working directory.

### Program output 

All the threads are blocked on an NIO filePath singleton object. 

"pool-6-thread-10" #165 prio=5 os_prio=0 tid=0x00007b5df13e5800 nid=0x1143 waiting for monitor entry [0x00007b5d6c440000] 

java.lang.Thread.State: BLOCKED (on object monitor) 

at nextflow.file.FileHelper.getLocalCachePath(FileHelper.groovy:636) 

	 

    waiting to lock <0x0000000084a4e5d8> (a sun.nio.fs.UnixPath) 
    at nextflow.executor.IgFileStagingStrategy.stage(IgFileStagingStrategy.groovy:81) 
    at nextflow.executor.IgScriptStagingStrategy.super$2$stage(IgScriptStagingStrategy.groovy) 
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
    at java.lang.reflect.Method.invoke(Method.java:498) 
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) 
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) 
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) 
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144) 
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:164) 
    at nextflow.executor.IgScriptStagingStrategy.stage(IgScriptStagingStrategy.groovy:55) 
    at nextflow.executor.IgScriptTask.beforeExecute(IgScriptTask.groovy:56) 
This is due to IgFileStagingStrategy using a singleton FileHelper object.
![image](https://user-images.githubusercontent.com/75790556/106135706-304c6600-6160-11eb-9b19-a148d541ce5d.png)

https://jar-download.com/artifacts/io.nextflow/nf-ignite/20.04.1-edge/source-code/nextflow/executor/IgFileStagingStrategy.groovy

### Environment 

* Nextflow version: 10.20.0
* Java version: openjdk version "1.8.0_265" (happens with Java 11 too)
* Operating system: Ubuntu and AWS Linux 2
* Bash version: (use the command `$SHELL --version`) : GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)

**Comment by namiller2015** [comment]
I think I am running into this issue on a smaller scale. My download from S3 is being killed by timing out. How were you able to monitor and get that debugging output in the AWS batch environment?

**Comment by pparsonsesp** [comment]
We got the debugging output from running NextFlow standalone but we have seen the same problem in Batch. You would just need to ssh into an instance in your batch cluster and run jstack on the nextflow instance.

**Comment by pparsonsesp** [comment]
We've since seen that the actual problem is in FileHelper.getLocalCachePath which has a synchonized block that copies the files to/from S3

**_synchronized_** (cacheDir)  {
            if( Files.exists(cached) )
                return cached

            return FilesEx.copyTo(sourcePath, cached)
        }

https://github.com/nextflow-io/nextflow/blob/master/modules/nf-commons/src/main/nextflow/file/FileHelper.groovy

**Comment by pditommaso** [comment]
`FileHelper.getLocalCachePath` is not involved with the AWS Batch executor

**Comment by pparsonsesp** [comment]
Pablo is right. We had a different issue with Batch.
