### ISSUE TITLE
LocalExecutor can throw ClosedByInterruptException randomly

### ISSUE THREAD

**Issue by austindoupnik** [nextflow-io/nextflow#188]
We have now seen this exception a few times, it seems to happen randomly and we haven't identified any sort of pattern for when it occurs yet. The version is `0.20.1`,

```
Caused by:
  java.nio.channels.ClosedByInterruptException

java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
        at java.nio.channels.Channels.writeFully(Channels.java:101)
        at java.nio.channels.Channels.access$000(Channels.java:61)
        at java.nio.channels.Channels$1.write(Channels.java:174)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at org.codehaus.groovy.runtime.NioGroovyMethods.write(NioGroovyMethods.java:462)
        at org.codehaus.groovy.runtime.NioGroovyMethods.setText(NioGroovyMethods.java:482)
        at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2705)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3747)
        at groovy.lang.DelegatingMetaClass.setProperty(DelegatingMetaClass.java:172)
        at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:199)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:484)
        at nextflow.executor.BashWrapperBuilder.build(BashWrapperBuilder.groovy:341)
        at nextflow.executor.LocalExecutor.createBashTaskHandler(LocalExecutor.groovy:71)
        at nextflow.executor.LocalExecutor.createTaskHandler(LocalExecutor.groovy:63)
        at nextflow.executor.LocalExecutor$createTaskHandler.call(Unknown Source)
        at nextflow.processor.TaskDispatcher.submit(TaskDispatcher.groovy:143)
        at nextflow.processor.TaskDispatcher$submit$0.call(Unknown Source)
        at nextflow.processor.TaskProcessor.submitTask(TaskProcessor.groovy:1629)
        at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
        at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:522)
        at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
        at nextflow.processor.ParallelTaskProcessor.invokeTask(ParallelTaskProcessor.groovy:217)
        at sun.reflect.GeneratedMethodAccessor274.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1261)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
        at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
        at groovy.lang.Script.invokeMethod(Script.java:80)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:430)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:369)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at Script38A8857B9B9268D5BD29A044B1FE7E78$_run_closure1.doCall(Script38A8857B9B9268D5BD29A044B1FE7E78:1)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
        at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
        at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by pditommaso** [comment]
Thank for reporting this. Can you include the following information about your system: 
* Java version 
* OS version 
* Number of cpus

**Comment by austindoupnik** [comment]
Of course! We have seen it on two different environments.

AWS
* CPUs: `r3.8xlarge` with 32 "vCPU"s
* OS: Debian 8 `3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux`
* Java: `1.8.0_72`

Physical
* CPUs: 2 processors, each with 10 physical cores, hyperthreading enabled, so 40 logical cores
* OS: Debian 8 `3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
* Java: `1.8.0_72`

**Comment by pditommaso** [comment]
How it is frequent let's say in 10 runs? Are you able to provide a script to replicate this problem?

**Comment by johnmu** [comment]
This would happen maybe 1-2 times every 10 runs. Unfortunately, the script we are running is proprietary. We can try to make a minimal test case, but we need some direction as to what could possibly be the problem.

**Comment by pditommaso** [comment]
> We can try to make a minimal test case, but we need some direction as to what could possibly be the problem

Yes, I mean that. It would be a huge help  to troubleshoot the issue.

**Comment by johnmu** [comment]
@pditommaso However, just looking at the exception, do you have any insight to share about where to start looking?

**Comment by johnmu** [comment]
@pditommaso if it helps, we consistently see the hang when the drive Nextflow is writing to fills up.

**Comment by pditommaso** [comment]
The exception is thrown at [this line](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L341). More in detail when the target script is saved to a file that exception is thrown because the current thread is interrupted by another thread. Weird. 

This [post](http://stackoverflow.com/questions/1161297/why-are-we-getting-closedbyinterruptexception-from-filechannel-map-in-java-1-6) suggests that it may happen if the thread pool is shutting down. 

Could you please included the full `.nextflow.log` file.

**Comment by austindoupnik** [comment]
Alright I took a random stab at reproducing it and was actually able to. It is a bit weird though. The workflow is very simple, just 100 processes all sleeping then echoing "hello world" and one process which writes about `14m` with dd, here it is,

[helloworld.nf.txt](https://github.com/nextflow-io/nextflow/files/333769/helloworld.nf.txt)
[nextflow.config.txt](https://github.com/nextflow-io/nextflow/files/333770/nextflow.config.txt)

I then created a `tmpfs` volume,

```
mount -t tmpfs -o size=16m tmpfs /mnt/helloworld
```

Since it is nondetermenistic I had to run it in a while loop until it hung, it took maybe an hour or so

```
cd /mnt/helloworld
while true ; do rm -rf * .* && ~/nextflow-0.20.1-all ~/helloworld.nf; done
```

**Comment by austindoupnik** [comment]
I realized I wasn't very clear. This reproduces the hang, and not the exception. It appears they are two unrelated concurrency bugs.

Is there a high level document for the design of the local executor, or is loading it up in a debugger and stepping through my best bet for understanding it? Any recommended IDE for this groovy code?

**Comment by pditommaso** [comment]
I see. If you manage to replicate the exception, please add the full `.nextflow.log` file. Unfortunately there's no high level docs. As IDE I suggest IntelliJ Idea, you can find [here](https://github.com/nextflow-io/nextflow#intellij-idea) the instruction to setup it. For the hang problem you may want to open a separate issue.

**Comment by patia013** [comment]
We observed this as well when latency issues with the filesystem were being observed. Ultimately, it was tracked down to a sub-optimal network interface. Releasing that NIC has addressed the issue at our end so far. I will post the Nextflow log is this issue is observed again. We use Nextflow 0.17.3 with Java 8 on a Centos 7 OS.

**Comment by pditommaso** [comment]
Please include the complete `.nextflow.log` for a run reporting this issue. The best would be if you could provide a script to replicate the issue. That would help me a lot to provide a patch.

**Comment by pditommaso** [comment]
Also I would suggest to upgrade to the latest nextflow version.

**Comment by austindoupnik** [comment]
Another details is that we are using docker containers

**Comment by pditommaso** [comment]
Are you still experiencing this exception? If so please include the complete `.nextflow.log` file.

**Comment by austindoupnik** [comment]
As with any concurrency bug it only happens rarely. We have not seen it again, so it is clearly quite rare.

**Comment by austindoupnik** [comment]
Alright we just saw this again, but unfortunately it was on an AWS instance which was shutdown before I managed to grab the `.nextflow.log`

**Comment by pditommaso** [comment]
Actually I've managed to replicate it. Working on a patch.

**Comment by austindoupnik** [comment]
That is fantastic, thank you!

**Comment by pditommaso** [comment]
I've released version `0.21.0-RC1` that solves this problem. Please give it a try to verify that everything is OK. 

To use it define in your launching environment the variable `NXF_VER=0.21.0-RC1`, then run nextflow as usual.

**Comment by patia013** [comment]
That's great! Thanks!

**Comment by austindoupnik** [comment]
Perfect. Thanks so much!
