### ISSUE TITLE
"Connection timed out" ConnectExceptions from checkIfCompleted()

### ISSUE THREAD

**Issue by alanbchristie** [nextflow-io/nextflow#1932]
## Bug report 

Failure observed using nextflow: -

- `21.02.0-edge`

Running nextflow in a container image (`FROM python:3.8.6-buster`) in AWS/EKS as part of a `k8s` workflow.

### Expected behavior and actual behavior

I expect the workflow to run to completion while also handling intermittent (occasional) "Connection timed out" exceptions without immediately crashing.

Instead, I see a number of **Connection timed out** exceptions  (`java.net.ConnectException`). These appear to emerge from Nextflow's polling process that's trying to determine whether the related processes (Pods) have completed. The underlying "java.net.ConnectException" seems to be catastrophic leading to the workflow simply crashing.

> Can the HttpURLConnection that's being used have the timeout provided by the user?

> What is the timeout?

### Steps to reproduce the problem

It's a complex process with proprietary data that's being processed so we can't provide an runnable example.

### Program output 

Here's the final part of the log (The full Nextflow log is attached): -

```
Feb-25 03:16:00.592 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'fragment (1144)'

Caused by:
  Connection timed out (Connection timed out)

java.net.ConnectException: Connection timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:366)
	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy)
	at nextflow.k8s.client.K8sClient.get(K8sClient.groovy:379)
	at nextflow.k8s.client.K8sClient.podStatus(K8sClient.groovy:196)
	at nextflow.k8s.client.K8sClient.podState(K8sClient.groovy:228)
	at nextflow.k8s.K8sTaskHandler.getState(K8sTaskHandler.groovy:261)
	at nextflow.k8s.K8sTaskHandler.checkIfCompleted(K8sTaskHandler.groovy:318)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:605)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:530)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:409)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.lang.Thread.run(Thread.java:834)
Feb-25 03:16:00.600 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Connection timed out (Connection timed out)
Feb-25 03:16:00.615 [Task monitor] DEBUG nextflow.Session - The following nodes are still active:
[process] collect_nodes
  status=ACTIVE
  port 0: (value) OPEN  ; channel: chunks
  port 1: (cntrl) -     ; channel: $

[process] collect_edges
  status=ACTIVE
  port 0: (value) OPEN  ; channel: chunks
  port 1: (cntrl) -     ; channel: $

[process] collect_rejects
  status=ACTIVE
  port 0: (value) OPEN  ; channel: chunks
  port 1: (cntrl) -     ; channel: $

Feb-25 03:16:00.618 [main] DEBUG nextflow.Session - Session await > all process finished
Feb-25 03:16:00.618 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-25 03:16:00.623 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (1)
Feb-25 03:16:00.910 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=1601; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=18d 1h 32m 50s; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=100; peakCpus=100; peakMemory=0; ]
Feb-25 03:16:00.910 [main] DEBUG nextflow.trace.ReportObserver - Flow completing -- rendering html report
Feb-25 03:16:01.571 [main] DEBUG nextflow.trace.ReportObserver - Execution report summary data:
  [{"cpuUsage":{"mean":93.97,"min":19.7,"q1":98.7,"q2":99,"q3":99.2,"max":99.7,"minLabel":"fragment (287)","maxLabel":"fragment (1186)","q1Label":"fragment (109)","q2Label":"fragment (475)","q3Label":"fragment (487)"},"process":"fragment","mem":{"mean":73019261.52,"min":67764224,"q1":72278016,"q2":72978432,"q3":73691136,"max":76521472,"minLabel":"fragment (1602)","maxLabel":"fragment (1186)","q1Label":"fragment (1362)","q2Label":"fragment (1199)","q3Label":"fragment (448)"},"memUsage":null,"timeUsage":null,"vmem":{"mean":272972143.13,"min":272617472,"q1":272875520,"q2":272883712,"q3":273137664,"max":273403904,"minLabel":"fragment (295)","maxLabel":"fragment (296)","q1Label":"fragment (1359)","q2Label":"fragment (408)","q3Label":"fragment (934)"},"reads":{"mean":4237655.04,"min":4218454,"q1":4235573,"q2":4236507,"q3":4237397,"max":4245962,"minLabel":"fragment (1602)","maxLabel":"fragment (1229)","q1Label":"fragment (748)","q2Label":"fragment (9)","q3Label":"fragment (904)"},"cpu":{"mean":93.97,"min":19.7,"q1":98.7,"q2":99,"q3":99.2,"max":99.7,"minLabel":"fragment (287)","maxLabel":"fragment (1186)","q1Label":"fragment (109)","q2Label":"fragment (475)","q3Label":"fragment (487)"},"time":{"mean":974872.06,"min":117870,"q1":679431,"q2":857356,"q3":1079921,"max":5947565,"minLabel":"fragment (1602)","maxLabel":"fragment (287)","q1Label":"fragment (463)","q2Label":"fragment (1326)","q3Label":"fragment (784)"},"writes":{"mean":35428800.81,"min":4821255,"q1":28291364,"q2":34786916,"q3":41942924,"max":72934065,"minLabel":"fragment (1602)","maxLabel":"fragment (1329)","q1Label":"fragment (142)","q2Label":"fragment (1500)","q3Label":"fragment (534)"}}]
Feb-25 03:16:02.392 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Feb-25 03:16:02.411 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow version: `21.02.0-edge`
* Java version: `openjdk version "11.0.9.1" 2020-11-04`
* Operating system: Linux container (Debain) running as a k8s Job in EKS
* Bash version: `GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)`

### Additional context

- Nextflow is being executed from an Ansible playbook.
- We cannot reproduce the fault on our cluster
- The customer is using a private EKS cluster we have no direct access to

[ConnectException.log](https://github.com/nextflow-io/nextflow/files/6051268/ConnectException.log)

**Comment by alanbchristie** [comment]
If any sort of `setConnectTimeout()` mechanism is in use, what value is passed in?

Regardless, I suspect the value can't be changed at runtime so is there any advice for users who experience this?

**Comment by alanbchristie** [comment]
Can a you re-open for advice on how to control timeouts as the bot didn't answer the question (see comment 8 Mar 2021)

**Comment by pditommaso** [comment]
We just improved the control over this. See https://github.com/nextflow-io/nextflow/commit/064f9bc4f43884208f0007a558c08ab479bbea63 and https://github.com/nextflow-io/nextflow/commit/527e0d5d5c04c505e47d0281b95ac105f843f8a8 and https://github.com/nextflow-io/nextflow/commit/58be212862329f3cd8b90a454ed94ea83caa648a
