### ISSUE TITLE
Nextflow 20.10 doesn't recognize AWS China credential?

### ISSUE THREAD

**Issue by shanzhong** [nextflow-io/nextflow#1952]
## Bug report 
I was trying to set up an analysis pipeline in Nextflow to run with AWS Batch in China (cn-northwest-1 region), starting with a simple test script. Using the same script and config file, the latest stable version (20.10) seems to not recognize the AWS credential and could not access S3, whereas an older version (19.10) runs successfully. Is it a bug, or is there any changes between the two versions that I'm not aware of?

EDIT: tested a few more versions, the script runs successfully till Nextflow 20.04.1, and started to break with 20.07

### Expected behavior and actual behavior

- Expected behavior: the output file (testout.txt) in test.nf should be published to the specified S3 location
- Actual behavior: 
  - Nextflow 20.10 fails to run the test script, giving an error message indicating that the AWS credential is not valid. 
  - Nextflow 19.10 works as expected

### Steps to reproduce the problem
test.nf:
```
#!/usr/bin/env nextflow
outpath = Channel.value(params.outdir)
process test_s3 {
    cpus 1
    memory '1 GB'
    publishDir "${params.outdir}", mode: "copy"
    output:
        path "testout.txt"
    script:
    """
    #!/bin/bash
    echo "hello world" > testout.txt
    """
}
```
nextflow.config:
```
aws {
    accessKey = 'XXXXXX'
    secretKey = 'XXXXXX'
    region = 'cn-northwest-1'
}
```
Running the test script:
```
nextflow run test.nf --outdir s3://<bucket>/<path>/
```

### Program output 
- Nextflow 20.10 output:
```
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [magical_lichterman] - revision: d7670ccb14
executor >  local (1)
[88/237e0f] process > test_s3 [  0%] 0 of 1
Error executing process > 'test_s3'

Caused by:
  The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: XXXXXX; S3 Extended Request ID: XXXXXX)
```
- Nextflow 19.10 output:
```
N E X T F L O W  ~  version 19.10.0
Launching `test.nf` [infallible_magritte] - revision: d7670ccb14
executor >  local (1)
[ae/8ba130] process > test_s3 [100%] 1 of 1 ✔

```
- `.nextflow.log` file from 20.10:
```
Mar-04 22:19:09.912 [main] DEBUG nextflow.cli.Launcher - $> nextflow run test.nf --outdir 's3://<bucket>/<path>/'
Mar-04 22:19:10.050 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.10.0
Mar-04 22:19:10.061 [main] INFO  nextflow.cli.CmdRun - Launching `test.nf` [magical_lichterman] - revision: d7670ccb14
Mar-04 22:19:10.088 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /<localpath>/nextflow.config
Mar-04 22:19:10.089 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /<localpath>/nextflow.config
Mar-04 22:19:10.112 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Mar-04 22:19:10.856 [main] DEBUG nextflow.Session - Session uuid: 5bbd20c9-cd16-48c2-af3a-5eb03f835cfa
Mar-04 22:19:10.857 [main] DEBUG nextflow.Session - Run name: magical_lichterman
Mar-04 22:19:10.857 [main] DEBUG nextflow.Session - Executor pool size: 12
Mar-04 22:19:10.887 [main] DEBUG nextflow.cli.CmdRun -
  Version: 20.10.0 build 5430
  Created: 01-11-2020 15:14 UTC (10:14 EDT)
  System: Mac OS X 10.16
  Runtime: Groovy 3.0.5 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_281-b09
  Encoding: UTF-8 (UTF-8)
  Process: 12716@HOST [192.168.1.92]
  CPUs: 12 - Mem: 16 GB (119.2 MB) - Swap: 3 GB (1.1 GB)
Mar-04 22:19:10.905 [main] DEBUG nextflow.Session - Work-dir: /<localpath>/work [Mac OS X]
Mar-04 22:19:10.905 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /<localpath>/bin
Mar-04 22:19:10.968 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Mar-04 22:19:10.970 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Mar-04 22:19:11.083 [main] DEBUG nextflow.Session - Session start invoked
Mar-04 22:19:11.305 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Mar-04 22:19:11.325 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: test_s3
Mar-04 22:19:11.384 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-04 22:19:11.384 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-04 22:19:11.387 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Mar-04 22:19:11.391 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=12; memory=16 GB; capacity=12; pollInterval=100ms; dumpInterval=5m
Mar-04 22:19:11.468 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Mar-04 22:19:11.468 [main] DEBUG nextflow.Session - Session await
Mar-04 22:19:11.597 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-04 22:19:11.602 [Task submitter] INFO  nextflow.Session - [88/237e0f] Submitted process > test_s3
Mar-04 22:19:11.642 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: test_s3; status: COMPLETED; exit: 0; error: -; workDir: /<localpath>/work/88/237e0f9a60c13d6614f364b5fd8a28]
Mar-04 22:19:11.679 [Task monitor] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Mar-04 22:19:11.683 [Task monitor] DEBUG nextflow.Global - Using AWS credentials defined in nextflow config file
Mar-04 22:19:11.684 [Task monitor] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=z4jn2G.., region=cn-northwest-1, access_key=AKIA3C..}
Mar-04 22:19:12.670 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'test_s3'

Caused by:
  The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: XXXXXXXX; S3 Extended Request ID: XXXXXXXX)

com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: XXXXXXXX; S3 Extended Request ID: XXXXXXXX)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:389)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5793)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1786)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1746)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1687)
	at com.upplication.s3fs.AmazonS3Client.putObject(AmazonS3Client.java:120)
	at com.upplication.s3fs.S3FileSystemProvider.createDirectory(S3FileSystemProvider.java:470)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at nextflow.processor.PublishDir.makeDirs(PublishDir.groovy:324)
	at nextflow.processor.PublishDir.createPublishDir(PublishDir.groovy:315)
	at nextflow.processor.PublishDir.apply0(PublishDir.groovy:160)
	at nextflow.processor.PublishDir.apply(PublishDir.groovy:210)
	at nextflow.processor.PublishDir$apply.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.processor.TaskProcessor.publishOutputs0(TaskProcessor.groovy:1256)
	at nextflow.processor.TaskProcessor.publishOutputs(TaskProcessor.groovy:1231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.finalizeTask0(TaskProcessor.groovy:2113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.finalizeTask(TaskProcessor.groovy:2084)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:613)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:530)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1259)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.lang.Thread.run(Thread.java:748)
Mar-04 22:19:12.678 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: XXXXXXXX; S3 Extended Request ID: XXXXXXXX)
Mar-04 22:19:12.700 [main] DEBUG nextflow.Session - Session await > all process finished
Mar-04 22:19:12.700 [main] DEBUG nextflow.Session - Session await > all barriers passed
Mar-04 22:19:12.709 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=1; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=1; loadMemory=1 GB; peakRunning=1; peakCpus=1; peakMemory=1 GB; ]
Mar-04 22:19:12.899 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Mar-04 22:19:12.902 [main] DEBUG nextflow.util.SpuriousDeps - AWS S3 uploader shutdown
Mar-04 22:19:12.913 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow version: 20.10.0.5430
* Java version: 1.8.0_281
* Operating system: macOS
* Bash version: zsh 5.8 (x86_64-apple-darwin20.0)

Same issue within Ubuntu environment in AWS EC2:
* Nextflow version: 20.10.0.5430
* Java version: openjdk version "11.0.10" 2021-01-19
* Operating system: Ubuntu 20.04 LTS
* Bash version: zsh 5.8 (x86_64-ubuntu-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Maybe a regression introduced by this change https://github.com/nextflow-io/nextflow/issues/1596#issuecomment-643258133

**Comment by benjschiller** [comment]
bump. running into this problem too + the last known working version 20.04.1 has other bugs that make it unusable for our deployment. if there's any info on when a fix is expected, that would helpful for planning. thanks!

**Comment by pditommaso** [comment]
Not much experience with the China region. I could not even find it in the list of avail regions in my account.

**Comment by shanzhong** [comment]
@pditommaso FYI, AWS China is separated from AWS global regions due to the regulation requirements there, and a separate AWS China account is needed in order to access the AWS China services. There are two regions, cn-north-1 and cn-northwest-1. More details can be found at https://www.amazonaws.cn/en/ . Would really appreciate it if this issue can be fixed! I would be happy to provide help if I can, though my skill in java is very limited.

**Comment by shenyang1981** [comment]
Hello, @shanzhong, it is due to the different endpoint used in China. You can specify the endpoint like this:

aws {
    accessKey = 'xxx'
    secretKey = 'xxx'
    region = 'cn-northwest-1'
    client {
     endpoint = "s3.cn-northwest-1.amazonaws.com.cn"
    }
}

Wish it works for you.

Cheers

**Comment by kern3020** [comment]
Thanks so much @shenyang1981! Setting this parameter works for me in cn-north-1. 
```
aws {
       client {
  	       endpoint = "s3.cn-north-1.amazonaws.com.cn"
      }
  }

**Comment by pditommaso** [comment]
It has been added a mention in the docs 9c81104. Thanks for reporting this issue and the solution.
