### ISSUE TITLE
Plugin installation fails when a deps requires a version lower than default one

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1961]
Using version 21.03.0edge

```
# NXF_PLUGINS_DEFAULT=false nextflow -log log plugins install nf-tower,nf-azure,nf-google,nf-amazon,xpack-amzn
Downloading plugin nf-tower@1.0.2
Downloading plugin nf-azure@0.9.5
Downloading plugin nf-google@1.0.3
Downloading plugin nf-amazon@1.0.2
Downloading plugin xpack-amzn@1.0.1
Call 'resolve' method first


sh-4.2# cat log 
Mar-09 14:13:13.370 [main] DEBUG nextflow.cli.Launcher - $> nextflow -log log plugins install nf-tower,nf-azure,nf-google,nf-amazon,xpack-amzn
Mar-09 14:13:13.434 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/.nextflow/plugins
Mar-09 14:13:13.437 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins local root: .nextflow/plr/empty
Mar-09 14:13:13.457 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Mar-09 14:13:13.458 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Mar-09 14:13:13.461 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Mar-09 14:13:13.468 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Mar-09 14:13:13.469 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-tower version: latest
Mar-09 14:13:13.961 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-tower@1.0.2
Mar-09 14:13:14.498 [main] INFO  org.pf4j.util.FileUtils - Expanded plugin zip 'nf-tower-1.0.2.zip' in 'nf-tower-1.0.2'
Mar-09 14:13:14.507 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-azure version: latest
Mar-09 14:13:14.508 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-azure@0.9.5
Mar-09 14:13:16.856 [main] INFO  org.pf4j.util.FileUtils - Expanded plugin zip 'nf-azure-0.9.5.zip' in 'nf-azure-0.9.5'
Mar-09 14:13:16.860 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-google version: latest
Mar-09 14:13:16.860 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-google@1.0.3
Mar-09 14:13:18.632 [main] INFO  org.pf4j.util.FileUtils - Expanded plugin zip 'nf-google-1.0.3.zip' in 'nf-google-1.0.3'
Mar-09 14:13:18.635 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: latest
Mar-09 14:13:18.635 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-amazon@1.0.2
Mar-09 14:13:20.849 [main] INFO  org.pf4j.util.FileUtils - Expanded plugin zip 'nf-amazon-1.0.2.zip' in 'nf-amazon-1.0.2'
Mar-09 14:13:20.851 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin xpack-amzn version: latest
Mar-09 14:13:20.852 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin xpack-amzn@1.0.1
Mar-09 14:13:21.527 [main] INFO  org.pf4j.util.FileUtils - Expanded plugin zip 'xpack-amzn-1.0.1.zip' in 'xpack-amzn-1.0.1'
Mar-09 14:13:21.533 [main] DEBUG nextflow.plugin.PluginUpdater - Plugin xpack-amzn requires nf-amazon supported version: >=1.0.1 - resolved version: 1.0.1
Mar-09 14:13:21.535 [main] DEBUG nextflow.plugin.PluginUpdater - Updating plugin nf-amazon version: 1.0.1 [current version: 1.0.2]
Mar-09 14:13:21.537 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.IllegalStateException: Call 'resolve' method first
	at org.pf4j.DependencyResolver.checkResolved(DependencyResolver.java:167)
	at org.pf4j.DependencyResolver.getDependents(DependencyResolver.java:124)
	at org.pf4j.AbstractPluginManager.stopPlugin(AbstractPluginManager.java:453)
	at org.pf4j.AbstractPluginManager.stopPlugin(AbstractPluginManager.java:432)
	at org.pf4j.AbstractPluginManager.deletePlugin(AbstractPluginManager.java:309)
	at nextflow.plugin.PluginUpdater.updatePlugin(PluginUpdater.groovy:287)
	at nextflow.plugin.PluginUpdater.pullPlugin0(PluginUpdater.groovy:124)
	at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:253)
	at nextflow.plugin.PluginUpdater.installPlugin(PluginUpdater.groovy:140)
	at nextflow.plugin.PluginUpdater.pullPlugin0(PluginUpdater.groovy:119)
	at nextflow.plugin.PluginUpdater.pullPlugins(PluginUpdater.groovy:106)
	at nextflow.plugin.PluginsFacade.pullPlugins(PluginsFacade.groovy:275)
	at nextflow.plugin.Plugins.pull(Plugins.groovy:60)
	at nextflow.cli.CmdPlugins.run(CmdPlugins.groovy:50)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

**Comment by pditommaso** [comment]
Solved by 535c2bb5
