### ISSUE TITLE
calling dump on process.out channel get an exception

### ISSUE THREAD

**Issue by eldadkd** [nextflow-io/nextflow#1977]
### Expected behavior and actual behavior
dsl 2
I would like to see the output of a process to its out channel
doing this `processX.out.dump(tag: 'X results')` fails with Unknown method invocation `dump` on ChannelOut type exception
while doing identity map works:
processX.out.map{it}.dump(tag: 'X results')

### Steps to reproduce the problem
on dsl2
create a process that has an output
try to dump the output of that profile

### Program output 
`N E X T F L O W  ~  version 20.07.1
Launching `dsl2.nf` [evil_darwin] - revision: 2221a0e14d
[-        ] process > x -
Unknown method invocation `dump` on ChannelOut type
`
`Possible solutions: dump(), sum(), sum(java.lang.Object), drop(int), sum(groovy.lang.Closure), drop(int)
Mar-18 15:40:35.130 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingMethodException: No signature of method: nextflow.script.ChannelOut.dump() is applicable for argument types: (LinkedHashMap) values: [[tag:test]]
Possible solutions: dump(), sum(), sum(java.lang.Object), drop(int), sum(groovy.lang.Closure), drop(int)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:49)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at nextflow.Script_b7cfeeab$_runScript_closure3$_closure6.doCall(Script_b7cfeeab:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:182)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:169)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:191)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:219)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:219)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:127)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:274)
	at nextflow.cli.Launcher.run(Launcher.groovy:466)
	at nextflow.cli.Launcher.main(Launcher.groovy:648)
`

### Environment 

* Nextflow version: 20.07.1 
* Java version: openjdk version "1.8.0_282"
* Operating system: ubuntu
* Bash version: zsh 5.8

**Comment by pditommaso** [comment]
Missing test case to replicate the error
