### ISSUE TITLE
A process script declaring a regexp expression results in a IllegalAccessexception

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#199]
To reproduce use the following script: 

```
process foo {
  input: 
  val runID from '12_34abc'
  output: 
  val runID
  
  script:
  match = (runID =~ /(\d+_\d+).*/)
  match.matches()
  def sampleID = match.group(1)
  """
  echo $sampleID
  """
}
```

Run this script one time. 
Then run a second time using the `-resume` option. 
The following exception is thrown: 

```
java.lang.IllegalAccessError: tried to access method java.util.regex.Matcher.<init>()V from class reflectasm.java.util.regex.MatcherConstructorAccess
	at reflectasm.java.util.regex.MatcherConstructorAccess.newInstance(Unknown Source)
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy$1.newInstance(Kryo.java:1193)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1061)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:547)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:523)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:143)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:21)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.Kryo$readClassAndObject$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:126)
	at nextflow.util.KryoHelper$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nextflow.processor.TaskContext.read(TaskContext.groovy:213)
	at nextflow.processor.TaskContext$read$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:623)
	at nextflow.processor.TaskProcessor$checkCachedOutput$2.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at nextflow.processor.ParallelTaskProcessor.invokeTask(ParallelTaskProcessor.groovy:217)
```

**Comment by pditommaso** [comment]
The problem is caused by the matcher `match = (runID =~ /(\d+_\d+).*/)` object in the script scope which it's included in the variable serialised to preserve process context. 

An easy workaround consists prefixing the matcher declaration with the `def` keyword e.g. `def match = (runID =~ /(\d+_\d+).*/)`. 

This will cause the matcher object to not be included in the serialised variables.
