### ISSUE TITLE
Java exeption when running nf-core/sarek with kuberun

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#1991]
## Bug report 

nextflow  kuberun nf-core/sarek -v nf-co-pvc:/mnt -w /mnt/tmp --input 'file' --genome GRCh38 --tools HaplotypeCaller,VEP,Manta

causes:
Unknown method invocation `check_resource`

Exception in thread "Task submitter" groovy.lang.MissingMethodException: No signature of method: Script_ccb43ab0.check_resource() is applicable for argument types: (Integer) values: [8]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:76)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:146)
	at nextflow.script.BaseScript.invokeMethod(BaseScript.groovy:159)
	at groovy.lang.GroovyObject$invokeMethod$0.call(Unknown Source)
	at nextflow.processor.TaskContext.invokeMethod(TaskContext.groovy:148)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at _nf_config_6469ab64$_run_closure3$_closure12.doCall(_nf_config_6469ab64:23)
	at _nf_config_6469ab64$_run_closure3$_closure12.doCall(_nf_config_6469ab64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy:523)
	at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy)
	at nextflow.processor.LazyMap.resolve(TaskConfig.groovy:484)
	at nextflow.processor.LazyMap.get(TaskConfig.groovy:547)
	at nextflow.processor.TaskConfig.get(TaskConfig.groovy:111)
	at nextflow.processor.TaskConfig.getCpus(TaskConfig.groovy:247)
	at nextflow.processor.TaskConfig$getCpus$0.call(Unknown Source)
	at nextflow.processor.TaskHandler.getTraceRecord(TaskHandler.groovy:168)
	at nextflow.k8s.K8sTaskHandler.getTraceRecord(K8sTaskHandler.groovy:405)
	at nextflow.Session.notifyTaskComplete(Session.groovy:955)
	at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:567)
	at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1259)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1039)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1133)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.lang.Thread.run(Thread.java:748)

nextflow.config:
k8s {
   namespace = 'nf-core'
   context   = 'hdha-cluster'
   runAsUser = 1000
   debug.yaml = true
   pod = [[env: 'KUBECONFIG', value: '/mnt/xhejtman/.kube/config'], [env:'NXF_DEBUG', value: '3'] ]
}

process {
   executor = 'k8s'
}

this one runs ok:
nextflow kuberun nextflow-io/rnatoy -v nf-co-pvc:/mnt

but it does not seem to be spawning additional pods.

### Environment 

* Nextflow version: 20.10
* Java version: in container: nextflow/nextflow:20.10.0
* Operating system: Kubernetes 1.20.4, Linux, Ubuntu
* Bash version: version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by xhejtman** [comment]
nextflow kuberun nextflow-io/hello -v nf-co-pvc:/mnt
Launcher pod spec file: .nextflow.pod.yaml
Pod started: extravagant-hypatia
N E X T F L O W  ~  version 20.10.0
Launching `nextflow-io/hello` [extravagant-hypatia] - revision: e6d9427e5b [master]
[b4/f3cbc7] Submitted process > sayHello (1)
[fe/c5a3e0] Submitted process > sayHello (2)
[0d/a666b7] Submitted process > sayHello (3)
[75/ba88ec] Submitted process > sayHello (4)
Bonjour world!
Ciao world!
Hello world!
Hola world!


hello example works ok as well and is submitting pods.

**Comment by xhejtman** [comment]
it can be fixed, if this function is added into pod's nextflow.config:

def check_resource(obj) {
    try {
      if (obj.getClass() == nextflow.util.MemoryUnit && obj.compareTo(params.max_memory as nextflow.util.MemoryUnit) == 1)
        return params.max_memory as nextflow.util.MemoryUnit
      else if (obj.getClass() == nextflow.util.Duration && obj.compareTo(params.max_time as nextflow.util.Duration) == 1)
        return params.max_time as nextflow.util.Duration
      else if (obj.getClass() == java.lang.Integer)
        return Math.min(obj, params.max_cpus as int)
      else
        return obj
    } catch (all) {
        println "   ### ERROR ###   Max params max_memory:'${params.max_memory}', max_time:'${params.max_time}' or max_cpus:'${params.max_cpus}'  is not valid! Using default value: $obj"
    }
}

however, if I add it into main nextflow.config, it is ignored. moreover, it should be enough that the function is defined in nf-core/sarek nextflow.config ?

**Comment by xhejtman** [comment]
Mar-25 21:07:07.229 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /mnt/projects/nf-core/sarek/nextflow.config
Mar-25 21:07:07.229 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /mnt/xhejtman/nextflow.config
Mar-25 21:07:07.230 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/projects/nf-core/sarek/nextflow.config
Mar-25 21:07:07.230 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/xhejtman/nextflow.config

for some strange reason, those two configs are not merged together, sarek/nextflow.config contains definition of check_resource.

**Comment by pditommaso** [comment]
This is a known issue. The `kuberun` command cannot handle custom functions defined the nextflow.config file.
