### ISSUE TITLE
toSortedList inconsistant behaviour with custom closure

### ISSUE THREAD

**Issue by GDCCP** [nextflow-io/nextflow#2076]
## Bug report 

It appears that toSortedList can only take inline closure, but not a variable holding a closure, nor a function (not covered in the test case). I think it is important for all the operators to have a more consistent treatment of closure/named functions or lambda expressions.

function support is very important in DSL2 because only function/process/workflow in a module are exported.

### Expected behavior and actual behavior
This is my test:

```
def ch = Channel.fromList(["ajvoidjs23","9oejfsdf","fijd","fjioe84sdfusd"])
def bySize =  { a,b -> (a.size() <=> b.size()) }

ch.toSortedList({a,b -> bySize(a,b)}).view()
ch.toSortedList(bySize).view()
```

The first toSortedList call produce valid outputs, but the 2nd one ends with an exception

### Steps to reproduce the problem
1. start nextflow console
2. paste the above 4 lines
3. hit Crtl-R to run the code

### Program output 

groovy> def ch = Channel.fromList(["ajvoidjs23","9oejfsdf","fijd","fjioe84sdfusd"]) 
groovy> def bySize =  { a,b -> (a.size() <=> b.size()) } 
groovy> ch.toSortedList({a,b -> bySize(a,b)}).view() 
groovy> ch.toSortedList(bySize).view() 
 
[fijd, 9oejfsdf, ajvoidjs23, fjioe84sdfusd]
Exception thrown

```
nextflow.dag.MultipleInputChannelException(stackTrace:[nextflow.dag.DAG.inbound(DAG.groovy:191), nextflow.dag.DAG.addVertex(DAG.groovy:130), nextflow.dag.DAG.addOperatorNode(DAG.groovy:101), nextflow.dag.NodeMarker.addOperatorNode(NodeMarker.groovy:63), nextflow.extension.OpCall.addGraphNode(OpCall.groovy:171), nextflow.extension.OpCall.invoke(OpCall.groovy:161), nextflow.extension.OpCall.call(OpCall.groovy:113), nextflow.extension.OperatorEx.invokeExtensionMethod(OperatorEx.groovy:108), ConsoleScript57.runScript(ConsoleScript57:6), nextflow.script.BaseScript.runDsl1(BaseScript.groovy:164), nextflow.script.BaseScript.run(BaseScript.groovy:200)], suppressed:[], stackTraceDepth:54, cause:null, message:Channels cannot be used as input in more than one process or operator, localizedMessage:Channels cannot be used as input in more than one process or operator)
	at nextflow.dag.DAG.inbound(DAG.groovy:191)
	at nextflow.dag.DAG.addVertex(DAG.groovy:130)
	at nextflow.dag.DAG.addOperatorNode(DAG.groovy:101)
	at nextflow.dag.NodeMarker.addOperatorNode(NodeMarker.groovy:63)
	at nextflow.extension.OpCall.addGraphNode(OpCall.groovy:171)
	at nextflow.extension.OpCall.invoke(OpCall.groovy:161)
	at nextflow.extension.OpCall.call(OpCall.groovy:113)
	at nextflow.extension.OperatorEx.invokeExtensionMethod(OperatorEx.groovy:108)
	at ConsoleScript57.runScript(ConsoleScript57:6)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:164)
```

### Environment 

* Nextflow version: 20.07.1
* Java version: 1.8.0
* Operating system: Centos 7
* Bash version: 4.2.46

### Additional context

What I am trying to do is more involved. I basically have a custom sort function in a module which is constructed using from some curry function. The custom sort will be shared/used in multiple places/modules.

**Comment by pditommaso** [comment]
Unable to replicate 

```
» NXF_VER=20.10.0 nextflow run test.nf -dsl2
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [happy_pesquet] - revision: f84439ca9f
[fijd, 9oejfsdf, ajvoidjs23, fjioe84sdfusd]
[fijd, 9oejfsdf, ajvoidjs23, fjioe84sdfusd]
```

**Comment by manuelesimi** [comment]
Hi @pditommaso, sorry to jump in after you closed.

Even if the issue mentions DSL2, I believe DSL2 was not enabled in the original request.

I get the same error without `-dsl2` and the reason is because the channel `ch` is consumed twice.

Something like the following perfectly works in DSL1:

<pre>
def ch = Channel.fromList(["ajvoidjs23","9oejfsdf","fijd","fjioe84sdfusd"])
ch.into { ch1; ch2 } 

def bySize =  { a,b -> (a.size() <=> b.size()) }

ch1.toSortedList({a,b -> bySize(a,b)}).view()
ch2.toSortedList(bySize).view()
</pre>

**Comment by pditommaso** [comment]
> Hi @pditommaso, sorry to jump in after you closed.

No pb! 


> I get the same error without -dsl2 and the reason is because the channel ch is consumed twice.

I've noticed the error reported is different

**Comment by manuelesimi** [comment]
I get the same stacktrace (which is very clear about the source of the error) in the .nextflow.log:

<pre>
May-02 11:38:08.246 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.dag.MultipleInputChannelException: Channels cannot be used as input in more than one process or operator
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:295)

</pre>

**Comment by pditommaso** [comment]
You got a point! 👍
