### ISSUE TITLE
Slurm MPI execution - Unknown daemon name: ignite

### ISSUE THREAD

**Issue by lescai** [nextflow-io/nextflow#2201]
### Expected behavior and actual behavior

Hi there, I am trying to use nextflow for the first time with MPI, and decided to test using an MPI implementation of BWA.
When I launch the job, I get the following error from Nextflow, indicating that **Unknown executor name: ignite**

### Steps to reproduce the problem

I tried to follow as literally as possible the docs here https://www.nextflow.io/docs/latest/ignite.html#linux-slurm-launcher

by creating the following job script (the resources and settings are just a copy / paste of the docs - don't care at this stage about bwa itself):

```
#!/bin/bash
#SBATCH --job-name=nfmpi
#SBATCH --output=/home/lescai/tests/nextflow/mpi/test_mpibwa_%j.log
#SBATCH --ntasks=5
#SBATCH --cpus-per-task=16
#SBATCH --tasks-per-node=1

module load conda/anaconda3
module load singularity/3.3.0
module load openmpi/gcc/64/1.10.7

conda activate nextflow_21.04.0

## export NXF_MODE=ignite <-- tried with and without this after looking at previous issues
export NXF_CLUSTER_SEED=$(shuf -i 0-16777216 -n 1)
srun nextflow run \
-c /home/lescai/tests/nextflow/mpi/eos_mpi.conf \
-profile singularity \
/home/lescai/tests/nextflow/mpi/test_mpibwa.nf \
-with-mpi
```

while the script itself should be relatively simple. 
I haven't indicated the process.executor, as I understood ```-with-mpi``` would set it to ignite.
I tried with and without ```export NXF_MODE=ignite``` in the script
but the result is the same.
I should perhaps mention the script is in DSL2, although it's just one process.

### Program output 

This is the relevant part from the log file

```
Jul-05 14:57:38.170 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-05 14:57:38.222 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: MPIBWA
Jul-05 14:57:38.434 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jul-05 14:57:38.435 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'ignite'
Jul-05 14:57:38.436 [main] DEBUG nextflow.Session - Session aborted -- Cause: Unknown executor name: ignite
Jul-05 14:57:38.472 [main] ERROR nextflow.cli.Launcher - Unknown executor name: ignite
java.lang.IllegalArgumentException: Unknown executor name: ignite
	at nextflow.executor.ExecutorFactory.getExecutorClass(ExecutorFactory.groovy:140)
	at nextflow.executor.ExecutorFactory.getExecutor(ExecutorFactory.groovy:184)
	at nextflow.script.ProcessDef.run(ProcessDef.groovy:198)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:95)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at Script_d3b1db54$_runScript_closure2$_closure6.doCall(Script_d3b1db54:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:191)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

### Environment 

* Nextflow version: 21.04.0
* Java version: openjdk version "11.0.9.1-internal" 2020-11-04
* Operating system: centOS 7
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by lescai** [comment]
Following the issue https://github.com/nextflow-io/nextflow/issues/118 I have launched again this time using

```
export NXF_CLUSTER_SEED=$(shuf -i 0-16777216 -n 1)
srun nextflow run \
-c /home/lescai/tests/nextflow/mpi/eos_mpi.conf \
-profile singularity \
/home/lescai/tests/nextflow/mpi/test_mpibwa.nf \
-process.executor ignite \
-with-mpi
```

i.e. with ```-process.executor ignite``` within the command line.
mpiBWA doesn't do great :) but Nextflow seems to launch/broadcast correctly now.
I'll close the issue but may I suggest to add this to the documentation here maybe?
https://www.nextflow.io/docs/latest/ignite.html#linux-slurm-launcher

**Comment by lescai** [comment]
I'm afraid I have to reopen this. I did believe it was running just fine because I could see the job running and the nextflow log printing the information I'd expect (i.e. ignite deployed, process launched).
however, it's doing nothing.
I've run the very same script on slurm, and it completed in seconds (it's just a poisson demo).
When I launch it with mpi, it doesn't even sym link the input file in the work directory (this is present as expected in a normal slurm run).
The only thing I've noticed is that in the slurm log file there's a message saying ```Unknown daemon name: ignite```.
I thought this wasn't a problem since the nextflow log prints
```Jul-07 10:56:47.982 [main] INFO  o.a.i.internal.IgniteKernal%nextflow - Daemon mode: off```
I have no clue how to move from here.
Some help would be really appreciated.
I am attaching the log files with hopefully clear names.
[fenics_local_nextflow.log](https://github.com/nextflow-io/nextflow/files/6775975/fenics_local_nextflow.log)
[fenics_mpi_nextflow.log](https://github.com/nextflow-io/nextflow/files/6775976/fenics_mpi_nextflow.log)
[fenics_mpi_slurm.log](https://github.com/nextflow-io/nextflow/files/6775977/fenics_mpi_slurm.log)

**Comment by pditommaso** [comment]
This feature is experimental and above all nextflow MPI support has nothing to do with tools MPI execution as it's your expectation reading the above comment. 

Nextflow can use MPI as a means to launch its own execution daemons, in no way it implies the use of MPI for job executions.

**Comment by lescai** [comment]
thanks for the very formal answer @pditommaso. apologies if - as a user - this wasn't clear enough to me. 
I hope this thread will then be useful to other users who, like me, did not understand this immediately by reading the documentation.
