### ISSUE TITLE
Request to improve error message when failures happen due to proxy settings 

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#2233]
We should have a useful message on the console when the failures happen due to proxy settings.

At the moment, these are only available in the `.nextflow.log` files

```
Jul-21 11:01:18.239 [main] ERROR o.p.update.DefaultUpdateRepository - Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
```

**Comment by abhi18av** [comment]
I'm guessing that this commit https://github.com/nextflow-io/nextflow/commit/ad41d1e980c2a0707cea1bf4e6ea4a3f3d347246 addressed the issue, right?

**Comment by pditommaso** [comment]
No, the above commit does not help. Similar problem happens when there's a network failure 

```
Aug-06 15:25:42.065 [main] ERROR o.p.update.DefaultUpdateRepository - No route to host (Host unreachable)
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1067)
	at org.pf4j.update.DefaultUpdateRepository.initPlugins(DefaultUpdateRepository.java:96)
	at org.pf4j.update.DefaultUpdateRepository.getPlugins(DefaultUpdateRepository.java:80)
	at org.pf4j.update.UpdateManager.getPluginsMap(UpdateManager.java:149)
	at org.pf4j.update.UpdateManager.findReleaseForPlugin(UpdateManager.java:319)
	at org.pf4j.update.UpdateManager.downloadPlugin(UpdateManager.java:268)
	at nextflow.plugin.PluginUpdater.download0(PluginUpdater.groovy:157)
	at nextflow.plugin.PluginUpdater.access$0(PluginUpdater.groovy)
	at nextflow.plugin.PluginUpdater$_safeDownload_closure2.doCall(PluginUpdater.groovy:212)
	at nextflow.plugin.PluginUpdater$_safeDownload_closure2.call(PluginUpdater.groovy)
	at nextflow.file.FileMutex.lock(FileMutex.groovy:107)
	at nextflow.plugin.PluginUpdater.safeDownload(PluginUpdater.groovy:212)
	at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:241)
	at nextflow.plugin.PluginUpdater.installPlugin(PluginUpdater.groovy:140)
	at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:88)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:241)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:251)
	at nextflow.plugin.PluginsFacade.setup(PluginsFacade.groovy:162)
	at nextflow.plugin.Plugins.setup(Plugins.groovy:39)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:276)
```
