### ISSUE TITLE
Sharing a private pipeline does not work

### ISSUE THREAD

**Issue by wclose** [nextflow-io/nextflow#2236]
### Expected behavior and actual behavior

Expected:
A Nxf pipeline in a private repository can be executed directly using the `nextflow run OWNER/NAME` syntax similar to `nextflow run nextflow-io/hello`. Credentials for the private repository can be supplied via the command-line using the `-user` flag or via a profile in `~/.nextflow/scm`.

Actual:
When pipelines are executed from private repositories, the GitHub API fails to authenticate and the resources are not found. If you make the repository public, it is able to execute without any issues proving that the authentication is not working. Using the API directly, I am able to verify that the resources exist.

### Steps to reproduce the problem

1. I copied the `nextflow-io/hello` pipeline into a personal public repository found here: https://github.com/wclose/nxf_test. The `manifest.defaultBranch` parameter was updated to `main`.
2. The pipeline successfully executed using `nextflow run wclose/nxf_test`.
3. The repository was changed to private.
4. The pipeline failed execution after `nextflow run wclose/nxf_test` as expected.
5. The pipeline failed execution after `nextflow run -user wclose wclose/nxf_test` and supplying my GitHub password which was NOT expected.
6. The pipeline failed execution after `nextflow run wclose/nxf_test -user wclose` and supplying my GitHub password which was NOT expected.
7. The pipeline failed execution using the following SCM file setups and running `nextflow run wclose/nxf_test` which was NOT expected.

`~/.nextflow/scm`
```
providers {

    github {
        user = 'wclose'
        password = '<MY_PASSWORD>'
    }

}
```
```
providers {

    github {
        user = 'wclose'
        token = '<MY_TOKEN>'
    }

}
```
```
providers {

    github {
        user = 'wclose'
        password = '<MY_PASSWORD>'
        token = '<MY_TOKEN>'
    }

}
```

8. I used the GitHub API to successfully verify that the resources were reachable in the private repository
```
curl -i -u wclose:$MY_TOKEN https://api.github.com/repos/wclose/nxf_test/contents/nextflow.config
``` 

### Program output 

`stdout`
```
PROMPT$ nextflow run -user wclose wclose/nxf_test
N E X T F L O W  ~  version 21.04.0
Checking wclose/nxf_test ...
Enter your github password: 
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/wclose/nxf_test/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/wclose/nxf_test/contents/main.nf
```

`.nextflow.log`
```
Jul-21 19:28:10.883 [main] DEBUG nextflow.cli.Launcher - $> nextflow run -user wclose wclose/nxf_test
Jul-21 19:28:10.980 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.0
Jul-21 19:28:28.768 [main] INFO  nextflow.cli.CmdRun - Pulling wclose/nxf_test ...
Jul-21 19:28:28.770 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials wclose:*****************] -> https://api.github.com/repos/wclose/nxf_test/contents/nextflow.config
Jul-21 19:28:29.118 [main] DEBUG nextflow.scm.RepositoryProvider - Response status: 404 -- {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-repository-content"}
Jul-21 19:28:29.123 [main] WARN  nextflow.scm.AssetManager - Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/wclose/nxf_test/contents/nextflow.config
nextflow.exception.AbortOperationException: Remote resource not found: https://api.github.com/repos/wclose/nxf_test/contents/nextflow.config
	at nextflow.scm.RepositoryProvider.checkResponse(RepositoryProvider.groovy:187)
	at nextflow.scm.RepositoryProvider.invoke(RepositoryProvider.groovy:136)
	at nextflow.scm.RepositoryProvider.memoizedMethodPriv$invokeAndParseResponseString(RepositoryProvider.groovy:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.scm.RepositoryProvider$_closure2.doCall(RepositoryProvider.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:428)
	at nextflow.scm.RepositoryProvider.invokeAndParseResponse(RepositoryProvider.groovy)
	at nextflow.scm.GithubRepositoryProvider.readBytes(GithubRepositoryProvider.groovy:100)
	at nextflow.scm.RepositoryProvider.readText(RepositoryProvider.groovy:232)
	at nextflow.scm.AssetManager.getManifest0(AssetManager.groovy:448)
	at nextflow.scm.AssetManager.memoizedMethodPriv$getManifest(AssetManager.groovy:441)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.scm.AssetManager$_closure2.doCall(AssetManager.groovy)
	at nextflow.scm.AssetManager$_closure2.doCall(AssetManager.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.scm.AssetManager.getManifest(AssetManager.groovy)
	at nextflow.scm.AssetManager.getMainScriptName(AssetManager.groovy:424)
	at nextflow.scm.AssetManager.checkValidRemoteRepo(AssetManager.groovy:382)
	at nextflow.scm.AssetManager.download(AssetManager.groovy:591)
	at nextflow.scm.AssetManager.download(AssetManager.groovy)
	at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:368)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:265)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
Jul-21 19:28:29.131 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials wclose:*****************] -> https://api.github.com/repos/wclose/nxf_test/contents/main.nf
Jul-21 19:28:29.173 [main] DEBUG nextflow.scm.RepositoryProvider - Response status: 404 -- {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-repository-content"}
Jul-21 19:28:29.174 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Remote resource not found: https://api.github.com/repos/wclose/nxf_test/contents/main.nf
	at nextflow.scm.RepositoryProvider.checkResponse(RepositoryProvider.groovy:187)
	at nextflow.scm.RepositoryProvider.invoke(RepositoryProvider.groovy:136)
	at nextflow.scm.RepositoryProvider.memoizedMethodPriv$invokeAndParseResponseString(RepositoryProvider.groovy:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.scm.RepositoryProvider$_closure2.doCall(RepositoryProvider.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:428)
	at nextflow.scm.RepositoryProvider.invokeAndParseResponse(RepositoryProvider.groovy)
	at nextflow.scm.GithubRepositoryProvider.readBytes(GithubRepositoryProvider.groovy:100)
	at nextflow.scm.RepositoryProvider.validateFor(RepositoryProvider.groovy:246)
	at nextflow.scm.AssetManager.checkValidRemoteRepo(AssetManager.groovy:383)
	at nextflow.scm.AssetManager.download(AssetManager.groovy:591)
	at nextflow.scm.AssetManager.download(AssetManager.groovy)
	at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:368)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:265)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

### Environment 

* Nextflow version: 20.10.0 and 21.04.0.5552 (installed via `conda` env)
* Java version: openjdk version "11.0.9.1-internal" 2020-11-04
* Operating system: Linux
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

### Additional context

N/A

**Comment by wclose** [comment]
I suspect this may be related to the transition away from using passwords for GitHub API calls as described here: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/. It looks like within a month, calls will only be accepted if using a token.

**Comment by wclose** [comment]
After realizing that only the token worked for accessing private repository data through the API, I used my token at the password prompt instead and it worked (yay!). I would suggest updating the documentation and the Nxf prompts to reflect the changes in credential requirements.

For anyone else that comes across this issue, here is an example of how to use this. Replace <MY_TOKEN> below with your GitHub OAuth token and you will be able to access private repositories correctly:
```
PROMPT$ nextflow run wclose/nxf_test2 -user wclose
N E X T F L O W  ~  version 21.04.0
Enter your github password: <MY_TOKEN>
Pulling wclose/nxf_test2 ...
 downloaded from https://github.com/wclose/nxf_test2.git
Launching `wclose/nxf_test2` [insane_lalande] - revision: 64f7883ff0 [main]
executor >  local (4)
[76/e5162f] process > sayHello (3) [100%] 4 of 4 ✔
Ciao world!

Hola world!

Bonjour world!

Hello world!
```

**Comment by wclose** [comment]
The last update to this is that the SCM configuration file must also reflect the above changes, namely putting your OAuth token in place of the password field. Per the [docs](https://www.nextflow.io/docs/latest/sharing.html#scm-configuration-file), the `token` field is only used by GitLab so the GitHub token must instead go into the `password` field. If you do this, the authentication works correctly and you are able to access the private repository.

`~/.nextflow/scm`
```
providers {

    github {
        user = 'wclose'
        password = '<MY_TOKEN>'
    }

}
```

Executing pipeline
```
PROMPT$ nextflow run wclose/nxf_test
N E X T F L O W  ~  version 21.04.0
Pulling wclose/nxf_test ...
 downloaded from https://github.com/wclose/nxf_test.git
Launching `wclose/nxf_test` [irreverent_mestorf] - revision: 64f7883ff0 [main]
executor >  local (4)
[37/b4dea5] process > sayHello (2) [100%] 4 of 4 ✔
Bonjour world!

Hola world!

Hello world!

Ciao world!
```

**Comment by pditommaso** [comment]
I've updated the docs to highlight the need for PAT in place of the password 4532b8e1e. Thanks for reporting.
