### ISSUE TITLE
fromSRA URL deprecated

### ISSUE THREAD

**Issue by Christian-Jansen** [nextflow-io/nextflow#2237]
### Expected behavior and actual behavior

The fromSRA channel factory method should give back a channel with tuples containing the accession number and corresponding ftp link/fastq location.
However when I provide the method with a list of accession numbers I get the error: `Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport`

Proposed solution:
Change the base URL in line 257 of the [SraExplorer.groovy](https://github.com/nextflow-io/nextflow/blob/e4d9b62cdce3327a530b153e54eefff171356ca0/modules/nextflow/src/main/groovy/nextflow/datasource/SraExplorer.groovy#L257) from https://www.ebi.ac.uk/ena/data/warehouse/filereport to https://www.ebi.ac.uk/ena/portal/api/filereport

### Steps to reproduce the problem

Example `main.nf` to replicate the issue:
```
nextflow.enable.dsl = 2
accList = ['ERR908507', 'ERR908506', 'ERR908505']
workflow {
    fastq_input_ch = Channel.fromSRA(accList)
    fastq_input_ch.view()
}
```

### Program output 

.nextflow.log file:
```
Jul-22 15:15:11.229 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf --input test-list.txt
Jul-22 15:15:11.367 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.2
Jul-22 15:15:11.401 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [berserk_kare] - revision: 565a65de67
Jul-22 15:15:11.416 [main] DEBUG nextflow.config.ConfigBuilder - Found config home: /home/jansen/.nextflow/config
Jul-22 15:15:11.418 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/jansen/Projects/bix-wgs/nextflow.config
Jul-22 15:15:11.419 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/jansen/.nextflow/config
Jul-22 15:15:11.420 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/jansen/Projects/bix-wgs/nextflow.config
Jul-22 15:15:11.450 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jul-22 15:15:12.255 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jul-22 15:15:12.372 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/jansen/.nextflow/plugins
Jul-22 15:15:12.374 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jul-22 15:15:12.377 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins local root: .nextflow/plr/empty
Jul-22 15:15:12.386 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jul-22 15:15:12.387 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jul-22 15:15:12.392 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jul-22 15:15:12.403 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jul-22 15:15:12.455 [main] DEBUG nextflow.Session - Session uuid: 4ae68f59-506a-4186-b34e-00915fd5eec1
Jul-22 15:15:12.455 [main] DEBUG nextflow.Session - Run name: berserk_kare
Jul-22 15:15:12.456 [main] DEBUG nextflow.Session - Executor pool size: 16
Jul-22 15:15:12.473 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.04.2 build 5558
  Created: 12-07-2021 07:54 UTC (09:54 CEST)
  System: Linux 5.12.15-300.fc34.x86_64
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 1.8.0_282-b08
  Encoding: UTF-8 (UTF-8)
  Process: 94969@localhost.localdomain [127.0.0.1]
  CPUs: 16 - Mem: 15.1 GB (6.3 GB) - Swap: 26.2 GB (25.8 GB)
Jul-22 15:15:12.497 [main] DEBUG nextflow.Session - Work-dir: /home/jansen/Projects/bix-wgs/work [ext2/ext3]
Jul-22 15:15:12.498 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/jansen/Projects/bix-wgs/bin
Jul-22 15:15:12.511 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jul-22 15:15:12.524 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jul-22 15:15:12.669 [main] DEBUG nextflow.Session - Session start invoked
Jul-22 15:15:12.899 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-22 15:15:13.075 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: TAXONOMIC_PROFILING
Jul-22 15:15:13.194 [main] DEBUG nextflow.extension.CH - Bridging dataflow queue=DataflowQueue(queue=[])
Jul-22 15:15:13.197 [main] DEBUG nextflow.Session - Ignite dataflow network (1)
Jul-22 15:15:13.203 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Jul-22 15:15:13.203 [main] DEBUG nextflow.Session - Session await
Jul-22 15:15:13.203 [main] DEBUG nextflow.Session - Session await > all process finished
Jul-22 15:15:13.203 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-22 15:15:13.205 [ForkJoinPool.commonPool-worker-9] DEBUG nextflow.datasource.SraExplorer - SRA search url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&usehistory=y&retmode=json&api_key=dbe349933cbf30be4d04320ae09f30c2ca08&term=ERR908507
Jul-22 15:15:14.619 [ForkJoinPool.commonPool-worker-9] DEBUG nextflow.datasource.SraExplorer - SRA data request url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=sra&retmode=json&query_key=1&WebEnv=MCID_60f96f62352c1671514ecbe8&retstart=0&retmax=1000&api_key=dbe349933cbf30be4d04320ae09f30c2ca08
Jul-22 15:15:16.483 [ForkJoinPool.commonPool-worker-9] DEBUG nextflow.datasource.SraExplorer - SRA fetch ftp fastq url=https://www.ebi.ac.uk/ena/data/warehouse/filereport?result=read_run&fields=fastq_ftp&accession=ERR908507
Jul-22 15:15:17.361 [ForkJoinPool.commonPool-worker-9] ERROR nextflow.Channel - Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport
java.io.IOException: Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.configuredInputStream(ResourceGroovyMethods.java:2222)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.newReader(ResourceGroovyMethods.java:2308)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:640)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:603)
	at org.codehaus.groovy.runtime.dgm$1041.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.doMethodInvoke(GeneratedMetaMethod.java:83)
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at nextflow.datasource.SraExplorer.readRunUrl(SraExplorer.groovy:260)
	at nextflow.datasource.SraExplorer.readRunFastqs(SraExplorer.groovy:248)
	at nextflow.datasource.SraExplorer.getFastqUrl(SraExplorer.groovy:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.parseDataResponse(SraExplorer.groovy:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.query1(SraExplorer.groovy:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.query0(SraExplorer.groovy:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.query0(SraExplorer.groovy:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.apply(SraExplorer.groovy:103)
	at nextflow.Channel$_fetchSraFiles0_closure16.doCall(Channel.groovy:608)
	at nextflow.Channel$_fetchSraFiles0_closure16.call(Channel.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Jul-22 15:15:17.375 [ForkJoinPool.commonPool-worker-9] DEBUG nextflow.Session - Session aborted -- Cause: Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport
Jul-22 15:15:17.413 [ForkJoinPool.commonPool-worker-9] DEBUG nextflow.Session - The following nodes are still active:
  [operator] view

Jul-22 15:15:17.436 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Jul-22 15:15:17.499 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Jul-22 15:15:17.526 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

```

### Environment 

* Nextflow version: [21.04.2.5558] 
* Java version: [openjdk version "1.8.0_282"]
* Operating system: [Linux Fedora 34]
* Bash version: [GNU bash, version 5.1.0(1)-release (x86_64-redhat-linux-gnu)]

### Additional context
From what I was able to find together with a colleague it seems, that the ebi has updated/moved the url which is why the base url for the api requests is no longer valid and produces the error.
The base url in my current nextflow version is:
https://www.ebi.ac.uk/ena/data/warehouse/filereport
When trying to access the api in the browser with this base url we were forwarded to the url in the error message.
When changing the base url to 
https://www.ebi.ac.uk/ena/portal/api/filereport
we got back the correct accession number and ftp path.

**Comment by abhi18av** [comment]
Thanks for reporting this change in the ENA API @Christian-Jansen!

We've implemented a solution in the linked PR - this would be available in the next `edge` release.

**Comment by PPrasai** [comment]
Thank you @Christian-Jansen . I was facing the exact same problem.
@abhi18av **Thanks for the fix.** When can this fix be expected to be included in the main release?

**Comment by abhi18av** [comment]
Hi @PPrasai ,

I think this would be there in `21.10.0` release.

But you could also make use of this via the latest edge releases https://github.com/nextflow-io/nextflow/releases/tag/v21.07.0-edge
