### ISSUE TITLE
No such variable error when declaring process' path output

### ISSUE THREAD

**Issue by Midnighter** [nextflow-io/nextflow#2245]
### Expected behavior and actual behavior

I have a simple process that creates a directory based on a string value passed to that process. I then want to include that directory in the output from that process. I would expect that to be possible but it is not, it fails the pipeline with the error `No such variable: meta`.

### Steps to reproduce the problem

```groovy
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

process FOO {
  input:
  val(meta)

  output:
  tuple val(meta), path(meta.id), emit: reads

  script:
  """
  mkdir "${meta.id}"
  """
}

workflow {
    FOO(Channel.of([id: 'sequence1']))
}
```

### Program output 

`No such variable: meta`

Log output in details.

<details>

```
Jul-27 18:57:40.932 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Jul-27 18:57:40.993 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.3
Jul-27 18:57:41.009 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [goofy_jepsen] - revision: b336120725
Jul-27 18:57:41.057 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/moritz/.nextflow/plugins
Jul-27 18:57:41.058 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jul-27 18:57:41.060 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins local root: .nextflow/plr/empty
Jul-27 18:57:41.066 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jul-27 18:57:41.067 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jul-27 18:57:41.069 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jul-27 18:57:41.077 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jul-27 18:57:41.117 [main] DEBUG nextflow.Session - Session uuid: f9705458-1ae7-44c4-95fd-b4f1690dad16
Jul-27 18:57:41.117 [main] DEBUG nextflow.Session - Run name: goofy_jepsen
Jul-27 18:57:41.118 [main] DEBUG nextflow.Session - Executor pool size: 16
Jul-27 18:57:41.147 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.04.3 build 5560
  Created: 21-07-2021 15:09 UTC (17:09 CEST)
  System: Linux 5.11.0-7620-generic
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04
  Encoding: UTF-8 (UTF-8)
  Process: 193344@helios [192.168.8.151]
  CPUs: 16 - Mem: 31.2 GB (6.1 GB) - Swap: 4 GB (4 GB)
Jul-27 18:57:41.166 [main] DEBUG nextflow.Session - Work-dir: /tmp/nf-bug/work [ext2/ext3]
Jul-27 18:57:41.167 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /tmp/nf-bug/bin
Jul-27 18:57:41.175 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jul-27 18:57:41.185 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jul-27 18:57:41.277 [main] DEBUG nextflow.Session - Session start invoked
Jul-27 18:57:41.834 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-27 18:57:41.861 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: FOO
Jul-27 18:57:41.926 [main] DEBUG nextflow.Session - Session aborted -- Cause: Unknown variable 'meta'
Jul-27 18:57:41.939 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: Unknown variable 'meta'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:295)
	at nextflow.script.ProcessConfig.getProperty(ProcessConfig.groovy:276)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:194)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:320)
	at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:310)
	at groovy.lang.Closure.getProperty(Closure.java:296)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at Script_b34fd4ec$_runScript_closure1.doCall(Script_b34fd4ec:10)
	at Script_b34fd4ec$_runScript_closure1.doCall(Script_b34fd4ec)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.ProcessDef.initialize(ProcessDef.groovy:111)
	at nextflow.script.ProcessDef.run(ProcessDef.groovy:165)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:95)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at Script_b34fd4ec$_runScript_closure2$_closure4.doCall(Script_b34fd4ec:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:191)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)

```

</details>

### Environment 

* Nextflow version: 21.04.3 build 5560
* Java version: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04
* Operating system: Linux 5.11.0-7620-generic
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

Redefining the output `path` using string interpolation resolves the problem which seems quite strange.

```groovy
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

process FOO {
  input:
  val(meta)

  output:
  tuple val(meta), path("${meta.id}"), emit: reads

  script:
  """
  mkdir "${meta.id}"
  """
}

workflow {
    FOO(Channel.of([id: 'sequence1']))
}
```

**Comment by bentsherman** [comment]
See my comment in #4215 . This happens because `meta.id` is normally evaluated during script execution, at which point `meta` isn't defined yet. But if you wrap it in a dynamic string, it will be lazily evaluated for each task, which is the desired behavior. Basically the DSL wraps the dynamic string in a closure while parsing the script.

**Comment by Midnighter** [comment]
I see, thank you for the explanation 🙂
