### ISSUE TITLE
NOTE: automatic download from remote repositories is disable.

### ISSUE THREAD

**Issue by ld9866** [nextflow-io/nextflow#2251]
hello! l have installed docker version sarek through print "docker pull nfcore/sarek" and it was done successfully.
Besides, l install nextflow through conda and it can successfully run. But when l print " nextflow run nf-core/sarek -profile docker" it showed that
N E X T F L O W ~ version 21.04.3
Unknown project nf-core/sarek -- NOTE: automatic download from remote repositories is disable.
l'd like to ask how can l solve it ?
thank you!

logfile:
16:54:43.019 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/sarek
16:54:43.186 [main] INFO nextflow.cli.CmdRun - N E X T F L O W ~ version 21.04.0
16:54:43.237 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unknown project nf-core/sarek -- NOTE: automatic download from remote repositories is disabled
at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:366)
at nextflow.cli.CmdRun.run(CmdRun.groovy:265)
at nextflow.cli.Launcher.run(Launcher.groovy:475)
at nextflow.cli.Launcher.main(Launcher.groovy:657)

**Comment by ld9866** [comment]
nextflow run hello is also not work!
N E X T F L O W  ~  version 21.04.3
Unknown project `nextflow-io/hello` -- NOTE: automatic download from remote repositories is disabled
