### ISSUE TITLE
AnsiLogObserver Thread.run error

### ISSUE THREAD

**Issue by agilly** [nextflow-io/nextflow#2283]
### Expected behavior and actual behavior

I would expect the process to either run or throw an error message and a suggestion to solve the problem. Instead, I am getting the following java exception (which breaks the display of the processes, I have cleaned it up a bit) below. I have pasted the process description below, which is intended to launch 22 parallel processes each consuming 50G RAM and 2 threads. The machine I am running this on can accomodate 22x50x2 GB RAM and 44 threads.

### Steps to reproduce the problem

Unfortunately due to patient privacy reasons, I am unable to share the data that is used in the following steps. This is the process that is causing the error:

```nextflow
process PrepareImputed {
	input:
	path keep from CommonSamples
	val filters from params.FilteringOptions
	path samplefile from params.SampleFile
	val bgenfile from params.BgenFile
	val ext from params.BgenExtension
	val chr from 1..22

	output:
	path 'chr*.filtered.{pgen,psam,pvar}' into PerChromosome

	"""
        plink2 --threads 2 --memory 50000 --bgen ${bgenfile}${chr}${ext} ref-first --sample $samplefile $filters --keep $keep --out chr${chr}.filtered --make-pgen > chr${chr}.plink.log 2>&1
	"""
}
```
My `nextflow.config` enables Singularity, specifies a container and two bind mounts, nothing else:

```
process.container = '/path/to/container' 
singularity.enabled = true
singularity {
        runOptions = "-B /data1 -B /data2"
}
```

### Program output 

```
Exception in thread "AnsiLogObserver" java.lang.NullPointerException
        at org.codehaus.groovy.runtime.StringGroovyMethods.count(StringGroovyMethods.java:353)
        at nextflow.trace.AnsiLogObserver.renderMessages(AnsiLogObserver.groovy:189)
        at nextflow.trace.AnsiLogObserver.renderMessages(AnsiLogObserver.groovy)1 ✔
        at nextflow.trace.AnsiLogObserver.renderProgress(AnsiLogObserver.groovy:282)
        at nextflow.trace.AnsiLogObserver.render0(AnsiLogObserver.groovy:169)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:829)
WARN: Killing pending tasks (22)
```

### Environment 
This was tested on 2 servers, producing the same error.

* Nextflow version: 21.04.3
* Java version: 
  * openjdk 11.0.11 2021-04-20
  * OpenJDK Runtime Environment (build 11.0.11+9-suse-3.56.1-x8664)
  * OpenJDK 64-Bit Server VM (build 11.0.11+9-suse-3.56.1-x8664, mixed mode)
  * also tested on:
  * openjdk 11.0.12 2021-07-20 LTS
  * OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
  * OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)
* Operating system: Tested on CentOS 7 and OpenSuse 15.3
* Bash version: 4.4.23(1)-release (x86_64-suse-linux-gnu) and 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context
One serious consequence of this bug is that despite the last line of the logs, the child `plink2` processes are not killed, which hogs the server pretty badly if not manually killed.

**Comment by pditommaso** [comment]
Thanks for reporting this. Could not find a way to replicate it, however, I've pushed a commit that should address the problem.
