### ISSUE TITLE
fromSRA returns http error 500

### ISSUE THREAD

**Issue by mybiotics** [nextflow-io/nextflow#2292]
### Expected behavior and actual behavior

I follow the example from this tutorial https://seqera.io/training/#_fromsra

```
Channel
    .fromSRA('SRP043510')
    .view()
```

I expect to see a list of SRA files, as described in the tutorial

### Steps to reproduce the problem

This is my command session:

```
export NCBI_API_KEY=<THE_KEY>
$ nextflow hello.nf
```

### Program output 

```
N E X T F L O W  ~  version 21.04.0
Launching `hello.nf` [marvelous_mirzakhani] - revision: 96b1e6b0f2
Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport
$ cat .nextflow.log
Sep-05 10:39:19.873 [main] DEBUG nextflow.cli.Launcher - $> nextflow hello.nf
Sep-05 10:39:19.969 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.0
Sep-05 10:39:19.995 [main] INFO  nextflow.cli.CmdRun - Launching `hello.nf` [marvelous_mirzakhani] - revision: 96b1e6b0f2
Sep-05 10:39:20.006 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Users/boris/temp/nextflowtraining/nextflow.config
Sep-05 10:39:20.006 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/boris/temp/nextflowtraining/nextflow.config
Sep-05 10:39:20.022 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Sep-05 10:39:20.394 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/Users/boris/.nextflow/plugins
Sep-05 10:39:20.395 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Sep-05 10:39:20.397 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins local root: .nextflow/plr/empty
Sep-05 10:39:20.402 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Sep-05 10:39:20.402 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Sep-05 10:39:20.405 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Sep-05 10:39:20.411 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Sep-05 10:39:20.455 [main] DEBUG nextflow.Session - Session uuid: 0815e1db-0636-4575-b574-7a0ebd6ce21e
Sep-05 10:39:20.455 [main] DEBUG nextflow.Session - Run name: marvelous_mirzakhani
Sep-05 10:39:20.456 [main] DEBUG nextflow.Session - Executor pool size: 16
Sep-05 10:39:20.755 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.04.0 build 5552
  Created: 02-05-2021 16:22 UTC (19:22 IDT)
  System: Mac OS X 10.16
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.9.1+1-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 35222@labs-MacBook-Pro.local [127.0.0.1]
  CPUs: 16 - Mem: 32 GB (848.6 MB) - Swap: 1 GB (969.5 MB)
Sep-05 10:39:20.766 [main] DEBUG nextflow.Session - Work-dir: /Users/boris/temp/nextflowtraining/work [Mac OS X]
Sep-05 10:39:20.766 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /Users/boris/temp/nextflowtraining/bin
Sep-05 10:39:20.777 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Sep-05 10:39:20.786 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Sep-05 10:39:20.882 [main] DEBUG nextflow.Session - Session start invoked
Sep-05 10:39:20.981 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Sep-05 10:39:21.103 [main] DEBUG nextflow.script.BaseScript - No entry workflow defined
Sep-05 10:39:21.104 [main] DEBUG nextflow.extension.CH - Bridging dataflow queue=DataflowQueue(queue=[])
Sep-05 10:39:21.105 [main] DEBUG nextflow.Session - Ignite dataflow network (1)
Sep-05 10:39:21.110 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Sep-05 10:39:21.110 [main] DEBUG nextflow.Session - Session await
Sep-05 10:39:21.110 [main] DEBUG nextflow.Session - Session await > all process finished
Sep-05 10:39:21.110 [main] DEBUG nextflow.Session - Session await > all barriers passed
Sep-05 10:39:21.111 [ForkJoinPool.commonPool-worker-19] DEBUG nextflow.datasource.SraExplorer - SRA search url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&usehistory=y&retmode=json&api_key=XXXXXXX&term=SRP043510
Sep-05 10:39:22.278 [ForkJoinPool.commonPool-worker-19] DEBUG nextflow.datasource.SraExplorer - SRA data request url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=sra&retmode=json&query_key=1&WebEnv=MCID_6134742a22c50449462dbca7&retstart=0&retmax=1000&api_key=XXXXXXX
Sep-05 10:39:22.939 [ForkJoinPool.commonPool-worker-19] DEBUG nextflow.datasource.SraExplorer - SRA fetch ftp fastq url=https://www.ebi.ac.uk/ena/data/warehouse/filereport?result=read_run&fields=fastq_ftp&accession=SRR1448794
Sep-05 10:39:24.775 [ForkJoinPool.commonPool-worker-19] ERROR nextflow.Channel - Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport
java.io.IOException: Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.configuredInputStream(ResourceGroovyMethods.java:2222)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.newReader(ResourceGroovyMethods.java:2308)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:640)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:603)
	at org.codehaus.groovy.runtime.dgm$1041.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.doMethodInvoke(GeneratedMetaMethod.java:83)
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at nextflow.datasource.SraExplorer.readRunUrl(SraExplorer.groovy:260)
	at nextflow.datasource.SraExplorer.readRunFastqs(SraExplorer.groovy:248)
	at nextflow.datasource.SraExplorer.getFastqUrl(SraExplorer.groovy:273)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.parseDataResponse(SraExplorer.groovy:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.query1(SraExplorer.groovy:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.query0(SraExplorer.groovy:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.datasource.SraExplorer.apply(SraExplorer.groovy:103)
	at nextflow.Channel$_fetchSraFiles0_closure16.doCall(Channel.groovy:608)
	at nextflow.Channel$_fetchSraFiles0_closure16.call(Channel.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Sep-05 10:39:24.783 [ForkJoinPool.commonPool-worker-19] DEBUG nextflow.Session - Session aborted -- Cause: Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport
Sep-05 10:39:24.799 [ForkJoinPool.commonPool-worker-19] DEBUG nextflow.Session - The following nodes are still active:
  [operator] view

Sep-05 10:39:24.811 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Sep-05 10:39:24.945 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Sep-05 10:39:24.961 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

Note, that some of the URLs in the log file are accessible. For example https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=sra&retmode=json&query_key=1&WebEnv=MCID_6134742a22c50449462dbca7&retstart=0&retmax=1000&api_key=XXXXX

### Environment 

* Nextflow version: 21.04.0

* Java version: openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)

* Operating system: macOS
* Bash version: (not bash) `zsh 5.8 (x86_64-apple-darwin20.0)`

### Additional context

I run this command directly in the terminal (not a container) and I tested it using three different network connections to rule out a possibility of an external firewall

**Comment by abhi18av** [comment]
Hello @mybiotics ,

Thanks for letting us know about this, however it is a known issue that the ENA api recently changed its URL, see https://github.com/nextflow-io/nextflow/pull/2239

This issue is addressed when using the latest `21.08-edge` release, it'll become a part of the next stable release (`21.10`).\

Please install the edge release to make use of this fix.
