### ISSUE TITLE
`params` not accessible from `executor` section in `nextflow.config`

### ISSUE THREAD

**Issue by vinjana** [nextflow-io/nextflow#2365]
## Bug report 

The following throws a NullPointerException in the logs. Instead of the changed job-name a default name is used.

```groovy
params {
    runName = "da run"
}
executor {
  jobName = { "$params.runName - $task.name - $task.hash" }
}
```

This is a bug, because the NullPointerExceptions are raised after previous jobs were submitted (also with errors) and long after any logging of `params` values from the `main.nf` happened. It is therefore certain that in principle the `params` should be available at this time point of the workflow's execution. Furthermore, the `params` variable **is** accessible (not null) at other places in the config. E.g. the following works:

```groovy
params {
    accountingName = "myAccount"
}
profiles {
  lsf {
     clusterOptions = "-P '${params.accountingName}'"
  }
}
```

### Expected behavior and actual behavior

`params` should be useable in the `executor` section (and in all other sections) of the config.

### Steps to reproduce the problem

Put the following into you config:

```groovy
executor {
  jobName = { "$params.runName - $task.name - $task.hash" }
}
```

### Program output 

```
Okt.-05 12:38:15.844 [Task submitter] DEBUG n.executor.AbstractGridExecutor - Unable to resolve job custom name
java.lang.NullPointerException: Cannot get property 'runName' on null object
        at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:194)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
        at _nf_config_f50e3033$_run_closure4$_closure18.doCall(_nf_config_f50e3033:113)
        at _nf_config_f50e3033$_run_closure4$_closure18.doCall(_nf_config_f50e3033)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.executor.AbstractGridExecutor.resolveCustomJobName(AbstractGridExecutor.groovy:175)
        at nextflow.executor.AbstractGridExecutor.getJobNameFor(AbstractGridExecutor.groovy:142)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at nextflow.executor.LsfExecutor.getDirectives(LsfExecutor.groovy:105)
        at nextflow.executor.AbstractGridExecutor.getDirectives(AbstractGridExecutor.groovy:122)
        at nextflow.executor.AbstractGridExecutor.getHeaders(AbstractGridExecutor.groovy:94)
        at nextflow.executor.AbstractGridExecutor.createBashWrapperBuilder(AbstractGridExecutor.groovy:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.executor.GridTaskHandler.submit(GridTaskHandler.groovy:120)
        at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:560)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1259)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1039)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1133)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

### Environment 

* Nextflow version:  21.04.0
* Java version: openjdk version "10.0.2" 2018-07-17, OpenJDK Runtime Environment Zulu10.3+5 (build 10.0.2+13), OpenJDK 64-Bit Server VM Zulu10.3+5 (build 10.0.2+13, mixed mode)
* Operating system: Linux
* Bash version: GNU bash, Version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

None.

**Comment by dixonmd** [comment]
Is there any solution for this?

**Comment by dixonmd** [comment]
Is there a solution for this issue? It's not reflecting in the PBS job name when we use $params.<variable> in the executor.jobName.

**Comment by dixonmd** [comment]
Is there a solution for this issue? It's not reflecting in the PBS job name when we use $params.\<variable\> in the executor.jobName.
