### ISSUE TITLE
AWS Issue with Nextflow 

### ISSUE THREAD

**Issue by rakeshponnala** [nextflow-io/nextflow#2398]
Hello, 
I am trying to use nextflow and run nfcore . But the issue I seem to have is configuration challenges with AWS. Below is the error message, any suggestions ?

Oct-19 10:01:17.812 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: 1.0.5
Oct-19 10:01:18.040 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-amazon@1.0.5' resolved
Oct-19 10:01:18.041 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@1.0.5'
Oct-19 10:01:18.114 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@1.0.5
Oct-19 10:01:18.130 [main] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
Oct-19 10:01:18.130 [main] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://ngi-igenomes/igenomes/Canis_familiaris/Ensembl/CanFam3.1/Sequence/WholeGenomeFasta/genome.fa
Oct-19 10:01:18.147 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Oct-19 10:01:18.155 [main] DEBUG nextflow.Global - Using AWS credential defined in `default` section in file: /sc/kzd/home/ponnar02/.aws/credentials
Oct-19 10:01:18.157 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=nolvM8.., region=us-east-1, access_key=AKIAI4..}
Oct-19 10:01:21.210 [main] DEBUG nextflow.Session - Session aborted -- Cause: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: EWEZYAXV6B8QXWPB; S3 Extended Request ID: 5ZEnQ2pMVcuHNGcZ0qdEQKoiMYCFzp0aesLte48p0rPYKgQwtXF7R93cOe2CAwXy8LKZw5rTsuI=)
Oct-19 10:01:21.227 [main] ERROR nextflow.cli.Launcher - @unknown
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: EWEZYAXV6B8QXWPB; S3 Extended Request ID: 5ZEnQ2pMVcuHNGcZ0qdEQKoiMYCFzp0aesLte48p0rPYKgQwtXF7R93cOe2CAwXy8LKZw5rTsuI=)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4854)
    at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:880)
    at com.upplication.s3fs.AmazonS3Client.listObjects(AmazonS3Client.java:105)
    at com.upplication.s3fs.util.S3ObjectSummaryLookup.lookup(S3ObjectSummaryLookup.java:113)
    at com.upplication.s3fs.S3FileSystemProvider.getAccessControl(S3FileSystemProvider.java:921)
    at com.upplication.s3fs.S3FileSystemProvider.checkAccess(S3FileSystemProvider.java:607)
    at java.nio.file.Files.exists(Files.java:2385)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:94)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
    at nextflow.extension.FilesEx.exists(FilesEx.groovy:454)
    at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:986)
    at nextflow.file.FileHelper$checkIfExists$2.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
    at nextflow.Nextflow.file(Nextflow.groovy:159)
    at nextflow.Nextflow$file.callStatic(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
    at Script_4145bff8.runScript(Script_4145bff8:104)
    at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:164)
    at nextflow.script.BaseScript.run(BaseScript.groovy:200)
    at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
    at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
    at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
    at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
    at nextflow.cli.Launcher.run(Launcher.groovy:475)
    at nextflow.cli.Launcher.main(Launcher.groovy:657)

**Comment by abhi18av** [comment]
Hi @rakeshponnala , the reason is because to debug effectively something we need the context, which is presented when you click on `New Issue`.

In anycase, this is more related to AWS configuration or pipeline data availability - I noticed you created another issue here https://github.com/nf-core/smrnaseq/issues/116 and the nf-core folks have started responding there to debug the issue.
