### ISSUE TITLE
Include statement is not allowed within a workflow definition

### ISSUE THREAD

**Issue by Orybies** [nextflow-io/nextflow#2587]
### Expected behavior and actual behavior

I am seeing 'Include statement is not allowed within a workflow definition' when running a VSN-pipeline workflow.

### Steps to reproduce the problem
pbmc_1k_v3_filtered_feature_bc_matrix files as input for a config file

nextflow config vib-singlecell-nf/vsn-pipelines \
    -profile tenx,singularity,single_sample > single_sample.config

nextflow -C single_sample.config \
    run vib-singlecell-nf/vsn-pipelines \
        -entry single_sample

### Program output 

Jan-24 13:34:01.812 [main] DEBUG nextflow.cli.Launcher - $> nextflow -C single_sample.config run vib-singlecell-nf/vsn-pipelines -entry single_sample
Jan-24 13:34:01.851 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.10.6
Jan-24 13:34:02.725 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/u0135347/.nextflow/assets/vib-singlecell-nf/vsn-pipelines/.git/config; branch: master; remote: origin; url: https://github.com/vib-singlecell-nf/vsn-pipelines.git
Jan-24 13:34:02.735 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/u0135347/.nextflow/assets/vib-singlecell-nf/vsn-pipelines/.git/config; branch: master; remote: origin; url: https://github.com/vib-singlecell-nf/vsn-pipelines.git
Jan-24 13:34:02.877 [main] INFO  nextflow.cli.CmdRun - Launching `vib-singlecell-nf/vsn-pipelines` [gloomy_wozniak] - revision: 96cff8e597 [master]
Jan-24 13:34:03.338 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/c/Users/u0135347/Documents/VSN-pipeline/single_sample_test/single_sample.config
Jan-24 13:34:03.343 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jan-24 13:34:03.547 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/u0135347/.nextflow/plugins
Jan-24 13:34:03.549 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jan-24 13:34:03.559 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jan-24 13:34:03.560 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jan-24 13:34:03.564 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jan-24 13:34:03.571 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jan-24 13:34:03.617 [main] DEBUG nextflow.Session - Session uuid: 64e2bc83-e445-44ca-921e-e62fd9fb5681
Jan-24 13:34:03.617 [main] DEBUG nextflow.Session - Run name: gloomy_wozniak
Jan-24 13:34:03.617 [main] DEBUG nextflow.Session - Executor pool size: 16
Jan-24 13:34:03.639 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.10.6 build 5660
  Created: 21-12-2021 16:55 UTC (17:55 CEST)
  System: Linux 4.4.0-19041-Microsoft
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 11.0.13+8-Ubuntu-0ubuntu1.20.04
  Encoding: UTF-8 (UTF-8)
  Process: 3362@GBW-L-W3541 [127.0.1.1]
  CPUs: 16 - Mem: 31.7 GB (20.9 GB) - Swap: 58.9 GB (58.9 GB)
Jan-24 13:34:03.665 [main] DEBUG nextflow.Session - Work-dir: /mnt/c/Users/u0135347/Documents/VSN-pipeline/single_sample_test/work [wslfs]
Jan-24 13:34:03.665 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/u0135347/.nextflow/assets/vib-singlecell-nf/vsn-pipelines/bin
Jan-24 13:34:03.672 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jan-24 13:34:03.680 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jan-24 13:34:03.736 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Jan-24 13:34:03.836 [main] DEBUG nextflow.Session - Session start invoked
Jan-24 13:34:03.839 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /mnt/c/Users/u0135347/Documents/VSN-pipeline/single_sample_test/out/nextflow_reports/execution_trace.txt
Jan-24 13:34:04.747 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jan-24 13:34:05.728 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Jan-24 13:34:07.353 [main] DEBUG nextflow.Session - Session aborted -- Cause: Include statement is not allowed within a workflow definition
Jan-24 13:34:07.366 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] view

Jan-24 13:34:07.374 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.IllegalStateException: Include statement is not allowed within a workflow definition
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at nextflow.script.BaseScript.include(BaseScript.groovy:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)
	at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:424)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at Script_2068717d$_runScript_closure7$_closure53.doCall(Script_2068717d:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:191)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

### Environment 

* Nextflow version: 21.10.6
* Java version: openjdk version "11.0.13" 
* Operating system: Ubuntu
* Bash version: GNU bash, version 5.0.17

### Additional context

When using older versions of nextflow ( < 21.10.3) error: nextflow missing process or function with name 'include'

**Comment by pditommaso** [comment]
This is expected https://github.com/nextflow-io/nextflow/issues/2162
