### ISSUE TITLE
Improve error message of non-sensical include

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#2612]
Suppose I have in `lib/Foo.groovy`:

```groovy
class Foo {
	String id
}
```

And in `main.nf`:

```nextflow
nextflow.enable.dsl=2

// bug
include { Foo } from "./lib/Foo.groovy"

process foo {
    input:
        val value

    output:
        path '*.txt'

    script:
        """
        touch ${value.id}.txt
        """
}

workflow {
    foo(Channel.from(new Foo(id: "hello_world")))
}
```

I get the follow error from `nextflow run .`:

```console
N E X T F L O W  ~  version 21.10.6
Launching `./main.nf` [special_liskov] - revision: 012584be92
Cannot cast object 'org.codehaus.groovy.runtime.InvokerHelper$1@1cbb3d3b' with class 'org.codehaus.groovy.runtime.InvokerHelper$1' to class 'nextflow.script.BaseScript'

 -- Check script 'main.nf' at line: 4 or see '.nextflow.log' file for more details
```

The full `.nextflow.log` is below:

<details>

<summary>`.nextflow.log`</summary>

```console
...
Feb-01 16:08:36.129 [main] DEBUG nextflow.Session - Work-dir: /private/tmp/issues/work [Mac OS X]
Feb-01 16:08:36.129 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /private/tmp/issues/bin
Feb-01 16:08:36.137 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Feb-01 16:08:36.148 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Feb-01 16:08:36.195 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Feb-01 16:08:36.318 [main] DEBUG nextflow.Session - Session start invoked
Feb-01 16:08:36.332 [main] DEBUG nextflow.Session - Using default localLib path: /private/tmp/issues/lib
Feb-01 16:08:36.337 [main] DEBUG nextflow.Session - Adding to the classpath library: /private/tmp/issues/lib
Feb-01 16:08:37.058 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Feb-01 16:08:37.096 [main] DEBUG nextflow.Session - Session aborted -- Cause: Cannot cast object 'org.codehaus.groovy.runtime.InvokerHelper$1@1cbb3d3b' with class 'org.codehaus.groovy.runtime.InvokerHelper$1' to class 'nextflow.script.BaseScript'
Feb-01 16:08:37.125 [main] ERROR nextflow.cli.Launcher - @unknown
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.codehaus.groovy.runtime.InvokerHelper$1@1cbb3d3b' with class 'org.codehaus.groovy.runtime.InvokerHelper$1' to class 'nextflow.script.BaseScript'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:408)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:243)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:615)
	at nextflow.script.ScriptParser.parse(ScriptParser.groovy:172)
	at nextflow.script.ScriptParser.parse(ScriptParser.groovy:191)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:206)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:201)
	at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:142)
	at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
	at nextflow.script.IncludeDef$__clinit__closure1.doCall(IncludeDef.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
	at nextflow.script.IncludeDef.load0(IncludeDef.groovy:114)
	at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_f16daf5a.runScript(Script_f16daf5a:4)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

</details>

Rather than the exception message, I'd like a more user friendly message on the console (in the log is fine), saying something like "could not compile the included script: /path/to/script".  Presumably, a try/catch could be wrapped around the code that is trying to compile the included NF script to provide a better message with the path to the script.

**Comment by pditommaso** [comment]
I see your point, worth mentioning that the inclusion of a foreign class is not expected to work as you are trying to do 

> // bug
include { Foo } from "./lib/Foo.groovy"

**Comment by nh13** [comment]
Agreed, just put `Foo.groovy` into `./lib` and it will be available to use.  Perhaps that's something worth mentioning in the docs and/or the error message?  May already be there.

**Comment by jorgeaguileraseqera** [comment]
The problem is the parser is expecting a script, not a class, so we can catch and improve the error message as you suggested

As a side note, this is an interesting use case as it "opens" the doors for a more complex/funny kind of script. For example

`lib/Foo.groovy`

```
class MyScript {
    String id    
}

def fooMethod(){
   new MyScript(id:'hello_world')
}
```

`main.nf`

```
nextflow.enable.dsl=2  
include { fooMethod } from "lib/Foo.groovy" 
process foo {
    input:
        val value

    output:
        path '*.txt'

    script:
        "echo 'hello'"
}
workflow {
    foo(Channel.from(fooMethod()))
}
```

**Comment by nh13** [comment]
I’ll say this was not a contrived example, but something I helped a new user debug. So docs on how custom groovy methods and classes are imported could be made more explicit, in addition to the error message. I.e. you do not need an “import” statement at the top of your Nextflow script.

**Comment by pditommaso** [comment]
Ok, solved

**Comment by nh13** [comment]
Thank you!
