### ISSUE TITLE
Exception in thread "AnsiLogObserver" java.lang.NullPointerException

### ISSUE THREAD

**Issue by shizhaojingszj** [nextflow-io/nextflow#2657]
## Bug report 

N E X T F L O W  ~  version 21.05.0-edge
Launching `../workflows/inference_pipeline2-fast.nf` [nice_mandelbrot] - revision: 042083fc81
scriptDir=...
Exception in thread "AnsiLogObserver" java.lang.NullPointerException
[80/f984at org.codehaus.groovy.runtime.StringGroovyMethods.count(StringGroovyMethods.java:367)
[18/8f32at nextflow.trace.AnsiLogObserver.renderMessages(AnsiLogObserver.groovy:189)
[ac/990bat nextflow.trace.AnsiLogObserver.renderMessages(AnsiLogObserver.groovy)
[cc/6620at nextflow.trace.AnsiLogObserver.renderProgress(AnsiLogObserver.groovy:282)
[82/53b5at nextflow.trace.AnsiLogObserver.render0(AnsiLogObserver.groovy:169)
[-      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[-      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[-      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
config.1at java.base/java.lang.reflect.Method.invoke(Method.java:566)
java.utiat org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
null    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
output_dat groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
output_dat groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
output_dat groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
output_dat groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
output_dat groovy.lang.Closure.call(Closure.java:412)20.json
output_dat groovy.lang.Closure.call(Closure.java:406)20.json
output_dat groovy.lang.Closure.run(Closure.java:493)420.json
WARN: Acat java.base/java.lang.Thread.run(Thread.java:829)

### Expected behavior and actual behavior

No such message.

### Steps to reproduce the problem

sorry, I cannot reproduce it in simple nf files.

### Program output 

no error message in log file

### Environment 

* Nextflow version: [?] 
* Java version: [?]
      openjdk version "11.0.14" 2022-01-18 LTS
      OpenJDK Runtime Environment Corretto-11.0.14.9.1 (build 11.0.14+9-LTS)
      OpenJDK 64-Bit Server VM Corretto-11.0.14.9.1 (build 11.0.14+9-LTS, mixed mode)
* Operating system: [macOS, Linux, etc]
      Ubuntu 16.04
* Bash version: (use the command `$SHELL --version`)
      zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by shizhaojingszj** [comment]
maybe duplicate to #2283

**Comment by shizhaojingszj** [comment]
already fixed in 22.01.0-edge.5656 ??? Good job, people.
