### ISSUE TITLE
Implement client side retries for Azure Batch APIs

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#2688]
## Bug report 

The bug report is focused on the frequent `409` -> `TooManyRequests` issue on Azure Batch.

```
Caused by:
  Status code 429, {
  "odata.metadata":"https://NF_BATCH_ACCOUNT.westeurope.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element","code":"TooManyRequests","message":{
    "lang":"en-US","value":"Request failed as server encountered too many requests. Please try again.\nRequestId:65799462-61c4-4c88-b663-804874db162e\nTime:2022-03-01T09:49:43.0256859Z"
  }
}

```

### Expected behavior and actual behavior

The expected behavior is that a substantially large pipeline (for example `nf-core/rnaseq` ) could be run with `test/test_full` profile.

The current behavior is that after a partial completion ( ~60 %) the pipeline fails abruptly with the aforementioned 

### Steps to reproduce the problem

I ran the pipeline through Tower by using the following steps 

1. Create a compute-env for Azure with default settings (Tower Forge)
2. Launch the `nf-core/rnaseq` pipeline on this compute-env 
3. The pipeline launches correctly on the resources

Eventually, it errors out and it seems abrupt since the same pipeline cannot be resumed.

**NOTE:** This problem wasn't observed with the `nextflow-io/rnaseq-nf` pipeline and is only observable on larger pipelines.

### Program output 

[nf-3sNohAkqRpOkUM.log](https://github.com/nextflow-io/nextflow/files/8162586/nf-3sNohAkqRpOkUM.log)

### Environment 

* Nextflow version: [22.01.0-edge and 22.02.0-edge] 

### Additional context

Upon further investigation, I found that this is a known [throttling error (see docs)](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshooting-throttling-errors) and on the [advice for retries (see docs)](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#general-rest-and-retry-guidelines) it is recommended that a client side resiliency framework should be used to overcome these issues - the docs used the Polly dotNET library example.

Possible resiliency frameworks in Java which could be evaluated 
- https://failsafe.dev/ 
- https://resilience4j.readme.io/

**Comment by abhi18av** [comment]
Ah, it seems that `failsafe` has already made it to the codebase as of January :) 

https://github.com/nextflow-io/nextflow/search?q=failsafe

**Comment by pditommaso** [comment]
Including the full error stack trace 

```

Caused by:
  Status code 429, {
  "odata.metadata":"https://AZURE_BATCH.westeurope.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element","code":"TooManyRequests","message":{
    "lang":"en-US","value":"Request failed as server encountered too many requests. Please try again.\nRequestId:e3792009-07e2-4545-bea1-b1df9f116af8\nTime:2022-03-01T11:37:02.8079717Z"
  }
}

com.microsoft.azure.batch.protocol.models.BatchErrorException: Status code 429, {
  "odata.metadata":"https://AZURE_BATCH.westeurope.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element","code":"TooManyRequests","message":{
    "lang":"en-US","value":"Request failed as server encountered too many requests. Please try again.\nRequestId:e3792009-07e2-4545-bea1-b1df9f116af8\nTime:2022-03-01T11:37:02.8079717Z"
  }
}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.rest.ServiceResponseBuilder.buildWithHeaders(ServiceResponseBuilder.java:151)
	at com.microsoft.azure.AzureResponseBuilder.buildWithHeaders(AzureResponseBuilder.java:82)
	at com.microsoft.azure.batch.protocol.implementation.JobsImpl.addDelegate(JobsImpl.java:2219)
	at com.microsoft.azure.batch.protocol.implementation.JobsImpl.access$800(JobsImpl.java:89)
	at com.microsoft.azure.batch.protocol.implementation.JobsImpl$44.call(JobsImpl.java:2206)
	at com.microsoft.azure.batch.protocol.implementation.JobsImpl$44.call(JobsImpl.java:2202)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.batch.protocol.implementation.JobsImpl.add(JobsImpl.java:2124)
	at com.microsoft.azure.batch.JobOperations.createJob(JobOperations.java:323)
	at com.microsoft.azure.batch.JobOperations.createJob(JobOperations.java:296)
	at com.microsoft.azure.batch.JobOperations.createJob(JobOperations.java:279)
	at nextflow.cloud.azure.batch.AzBatchService.getOrCreateJob(AzBatchService.groovy:301)
	at nextflow.cloud.azure.batch.AzBatchService.submitTask(AzBatchService.groovy:266)
	at nextflow.cloud.azure.batch.AzBatchTaskHandler.submit(AzBatchTaskHandler.groovy:93)
	at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
	at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:562)
	at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by pditommaso** [comment]
A retry policy has been added 991c6175

**Comment by abhi18av** [comment]
Thanks for the update Paolo - will test this one out today 👍
