### ISSUE TITLE
Resuming workflow fails before caching all jobs

### ISSUE THREAD

**Issue by juliofdiaz** [nextflow-io/nextflow#2707]
I am running nextflow with about 55,000 files being processed. When I try to resume nextflow after a fail, nextflow errors out before caching all the completed jobs.  This behaviour is not consistent, sometimes I try resuming it for multiple times and it may fully resume on a random try. The error I get is:

```
Workflow execution completed unsuccessfully 
java.lang.reflect.InvocationTargetException
```
[nextflow.log.gz](https://github.com/nextflow-io/nextflow/files/8213240/nextflow.log.gz)

I am attaching the nextflow.

**Comment by pditommaso** [comment]
The log reports the use of 1000 threads, which is abnormal and I think it can be related to the problem reported. Are you setting the thread number using the option `nxf.pool.maxThreads` ?

**Comment by antunderwood** [comment]
We currently have `-Dnxf.pool.maxThreads=2000`

**Comment by antunderwood** [comment]
I tried adding `-Dnxf.pool.type=sync` as per https://github.com/nextflow-io/nextflow/issues/1871
and values between `-Dnxf.pool.maxThreads=200` and `-Dnxf.pool.maxThreads=10000` but all resulted in `java.lang.reflect.InvocationTargetException`

**Comment by pditommaso** [comment]
Can you update to the latest stable (21.10.6) and try using default settings?

**Comment by antunderwood** [comment]
We tried this but the resume where we specified a specific version (`-resume dreamy_feynman`) did not resume but re-submitted all jobs.
Is this because the NF version is new??

**Comment by pditommaso** [comment]
Not sure this is still a problem, however looking better the error stack trace it says 

```
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.math.BigDecimal#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class [C]
	[class java.lang.String]
	at groovy.lang.MetaClassImpl.doChooseMostSpecificParams(MetaClassImpl.java:3385)
	at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:3361)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3351)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3295)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1824)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1615)
	at groovy.lang.DelegatingMetaClass.invokeConstructor(DelegatingMetaClass.java:133)
	at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at Script_0c0c85f8.find_total_number_of_bases(Script_0c0c85f8:9)
```

It looks like there's a `null` in some math in the custom routine  `find_total_number_of_bases`
