### ISSUE TITLE
Unable to resume cache when running on AWS Batch when there are spaces in file names

### ISSUE THREAD

**Issue by kathleencheung** [nextflow-io/nextflow#2734]
When running jobs on AWS Batch via Nextflow tower and there are spaces in the file names, the workflow finds the files and runs successfully. However, when I try to resume the workflow, it is unable to resume and starts the workflow from beginning. Checking the log files reveals an illegal character error: 

```
Mar-17 08:59:16.521 [Actor Thread 6] WARN  nextflow.processor.TaskProcessor - [FG_GATK_BAM:PROCESS_BAM:PROCESS_MARKDUPS_ONLY:BWA_MEM_PAIRED (test_sample-1_1)] Unable to resume cached task -- See log file for details
com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Illegal character in path at index 54: s3:///kc1-test-output/testing_filename_spaces/SRR6798772 toy10k 1.fastq.gz
Serialization trace:
target (nextflow.processor.TaskPath)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:143)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:21)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.Kryo$readClassAndObject$16.call(Unknown Source)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:182)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy)
	at nextflow.util.KryoHelper$deserialize$4.call(Unknown Source)
	at nextflow.processor.TaskContext.deserialize(TaskContext.groovy:190)
	at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:163)
	at nextflow.CacheDB$getTaskEntry.call(Unknown Source)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:869)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:758)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:592)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:59)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 54: s3:///kc1-test-output/testing_filename_spaces/SRR6798772 toy10k 1.fastq.gz
	at java.base/java.net.URI.create(URI.java:883)
	at nextflow.util.PathSerializer.read(SerializationHelper.groovy:284)
	at nextflow.util.PathSerializer.read(SerializationHelper.groovy)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
	... 30 common frames omitted
```
Ideally, there wouldn't be any spaces in the file names, however we receive files from external sources with spaces in and do not want to rename them. Additionally, this issue doesn't occur on our local servers where spaces do not pose an issue when resuming. Is there a way to escape spaces so that Nextflow both recognises the files when running the first time AND when resuming a run on AWS Batch?

**Comment by colindaven** [comment]
I would rename all spaces with "_" and also sanitize special characters. Believe me, this will save you a world of pain in bioinformatics and Linux as a whole, where spaces are very uncommon. I would also teach your file contributors to use "_".

**Comment by pditommaso** [comment]
I could agree but we cannot enforce on doing that 😅. 

In general, nextflow is able to handle blanks in paths, however, it's also true that tricky errors may arise like the one above. In this specific case, I believe this is happening because the file path is captured in the task execution context and the deserialization fails later on when resuming the pipeline execution. 

If a replicable test case can be provided, that would help to troubleshoot the problem.

**Comment by pditommaso** [comment]
Ideally, S3 paths should be serialised as plain strings. It should be investigated why this happen 

https://github.com/nextflow-io/nextflow/blob/40d56735243c7fd10ba066ee52dd056b10fa8c61/modules/nextflow/src/main/groovy/nextflow/util/SerializationHelper.groovy#L263-L287
