### ISSUE TITLE
`java.lang.NullPointerException` with Azure Batch on the command-line (works on Tower)

### ISSUE THREAD

**Issue by rpetit3** [nextflow-io/nextflow#2803]
## Bug report 

I am able to launch jobs on Tower using my Azure credentials. But when I use those same credentials locally, I get `java.lang.NullPointerException`. I've tried multiple versions of Nextflow and OpenJDK. I've also tried different Azure pools, including the one Tower created. Finally, I've tried multiple pipelines.

### Expected behavior and actual behavior

Nextflow should behave the same on the command-line as it does on Tower

### Steps to reproduce the problem

My config
```
profiles {
  azure {
    azure {
      batch {
        location = "westus"
        accountName = "NAME"
        accountKey = "KEY"
      }
      storage {
        accountName = "NAME"
        accountKey = "KEY"
      }
    }

    process {
      executor = 'azurebatch'
      queue = "tower-pool-2Nn6h1Nr..."
    }
  }
}
```

Tests
```
nextflow run nf-core/rnaseq -profile test,azure -c azure.config -w az://wphltower-container/work --outdir az://wphltower-container/testrnaseq

nextflow run bactopia/bactopia -profile test,docker,azure -c azure.config -w az://wphltower-container/work --outdir az://wphltower-container/testbactopia
```

### Program output 

From `nf-core/rnaseq`
```
Apr-15 19:02:27.194 [Actor Thread 93] DEBUG nextflow.sort.BigSort - Sort completed -- entries: 1; slices: 1; internal sort time: 0.001 s; external sort time: 0.035 s; total time: 0.036 s
Apr-15 19:02:27.237 [Actor Thread 13] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=2; maxSize=2; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Apr-15 19:02:27.260 [Actor Thread 93] DEBUG nextflow.file.FileCollector - Saved collect-files list to: /tmp/1658c18f305a958b2ab6e82c03cd8b44.collect-file
Apr-15 19:02:27.288 [Actor Thread 93] DEBUG nextflow.file.FileCollector - Deleting file collector temp dir: /tmp/nxf-16749848156946193771
Apr-15 19:02:27.390 [FileTransfer-1] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://github.com/nf-core/test-datasets/raw/rnaseq/reference/salmon.tar.gz at az://wphltower-container/work/stage/ee/d5efabdfe069130879a74cf8176219/salmon.tar.gz
Apr-15 19:02:27.539 [FileTransfer-2] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://github.com/nf-core/test-datasets/raw/rnaseq/reference/star.tar.gz at az://wphltower-container/work/stage/5b/641338deaea2ba4c0c73c4deee60a5/star.tar.gz
Apr-15 19:02:27.630 [FileTransfer-2] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/samplesheet/v3.4/samplesheet_test.csv at az://wphltower-container/work/stage/0d/890f118dda012d5b6158f573ea8b0e/samplesheet_test.csv
Apr-15 19:02:27.677 [Actor Thread 20] DEBUG nextflow.util.CacheHelper - Hash asset file sha-256: /home/azureuser/.nextflow/assets/nf-core/rnaseq/bin/check_samplesheet.py
Apr-15 19:02:27.700 [FileTransfer-1] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://github.com/nf-core/test-datasets/raw/rnaseq/reference/genes.gtf.gz at az://wphltower-container/work/stage/e8/3b6c537d01766a83abb4ecbd3f795a/genes.gtf.gz
Apr-15 19:02:27.728 [Task submitter] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Submitting task NFCORE_RNASEQ:RNASEQ:PREPARE_GENOME:UNTAR_STAR_INDEX (star.tar.gz) - work-dir=az://wphltower-container/work/7e/aa4af2fe9485fd6564694f21d7617a
Apr-15 19:02:27.889 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Executor options=endpoint=null; account-name=temptestbatch; account-key=f1g83...
Apr-15 19:02:27.935 [FileTransfer-2] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://github.com/nf-core/test-datasets/raw/rnaseq/reference/gfp.fa.gz at az://wphltower-container/work/stage/b2/288f8a49a485badd81ce65a93a1327/gfp.fa.gz
Apr-15 19:02:28.734 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Checking VM pool id=test4; size=AzVmType(name:Standard_D4s_v3, maxDataDiskCount:8, memory:16 GB, numberOfCores:4, osDiskSize:1023 GB, resourceDiskSize:32 GB)
Apr-15 19:02:29.041 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_RNASEQ:RNASEQ:PREPARE_GENOME:UNTAR_STAR_INDEX (star.tar.gz)'

Caused by:
  java.lang.NullPointerException

java.lang.NullPointerException: null
        at nextflow.cloud.azure.batch.AzBatchService.runTask(AzBatchService.groovy:347)
        at nextflow.cloud.azure.batch.AzBatchService.submitTask(AzBatchService.groovy:273)
        at nextflow.cloud.azure.batch.AzBatchTaskHandler.submit(AzBatchTaskHandler.groovy:93)
        at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:562)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

From `bactopia` 
```
Apr-15 12:58:13.248 [Actor Thread 6] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=4; maxSize=4; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Apr-15 12:58:13.784 [FileTransfer-3] DEBUG nextflow.file.FilePorter - Local cache found for foreign file /home/rpetit3/miniconda3/envs/bactopia-dev-2.0.3/share/bactopia-2.0.x/data/EMPTY_EXTRA at az://wphltower-container/stage/fc/71cd130694f1f841416e5ea899b26a/EMPTY_EXTRA
Apr-15 12:58:13.826 [FileTransfer-1] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://github.com/bactopia/bactopia-tests/raw/main/data/species/portiera/illumina/SRR2838702_R1.fastq.gz at az://wphltower-container/stage/db/136a5fd1c3bdf1b3bae499b7084070/SRR2838702_R1.fastq.gz
Apr-15 12:58:14.125 [FileTransfer-2] DEBUG nextflow.file.FilePorter - Local cache found for foreign file https://github.com/bactopia/bactopia-tests/raw/main/data/species/portiera/illumina/SRR2838702_R2.fastq.gz at az://wphltower-container/stage/d6/fac2b716afaf5fc3e9596f876a6559/SRR2838702_R2.fastq.gz
Apr-15 12:58:14.744 [Task submitter] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Submitting task BACTOPIA:GATHER_SAMPLES (SRR2838702) - work-dir=az://wphltower-container/c3/3b41dfbea8d734398987275611f7c9
Apr-15 12:58:15.004 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Executor options=endpoint=null; account-name=temptestbatch; account-key=f1g83...
Apr-15 12:58:16.008 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Checking VM pool id=tower-pool-2Nn6h1Nr7OCZQE4lI6Gu1G; size=AzVmType(name:Standard_D4s_v3, maxDataDiskCount:8, memory:16 GB, numberOfCores:4, osDiskSize:1023 GB, resourceDiskSize:32 GB)
Apr-15 12:58:16.616 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'BACTOPIA:GATHER_SAMPLES (SRR2838702)'

Caused by:
  java.lang.NullPointerException

java.lang.NullPointerException: null
        at nextflow.cloud.azure.batch.AzBatchService.runTask(AzBatchService.groovy:347)
        at nextflow.cloud.azure.batch.AzBatchService.submitTask(AzBatchService.groovy:273)
        at nextflow.cloud.azure.batch.AzBatchTaskHandler.submit(AzBatchTaskHandler.groovy:93)
        at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:562)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

The files get staged properly in my Azure Storage Container

### Environment 

* Nextflow version: `21.10.6` and `22.03.1-edge build 5695`
* Java version: Tried the following
```
Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.14.1+1-LTS
Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.14.1+1-b2043.25
Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.13+7-b1751.21
Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src
Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.1-internal+0-adhoc..src
```
* Operating system: Linux (Debian), 3 different systems on different networks
* Bash version: `GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)`

### Additional context

Please let me know if other info is needed.

**Comment by abhi18av** [comment]
@rpetit3 , could you please confirm the resolved configuration (in Tower) that the following options were not there?

```
azure.batch.deletePoolsOnCompletion
azure.batch.deleteJobsOnCompletion
```

Typically, this happens because the Azure Batch resources created by the Nextflow CLI are no longer present 🤔

**Comment by rpetit3** [comment]
Hi @abhi18av 

Those would have been the defaults so I think `deleteJobsOnCompletion = true` and `deletePoolsOnCompletion = false`.

So I think I figured out the issue.

In my config I specified a pool that exists on Azure, but didn't describe it in the config.

```
profiles {
  azure {
    azure {
      batch {
        location = "westus"
        accountName = "NAME"
        accountKey = "KEY"
        autoPoolMode = false
      }
      storage {
        accountName = "NAME"
        accountKey = "KEY"
      }
    }

    process {
      executor = 'azurebatch'
      queue = "test"
    }
  }
}
```

When the azure plugin is submitting a task it accesses `pool.opts` (e.g. https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy#L362) and my config did not have it so it was `null`. 

I added the pool to my config like this:

```
profiles {
  azure {
    azure {
      batch {
        location = "westus"
        accountName = "NAME"
        accountKey = "KEY"
        autoPoolMode = false
        pools {
          test {
            runAs = 'noadmin'
          }
        }
      }
      storage {
        accountName = "NAME"
        accountKey = "KEY"
      }
    }

    process {
      executor = 'azurebatch'
      queue = "test"
    }
  }
}
```

And that was enough to get make the `java.lang.NullPointerException` go away. 

I wonder if its worth checking `pool.opts` exists somewhere in the function https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy#L327

I do think the issue is resolved though, so please feel free to close. I'm documenting my progress on the Slack if you want to take a look.

**Comment by pditommaso** [comment]
I'm unable to replicate this. With the provided config i'm getting this error message 

```
 Cannot find Azure Batch config for pool: tests
```

Can you please include the `.nextflow.log` run with latest `22.03.1-edge` even better adding the option below: 

```
NXF_VER=22.03.1-edge nextflow -trace nextflow run [the pipeline args]
```

**Comment by rpetit3** [comment]
I think the ` Cannot find Azure Batch config for pool: tests` makes sense, unless you had a pool named `tests`. 

I've been doing some more playing on my end. I'm able to submit jobs from https://tower.nf/ to my Azure account, and the finish successfully.  So I took the Azure config section from one of my Tower jobs and used it on the command line.

```
profiles {
  azure {
    azure {
      batch {
        location = "westus"
        accountName = 'temptestbatch'
        accountKey = MY_BATCH_KEY
        copyToolInstallMode = 'node'
        autoPoolMode = false
        allowPoolCreation = false
        pools {
          'tower-pool-2Nn6h1Nr7OCZQE4lI6Gu1G' {
            vmType = 'standard_d4s_v3'
            vmCount = 0
          }
        }
      }
      {
        accountName = "wphltower"
        accountKey = MY_STORAGE_KEY
      }
    }

    process {
        executor = 'azurebatch'
        queue = 'tower-pool-2Nn6h1Nr7OCZQE4lI6Gu1G'
    }
  }

```

`azure.batch.accountKey` and `azure.storage.accountKey` match what was stored on Tower. I then used this on the command-line via 

```
# test Bactopia (runs fine if submitted from Tower)
NXF_VER=22.03.1-edge nextflow -trace nextflow run bactopia/bactopia \
    -profile test,docker,azure \
    -c azure.config \
    -w az://wphltower-container/work3 \
    --outdir az://wphltower-container/bactopia3

# Test nf-core/rnaseq (runs fine if submitted from Tower)
NXF_VER=22.03.1-edge nextflow -trace nextflow run nf-core/rnaseq \
    -profile test,azure \
    -c azure.config \
    -w az://wphltower-container/work-rnaseq \
    --outdir az://wphltower-container/rnaseq
```

I see the pools getting started, the jobs submitted, and files staged to Blob storage. But I am soon met with:
```
Caused by:
  Not a valid Azure Blob Storage file attribute view: interface java.nio.file.attribute.BasicWithKeyFileAttributeView
```
This occurs from both `bactopia` and `nf-core/rnaseq`.

Hopefully there's an obvious reason for pipelines running fine on Tower, but not at the command line. I've attached the Nextflow logs from the rnaseq and bactopia runs. Please let me know if I can provide any other details!

[bactopia-nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/8502334/bactopia-nextflow.log.txt)
[rnaseq.nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/8502335/rnaseq.nextflow.log.txt)

**Comment by pditommaso** [comment]
This is weird, I cannot even found the interface `java.nio.file.attribute.BasicWithKeyFileAttributeView` in my Java distribution

**Comment by pditommaso** [comment]
Which Java version are you running?

**Comment by rpetit3** [comment]
Here we go: 

```
java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)
```

**Comment by rpetit3** [comment]
@pditommaso You might have found the issue!

Tried changing versions to 
```
java --version
openjdk 11.0.14.1 2022-02-08 LTS
OpenJDK Runtime Environment Microsoft-31205 (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-31205 (build 11.0.14.1+1-LTS, mixed mode)
```

Things are moving! I'll report back shortly with an update!

**Comment by pditommaso** [comment]
Ummm OpenJDK JBR, never heard before. it looks stands for [JetBrains runtime](https://github.com/JetBrains/JetBrainsRuntime/wiki). 

I have no idea why conda is distributing this version, but it looks a bad idea. it says 

> JetBrains Runtime is not a certified build of OpenJDK. Please, use at your own risk.

I'd suggest using a [certified JVM](https://whichjdk.com/), use https://sdkman.io to install it

**Comment by rpetit3** [comment]
Success!

```
    Bactopia Execution Summary
    ---------------------------
    Bactopia Version : 2.0.2
    Nextflow Version : 22.03.1.edge
    Command Line     : nextflow -trace nextflow run bactopia/bactopia -profile test,docker,azure -c azure.config -w 'az://wphltower-container/work3' --outdir 'az://wphltower-container/bactopia3'
    Resumed          : false
    Completed At     : 2022-04-17T21:20:04.901526Z
    Duration         : 14m 4s
    Success          : true
    Exit Code        : 0
    Error Report     : -
    Launch Dir       : /home/robert_petit/test-azure
```

Looks like I installed the JBR openjdk (https://anaconda.org/anaconda/openjdk) when I was testing all multiple versions to figure out the original `java.lang.NullPointerException` error. 

Going to go ahead and close this, thank you so much for your help!

**Comment by abhi18av** [comment]
Whoa, interesting twist on this issue!

Glad it was resolved, something to remember about the JVM versions on conda. I've also run across with the `internal` JDK builds being distributed via conda apparently 🤷
