### ISSUE TITLE
.command.env is written into current working directory instead of process directory

### ISSUE THREAD

**Issue by Kibubu** [nextflow-io/nextflow#2812]
### Expected behavior and actual behavior
**Expected**
`.command.env` file containing exported environment variables is expected to reside always within the same folder beside `.command.sh`, `.command.run`, etc. even if the working directory was changed within the script.

**Actual**
`.command.env` is actually being written into the current working directory resulting in a no such file error.

### Steps to reproduce the problem

```nextflow
process ok {

  output:
  env FOO into ok

  """
  #!/usr/bin/env bash

  FOO="bar"
  """
}

process bug {

  output:
  env FOO into bug

  """
  #!/usr/bin/env bash

  cd $projectDir

  FOO="bar"
  """
}
```

### Program output 

**Shell**
```shell
❯ ./nextflow run bug.nf
N E X T F L O W  ~  version 21.10.6
Launching `bug.nf` [nice_heisenberg] - revision: c67bc5f3d7
executor >  local (2)
[d3/9e8db8] process > ok  [100%] 1 of 1 ✔
[ff/34d53e] process > bug [100%] 1 of 1, failed: 1 ✘
No such file:  /home/USER/workdir/nfbug/work/ff/34d53e782b3d5899b7799f165fb0e1/.command.env
```

**.nextflow.log**
```
Apr-21 23:23:27.598 [main] DEBUG nextflow.cli.Launcher - $> nextflow run bug.nf
Apr-21 23:23:27.754 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.10.6
Apr-21 23:23:27.774 [main] INFO  nextflow.cli.CmdRun - Launching `bug.nf` [nice_heisenberg] - revision: c67bc5f3d7
Apr-21 23:23:27.789 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/USER/workdir/nfbug/nextflow.config
Apr-21 23:23:27.790 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/USER/workdir/nfbug/nextflow.config
Apr-21 23:23:27.808 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Apr-21 23:23:28.433 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/USER/.nextflow/plugins
Apr-21 23:23:28.434 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Apr-21 23:23:28.444 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-21 23:23:28.445 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-21 23:23:28.448 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-21 23:23:28.458 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Apr-21 23:23:28.509 [main] DEBUG nextflow.Session - Session uuid: 8cc1c637-df85-4143-8f5e-9afc04d4b7e1
Apr-21 23:23:28.509 [main] DEBUG nextflow.Session - Run name: nice_heisenberg
Apr-21 23:23:28.510 [main] DEBUG nextflow.Session - Executor pool size: 8
Apr-21 23:23:28.524 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.10.6 build 5660
  Created: 21-12-2021 16:55 UTC (17:55 CEST)
  System: Linux 5.15.34-1-MANJARO
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 1.8.0_332-b04
  Encoding: UTF-8 (UTF-8)
  Process: 341096@earth [127.0.1.1]
  CPUs: 8 - Mem: 31.1 GB (17.8 GB) - Swap: 34.2 GB (31.2 GB)
Apr-21 23:23:28.540 [main] DEBUG nextflow.Session - Work-dir: /home/USER/workdir/nfbug/work [btrfs]
Apr-21 23:23:28.540 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/USER/workdir/nfbug/bin
Apr-21 23:23:28.547 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Apr-21 23:23:28.558 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-21 23:23:28.597 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Apr-21 23:23:28.683 [main] DEBUG nextflow.Session - Session start invoked
Apr-21 23:23:28.931 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-21 23:23:29.043 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-21 23:23:29.043 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-21 23:23:29.048 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Apr-21 23:23:29.053 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=31.1 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Apr-21 23:23:29.072 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Apr-21 23:23:29.149 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-21 23:23:29.150 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-21 23:23:29.154 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: bug, ok
Apr-21 23:23:29.155 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Apr-21 23:23:29.155 [main] DEBUG nextflow.Session - Session await
Apr-21 23:23:29.258 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-21 23:23:29.263 [Task submitter] INFO  nextflow.Session - [ff/34d53e] Submitted process > bug
Apr-21 23:23:29.273 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-21 23:23:29.274 [Task submitter] INFO  nextflow.Session - [d3/9e8db8] Submitted process > ok
Apr-21 23:23:29.289 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: bug; status: COMPLETED; exit: 0; error: -; workDir: /home/USER/workdir/nfbug/work/ff/34d53e782b3d5899b7799f165fb0e1]
Apr-21 23:23:29.304 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'bug'

Caused by:
  No such file: /home/USER/workdir/nfbug/work/ff/34d53e782b3d5899b7799f165fb0e1/.command.env

java.nio.file.NoSuchFileException: /home/USER/workdir/nfbug/work/ff/34d53e782b3d5899b7799f165fb0e1/.command.env
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at org.apache.groovy.nio.extensions.NioExtensions.newReader(NioExtensions.java:1404)
	at org.apache.groovy.nio.extensions.NioExtensions.getText(NioExtensions.java:397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1956)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3843)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.getProperty(NextflowDelegatingMetaClass.java:75)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:199)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassGetPropertySite.getProperty(PojoMetaClassGetPropertySite.java:36)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at nextflow.processor.TaskProcessor.memoizedMethodPriv$collectOutEnvMapPath(TaskProcessor.groovy:1452)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor$_closure2.doCall(TaskProcessor.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.apache.groovy.util.concurrent.concurrentlinkedhashmap.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:788)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.groovy.util.concurrent.concurrentlinkedhashmap.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:800)
	at org.apache.groovy.util.concurrent.concurrentlinkedhashmap.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:777)
	at org.codehaus.groovy.runtime.memoize.LRUCache.getAndPut(LRUCache.java:63)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:428)
	at groovy.lang.Closure$call.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.processor.TaskProcessor.collectOutEnvMap(TaskProcessor.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.collectOutEnvParam(TaskProcessor.groovy:1440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:170)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at nextflow.processor.TaskProcessor.collectOutputs(TaskProcessor.groovy:1424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212)
	at nextflow.processor.TaskProcessor.collectOutputs(TaskProcessor.groovy:1397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.finalizeTask(TaskProcessor.groovy:2150)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:616)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:534)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.lang.Thread.run(Thread.java:750)
Apr-21 23:23:29.326 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: /home/USER/workdir/nfbug/work/ff/34d53e782b3d5899b7799f165fb0e1/.command.env
Apr-21 23:23:29.351 [main] DEBUG nextflow.Session - Session await > all process finished
Apr-21 23:23:29.352 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-21 23:23:29.354 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: ok; status: COMPLETED; exit: 0; error: -; workDir: /home/USER/workdir/nfbug/work/d3/9e8db8104f64c8bbbfc632425b1e3f]
Apr-21 23:23:29.358 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=1; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=2ms; cachedDuration=0ms;loadCpus=1; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Apr-21 23:23:29.529 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Apr-21 23:23:29.550 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow version: 21.10.6
* Java version: 1.8.0_332
* Operating system: Linux
* Bash version: GNU bash, Version 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Comment by Kibubu** [comment]
Since I stumbled over this same issue half a year later and even found my own ticket

**Workaround**
Make sure to `cd` back into the initial working directory at the end of the script. The `.command.env` file is written into the last known working directory after the script finishes.

```bash
"""
TASK_DIR=\$(pwd)
...
# do work
FOO="bar"
...
cd \$TASK_DIR
"""
```

So something like
```bash
FOO="bar"
cd test
```
will also fail

**Comment by pditommaso** [comment]
Finally solved! 👉 8e4d7fed.

**Comment by pditommaso** [comment]
This is already available as of 23.10.x

**Comment by GuillaumeTh** [comment]
Ok. I got the same issue with the 23.10.1.

The only difference with the example of this issue is in the nextflow.config with  `scratch = false`.

**Comment by pditommaso** [comment]
Then open a new issue including a replicable test case
