### ISSUE TITLE
Cause: No such property: ch_design_reads_csv for class

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [nextflow-io/nextflow#2826]
## Bug report 

I made self-update to nextflow latest from 21.10 stable. I got error `Cause: No such property: ch_design_reads_csv for class`. Previous runs with 21.10 were successfull.

### Expected behavior and actual behavior

No design file error should be given.

### Steps to reproduce the problem

`nextflow run nf-core/chipseq -profile docker -r 1.2.1 --input script/FLI1_FRA1_ChIP_revision_260422_2.csv -c script/ibg.config --paired_end --seq_center GeneCore --genome hg38 --narrow_peak --macs_pvalue 0.00001 --outdir results_narrow_peak_pval000001`

### Program output 

```
Apr-27 14:09:21.554 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/chipseq -profile docker -r 1.2.1 --input script/FLI1_FRA1_ChIP_revision_260422.csv -c script/ibg.config --paired_end --seq_center GeneCore --genome hg38 --narrow_peak --macs_pvalue 0.00001 --outdir results_narrow_peak_pval000001
Apr-27 14:09:21.626 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.0
Apr-27 14:09:22.425 [main] DEBUG nextflow.scm.AssetManager - Git config: /root/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/chipseq.git
Apr-27 14:09:22.437 [main] DEBUG nextflow.scm.AssetManager - Git config: /root/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/chipseq.git
Apr-27 14:09:28.182 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /root/.nextflow/assets/nf-core/chipseq/nextflow.config
Apr-27 14:09:28.185 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /archive/erkeklabshared/Tubitak_3501/ChIPseq/raw_data/FLI1_FRA1_revision/script/ibg.config
Apr-27 14:09:28.185 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /root/.nextflow/assets/nf-core/chipseq/nextflow.config
Apr-27 14:09:28.185 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /archive/erkeklabshared/Tubitak_3501/ChIPseq/raw_data/FLI1_FRA1_revision/script/ibg.config
Apr-27 14:09:28.192 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `docker`
Apr-27 14:09:28.382 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Apr-27 14:09:28.391 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-27 14:09:28.392 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-27 14:09:28.395 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-27 14:09:28.398 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Apr-27 14:09:34.059 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `docker`
Apr-27 14:09:34.074 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, ifb_core, denbi_qbic, genotoul, alice, uppmax, abims, nihbiowulf, nu_genomics, oist, sahmri, mpcdf, leicester, lugh, cambridge, unibe_ibu, vai, czbiohub_aws, jax, cheaha, ccga_med, test, google, computerome, seg_globe, sanger, pasteur, test_full, eddie, azurebatch, bi, bigpurple, cedars, docker, gis, eva, utd_ganymede, fgcz, conda, singularity, icr_davros, munin, rosalind, prince, hasta, hebbe, cfc, utd_sysbio, uzh, debug, genouest, cbe, ebc, ccga_dx, crick, marvin, phoenix, biohpc_gen, awsbatch, uct_hpc, imperial, maestro, aws_tower, binac]
Apr-27 14:09:34.108 [main] INFO  nextflow.cli.CmdRun - Launching `https://github.com/nf-core/chipseq` [condescending_watson] DSL2 - revision: 0f487ed76d [1.2.1]
Apr-27 14:09:34.109 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/root/.nextflow/plugins; core-plugins: nf-amazon@1.7.1,nf-azure@0.13.1,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
Apr-27 14:09:34.110 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Apr-27 14:09:34.173 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-27 14:09:34.173 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-27 14:09:34.175 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-27 14:09:34.181 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Apr-27 14:09:34.225 [main] DEBUG nextflow.Session - Session uuid: c9f2a8cf-52c3-43de-a6f3-0d4cd5c16371
Apr-27 14:09:34.225 [main] DEBUG nextflow.Session - Run name: condescending_watson
Apr-27 14:09:34.226 [main] DEBUG nextflow.Session - Executor pool size: 40
Apr-27 14:09:34.251 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.04.0 build 5697
  Created: 23-04-2022 18:00 UTC (21:00 TRST)
  System: Linux 3.10.0-1062.4.1.el7.x86_64
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)
  Process: 199674@node02 [10.100.120.102]
  CPUs: 40 - Mem: 0 (45.9 GB) - Swap: 0 (12 GB)
Apr-27 14:09:34.342 [main] DEBUG nextflow.Session - Work-dir: /archive/erkeklabshared/Tubitak_3501/ChIPseq/raw_data/FLI1_FRA1_revision/work [nfs]
Apr-27 14:09:34.353 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Apr-27 14:09:34.362 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-27 14:09:34.432 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Apr-27 14:09:34.443 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 41; maxThreads: 1000
Apr-27 14:09:34.573 [main] DEBUG nextflow.Session - Session start invoked
Apr-27 14:09:34.577 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /archive/erkeklabshared/Tubitak_3501/ChIPseq/raw_data/FLI1_FRA1_revision/results_narrow_peak_pval000001/pipeline_info/execution_trace.txt
Apr-27 14:09:36.928 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-27 14:09:36.982 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: 1.7.1
Apr-27 14:09:36.989 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-amazon@1.7.1' resolved
Apr-27 14:09:36.989 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@1.7.1'
Apr-27 14:09:37.000 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@1.7.1
Apr-27 14:09:37.015 [main] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
Apr-27 14:09:37.015 [main] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf
Apr-27 14:09:37.022 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Apr-27 14:09:37.029 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {max_error_retry=5}
Apr-27 14:09:37.357 [main] DEBUG c.u.s3fs.S3FileSystemProvider - Using S3 multi-part downloader
Apr-27 14:09:37.359 [main] DEBUG c.u.s3fs.ng.S3ParallelDownload - Creating S3 download thread pool: workers=10; chunkSize=10 MB; queueSize=10000; max-mem=1 GB; maxAttempts=5; maxDelay=1m 30s; pool-capacity=103
Apr-27 14:09:40.396 [main] WARN  c.a.i.InstanceMetadataServiceResourceFetcher - Fail to retrieve token 
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:58)
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:46)
	at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112)
	at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:165)
	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.getCredentials(EC2ContainerCredentialsProviderWrapper.java:75)
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
	at com.amazonaws.services.s3.S3CredentialsProviderChain.getCredentials(S3CredentialsProviderChain.java:36)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1266)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1287)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:6428)
	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:6401)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5438)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5394)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:928)
	at com.upplication.s3fs.AmazonS3Client.listObjects(AmazonS3Client.java:129)
	at com.upplication.s3fs.util.S3ObjectSummaryLookup.lookup(S3ObjectSummaryLookup.java:113)
	at com.upplication.s3fs.S3FileSystemProvider.checkAccess(S3FileSystemProvider.java:642)
	at java.base/java.nio.file.Files.exists(Files.java:2439)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:94)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.FilesEx.exists(FilesEx.groovy:454)
	at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:1032)
	at nextflow.file.FileHelper$checkIfExists$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at nextflow.file.FileHelper$checkIfExists$1.call(Unknown Source)
	at nextflow.Nextflow.file(Nextflow.groovy:159)
	at nextflow.Nextflow$file.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at Script_cc06130a.runScript(Script_cc06130a:171)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:170)
	at nextflow.script.BaseScript.run(BaseScript.groovy:203)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:220)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:334)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:95)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
	... 61 common frames omitted
Apr-27 14:10:01.489 [main] WARN  c.a.i.InstanceMetadataServiceResourceFetcher - Fail to retrieve token 
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:58)
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:46)
	at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112)
	at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:165)
	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.getCredentials(EC2ContainerCredentialsProviderWrapper.java:75)
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
	at com.amazonaws.services.s3.S3CredentialsProviderChain.getCredentials(S3CredentialsProviderChain.java:36)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1266)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1287)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5394)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:928)
	at com.upplication.s3fs.AmazonS3Client.listObjects(AmazonS3Client.java:129)
	at com.upplication.s3fs.util.S3ObjectSummaryLookup.lookup(S3ObjectSummaryLookup.java:113)
	at com.upplication.s3fs.S3FileSystemProvider.checkAccess(S3FileSystemProvider.java:642)
	at java.base/java.nio.file.Files.exists(Files.java:2439)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.FilesEx.exists(FilesEx.groovy:454)
	at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:1032)
	at nextflow.file.FileHelper$checkIfExists$1.call(Unknown Source)
	at nextflow.Nextflow.file(Nextflow.groovy:159)
	at nextflow.Nextflow$file.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at Script_cc06130a.runScript(Script_cc06130a:178)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:170)
	at nextflow.script.BaseScript.run(BaseScript.groovy:203)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:220)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:334)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:95)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
	... 54 common frames omitted
Apr-27 14:10:01.595 [main] INFO  nextflow.Nextflow - -[2m--------------------------------------------------[0m-
                                        [0;32m,--.[0;30m/[0;32m,-.[0m
[0;34m        ___     __   __   __   ___     [0;32m/,-._.--~'[0m
[0;34m  |\ | |__  __ /  ` /  \ |__) |__         [0;33m}  {[0m
[0;34m  | \| |       \__, \__/ |  \ |___     [0;32m\`-._,-`-,[0m
                                        [0;32m`._,._,'[0m
[0;35m  nf-core/chipseq v1.2.1[0m
-[2m--------------------------------------------------[0m-

Apr-27 14:10:01.599 [main] INFO  nextflow.Nextflow - Run Name            : condescending_watson
Data Type           : Paired-End
Design File         : script/FLI1_FRA1_ChIP_revision_260422.csv
Genome              : hg38
Fasta File          : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa
GTF File            : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf
Gene BED File       : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.bed
BWA Index           : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Sequence/BWAIndex/genome.fa
Blacklist BED       : /root/.nextflow/assets/nf-core/chipseq/assets/blacklists/hg38-blacklist.bed
MACS2 Genome Size   : 2.7e9
Min Consensus Reps  : 1
MACS2 Narrow Peaks  : Yes
MACS2 P-value       : 1.0E-5
Trim R1             : 0 bp
Trim R2             : 0 bp
Trim 3' R1          : 0 bp
Trim 3' R2          : 0 bp
NextSeq Trim        : 0 bp
Sequencing Center   : GeneCore
Fingerprint Bins    : 500000
Save Genome Index   : No
Max Resources       : 128 GB memory, 16 cpus, 10d time per job
Container           : docker - nfcore/chipseq:1.2.1
Output Dir          : results_narrow_peak_pval000001
Launch Dir          : /archive/erkeklabshared/Tubitak_3501/ChIPseq/raw_data/FLI1_FRA1_revision
Working Dir         : /archive/erkeklabshared/Tubitak_3501/ChIPseq/raw_data/FLI1_FRA1_revision/work
Script Dir          : /root/.nextflow/assets/nf-core/chipseq
User                : root
Config Profile      : docker
Apr-27 14:10:01.599 [main] INFO  nextflow.Nextflow - -[2m--------------------------------------------------[0m-
Apr-27 14:10:01.606 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: ch_design_reads_csv for class: Script_cc06130a
Apr-27 14:10:01.621 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: ch_design_reads_csv for class: Script_cc06130a
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at Script_cc06130a.runScript(Script_cc06130a:346)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:170)
	at nextflow.script.BaseScript.run(BaseScript.groovy:203)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:220)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:334)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

```

### Environment 

* Nextflow version: 22.04
* Java version: 1.8
* Operating system: centos 7
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

### Additional context

If a design file error is present, error should be like this: 
```
Command output:
  ERROR: Please check design file: 
```
When I run pipeline with nextflow 21.10, the error above appears and it is the correct error display according to wrong replicate id in design file.

**Comment by pditommaso** [comment]
This looks like a network problem 


```
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
```

**Comment by alirizaaribas-ibg** [comment]
I checked network. Bash pings well. 22.04 not recognizing network, 21.10 downloads successfully. Operating system could update from internet like nextflow self-update.

**Comment by JoseEspinosa** [comment]
You should add to your command the `-dsl1` flag since `dsl2` has become the default dsl from 22.04.0 In future releases the DSL will be autodetected once [this](https://github.com/nextflow-io/nextflow/pull/2879) PR is included on a new release

**Comment by pditommaso** [comment]
Version 22.04.3 should detect the correct DSL syntax automatically
