### ISSUE TITLE
Cannot start Nextflow pipeline trough ssh command

### ISSUE THREAD

**Issue by rduque1** [nextflow-io/nextflow#290]
I created a aws cluster with Nextflow, where I want to start the Nextflow pipeline with:

```
ssh -t ubuntu@ec2-34-250-62-245.eu-west-1.compute.amazonaws.com './nextflow run InSilicoDB/docker-impute2 --rawdata=s3://some-bucket/some.file' 
N E X T F L O W  ~  version 0.23.2
Launching `InSilicoDB/docker-impute2` [desperate_mcnulty] - revision: e65b3e8860 [master]
id_98
[warm up] executor > local
ERROR ~ Error executing process > 'plink (1)'

Caused by:
  Cannot invoke method closeQuietly() on null object


 -- Check '.nextflow.log' file for details
Connection to ec2-34-250-62-245.eu-west-1.compute.amazonaws.com closed.
```

When I ssh into the server and then run the same command, it works perfectly. But I can't make it work through ssh.
I don't find a solution and I am stuck, could you help?

The full `.nextflow.log` is:

```
Feb-17 13:57:25.542 [main] DEBUG nextflow.cli.Launcher - $> ./nextflow run InSilicoDB/docker-impute2 --rawdata=s3://some-bucket/some.file
Feb-17 13:57:25.662 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.23.2
Feb-17 13:57:26.166 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/ubuntu/.nextflow/assets/InSilicoDB/docker-impute2/.git/config; branch: master; remote: origin; url: https://github.com/InSilicoDB/docker-impute2.git
Feb-17 13:57:26.227 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/ubuntu/.nextflow/assets/InSilicoDB/docker-impute2/.git/config; branch: master; remote: origin; url: https://github.com/InSilicoDB/docker-impute2.git
Feb-17 13:57:26.498 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/ubuntu/.nextflow/assets/InSilicoDB/docker-impute2/.git/config; branch: master; remote: origin; url: https://github.com/InSilicoDB/docker-impute2.git
Feb-17 13:57:26.498 [main] INFO  nextflow.cli.CmdRun - Launching `InSilicoDB/docker-impute2` [desperate_mcnulty] - revision: e65b3e8860 [master]
Feb-17 13:57:26.510 [main] DEBUG nextflow.config.ConfigBuilder - Found config home: /home/ubuntu/.nextflow/config
Feb-17 13:57:26.510 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/ubuntu/.nextflow/assets/InSilicoDB/docker-impute2/nextflow.config
Feb-17 13:57:26.512 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/ubuntu/.nextflow/config
Feb-17 13:57:26.512 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/ubuntu/.nextflow/assets/InSilicoDB/docker-impute2/nextflow.config
Feb-17 13:57:26.540 [main] DEBUG nextflow.config.ConfigBuilder - Setting config profile: 'standard'
Feb-17 13:57:26.654 [main] DEBUG nextflow.Session - Session uuid: 7c1b27c0-1e51-4e3e-ac00-84ca8af4b913
Feb-17 13:57:26.655 [main] DEBUG nextflow.Session - Run name: desperate_mcnulty
Feb-17 13:57:26.655 [main] DEBUG nextflow.Session - Executor pool size: 4
Feb-17 13:57:26.671 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 0.23.2 build 4153
  Modified: 02-02-2017 13:39 UTC 
  System: Linux 4.4.0-62-generic
  Runtime: Groovy 2.4.7 on OpenJDK 64-Bit Server VM 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13
  Encoding: UTF-8 (ANSI_X3.4-1968)
  Process: 16765@ip-172-31-0-197 [172.31.0.197]
  CPUs: 4 - Mem: 15.7 GB (14.1 GB) - Swap: 0 (0)
Feb-17 13:57:26.677 [main] DEBUG nextflow.Session - Work-dir: /home/ubuntu/work [ext2/ext3]
Feb-17 13:57:26.677 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/ubuntu/.nextflow/assets/InSilicoDB/docker-impute2/bin
Feb-17 13:57:27.339 [main] DEBUG nextflow.Session - Session start invoked
Feb-17 13:57:27.342 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Feb-17 13:57:27.343 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Feb-17 13:57:27.621 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Feb-17 13:57:27.660 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Feb-17 13:57:27.674 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {region=eu-west-1}
Feb-17 13:57:28.261 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.262 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.269 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.271 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Feb-17 13:57:28.275 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=4; memory=15.7 GB; capacity=4; pollInterval=100ms; dumpInterval=5m
Feb-17 13:57:28.279 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Feb-17 13:57:28.280 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Feb-17 13:57:28.282 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Feb-17 13:57:28.324 [main] DEBUG nextflow.Session - >>> barrier register (process: plink)
Feb-17 13:57:28.338 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > plink -- maxForks: 6
Feb-17 13:57:28.379 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.379 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.379 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.381 [main] DEBUG nextflow.Session - >>> barrier register (process: extractChromosome)
Feb-17 13:57:28.392 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <plink> Poison pill arrived
Feb-17 13:57:28.395 [main] DEBUG nextflow.processor.TaskProcessor - Creating *combiner* operator for each param(s) at index(es): [0]
Feb-17 13:57:28.405 [Actor Thread 2] DEBUG nextflow.processor.StateObj - <plink> State before poison: StateObj[submitted: 1; completed: 0; poisoned: false ]
Feb-17 13:57:28.429 [Actor Thread 3] DEBUG nextflow.processor.TaskProcessor - Copying to process workdir foreign file: s3:///imputation-gp2/id_98_raw_data.txt
Feb-17 13:57:28.459 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > extractChromosome -- maxForks: 4
Feb-17 13:57:28.477 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.477 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.477 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.478 [main] DEBUG nextflow.Session - >>> barrier register (process: checkStrandFlips)
Feb-17 13:57:28.509 [Actor Thread 3] ERROR nextflow.processor.TaskProcessor - Error executing process > 'plink (1)'

Caused by:
  Cannot invoke method closeQuietly() on null object

java.lang.NullPointerException: Cannot invoke method closeQuietly() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at nextflow.processor.TaskProcessor.normalizeInputToFile(TaskProcessor.groovy:1541)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at nextflow.processor.TaskProcessor.normalizeInputToFiles(TaskProcessor.groovy:1565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at nextflow.processor.TaskProcessor$_makeTaskContextStage2_closure38.doCall(TaskProcessor.groovy:1766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5226)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2107)
	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nextflow.processor.TaskProcessor.makeTaskContextStage2(TaskProcessor.groovy:1763)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:546)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1261)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:430)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:369)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at Script465E893140CC2607DC9D85E63608E4F1$_run_closure1.doCall(Script465E893140CC2607DC9D85E63608E4F1:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb-17 13:57:28.512 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > checkStrandFlips -- maxForks: 4
Feb-17 13:57:28.526 [Actor Thread 3] DEBUG nextflow.Session - Session aborted -- Cause: Cannot invoke method closeQuietly() on null object
Feb-17 13:57:28.532 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.532 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.533 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.534 [main] DEBUG nextflow.Session - >>> barrier register (process: impute2)
Feb-17 13:57:28.541 [Thread-3] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Feb-17 13:57:28.543 [Actor Thread 5] DEBUG nextflow.processor.TaskProcessor - <extractChromosome> After stop
Feb-17 13:57:28.543 [Actor Thread 5] DEBUG nextflow.processor.TaskProcessor - <checkStrandFlips> After stop
Feb-17 13:57:28.545 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <plink> After stop
Feb-17 13:57:28.546 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > impute2 -- maxForks: 4
Feb-17 13:57:28.571 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.571 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.571 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.572 [main] DEBUG nextflow.Session - >>> barrier register (process: summarize)
Feb-17 13:57:28.580 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > summarize -- maxForks: 4
Feb-17 13:57:28.596 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.596 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.597 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.597 [main] DEBUG nextflow.Session - >>> barrier register (process: zipping)
Feb-17 13:57:28.605 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > zipping -- maxForks: 4
Feb-17 13:57:28.616 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.616 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.617 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.618 [main] DEBUG nextflow.Session - >>> barrier register (process: createPDataFile)
Feb-17 13:57:28.626 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > createPDataFile -- maxForks: 4
Feb-17 13:57:28.633 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.633 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.633 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.634 [main] DEBUG nextflow.Session - >>> barrier register (process: downloadRepo)
Feb-17 13:57:28.641 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > downloadRepo -- maxForks: 4
Feb-17 13:57:28.642 [Actor Thread 3] DEBUG nextflow.processor.TaskProcessor - <downloadRepo> Poison pill arrived
Feb-17 13:57:28.646 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Feb-17 13:57:28.646 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-17 13:57:28.646 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-17 13:57:28.647 [main] DEBUG nextflow.Session - >>> barrier register (process: crawlForSnpToAnalyze)
Feb-17 13:57:28.648 [Actor Thread 2] DEBUG nextflow.processor.StateObj - <downloadRepo> State before poison: StateObj[submitted: 1; completed: 0; poisoned: false ]
Feb-17 13:57:28.653 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > crawlForSnpToAnalyze -- maxForks: 4
Feb-17 13:57:28.657 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Feb-17 13:57:28.658 [main] DEBUG nextflow.Session - Session await
Feb-17 13:57:28.658 [main] DEBUG nextflow.Session - Session await > all process finished
Feb-17 13:57:28.658 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-17 13:57:28.687 [main] DEBUG nextflow.Session - AWS S3 uploader shutdown
Feb-17 13:57:28.701 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

**Comment by pditommaso** [comment]
Hi Robin, I guess that's some problem accessing the data on S3. Can you check that is the files are available and in the same region where you are running the ec2 instances?

**Comment by rduque1** [comment]
Hi Paolo, thanks for the quick reply. The files are in the same region as the server. The command works when I ssh in the machine first and then run the command. It doesn't when I want to execute the command through ssh.

When I do:

```
robin:~$ ssh -t ubuntu@ec2-34-250-62-245.eu-west-1.compute.amazonaws.com './nextflow run InSilicoDB/docker-impute2 --rawdata=s3://imputation-gp2/id_98_raw_data.txt' 
```
it doesn't work.

But when I do:
```
robin:~$ ssh ubuntu@ec2-34-250-62-245.eu-west-1.compute.amazonaws.com
ubuntu:~$ ./nextflow run InSilicoDB/docker-impute2 --rawdata=s3://imputation-gp2/id_98_raw_data.txt'
```
it works.

**Comment by pditommaso** [comment]
I see. I guess it's something related the environment configuration. NF sets some variables in the `.bash_profile` file. I think for some reason are not read when you execute the command via ssh. 

You can test that by running: 
```
ssh host-name 'env | sort'
```

It should print some `NXF_xxx` variables and the `AWS_xxx` credentials.

**Comment by rduque1** [comment]
Thanks that's it. When i first `source` the `.bash_profile` file then it works.
