### ISSUE TITLE
cannot provide s3 object as input to -params-file

### ISSUE THREAD

**Issue by mikomatic** [nextflow-io/nextflow#2929]
## Bug report 

It would seem it is not possible to provide an S3 object as input of -params-file

### Expected behavior and actual behavior

I am running a command : `nextflow run . -profile local -params-file s3://<OBJECT_KEY>/params.yml`

The "local" profile only contains minimal configuration for Docker containers
```
profiles {

    local {
        docker {
            enabled = true
        }
    }

}
```

I would expect this command to download the specified params file, but instead i get an error

```
WARN: Unable to start plugin 'nf-amazon' required by s3://<OBJECT_KEY>/params.yml
Missing plugin 'nf-amazon' required to read file: s3://<OBJECT_KEY>/params.yml
```

The workflow seems to work if the `params.yml` file is created locally. S3 Endpoint seems to be supported only "inside" the pipeline contrary to what is stated in https://github.com/nextflow-io/nextflow/issues/1412

### Steps to reproduce the problem

1. Declare a workflow
2. Pass a `-params-file` referencing an S3 endpoint

### Program output 

```
WARN: Unable to start plugin 'nf-amazon' required by s3://<OBJECT_KEY>/params.yml
Missing plugin 'nf-amazon' required to read file: s3://<OBJECT_KEY>/params.yml
```

The nextflow.log file (redacted):

```
Jun-06 14:45:49.853 [main] DEBUG nextflow.cli.Launcher - $> nextflow run . -profile local -params-file '<OBJECT_KEY>/params.yml'
Jun-06 14:45:49.936 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.3
Jun-06 14:45:50.477 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/dev/bnew/nextflow-workflows/bnxt-487-demo/nextflow.config
Jun-06 14:45:50.477 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/dev/bnew/nextflow-workflows/bnxt-487-demo/nextflow.config
Jun-06 14:45:50.492 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Jun-06 14:45:50.500 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-06 14:45:50.501 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-06 14:45:50.503 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jun-06 14:45:50.509 [main] WARN  nextflow.file.FileHelper - Unable to start plugin 'nf-amazon' required by s3://<OBJECT_KEY>/params.yml
java.lang.NullPointerException: Cannot invoke "nextflow.plugin.CustomPluginManager.getPlugin(String)" because "this.manager" is null
	at nextflow.plugin.PluginsFacade.isStarted(PluginsFacade.groovy:322)
	at nextflow.plugin.PluginsFacade.startIfMissing(PluginsFacade.groovy:409)
	at nextflow.plugin.Plugins.startIfMissing(Plugins.groovy:73)
	at nextflow.file.FileHelper.autoStartMissingPlugin(FileHelper.groovy:288)
	at nextflow.file.FileHelper.asPath(FileHelper.groovy:268)
	at nextflow.cli.CmdRun.validateParamsFile(CmdRun.groovy:587)
	at nextflow.cli.CmdRun.memoizedMethodPriv$parsedParamsMap(CmdRun.groovy:522)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.cli.CmdRun$_closure1.doCall(CmdRun.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:428)
	at nextflow.cli.CmdRun.parsedParams(CmdRun.groovy)
	at nextflow.cli.CmdRun$parsedParams$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:350)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:317)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:754)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:767)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:294)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
Jun-06 14:45:50.510 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Jun-06 14:45:50.510 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.IllegalStateException: Missing plugin 'nf-amazon' required to read file: s3://<OBJECT_KEY>/params.yml
	at nextflow.file.FileHelper.asPath(FileHelper.groovy:320)
	at nextflow.file.FileHelper.asPath(FileHelper.groovy:274)
	at nextflow.cli.CmdRun.validateParamsFile(CmdRun.groovy:587)
	at nextflow.cli.CmdRun.memoizedMethodPriv$parsedParamsMap(CmdRun.groovy:522)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.cli.CmdRun$_closure1.doCall(CmdRun.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:428)
	at nextflow.cli.CmdRun.parsedParams(CmdRun.groovy)
	at nextflow.cli.CmdRun$parsedParams$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:350)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:317)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:754)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:767)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:294)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

```

### Environment 

* Nextflow version: 22.04.3
* Java version: OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
* Operating system: Ubuntu 
* Bash version: zsh 5.8 (x86_64-ubuntu-linux-gnu)

**Comment by jorgeaguileraseqera** [comment]
I think it's fixed in the next release

version 22.04.3:

```
NXF_VER=22.04.3 nextflow run hello  -params-file s3://tower-reg-test/outofmemory/params.yml
N E X T F L O W  ~  version 22.04.3
WARN: Unable to start plugin 'nf-amazon' required by s3://tower-reg-test/outofmemory/params.yml
Missing plugin 'nf-amazon' required to read file: s3://tower-reg-test/outofmemory/params.yml
```

version 22.06.0-edge

```
NXF_VER=22.06.0-edge nextflow run hello  -params-file s3://tower-reg-test/outofmemory/params.yml
N E X T F L O W  ~  version 22.06.0-edge
Launching `https://github.com/nextflow-io/hello` [sad_visvesvaraya] DSL2 - revision: 4eab81bd42 [master]
executor >  local (4)
[a9/711c06] process > sayHello (1) [100%] 4 of 4 ✔
Hola world!

Hello world!

Ciao world!

Bonjour world!
```

can you try with this edge version to validate it, please?

**Comment by jorgeaguileraseqera** [comment]
I think it's fixed in the next release

version 22.04.3:

NXF_VER=22.04.3 nextflow run hello  -params-file s3://<BUCKET>/params.yml
N E X T F L O W  ~  version 22.04.3
WARN: Unable to start plugin 'nf-amazon' required by s3://<BUCKET>/params.yml
Missing plugin 'nf-amazon' required to read file: s3://<BUCKET>/params.yml

version 22.06.0-edge

NXF_VER=22.06.0-edge nextflow run hello  -params-file s3://<BUCKET>/params.yml
N E X T F L O W  ~  version 22.06.0-edge
Launching `https://github.com/nextflow-io/hello` [sad_visvesvaraya] DSL2 - revision: 4eab81bd42 [master]
executor >  local (4)
[a9/711c06] process > sayHello (1) [100%] 4 of 4 ✔
Hola world!

Hello world!

Ciao world!

Bonjour world!

can you try with this edge version to validate it, please?
