### ISSUE TITLE
Using `process.containerOptions` with AWS Batch throws an exception

### ISSUE THREAD

**Issue by ramdayan** [nextflow-io/nextflow#3019]
### Expected behavior and actual behavior

Using `process.containerOptions` should work when using the AWS Batch executor just like it works when using Docker locally.

### Steps to reproduce the problem

Configure the AWS Batch executor and set the `process.containerOptions` to some Docker container options (e.g. `-e x=y`).

### Program output 

Here’s the top of the stack trace:
```
Error executing process > 'p1'

Caused by:
  java.lang.UnsupportedOperationException

java.lang.UnsupportedOperationException: null
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at nextflow.cloud.aws.batch.AwsContainerOptionsMapper.checkEnvVars(AwsContainerOptionsMapper.groovy:50)
	at nextflow.cloud.aws.batch.AwsContainerOptionsMapper.createContainerProperties(AwsContainerOptionsMapper.groovy:31)
	at nextflow.cloud.aws.batch.AwsContainerOptionsMapper$createContainerProperties.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:231)
	at nextflow.cloud.aws.batch.AwsBatchTaskHandler.configJobDefRequest(AwsBatchTaskHandler.groovy:471)
...
```

### Environment 

* Nextflow version: 22.04.4
* Java version: openjdk 11.0.15 2022-04-19
* Operating system: Linux

**Comment by pditommaso** [comment]
Please include a test case

**Comment by ramdayan** [comment]
Nextflow config:
```
aws {
    region = 'us-east-1'
    batch {
        cliPath = '/usr/local/bin/aws'
        jobRole = 'my-aws-batch-job-role'
    }
}

process {
    echo = true
    executor = 'awsbatch'
    queue = 'my-aws-batch-queue'
    container = "python"
    containerOptions = '-e x=y'
}

workDir = 's3://my-bucket'
```

Nextflow script:
```
#!/usr/bin/env nextflow

process p1 {
    """
    #!/usr/bin/env bash
    env
    """
}
```

**Comment by pditommaso** [comment]
Gotcha! found, thanks

**Comment by ramdayan** [comment]
> Gotcha! found, thanks

Awesome!
What's the process from here?
When is the fix going to be available in an official release?

**Comment by pditommaso** [comment]
We do an edge release every month, scheduled in a couple of days, and a stable release (milestone) very 6, that's scheduled in October. 

In any case a simple workaround is just to use the `--env` option instead of `-e` to prevent this glitch

**Comment by ramdayan** [comment]
Thanks for the workaround!
