### ISSUE TITLE
Queue full error with AWS Batch executor

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3117]
As of version 22.08.1 the following error is thrown when submitting a large number jobs 

```
Caused by:
  Queue full

java.lang.IllegalStateException: Queue full
	at java.base/java.util.AbstractQueue.add(AbstractQueue.java:98)
	at java.base/java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:326)
	at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:199)
	at nextflow.processor.ParallelPollingMonitor.submit0(ParallelPollingMonitor.groovy:61)
	at nextflow.processor.ParallelPollingMonitor$1.invoke(ParallelPollingMonitor.groovy:70)
	at nextflow.util.ThrottlingExecutor$Recoverable.call(ThrottlingExecutor.groovy:404)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This is a side effect of this change https://github.com/nextflow-io/nextflow/pull/3093/files. 

I think the problem is that [canSubmit](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy#L557-L557) is not consistent since the [submit](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/processor/ParallelPollingMonitor.groovy#L65-L65) operation is performed in parallel

**Comment by pditommaso** [comment]
Also checking more, the queue limit is always implemented at the level of the thread pool 

https://github.com/nextflow-io/nextflow/blob/81825f5417b865b8a556e96aa2e663b80b08e146/modules/nextflow/src/main/groovy/nextflow/util/ThrottlingExecutor.groovy#L507-L508


The [acquire](https://github.com/nextflow-io/nextflow/blob/81825f5417b865b8a556e96aa2e663b80b08e146/modules/nextflow/src/main/groovy/nextflow/util/ThrottlingExecutor.groovy#L514-L514) should block when the queue size is reached. 


I think we need to rollback #3093 and investigate why the semaphore is working as expected
