### ISSUE TITLE
Nextflow kuberun login -v volume:/data gives bearer error

### ISSUE THREAD

**Issue by mikarinneoracle** [nextflow-io/nextflow#3124]
kuberun login -v volume:/data

Illegal character(s) in message header value: Bearer No resources found in default namespace.
No resources found in default namespace.

**Comment by jkmatila** [comment]
Here is the command and output:

```
$ nextflow kuberun login -v fss-pvc:/workspace
Illegal character(s) in message header value: Bearer No resources found in default namespace.
No resources found in default namespace.
```

Here is the content of `.nextflow.log`:
```
Aug-18 10:22:51.225 [main] DEBUG nextflow.cli.Launcher - $> nextflow kuberun login -v 'fss-pvc:/workspace'
Aug-18 10:22:53.549 [main] DEBUG nextflow.k8s.K8sConfig - Kubernetes workDir=/workspace/jukka/work; projectDir=/workspace/projects; volumeClaims=[fss-pvc]
Aug-18 10:22:53.624 [main] ERROR nextflow.cli.Launcher - Illegal character(s) in message header value: Bearer No resources found in default namespace.
No resources found in default namespace.
java.lang.IllegalArgumentException: Illegal character(s) in message header value: Bearer No resources found in default namespace.
No resources found in default namespace.
        at java.base/sun.net.www.protocol.http.HttpURLConnection.checkMessageHeader(HttpURLConnection.java:585)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.isExternalMessageHeaderAllowed(HttpURLConnection.java:515)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(HttpURLConnection.java:3313)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestProperty(HttpsURLConnectionImpl.java:286)
        at nextflow.k8s.client.K8sClient.makeRequestCall(K8sClient.groovy:411)
        at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:389)
        at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy)
        at nextflow.k8s.client.K8sClient.get(K8sClient.groovy:442)
        at nextflow.k8s.client.K8sClient.volumeClaimRead(K8sClient.groovy:492)
        at nextflow.k8s.K8sConfig.checkStorageAndPaths(K8sConfig.groovy:216)
        at nextflow.k8s.K8sConfig$checkStorageAndPaths$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.k8s.K8sDriverLauncher.run(K8sDriverLauncher.groovy:133)
        at nextflow.cli.CmdKubeRun.run(CmdKubeRun.groovy:88)
        at nextflow.cli.Launcher.run(Launcher.groovy:480)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

The `KUBECONFIG` environment variable is set, and the Kubernetes cluster is functional (e.g. can start pods with kubectl). The mentioned persistent volume claim is working, verified by starting a pod with that persistent volume mounted.

```
$ kubectl cluster-info
Kubernetes control plane is running at https://XXX.XXX.XXX.XXX:6443
CoreDNS is running at https://XXX.XXX.XXX.XXX:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.1
```

**Comment by jkmatila** [comment]
Reading the source code, I think I see what is the problem.

In [K8sClient.groovy:411](https://github.com/nextflow-io/nextflow/blob/v22.04.5/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L411), the code should set the bearer token to the Authorization header, but instead of a token, `config.token` in this case contains an error message "No resources found in default namespace."

This error message seems to come from [ConfigDiscovery.discoverAuthToken()](https://github.com/nextflow-io/nextflow/blob/v22.04.5/modules/nextflow/src/main/groovy/nextflow/k8s/client/ConfigDiscovery.groovy#L135), which attempts to find the auth token by running some kubectl commands, but instead just gets the error message.

But why the code calls discoverAuthToken() in the first place seems to be because it is a fall-back when it fails to correctly find the auth token based on the kubeconfig file. In [ClientConfig.groovy:90-93](https://github.com/nextflow-io/nextflow/blob/v22.04.5/modules/nextflow/src/main/groovy/nextflow/k8s/client/ClientConfig.groovy#L90-L93) it checks the `token` and `tokenFile` attributes of the user in kubeconfig, but does not check a third possibility, the `exec` attribute, which is another way of specifying how to obtain the token (by executing a command); see [here](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins).

**Comment by jawadqur** [comment]
with the newest version of kubernetes, serviceaccount secrets are not created automatically. 

Once you create your service account, we also need to create the secret like this: 

```
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: wave-sa
  annotations:
    kubernetes.io/service-account.name: "wave-sa"

```

That is because of this https://github.com/nextflow-io/nextflow/blob/v23.04.1/modules/nextflow/src/main/groovy/nextflow/k8s/client/ConfigDiscovery.groovy#L172
