### ISSUE TITLE
Execution time is incorrect for the local executor

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#313]
Please see discussion here: https://groups.google.com/forum/#!topic/nextflow/pUcxiOpIrJg

While the same error can occur when using a grid scheduler due to NFS latency, this error is likely due to setting the `time` directive and having Nextflow wait too long to measure the end-time of the process.  In the linked discussion, I have a process that runs in less than 20s with a time directive of `5m` along with many other processes, it returns an exit code of zero, but the Nextflow error still shows that it is terminated.  I have copied some of the error message below.  Note that the `.exitcode` file contains `0`, the log shows that the tool run by the process completes successfully (a Picard tool that reports execution time).

```
...
Mar-24 15:22:30.501 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Mar-24 15:22:31.108 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: local
Mar-24 15:22:31.109 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-24 15:22:31.118 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-24 15:22:31.120 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Mar-24 15:22:31.127 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=24 GB; capacity=56; pollInterval=100ms; dumpInterval=5m
Mar-24 15:22:31.134 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Mar-24 15:22:31.135 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
...
Mar-24 15:30:17.617 [Actor Thread 2] TRACE nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -c /bin/bash -ue .command.run &> /tmp/../work/d7/6090cb2bbc51d866b0b8c5b73a910b/.command.log
Mar-24 15:30:17.625 [Thread-1] TRACE nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: id: 13; name: some_task_name (some_task_tag); type: SCRIPTLET; status: 2147483647; error: null; workDirectory: /tmp/../work/13/01e580bac9dd6ad5f33698c462c8fc
  error [nextflow.exception.ProcessFailedException]: Process `some_task_name (some_task_tag)` terminated for an unknown reason -- Likely it has been terminated by the external system
Mar-24 15:30:17.628 [Actor Thread 2] INFO  nextflow.Session - [d7/6090cb] Submitted process > some_other_task (some_task_tag.2)
Mar-24 15:30:17.629 [Actor Thread 2] TRACE nextflow.processor.TaskProcessor - <some_other_task> After run
Mar-24 15:30:17.684 [Thread-1] ERROR nextflow.processor.TaskProcessor - Error executing process > 'some_task_name (some_task_tag)'

Caused by:
  Process `some_task_name (some_task_tag)` terminated for an unknown reason -- Likely it has been terminated by the external system

Command executed:

  SOME COMMAND THAT EXITS WITH ZERO STATUS

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /tmp/../work/13/01e580bac9dd6ad5f33698c462c8fc

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named: '.command.sh'
nextflow.exception.ProcessFailedException: Process `some_task_name (some_task_tag)` terminated for an unknown reason -- Likely it has been terminated by the external system
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
    at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
    at nextflow.processor.TaskProcessor.finalizeTask(TaskProcessor.groovy:1939)
    at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:438)
    at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:394)
    at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:340)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
    at nextflow.processor.TaskPollingMonitor$_start_closure6.doCall(TaskPollingMonitor.groovy:319)
    at nextflow.processor.TaskPollingMonitor$_start_closure6.call(TaskPollingMonitor.groovy)
    at groovy.lang.Closure.run(Closure.java:495)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by pditommaso** [comment]
I guess the problem is the `startTimeMillis` is set when the [object is instantiated](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/LocalExecutor.groovy#L94-94), but the job can be submitted later resulting in that inconstancy.

**Comment by pditommaso** [comment]
You can give a try to this patch by using the latest snapshot by using the following command: 

```
NXF_VER=0.24.2-SNAPSHOT nextflow run .. etc
```

**Comment by pditommaso** [comment]
version 0.24.2

**Comment by nh13** [comment]
Thank-you!

**Comment by pditommaso** [comment]
👍
