### ISSUE TITLE
SocketTimeoutException (k8sClient) 

### ISSUE THREAD

**Issue by naineshmp** [nextflow-io/nextflow#3190]
## Bug report 

K8s-Client should handle `SocketTimeoutException` like `SocketException` and `K8sResponseException`, which are retried up to 5 times. 

### Expected behavior and actual behavior

`SocketTimeoutException` is not part of the `SocketException` (below screenshot). 

![image](https://user-images.githubusercontent.com/26369197/188763001-22dbd9c9-70a1-430d-8a9b-ba1c422268f0.png)

https://github.com/nextflow-io/nextflow/blob/3dbe007f0fedb3ac7b823c8a7e5d6155e4d8ce0a/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L629

### Program output 

```log

java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at nextflow.k8s.client.K8sClient.makeRequestCall(K8sClient.groovy:391)
```
### Environment 

* Nextflow version: v20.10.0, v22.04.3, v22.04.4
* Java version: openjdk 11.0.16 2022-07-19
* Operating system: Linux

**Comment by naineshmp** [comment]
In my local load test, handling a parent IOException, improved test results. I am happy to create PR and test based on your @pditommaso @bentsherman  suggestions. 

```java
catch ( K8sResponseException | IOException e  ) {
```

**Comment by pditommaso** [comment]
I think it's fine to add `SocketTimeoutException`

**Comment by bentsherman** [comment]
`SocketException` and `SocketTimeoutException` both inherit from `IOException`, think we should just use that instead?

**Comment by pditommaso** [comment]
Nope, because IOException includes a huge range of of errors

**Comment by bentsherman** [comment]
Okay, then PR is ready #3208

**Comment by naineshmp** [comment]
Thank you! @bentsherman
