### ISSUE TITLE
Unable to download/access s3 files using glob

### ISSUE THREAD

**Issue by ryanames-eagle** [nextflow-io/nextflow#3204]
## Bug report 

Trying to access files from an Amazon s3 bucket results in `Unexpected error [UnsupportedOperationException]` error. 

### Expected behavior and actual behavior

Using `fromPath` without glob works as expected for identifying individual folders or individual files. Using `fromPath` or `fromFilePairs` using glob (`*`) to identify multiple files and folders results in the above error.

`Channel.fromPath('s3://<path>/<to>/<seqs>/input_seqs/Sample.S03/*').view()`

results in the error. Note I've tried many combinations such as `S*_R{1,2}.fastq.gz` with the same results. I've checked other issues such as [#511](https://github.com/nextflow-io/nextflow/issues/511), [#153](https://github.com/SciLifeLab/NGI-RNAseq/issues/153) and others but nothing has fit.

`Channel.fromPath('s3://<path>/<to>/<seqs>/input_seqs/Sample.S03/S03_R1.fastq.gz').view()`

works as expected.

### Steps to reproduce the problem

Apologies the s3 bucket and data is confidential so I can't provide access. I'm hoping someone can either spot the issue or has experience to spot why this isn't working.

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

```
Sep-12 14:48:16.822 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Sep-12 14:48:16.859 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.4
Sep-12 14:48:16.910 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Sep-12 14:48:16.925 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [tender_stone] DSL2 - revision: 77faea2fbe
Sep-12 14:48:16.936 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/ubuntu/.nextflow/plugins; core-plugins: nf-amazon@1.7.2,nf-azure@0.13.2,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
Sep-12 14:48:16.937 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Sep-12 14:48:16.946 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Sep-12 14:48:16.947 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Sep-12 14:48:16.950 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Sep-12 14:48:16.958 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Sep-12 14:48:17.000 [main] DEBUG nextflow.Session - Session uuid: 61173306-5376-4e2b-9f4b-4a7d09137e1d
Sep-12 14:48:17.000 [main] DEBUG nextflow.Session - Run name: tender_stone
Sep-12 14:48:17.001 [main] DEBUG nextflow.Session - Executor pool size: 64
Sep-12 14:48:17.039 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.04.4 build 5706
  Created: 19-06-2022 20:51 UTC 
  System: Linux 5.4.0-1090-azure
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.13+7-b1751.21
  Encoding: UTF-8 (UTF-8)
  CPUs: 64 - Mem: 503.9 GB (41.5 GB) - Swap: 0 (0)
Sep-12 14:48:17.059 [main] DEBUG nextflow.Session - Work-dir: /home/ubuntu/aws_testing/work [ext2/ext3]
Sep-12 14:48:17.059 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/ubuntu/aws_testing/bin
Sep-12 14:48:17.069 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Sep-12 14:48:17.078 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Sep-12 14:48:17.099 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Sep-12 14:48:17.110 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 65; maxThreads: 1000
Sep-12 14:48:17.194 [main] DEBUG nextflow.Session - Session start invoked
Sep-12 14:48:17.616 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Sep-12 14:48:17.740 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: 
Sep-12 14:48:17.741 [main] DEBUG nextflow.Session - Ignite dataflow network (1)
Sep-12 14:48:17.747 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Sep-12 14:48:17.747 [main] DEBUG nextflow.Session - Session await
Sep-12 14:48:17.747 [main] DEBUG nextflow.Session - Session await > all process finished
Sep-12 14:48:17.747 [main] DEBUG nextflow.Session - Session await > all barriers passed
Sep-12 14:48:17.759 [PathVisitor-1] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: 1.7.2
Sep-12 14:48:17.768 [PathVisitor-1] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-amazon@1.7.2' resolved
Sep-12 14:48:17.768 [PathVisitor-1] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@1.7.2'
Sep-12 14:48:17.782 [PathVisitor-1] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@1.7.2
Sep-12 14:48:17.796 [PathVisitor-1] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
Sep-12 14:48:17.796 [PathVisitor-1] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://<path>/<to>/<seqs>/input_seqs/Sample.S03/*
Sep-12 14:48:17.807 [PathVisitor-1] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Sep-12 14:48:17.816 [PathVisitor-1] DEBUG nextflow.Global - Using AWS credential defined in `default` section in file: /home/ubuntu/.aws/credentials
Sep-12 14:48:17.817 [PathVisitor-1] DEBUG nextflow.file.FileHelper - AWS S3 config details: {<details>}
Sep-12 14:48:18.138 [PathVisitor-1] DEBUG c.u.s3fs.S3FileSystemProvider - Using S3 multi-part downloader
Sep-12 14:48:18.140 [PathVisitor-1] DEBUG c.u.s3fs.ng.S3ParallelDownload - Creating S3 download thread pool: workers=10; chunkSize=10 MB; queueSize=10000; max-mem=1 GB; maxAttempts=5; maxDelay=1m 30s; pool-capacity=103
Sep-12 14:48:18.161 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: <path>/<to>/<seqs>/input_seqs/Sample.S03/; pattern: *; options: [:]
Sep-12 14:48:18.168 [PathVisitor-1] ERROR nextflow.Channel - null
java.lang.UnsupportedOperationException: null
        at com.upplication.s3fs.S3FileSystemProvider.getFileAttributeView(S3FileSystemProvider.java:697)
        at java.base/java.nio.file.Files.getFileAttributeView(Files.java:1776)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:221)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:282)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:328)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2792)
        at nextflow.file.FileHelper.visitFiles(FileHelper.groovy:801)
        at nextflow.file.PathVisitor.pathImpl(PathVisitor.groovy:163)
        at nextflow.file.PathVisitor.applyGlobPattern0(PathVisitor.groovy:131)
        at nextflow.file.PathVisitor.apply(PathVisitor.groovy:69)
        at nextflow.file.PathVisitor$_applyAsync_closure1.doCall(PathVisitor.groovy:78)
        at nextflow.file.PathVisitor$_applyAsync_closure1.call(PathVisitor.groovy)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Sep-12 14:48:18.176 [PathVisitor-1] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.UnsupportedOperationException
Sep-12 14:48:18.179 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Sep-12 14:48:18.214 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Sep-12 14:48:18.214 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-amazon@1.7.2'
Sep-12 14:48:18.215 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-amazon
Sep-12 14:48:18.216 [main] DEBUG c.u.s3fs.ng.S3ParallelDownload - Shutdown S3 downloader
Sep-12 14:48:18.216 [main] DEBUG c.u.s3fs.ng.S3ParallelDownload - Shutdown S3 downloader - done
Sep-12 14:48:18.230 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

Clearly the Channel I'm trying to create comes back as null but I don't know why - the pattern does match existing files.

### Environment 

* Nextflow version: 22.04.4
* nf-amazon: 1.7.2
* Java version: 11.0.13
* Operating system: Linux
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by pditommaso** [comment]
Can you please include the output of the `java -version` command?

**Comment by ryanames-eagle** [comment]
Thanks for the response - the output is:

```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)
```

**Comment by pditommaso** [comment]
That's the Jetbrain Java runtime causing the problem. Looks [here](https://github.com/nextflow-io/nextflow/issues/2803#issuecomment-1100950209) for more details

**Comment by ryanames-eagle** [comment]
I've updated the java JDK so that `java -version` now outputs:

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)
```

but I'm still hitting the same issue. I wonder whether it is because Groovy doesn't seem to be using the newly installed version of java. From the `nextflow.log` file:

```
Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.13+7-b1751.21
```

Is there a way to change this?

**Comment by pditommaso** [comment]
Groovy in unrelated to this. Try deleting `~/.nextflow/tmp` directly and run again the `nextflow info` command. 

If the problem persist make sure the JAVA_HOME is pointing to the new installed Jvm. If this variable is not defined, nextflow uses the Jvm returned by the command `which java`

**Comment by ryanames-eagle** [comment]
It was JAVA_HOME not being updated to the new JDK. Changing it to the right location has solved the issue and the code works as expected. Many thanks, this can be closed.
