### ISSUE TITLE
NPE is thrown when Singularity is enabled and a process uses no container

### ISSUE THREAD

**Issue by chdem** [nextflow-io/nextflow#324]
Hello !

I want to use singularity containers for some process, and no container (normal execution) for a process. When I try that, a `java.lang.NullPointerException` is throwed. 
Here, an extract of my config file : 

```
process {
	$bam_to_fastq{
		container="$params.containers_folder/bedtools/2.26/chdem_bedtools_2.26-2017-04-19-9c60dc4e29f6.img"
	}
	$hot_count_bam{
	}
}
singularity {
	enabled = true
	autoMounts = true
}
```

Here an extract of the log : 
```
Apr-20 16:20:04.772 [Actor Thread 3] ERROR nextflow.processor.TaskProcessor - Error executing process > 'hot_count_bam (vhl-500_20170420_04-19)'

Caused by:
  java.lang.NullPointerException

java.lang.NullPointerException: null
        at nextflow.container.SingularityBuilder.normalizeImageName(SingularityBuilder.groovy:161)
        at nextflow.container.SingularityBuilder$normalizeImageName$3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at nextflow.container.SingularityBuilder$normalizeImageName$3.call(Unknown Source)
        at nextflow.processor.TaskRun.getContainer(TaskRun.groovy:550)
        at nextflow.processor.TaskBean.<init>(TaskBean.groovy:125)
        at sun.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
        at nextflow.executor.BashWrapperBuilder.<init>(BashWrapperBuilder.groovy:246)
        at nextflow.executor.LocalExecutor.createBashTaskHandler(LocalExecutor.groovy:70)
        at nextflow.executor.LocalExecutor.createTaskHandler(LocalExecutor.groovy:63)
        at nextflow.executor.LocalExecutor$createTaskHandler.call(Unknown Source)
        at nextflow.processor.TaskDispatcher.submit(TaskDispatcher.groovy:143)
        at nextflow.processor.TaskDispatcher$submit$0.call(Unknown Source)
        at nextflow.processor.TaskProcessor.submitTask(TaskProcessor.groovy:1899)
        at sun.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
        at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:735)
        at sun.reflect.GeneratedMethodAccessor370.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1220)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
        at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
        at groovy.lang.Script.invokeMethod(Script.java:80)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:430)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:369)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at ScriptED06C27BC0377A185EA6C210977107C5$_run_closure1.doCall(ScriptED06C27BC0377A185EA6C210977107C5:1)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
        at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
        at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Apr-20 16:20:04.781 [Actor Thread 3] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.NullPointerException
Apr-20 16:20:04.783 [Thread-2] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Apr-20 16:20:04.783 [main] DEBUG nextflow.Session - Session await > all process finished
Apr-20 16:20:04.783 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-20 16:20:04.784 [Actor Thread 27] DEBUG nextflow.processor.TaskProcessor - <stats> After stop
Apr-20 16:20:04.784 [Actor Thread 26] DEBUG nextflow.processor.TaskProcessor - <hot_count_bam> After stop
Apr-20 16:20:06.852 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

Do I made something wrong ?

Thank you !

**Comment by pditommaso** [comment]
Released with version `0.24.3`.
