### ISSUE TITLE
New resource labels feature throws error

### ISSUE THREAD

**Issue by jchorl** [nextflow-io/nextflow#3260]
## Bug report 

I saw https://github.com/nextflow-io/nextflow/commit/5d0b7c35608a9c334e548625e91a87a6e982e6d9, which is *awesome*. Figured I'd give it a whirl.

As best I can tell, it should be in the version I'm running (22.09.7-edge):
![Screenshot 2022-10-02 at 17-51-42 Add support for label_tags (#2853) · nextflow-io_nextflow@5d0b7c3](https://user-images.githubusercontent.com/6404517/193468582-1778d67b-88d1-4b63-b1d9-8de013a6949e.png)

### Expected behavior and actual behavior

I wasn't really sure what to expect. I figured at the very least, the script would complete successfully. At best, even with local running, I could see the labels added to the processes to see that it's working, and play around with it.

### Steps to reproduce the problem

I used the nextflow hello-world just to try it out:

```
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

process sayHello {
  input: 
    val x
  output:
    stdout
  label organization: 'MyOrganization'
  script:
    """
    echo '$x world!'
    """
}

workflow {
  Channel.of('Bonjour', 'Ciao', 'Hello', 'Hola') | sayHello | view
}
```

And then running:
```
$ docker run -it --rm -v $(pwd):/work -w /work nextflow/nextflow:22.09.7-edge bash
bash-4.2# nextflow run main.nf 
N E X T F L O W  ~  version 22.09.7-edge
Launching `main.nf` [nauseous_hilbert] DSL2 - revision: 6c5ce6d262
Cannot cast object '{organization=MyOrganization}' with class 'java.util.LinkedHashMap' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(LinkedHashMap)

 -- Check script 'main.nf' at line: 17 or see '.nextflow.log' file for more details
```

### Program output 

Here's `.nextflow.log`:
```
Oct-02 17:47:20.186 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Oct-02 17:47:20.224 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.09.7-edge
Oct-02 17:47:20.237 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/.nextflow/plugins; core-plugins: nf-amazon@1.10.7,nf-azure@0.14.2,nf-codecommit@0.1.2,nf-console@1.0.4,nf-ga4gh@1.0.4,nf-google@1.4.4,nf-tower@1.5.4,nf-wave@0.4.4
Oct-02 17:47:20.243 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Oct-02 17:47:20.244 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Oct-02 17:47:20.246 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Oct-02 17:47:20.251 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Oct-02 17:47:20.262 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /work/nextflow.config
Oct-02 17:47:20.263 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /work/nextflow.config
Oct-02 17:47:20.275 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Oct-02 17:47:20.548 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Oct-02 17:47:20.557 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [nauseous_hilbert] DSL2 - revision: 6c5ce6d262
Oct-02 17:47:20.558 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Oct-02 17:47:20.558 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Oct-02 17:47:20.563 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /.nextflow/secrets/store.json
Oct-02 17:47:20.565 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@6b52dd31] - activable => nextflow.secret.LocalSecretsProvider@6b52dd31
Oct-02 17:47:20.598 [main] DEBUG nextflow.Session - Session UUID: 2307079a-bb93-4ca6-81e8-beac930a2a7d
Oct-02 17:47:20.599 [main] DEBUG nextflow.Session - Run name: nauseous_hilbert
Oct-02 17:47:20.599 [main] DEBUG nextflow.Session - Executor pool size: 16
Oct-02 17:47:20.605 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=48; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Oct-02 17:47:20.618 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.09.7-edge build 5806
  Created: 28-09-2022 09:36 UTC 
  System: Linux 5.15.0-48-generic
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 17.0.4.1+9-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 7@2d7230ad6639 [172.17.0.3]
  CPUs: 16 - Mem: 15 GB (3.6 GB) - Swap: 4 GB (4 GB)
Oct-02 17:47:20.632 [main] DEBUG nextflow.Session - Work-dir: /work/work [ext2/ext3]
Oct-02 17:47:20.632 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /work/bin
Oct-02 17:47:20.637 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Oct-02 17:47:20.642 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Oct-02 17:47:20.652 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Oct-02 17:47:20.659 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Oct-02 17:47:20.722 [main] DEBUG nextflow.Session - Session start
Oct-02 17:47:20.890 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Oct-02 17:47:20.935 [main] DEBUG nextflow.Session - Session aborted -- Cause: Cannot cast object '{organization=MyOrganization}' with class 'java.util.LinkedHashMap' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(LinkedHashMap)
Oct-02 17:47:20.944 [main] ERROR nextflow.cli.Launcher - @unknown
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '{organization=MyOrganization}' with class 'java.util.LinkedHashMap' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(LinkedHashMap)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:406)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnCollection(DefaultTypeTransformation.java:277)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:230)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:615)
	at nextflow.script.ProcessConfig.getLabels(ProcessConfig.groovy:738)
	at nextflow.script.ProcessConfig.applyConfig(ProcessConfig.groovy:393)
	at nextflow.script.ProcessDef.initialize(ProcessDef.groovy:117)
	at nextflow.script.ProcessDef.run(ProcessDef.groovy:169)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
	at nextflow.extension.ChannelEx.or(ChannelEx.groovy:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:65)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_113bc322$_runScript_closure2$_closure4.doCall(Script_113bc322:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:205)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:189)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:208)
	at nextflow.script.BaseScript.run(BaseScript.groovy:217)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:230)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:225)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:131)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:354)
	at nextflow.cli.Launcher.run(Launcher.groovy:487)
	at nextflow.cli.Launcher.main(Launcher.groovy:646)
	Suppressed: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(LinkedHashMap)
		at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1845)
		at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1615)
		at org.codehaus.groovy.runtime.InvokerHelper.invokeConstructorOf(InvokerHelper.java:1060)
		at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:382)
		... 51 common frames omitted
```

### Environment 

See nextflow.log. I was also just using the docker image, sha for reproducibility: `nextflow/nextflow@sha256:7648f8d965e7ac34e003cd2e5209e3aa97a6369bb8c07ec726fe9426be9025cc`.

### Additional context

Am I using the feature wrong?

Relatedly, but separate, github seems to render the docs wrong:
![Screenshot 2022-10-02 at 17-51-20 nextflow_process rst at master · nextflow-io_nextflow · GitHub](https://user-images.githubusercontent.com/6404517/193468759-2aaf2b86-27a6-41ff-8bb7-1010f33a2450.png)

I assume the `label` should be spread amongst different lines.

**Comment by pditommaso** [comment]
Resource labels uses the `resourceLabels` directive instead of `label`

**Comment by jchorl** [comment]
Thanks for the super quick response!! So I guess the docs need updating?

**Comment by pditommaso** [comment]
Yes, you are right
