### ISSUE TITLE
CAPSULE: IOException while creating app cache: Function not implemented

### ISSUE THREAD

**Issue by aubinthomas** [nextflow-io/nextflow#3269]
Hello, 

I'm trying to install the -all version of nextflow to be able to use it offline.
When I'm running the command 
`$ ./nextflow-22.10.0-RC1-all -Dcapsule.log=verbose info`

I have the following output that I do not understand:

```
CAPSULE: Jar: /lustre/thomasa/pipeline_chipseq/nf-core-chipseq-1.2.2/nextflow-22.10.0-RC1-all
CAPSULE: Platform: linux
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: nextflow-all_22.10.0-RC1
CAPSULE: Launching app nextflow-all_22.10.0-RC1
CAPSULE: WARNING resolve [] was empty
CAPSULE: Cache directory: /home/thomasa/.nextflow/capsule
CAPSULE: Creating temp file/dir /home/thomasa/.nextflow/capsule/apps/nextflow-all_22.10.0-RC1/.lock
CAPSULE: Locking /home/thomasa/.nextflow/capsule/apps/nextflow-all_22.10.0-RC1/.lock
CAPSULE: IOException while creating app cache: Function not implemented
java.io.IOException: Function not implemented
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1073)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
        at Capsule.lockAppCache(Capsule.java:2167)
        at Capsule.isAppCacheUpToDate1(Capsule.java:2104)
        at Capsule.buildAppCacheDir0(Capsule.java:2070)
        at Capsule.buildAppCacheDir(Capsule.java:2056)
        at Capsule.getOrCreateAppDir(Capsule.java:2004)
        at Capsule.appDir(Capsule.java:2016)
        at Capsule.simpleResolve(Capsule.java:3501)
        at Capsule.resolve00(Capsule.java:3490)
        at Capsule.resolve0(Capsule.java:3402)
        at Capsule.resolve(Capsule.java:3375)
        at Capsule.resolve00(Capsule.java:3421)
        at Capsule.resolve0(Capsule.java:3402)
        at Capsule.resolve(Capsule.java:3375)
        at Capsule.resolve(Capsule.java:3389)
        at Capsule.buildJavaProcess(Capsule.java:2228)
        at Capsule.buildProcess0(Capsule.java:1530)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.prelaunch0(Capsule.java:1494)
        at Capsule.prelaunch(Capsule.java:1487)
        at NextflowLoader.prelaunch(NextflowLoader.java:42)
        at Capsule.prepareForLaunch(Capsule.java:1339)
        at Capsule.launch(Capsule.java:1268)
        at Capsule.main0(Capsule.java:399)
        at Capsule.main(Capsule.java:379)
CAPSULE: Cleanup
CAPSULE EXCEPTION: Capsule not extracted. while processing attribute App-Class-Path: [/lustre/thomasa/pipeline_chipseq/nf-core-chipseq-1.2.2/nextflow-22.10.0-RC1-all, [nf-amazon-1.11.0.jar, nextflow-22.10.0-RC1.jar, ivy-2.3.0.jar, nf-httpfs-22.10.0-RC1.jar, jaxb-api-2.3.1.jar, aws-java-sdk-s3-1.12.129.jar, aws-java-sdk-ec2-1.12.129.jar, aws-java-sdk-batch-1.12.129.jar, aws-java-sdk-iam-1.12.129.jar, aws-java-sdk-ecs-1.12.129.jar, aws-java-sdk-logs-1.12.129.jar, aws-java-sdk-codecommit-1.12.129.jar, aws-java-sdk-sts-1.12.129.jar, nf-commons-22.10.0-RC1.jar, groovy-nio-3.0.13.jar, groovy-templates-3.0.13.jar, groovy-xml-3.0.13.jar, groovy-json-3.0.13.jar, groovy-3.0.13.jar, aws-java-sdk-kms-1.12.129.jar, aws-java-sdk-core-1.12.129.jar, httpclient-4.5.13.jar, jcl-over-slf4j-1.7.36.jar, jul-to-slf4j-1.7.36.jar, log4j-over-slf4j-1.7.36.jar, logback-classic-1.2.11.jar, logback-core-1.2.11.jar, gpars-1.2.1.jar, grengine-1.3.0.jar, commons-lang-2.6.jar, pf4j-update-2.3.0.jar, commons-codec-1.15.jar, commons-io-2.11.0.jar, jcommander-1.35.jar, kryo-2.24.0.jar, leveldb-0.12.jar, org.eclipse.jgit-6.2.0.202206071550-r.jar, mail-1.4.7.jar, activation-1.1.1.jar, snakeyaml-1.30.jar, jsoup-1.14.3.jar, jline-2.9.jar, pf4j-3.4.1.jar, failsafe-3.1.0.jar, javax.activation-api-1.2.0.jar, jmespath-java-1.12.129.jar, guava-31.1-jre.jar, slf4j-api-1.7.36.jar, multiverse-core-0.7.0.jar, jsr166y-1.7.0.jar, objenesis-2.1.jar, leveldb-api-0.12.jar, JavaEWAH-1.1.13.jar, java-semver-0.9.0.jar, ion-java-1.0.2.jar, jackson-annotations-2.12.3.jar, jackson-core-2.12.3.jar, jackson-dataformat-cbor-2.12.3.jar, jackson-databind-2.12.3.jar, joda-time-2.8.1.jar, failureaccess-1.0.1.jar, listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar, jsr305-3.0.2.jar, checker-qual-3.12.0.jar, error_prone_annotations-2.11.0.jar, j2objc-annotations-1.3.jar, gson-2.2.4.jar, httpcore-4.4.13.jar, nf-google-1.4.4.jar, google-cloud-batch-0.2.2.jar, google-cloud-logging-3.8.0.jar, google-cloud-nio-0.124.8.jar, google-cloud-storage-2.9.3.jar, google-cloud-core-2.8.0.jar, gax-2.18.7.jar, google-auth-library-oauth2-http-1.8.1.jar, google-api-services-lifesciences-v2beta-rev20210527-1.31.5.jar, google-api-services-storage-v1-rev20220705-1.32.1.jar, google-api-client-1.35.1.jar, google-oauth-client-1.34.1.jar, google-http-client-gson-1.42.2.jar, google-http-client-apache-v2-1.42.0.jar, google-http-client-1.42.2.jar, opencensus-contrib-http-util-0.31.1.jar, api-common-2.2.1.jar, protobuf-java-util-3.21.4.jar, proto-google-cloud-batch-v1alpha-0.2.2.jar, proto-google-cloud-batch-v1-0.2.2.jar, proto-google-cloud-logging-v2-0.97.0.jar, auto-value-annotations-1.9.jar, google-auth-library-credentials-1.8.1.jar, google-http-client-jackson2-1.42.0.jar, grpc-api-1.48.0.jar, opencensus-api-0.31.1.jar, grpc-context-1.48.0.jar, error_prone_annotations-2.14.0.jar, grpc-stub-1.48.0.jar, grpc-protobuf-1.48.0.jar, grpc-protobuf-lite-1.48.0.jar, javax.annotation-api-1.3.2.jar, proto-google-iam-v1-1.5.2.jar, proto-google-common-protos-2.9.2.jar, protobuf-java-3.21.4.jar, grpc-google-common-protos-2.9.2.jar, checker-qual-3.23.0.jar, checker-compat-qual-2.5.5.jar, grpc-google-iam-v1-1.5.2.jar, gax-grpc-2.18.7.jar, grpc-alts-1.48.0.jar, grpc-grpclb-1.48.0.jar, conscrypt-openjdk-uber-2.5.2.jar, grpc-auth-1.48.0.jar, grpc-netty-shaded-1.48.0.jar, perfmark-api-0.25.0.jar, grpc-core-1.48.0.jar, annotations-4.1.1.4.jar, animal-sniffer-annotations-1.21.jar, grpc-googleapis-1.48.0.jar, grpc-xds-1.48.0.jar, grpc-services-1.48.0.jar, re2j-1.6.jar, opencensus-proto-0.2.0.jar, gax-httpjson-0.103.7.jar, gson-2.9.1.jar, httpcore-4.4.15.jar, threetenbp-1.6.0.jar, bcpkix-jdk15on-1.67.jar, bcprov-jdk15on-1.67.jar, google-cloud-core-grpc-2.6.0.jar, javax.inject-1.jar, google-cloud-core-http-2.8.0.jar, google-http-client-appengine-1.42.0.jar, jackson-core-2.13.3.jar, nf-tower-1.5.5.jar, jackson-databind-2.12.5.jar, jackson-core-2.12.5.jar, jackson-annotations-2.12.5.jar, jackson-dataformat-yaml-2.12.5.jar, groovy-yaml-3.0.13.jar]]
java.lang.IllegalStateException: Capsule not extracted.
        at Capsule.appDir(Capsule.java:2025)
        at Capsule.simpleResolve(Capsule.java:3501)
        at Capsule.resolve00(Capsule.java:3490)
        at Capsule.resolve0(Capsule.java:3402)
        at Capsule.resolve(Capsule.java:3375)
        at Capsule.resolve00(Capsule.java:3421)
        at Capsule.resolve0(Capsule.java:3402)
        at Capsule.resolve(Capsule.java:3375)
        at Capsule.resolve(Capsule.java:3389)
        at Capsule.buildJavaProcess(Capsule.java:2228)
        at Capsule.buildProcess0(Capsule.java:1530)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.prelaunch0(Capsule.java:1494)
        at Capsule.prelaunch(Capsule.java:1487)
        at NextflowLoader.prelaunch(NextflowLoader.java:42)
        at Capsule.prepareForLaunch(Capsule.java:1339)
        at Capsule.launch(Capsule.java:1268)
        at Capsule.main0(Capsule.java:399)
        at Capsule.main(Capsule.java:379)
Unable to initialize nextflow environment

```

My version of Java is : 
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

Thank you in advance

**Comment by aubinthomas** [comment]
OK I think I understand. Seems it is a problem of lock on lustre filesystem. The gateway seems to be unable to create any lock, but computational nodes are. It works on computational nodes.
