### ISSUE TITLE
"java.lang.NullPointerException: Cannot get property 'XYZ' on null object" in tag

### ISSUE THREAD

**Issue by jpfeuffer** [nextflow-io/nextflow#3300]
### Expected behavior and actual behavior

From time to time, our workflow randomly fails during a resume at the following line:
https://github.com/nf-core/quantms/blob/dev/modules/local/diannconvert/main.nf#L2

We even tried lazy evaluation with: `tag "${ -> exp_design.getSimpleName() }"` which did not help.

### Steps to reproduce the problem

Try the test_dia profile with resume many times.

### Program output 

```
Oct-18 13:28:20.629 [Task submitter] INFO  nextflow.Session - [d0/084994] Submitted process > NFCORE_QUANTMS:QUANTMS:DIA:DIANNSUMMARY (1)
Oct-18 13:29:30.148 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 3642816; id: 25; name: NFCORE_QUANTMS:QUANTMS:DIA:DIANNSUMMARY (1); status: COMPLETED; exit: 0; error: -; workDir: /hps/nobackup/juan/pride/reanalysis/dia-projects/francesca/work/d0/0849944f2313aaa427143658b89ad2 started: 1666096135137; exited: 2022-10-18T12:29:19Z; ]
Oct-18 13:29:30.184 [Actor Thread 81] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.NullPointerException: Cannot get property 'Name' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:194)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at Script_83ce4d20$_runScript_closure1$_closure2.doCall(Script_83ce4d20:2)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.GString.writeTo(GString.java:192)
	at groovy.lang.GString.toString(GString.java:157)
	at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy:581)
	at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy)
	at nextflow.processor.LazyMap.resolve(TaskConfig.groovy:533)
	at nextflow.processor.LazyMap.getValue(TaskConfig.groovy:600)
	at nextflow.processor.LazyMap.get(TaskConfig.groovy:595)
	at nextflow.processor.TaskConfig.get(TaskConfig.groovy:146)
	at nextflow.processor.TaskConfig.getProperty(TaskConfig.groovy:129)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at nextflow.processor.TaskRun.getName(TaskRun.groovy:354)
	at sun.reflect.GeneratedMethodAccessor327.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:85)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetPropertySafe(AbstractCallSite.java:454)
	at nextflow.processor.TaskProcessor.resumeOrDie(TaskProcessor.groovy:1034)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.processor.TaskProcessor.handleException(TaskProcessor.groovy:947)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:94)
	at nextflow.processor.TaskProcessor.this$dist$invoke$1(TaskProcessor.groovy)
	at nextflow.processor.TaskProcessor$TaskProcessorInterceptor.methodMissing(TaskProcessor.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:953)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1347)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1270)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.processor.TaskProcessor$TaskProcessorInterceptor.onException(TaskProcessor.groovy:2343)
	at groovyx.gpars.dataflow.operator.DataflowProcessor.fireOnException(DataflowProcessor.java:331)
	at groovyx.gpars.dataflow.operator.DataflowProcessor.reportError(DataflowProcessor.java:293)
	at groovyx.gpars.dataflow.operator.DataflowProcessorActor.reportException(DataflowProcessorActor.java:125)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:122)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment 

* Nextflow version: Various
* Java version: [?]
* Operating system: Linux
* Bash version: (use the command `$SHELL --version`)

### Additional context

Probably a duplicate of the unsolved but closed issue #1342

**Comment by bentsherman** [comment]
Hi @jpfeuffer , I think I have had this problem too. It seems like certain directives are inconsistent with which variables they can access with/without a closure. I haven't figured out the underlying cause yet.

Does it work if you explicitly use a closure?
```
tag { exp_design.Name }
```

**Comment by pditommaso** [comment]
Unable to replicate
