### ISSUE TITLE
Sending email with attachment is failing when using awsbatch executor

### ISSUE THREAD

**Issue by markpanganiban** [nextflow-io/nextflow#3330]
I've tested a couple of different versions of sending email but usually still ends up having an error when using awsbatch as executor for both DSL1 and DSL2. Below is the debug and trace logs of the most recent testing using the latest nextflow version. This works when tested with Slurm.
```
Oct.-27 11:44:22.052 [Task monitor] TRACE n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] hit cache for describe job=e8eb0a57-cc3c-4795-bee5-01f3fd34e5b6
Oct.-27 11:44:22.056 [Task monitor] DEBUG c.u.s3fs.S3FileSystemProvider - S3 parallel download with direct buffer: s3://nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4/.exitcode
Oct.-27 11:44:22.415 [Task monitor] TRACE nextflow.file.FileSystemPathFactory - File system path factories: [nextflow.cloud.aws.util.S3PathFactory@695c938d]
Oct.-27 11:44:22.416 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: test (1); status: COMPLETED; exit: 0; error: -; workDir: s3://nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4]
Oct.-27 11:44:22.416 [Task monitor] TRACE nextflow.processor.TaskProcessor - finalizing process > test (1) -- id: 1; name: null; type: SCRIPTLET; exit: 0; error: null; workDir: /nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4
Oct.-27 11:44:22.423 [Task monitor] TRACE nextflow.processor.TaskProcessor - <test> collecting output: [fileoutparam<0>:null]
Oct.-27 11:44:22.444 [Task monitor] TRACE nextflow.file.FileHelper - Path matcher not defined by 'S3FileSystem' file system -- using default default strategy
Oct.-27 11:44:23.017 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > dir=; depth=0; includeDir=true; matches=false; isDir=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=.command.begin; includeFile=true; matches=false; isRegularFile=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=.command.err; includeFile=true; matches=false; isRegularFile=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=.command.log; includeFile=true; matches=false; isRegularFile=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=.command.out; includeFile=true; matches=false; isRegularFile=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=.command.run; includeFile=true; matches=false; isRegularFile=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=.command.sh; includeFile=true; matches=false; isRegularFile=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=.exitcode; includeFile=true; matches=false; isRegularFile=true
Oct.-27 11:44:23.076 [Task monitor] TRACE nextflow.file.FileHelper - visitFiles > file=test.txt; includeFile=true; matches=true; isRegularFile=true
Oct.-27 11:44:23.083 [Task monitor] TRACE nextflow.processor.TaskProcessor - Process test (1) > after removing staged inputs: [/nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4/test.txt]
Oct.-27 11:44:23.085 [Task monitor] TRACE nextflow.processor.TaskProcessor - Finalize process > test (1)
Oct.-27 11:44:23.088 [Task monitor] TRACE nextflow.processor.TaskProcessor - Process test > collecting out param: fileoutparam<0> = /nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4/test.txt
Oct.-27 11:44:23.089 [Task monitor] TRACE nextflow.processor.TaskProcessor - Process test > Binding out param: fileoutparam<0> = [/nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4/test.txt]
Oct.-27 11:44:23.089 [Task monitor] TRACE nextflow.processor.TaskProcessor - <test> Binding param fileoutparam<0> with [/nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4/test.txt]
Oct.-27 11:44:23.091 [Task monitor] DEBUG c.u.s3fs.S3FileSystemProvider - S3 parallel download with direct buffer: s3://nf-mpanganiban/scratch/a3/6dae190c870f94b43453b1b8d880f4/.command.out
Oct.-27 11:44:23.119 [Actor Thread 7] ERROR nextflow.extension.DataflowHelper - @unknown
java.lang.UnsupportedOperationException: null
    at com.upplication.s3fs.S3Path.toFile(S3Path.java:450)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
    at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:65)
```

Replication:
```
#!/usr/bin/env nextflow

nextflow.enable.dsl=2

process generate_email {
    debug true
    input:
        val(input_file_content)

    output:
        path "*_output.txt"

    script:
        """
        echo "${input_file_content}" > sample_output.txt
        """
}

workflow { 
    main: 
        channel.from("Here is some text")
        | generate_email
        | flatten
        | map { file_attachment ->
             sendMail {
                 to 'email@email.com'
                 attach "${file_attachment}"
                 subject "TEST EMAIL"
                 """
                 TEST CONTENT
                 """
             }
        }
}
```

**Comment by pditommaso** [comment]
please include the full .nextflow.log file

**Comment by pditommaso** [comment]
and @robsyme knows the cause of this

**Comment by markpanganiban** [comment]
Full Logs: [nextflow_s3.log](https://github.com/nextflow-io/nextflow/files/9905672/nextflow_s3.log)

**Comment by pditommaso** [comment]
The problem is that the attachment file path is wrapped into a string 

```
     attach "${file_attachment}"
```

it should be 

```
   attach file_attachment
```

Files are not strings!
