### ISSUE TITLE
Regression: Unable to save execution report over existing file

### ISSUE THREAD

**Issue by ScottNortonPhD** [nextflow-io/nextflow#3334]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

This concerns the option `-with-report path/to/report.html`. If the target file already exists, the previous behavior was to first rename the old file to `path/to/report.html.1` (with that number incrementing as needed). As of 22.10.0 (and still the case in 22.10.1), this throws an internal error, which is handled as a warning to the CLI (`WARN: Failed to render execution report -- see the log file for details`).

### Steps to reproduce the problem

```bash
touch hello.html
nextflow run hello -with-report hello.html
```

### Program output 
```
N E X T F L O W  ~  version 22.10.1
Launching `https://github.com/nextflow-io/hello` [romantic_morse] DSL2 - revision: 4eab81bd42 [master]
executor >  local (4)
[b8/1b7903] process > sayHello (3) [100%] 4 of 4 ✔
Ciao world!

Bonjour world!

Hola world!

Hello world!

WARN: Failed to render execution report -- see the log file for details
```

Relevant portion of the log, with redactions:

```
Oct-31 17:18:06.980 [main] WARN  nextflow.trace.ReportObserver - Failed to render execution report -- see the log file for details
nextflow.exception.AbortOperationException: Report file already exists: [...]/hello.html
        at nextflow.trace.TraceHelper.newFileWriter(TraceHelper.groovy:66)
        at nextflow.trace.ReportObserver.renderHtml(ReportObserver.groovy:283)
        at nextflow.trace.ReportObserver.onFlowComplete(ReportObserver.groovy:140)
        at nextflow.Session.notifyFlowComplete(Session.groovy:1075)
        at nextflow.Session.shutdown0(Session.groovy:702)
        at nextflow.Session.destroy(Session.groovy:644)
        at nextflow.script.ScriptRunner.shutdown(ScriptRunner.groovy:240)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:135)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:354)
        at nextflow.cli.Launcher.run(Launcher.groovy:487)
        at nextflow.cli.Launcher.main(Launcher.groovy:646)
Caused by: java.nio.file.FileAlreadyExistsException: [...]/hello.html
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2920)
        at nextflow.trace.TraceHelper.newFileWriter(TraceHelper.groovy:63)
        ... 10 common frames omitted
```

### Environment 

* Nextflow version: 22.10.1
* Java version: openjdk version "11.0.5-internal" 2022-04-19
* Operating system: CentOS Enterprise 7 x86_64
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
Hi @ScottNortonPhD , we removed the rolling filenames in 22.10.0. The default report name now includes a pseudo-timestamp to prevent name collisions. If you want to keep the same report name, you can enable the `report.overwrite` option in your config file.

https://www.nextflow.io/docs/latest/config.html#scope-report

**Comment by ScottNortonPhD** [comment]
Thanks Ben. Is it possible for the report filename to be dynamic, i.e.
```
report.file = "${params.output}/report.html"
```

**Comment by bentsherman** [comment]
Yes, you can still use dynamic strings. The nf-core pipelines use dynamic filenames to add a timestamp to each report like so:

https://github.com/nf-core/rnaseq/blob/e049f51f0214b2aef7624b9dd496a404a7c34d14/nextflow.config#L229-L232
