### ISSUE TITLE
Specifying `executor 'local'` on process running on AWS batch throws exception

### ISSUE THREAD

**Issue by robsyme** [nextflow-io/nextflow#3339]
### Expected behavior and actual behavior

For very small tasks, it is very wasteful to spin up a new instance and VM. I would expect that we can run small processes on the head node. This would also allow us to send emails from processes rather than relying on the `sendMail` block, which might make attaching files from S3 easier. 

In summary, I would expect this minimal workflow to be runnable on AWS:

```groovy

process MakeTest {
    executor 'local'

    output:
    path("*.txt")

    "echo test > out.txt"
}

workflow {
    MakeTest() | view
}
```

... but this throws an exception when getting the secrets

```
Nov-01 22:17:58.489 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'MakeTest'

Caused by:
  java.lang.UnsupportedOperationException

java.lang.UnsupportedOperationException: null
	at nextflow.cloud.aws.secrets.AwsSecretsProvider.getSecretsEnv(AwsSecretsProvider.groovy:182)
	at nextflow.executor.BashWrapperBuilder.getSecretsEnv(BashWrapperBuilder.groovy:294)
	at nextflow.executor.BashWrapperBuilder.makeBinding(BashWrapperBuilder.groovy:253)
	at nextflow.executor.BashWrapperBuilder.buildNew0(BashWrapperBuilder.groovy:308)
...
```

### Steps to reproduce the problem

Repository with example workflow available at https://github.com/robsyme/nf-test/tree/email-test-2356

### Program output 

Relevant parts of `nextflow.log` are:

```
Nov-01 22:17:58.297 [main] INFO  io.seqera.tower.plugin.TowerClient - Monitor the execution with Nextflow Tower using this URL: https://tower.nf/orgs/seqeralabs/workspaces/testing/watch/1Bd5DX1kEezp1X
Nov-01 22:17:58.297 [main] DEBUG nextflow.Session - Igniting dataflow network (1)
Nov-01 22:17:58.297 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > MakeTest
Nov-01 22:17:58.298 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Nov-01 22:17:58.298 [main] DEBUG nextflow.Session - Session await
Nov-01 22:17:58.489 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'MakeTest'

Caused by:
  java.lang.UnsupportedOperationException

java.lang.UnsupportedOperationException: null
	at nextflow.cloud.aws.secrets.AwsSecretsProvider.getSecretsEnv(AwsSecretsProvider.groovy:182)
	at nextflow.executor.BashWrapperBuilder.getSecretsEnv(BashWrapperBuilder.groovy:294)
	at nextflow.executor.BashWrapperBuilder.makeBinding(BashWrapperBuilder.groovy:253)
	at nextflow.executor.BashWrapperBuilder.buildNew0(BashWrapperBuilder.groovy:308)
	at nextflow.executor.BashWrapperBuilder.buildNew0(BashWrapperBuilder.groovy:153)
	at nextflow.executor.BashWrapperBuilder.build(BashWrapperBuilder.groovy:323)
	at nextflow.executor.local.LocalTaskHandler.buildTaskWrapper(LocalTaskHandler.groovy:127)
	at nextflow.executor.local.LocalTaskHandler.submit(LocalTaskHandler.groovy:95)
	at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
	at nextflow.processor.LocalPollingMonitor.submit(LocalPollingMonitor.groovy:193)
	at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:562)
	at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.lang.Thread.run(Thread.java:833)
Nov-01 22:17:58.492 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.UnsupportedOperationException
Nov-01 22:17:58.499 [Task submitter] DEBUG nextflow.Session - The following nodes are still active:
  [operator] view

```
### Environment 

* Nextflow version: 22.10.0
* Operating system: Linux

**Comment by pditommaso** [comment]
Please include the `.nextflow.log` file

**Comment by robsyme** [comment]
Log file attached. Thanks Paolo

This is related to the recent discussions about the inability to attach S3 files to email. My thinking was that if we can send email from a process, the files would be staged and available. The catch is that this would have to happen from the head node rather than a batch job (so that email settings are available).

[nf-1Bd5DX1kEezp1X.log](https://github.com/nextflow-io/nextflow/files/9920757/nf-1Bd5DX1kEezp1X.log)

**Comment by pditommaso** [comment]
Bit confused by this. In principle the `AwsSecretsProvider` should only be activated when AWS Batch job-specific variables exist in the launch environment. 
 
Are you running this into a plain Ec2 instance or AWS Batch launched env?

**Comment by robsyme** [comment]
The task is launched as an AWS batch job (both head node and task are in batch).

For the Seqera people, you can see an example failing run here: https://tower.nf/orgs/seqeralabs/workspaces/testing/watch/1Bd5DX1kEezp1X

**Comment by pditommaso** [comment]
Well, essentially the `AwsSecretsProvider` is designed to work with the batch executor. Therefore this is expected

**Comment by pditommaso** [comment]
Tho you would still claim that hybrid execution with local executor should work

**Comment by robsyme** [comment]
I would suggest that it would be great if hybrid execution with the local executor did work. Though if this is a fundamental incompatibility, I understand.

**Comment by bentsherman** [comment]
Think this was fixed by https://github.com/nextflow-io/nextflow/commit/850bc3d9e7f55d5c4f023fbb72f4ef7c69533bfc
