### ISSUE TITLE
Failures in pipelines due to Kube API rotation in EKS

### ISSUE THREAD

**Issue by kanor1306** [nextflow-io/nextflow#3576]
### Expected behavior and actual behavior

The K8sClient does not retry [when the Kube API returns a 401](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L633). It only retries when the error is 500. This used to be fine, but since some time ago it seems that during Kube API rotation in EKS [sometimes it returns 401](https://github.com/aws/containers-roadmap/issues/1810).

### Program output 
```
Caused by:
Request GET /api/v1/namespaces/workflows/pods/nf-16da17fbdd99af1d809f8fce8109432d/status returned an error code=401

{
"kind": "Status",
"apiVersion": "v1",
"metadata": {

},
"status": "Failure",
"message": "Unauthorized",
"reason": "Unauthorized",
"code": 401
}


nextflow.k8s.client.K8sResponseException: Request GET /api/v1/namespaces/workflows/pods/nf-16da17fbdd99af1d809f8fce8109432d/status returned an error code=401

{
"kind": "Status",
"apiVersion": "v1",
"metadata": {

},
"status": "Failure",
"message": "Unauthorized",
"reason": "Unauthorized",
"code": 401
}

at nextflow.k8s.client.K8sClient.makeRequestCall(K8sClient.groovy:670)
at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:626)
at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy)
at nextflow.k8s.client.K8sClient.get(K8sClient.groovy:679)
at nextflow.k8s.client.K8sClient.podStatus(K8sClient.groovy:317)
at nextflow.k8s.client.K8sClient.podStatus0(K8sClient.groovy:328)
at nextflow.k8s.client.K8sClient.podState(K8sClient.groovy:461)
at nextflow.k8s.K8sTaskHandler.getState(K8sTaskHandler.groovy:323)
at nextflow.k8s.K8sTaskHandler.checkIfCompleted(K8sTaskHandler.groovy:393)
at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:610)
at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:534)
at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:409)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
at groovy.lang.Closure.run(Closure.java:493)
at java.base/java.lang.Thread.run(Thread.java:833)
```

### Environment 

* Nextflow version: 22.10.4 

### Additional context

Screenshot of the metrics of the Kube API, that shows it being rotated at the time of the error.  
<img width="554" alt="kube-api-rotation" src="https://user-images.githubusercontent.com/1013912/214809956-1313bc8b-15a5-4b2c-ad71-b452b00f1f01.png">

**Comment by bentsherman** [comment]
We could add some wiring to backoff/retry API requests that fail due to cert rotation, but we need a way to detect that cert rotation is the cause. Retrying on any 401 response seems too broad. Is there any other information we can use to detect the cert rotation?

**Comment by pditommaso** [comment]
401 means Unauthorised http request, why it should retry?

**Comment by kanor1306** [comment]
> We could add some wiring to backoff/retry API requests that fail due to cert rotation, but we need a way to detect that cert rotation is the cause. Retrying on any 401 response seems too broad. Is there any other information we can use to detect the cert rotation?

I don't think there is a simple way for Nextflow to know that there are new kube-api IPs, unless it somehow could keep track of the available ones (which I don't even know if it is possible, and it will add a lot of complexity). Even in that case, the error comes from the old kube-api, so not a simple solution, and does not sound like something Nextflow should really have to take care of.

> 401 means Unauthorised http request, why it should retry?

In a normal situation I would say it shouldn't, but this is just what happens in EKS when Amazon rotates the kube-apis, effectively breaking most jobs running in that moment in said cluster. Of course I would like for Amazon to change this behavior, as it is not nice seeing jobs that have been running for a couple days break due to this, but seeing that the issue is opened since August, does not look like it will happen in the near future. Then I thought that I would have a better chance of having a workaround in Nextflow by maing some retries in other cases than 500. 

Of course I understand if this is something that you don't want to address as it is not really Nextflow's fault, but I wanted to ask here before having to maintain a fork with a workaround.

**Comment by bentsherman** [comment]
I understand. I don't think there is much we can do. Seems like EKS either needs to change the error code or provide a more detailed error message that Nextflow can use to target this error.

**Comment by kanor1306** [comment]
Fair enough. I will close this and reopen in the future if EKS does something that makes sense to be implemented in NF
