### ISSUE TITLE
GroovyRuntimeException during foreign file copy process

### ISSUE THREAD

**Issue by amacbride** [nextflow-io/nextflow#360]
It looks like the underlying process threw a SocketException, but the NF runtime had an (additional) error when that happened:

```
Caused by:
  Could not find matching constructor for: nextflow.exception.ProcessStageException(org.codehaus.groovy.runtime.GStringImpl, java.net.SocketException)

groovy.lang.GroovyRuntimeException: Could not find matching constructor for: nextflow.exception.ProcessStageException(org.codehaus.groovy.runtime.GStringImpl, java.net.SocketException)
at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1737)
        at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1537)
        at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:49)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
        at nextflow.processor.TaskProcessor.normalizeInputToFile(TaskProcessor.groovy:1573)

...

May-31 03:40:19.915 [Actor Thread 27] DEBUG nextflow.Session - Session aborted -- Cause: Could not find matching constructor for: nextflow.exception.ProcessStageException(org.codehaus.groovy.runtime.GStringImpl, java.net.SocketException)

```

**Comment by pditommaso** [comment]
Oops, you are right!
