### ISSUE TITLE
NextFlow does not work with GCP buckets that include underscores, "Execution aborted due to an unexpected error"

### ISSUE THREAD

**Issue by BeyondTheProof** [nextflow-io/nextflow#3619]
### Expected behavior and actual behavior

`nextflow run` fails when computing on GCP whenever working in a bucket containing underscores, returns cryptic message. 

### Steps to reproduce the problem

Test case provided in another ticket: https://github.com/nextflow-io/nextflow/issues/1069 and https://github.com/nextflow-io/nextflow/issues/1527

### Program output 

```
jupyter@instance-name-1:~/pipe/twas/test_local$ nextflow run ~/twas/nf_pipeline/main.nf  -c ~/twas/nf_pipeline/modules/gcs_nextflow.config
N E X T F L O W  ~  version 22.10.6                                                                                                                               
Launching `/home/jupyter/project/new-targets/twas/nf_pipeline/main.nf` [modest_kimura] DSL2 - revision: f8d1c49809
executor >  google-batch (1)
[e2/0b8ff1] process > CREATE_INPUT_FILES (1) [100%] 1 of 1 ✔
**Execution aborted due to an unexpected error**



jupyter@instance-name-1:~/pipe/twas/test_local$
```

Here's the .nextflow.log file:
```
-9991-f61597599563; work-dir=gs://comp_genetics/pipe/e2/0b8ff17440aec326a74501729dd590
Feb-07 17:14:31.019 [Task submitter] INFO  nextflow.Session - [e2/0b8ff1] Submitted process > CREATE_INPUT_FILES (1)
Feb-07 17:19:38.752 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor google-batch > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: CREATE_INPUT_FILES (1); status: RUNNING; exit: -; error: -; workDir: gs://comp_genetics/pipe/e2/0b8ff17440aec326a74501729dd590]
Feb-07 17:19:58.813 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Terminated job=nf-e20b8ff1-1675790069773; state=SUCCEEDED
Feb-07 17:19:58.942 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: CREATE_INPUT_FILES (1); status: COMPLETED; exi
t: 0; error: -; workDir: gs://comp_genetics/pipe/e2/0b8ff17440aec326a74501729dd590]
Feb-07 17:19:59.039 [Task monitor] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.AssertionError: java.net.URISyntaxException: Illegal character in hostname at index 9: gs://comp_genetics/pipe/e2/0b8ff17440aec326a74501729dd590
        at com.google.cloud.storage.contrib.nio.CloudStoragePath.toUri(CloudStoragePath.java:374)
        at com.google.cloud.storage.contrib.nio.CloudStoragePseudoDirectoryAttributes.<init>(CloudStoragePseudoDirectoryAttributes.java:31)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.readAttributes(CloudStorageFileSystemProvider.java:808)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.nio.file.FileTreeWalker.getAttributes
...
       at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
        at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:833)
**Caused by: java.net.URISyntaxException: Illegal character in hostname at index 9: gs://comp_genetics/pipe/e2/0b8ff17440aec326a74501729dd590**
        at java.base/java.net.URI$Parser.fail(URI.java:2974)
        at java.base/java.net.URI$Parser.parseHostname(URI.java:3509)
        at java.base/java.net.URI$Parser.parseServer(URI.java:3358)
        at java.base/java.net.URI$Parser.parseAuthority(URI.java:3277)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3219)
        at java.base/java.net.URI$Parser.parse(URI.java:3175)
        at java.base/java.net.URI.<init>(URI.java:708)
        at java.base/java.net.URI.<init>(URI.java:809)
        at com.google.cloud.storage.contrib.nio.CloudStoragePath.toUri(CloudStoragePath.java:372)
        ... 75 common frames omitted
Feb-07 17:19:59.053 [main] DEBUG nextflow.Session - Session await > all processes finished
Feb-07 17:19:59.088 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: java.net.URISyntaxException: Illegal character in hostname at index 9: gs://comp_genetics/pipe/e2/0b8ff17440aec326a74501729dd590
Feb-07 17:19:59.169 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-07 17:19:59.280 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=1; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=8m 1s; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=4; peakMemory=32 GB; ]
Feb-07 17:19:59.291 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Feb-07 17:19:59.291 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-google@1.4.5'
Feb-07 17:19:59.291 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-google
Feb-07 17:19:59.304 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow version: 22.10.6
* Java version: openjdk version "17.0.5" 2022-10-18
  OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
  OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)
* Operating system: Linux
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by bentsherman** [comment]
I believe this is the expected behavior, as underscores are not allowed in the name of a Google Storage bucket:

https://cloud.google.com/storage/docs/buckets

**Comment by bentsherman** [comment]
Hold on, I misread those docs -- underscores are allowed in the bucket name.

> Bucket names can only contain lowercase letters, numeric characters, dashes (-), underscores (_), and dots (.). Spaces are not allowed. Names containing dots require [verification](https://cloud.google.com/storage/docs/domain-name-verification).

**Comment by bentsherman** [comment]
Apologies @BeyondTheProof for the multiple emails. At a quick glance, I don't think there is much that Nextflow can do to alleviate this issue, because it is internal to the Google Java SDK. Looking at the related tickets you linked, the support for underscores seems to be spotty in general, such that it's probably a good idea to avoid them altogether, not just with Nextflow but with any of your tools that interact with Google Cloud Storage.

**Comment by pditommaso** [comment]
Indeed. This is a limitation of the Google SDK. More details [here](https://github.com/nextflow-io/nextflow/issues/1527)
