### ISSUE TITLE
Clean up option fail when using AWS Batch (and likely other clouds)

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3645]
## Bug report 

Nextflow fails to perform the pipeline work directory [cleanup](https://www.nextflow.io/docs/latest/config.html?highlight=cleanup#miscellaneous) when using AWS Batch and other cloud providers 

The following error is reported 

```
Feb-14 18:55:04.981 [main] WARN  nextflow.file.FileHelper - Unable to start plugin 'nf-amazon' required by s3://nextflow-ci/work/79/17395af5457010376510e5808a2881
java.lang.NullPointerException: Cannot invoke "nextflow.plugin.CustomPluginManager.getPlugin(String)" because "this.manager" is null
	at nextflow.plugin.PluginsFacade.isStarted(PluginsFacade.groovy:338)
	at nextflow.plugin.PluginsFacade.startIfMissing(PluginsFacade.groovy:432)
	at nextflow.plugin.Plugins.startIfMissing(Plugins.groovy:91)
	at nextflow.file.FileHelper.autoStartMissingPlugin(FileHelper.groovy:288)
	at nextflow.file.FileHelper.asPath(FileHelper.groovy:268)

```

Complete log file is attached 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/10735602/nextflow.log)

**Comment by BrunoGrandePhD** [comment]
@bentsherman Thanks for tackling this!
