### ISSUE TITLE
NF occasionally crashing with "Read timed out"

### ISSUE THREAD

**Issue by BeyondTheProof** [nextflow-io/nextflow#3689]
### Expected behavior and actual behavior

Nextflow should not crash 

### Steps to reproduce the problem

Sporadic -- happens when uploading "large" files, evidently, although unclear from traceback. In practice, was uploading files << 1 GB

### Program output 

```
Feb-25 04:13:09.153 [Task submitter] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=CREATE_INPUT_FILES (607); work-dir=gs://rome-repeat-genetics/pipe/work/3d/82748780240d98922c790e4581c62b
  error [com.google.cloud.storage.StorageException]: Read timed out
Feb-25 04:13:09.162 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'CREATE_INPUT_FILES (607)'

Caused by:
  Read timed out

com.google.cloud.storage.StorageException: Read timed out
        at com.google.cloud.storage.StorageException.translate(StorageException.java:118)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:287)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.writeWithResponse(HttpStorageRpc.java:959)
        at com.google.cloud.storage.BlobWriteChannel.transmitChunk(BlobWriteChannel.java:67)
        at com.google.cloud.storage.BlobWriteChannel.access$1400(BlobWriteChannel.java:34)
        at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:252)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
        at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:183)
        at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:151)
        at com.google.cloud.storage.contrib.nio.CloudStorageWriteChannel.close(CloudStorageWriteChannel.java:55)
        at java.base/java.nio.channels.Channels$1.close(Channels.java:176)
        at java.base/java.nio.file.Files.write(Files.java:3520)
        at nextflow.executor.BashWrapperBuilder.write0(BashWrapperBuilder.groovy:340)
        at nextflow.executor.BashWrapperBuilder.build(BashWrapperBuilder.groovy:326)
        at nextflow.cloud.google.batch.GoogleBatchTaskHandler.submit(GoogleBatchTaskHandler.groovy:102)
        at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:562)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:824)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:36)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:152)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.writeWithResponse(HttpStorageRpc.java:932)
        ... 32 common frames omitted
Feb-25 04:13:09.166 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: Read timed out
```

### Environment 

* Nextflow version: 23.01.0-edge build 5834
* Java version: 
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)
* Operating system: Ubuntu
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

GCS occasionally throws error when uploading large files (see thread here: https://github.com/googleapis/java-storage/issues/43). Thread provides some guidance on how to resolve issue. Would be great if Nextflow provided some robustness to this!

**Comment by BeyondTheProof** [comment]
Update: Resumed the workflow with `-resume`, and the workflow finished. Btw, I had `errorStrategy = 'retry'` and `maxRetries = 3`, so it's doubtful that it was a single error that killed the workflow.

**Comment by pditommaso** [comment]
What version of nextflow are you using ?

**Comment by pditommaso** [comment]
This looks like a failure on Google side, however I've added a retry strategy that should help to recover this error condition. See 1e38274a. 

@bentsherman I think this help also the head job error you were reporting.
