### ISSUE TITLE
nextflow run failed, Unparseable date: "yyyy-MM-dd HH:mm:ss"

### ISSUE THREAD

**Issue by DescartesM** [nextflow-io/nextflow#3698]
## Bug report 

I'm not sure if it's a bug, but it's really strange...

### Expected behavior and actual behavior

**Expected behavior：** 
nextflow run  xxx.nf successfully;

**Actual behavior**
The following error message is obtained.
![image](https://user-images.githubusercontent.com/6761716/222060206-1394b48a-a898-46c8-add8-6058b99cb486.png)
And I also check the .nextflow.log for more detail, it seems like the data format error, there are so many <0x00>
![image](https://user-images.githubusercontent.com/6761716/222060780-90e5cf93-8cab-4014-a29d-51fe82235367.png)
Error stack information：
```
	at java.base/java.text.DateFormat.parse(Unknown Source)
	at java_text_DateFormat$parse$1.call(Unknown Source)
	at nextflow.util.HistoryFile$Record.parse(HistoryFile.groovy:400)
	at nextflow.util.HistoryFile$Record$parse.call(Unknown Source)
	at nextflow.util.HistoryFile$_getByName_closure5.doCall(HistoryFile.groovy:176)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findResult(DefaultGroovyMethods.java:4601)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findResult(DefaultGroovyMethods.java:4642)
	at org.codehaus.groovy.runtime.dgm$275.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.util.HistoryFile.getByName(HistoryFile.groovy:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.util.HistoryFile$_checkExistsByName_closure4.doCall(HistoryFile.groovy:155)
	at nextflow.util.HistoryFile$_checkExistsByName_closure4.doCall(HistoryFile.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at nextflow.util.HistoryFile.withFileLock(HistoryFile.groovy:447)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.util.HistoryFile.checkExistsByName(HistoryFile.groovy:155)
	at nextflow.cli.CmdRun.checkRunName(CmdRun.groovy:434)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:294)
	at nextflow.cli.Launcher.run(Launcher.groovy:487)
	at nextflow.cli.Launcher.main(Launcher.groovy:646)
```

And then I find this issue:https://github.com/nextflow-io/nextflow/issues/962
 and check the locale, it seems also ok for me;
![image](https://user-images.githubusercontent.com/6761716/222061113-a6509f62-b316-4118-a579-abf3b0660bf7.png)

### Steps to reproduce the problem

At present, I have not successfully reappeared, but I have a guess；
The time "2023-03-01 10:50:46" is very close to my container restart time "2023/03/01 10:49:11", and I find there and many NULL in the .nextflow/history
![image](https://user-images.githubusercontent.com/6761716/222063122-b9e351a7-8ada-48f0-b46e-1fffebe92ffd.png)
![image](https://user-images.githubusercontent.com/6761716/222063163-7eb8bf32-eab9-4565-bec3-2915a61258e5.png)

**I try to remove these NULL manually, and then the problem has fixed temporarily.But I have the following questions**
1. Why are there so many NULL characters in the history file? Is it related to my container restart?
2. Is there any way to automatically recover? Currently, the NULL of this line will block the delivery of subsequent jobs.
 

### Program output 

I put the nextflow.log in Actual behavior chapter；
### Environment 

* Nextflow version: 22.10.06
* Java version: Java11
* Operating system: Linux, CentOS7
* Bash version: GNU bash, version 5.0.17(1)-release

**Comment by pditommaso** [comment]
It looks like the history file is corrupted. I'm unable to replicate it. Closing this issue. Feel free to re-open if you can provide a replicable test case
