### ISSUE TITLE
Missing information in trace.txt

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#371]
(originally posted at https://groups.google.com/forum/#!topic/nextflow/TPnw5Gptheo)

I am running a Nextflow pipeline locally using Docker containers.
Overall, the pipeline runs without problems, however, the trace.txt file lacks information about used system resources and whether a process finished or not.
Here is an excerpt from the trace.txt file:
```
task_id	hash	native_id	name	status	exit	submit	duration	realtime	%cpu	rss	vmem	rchar	wchar
56	7b/bb194b	2818	tool1 (s1)	COMPLETED	0	2017-06-12 10:54:38.235	21m 24s	21m 20s	705.0%	8 GB	16.9 GB	22.9 GB	11.1 GB
52	79/a5b94d	27342	tool2 (s2)	COMPLETED	0	2017-06-12 10:45:01.081	32m 10s	32m 10s	-	-	-	-	-
57	88/6d0068	2866	tool2 (s1)	COMPLETED	0	2017-06-12 10:54:38.402	24m 22s	24m 22s	-	-	-	-	-
1	7d/c18403	26764	tool3 (s3)	RUNNING	-	2017-06-12 09:54:55.906	-	-	-	-	-	-	-
3	a6/8f9f09	12686	tool4 (s3)	RUNNING	-	2017-06-12 09:50:23.970	-	-	-	-	-	-	-
```

Potentially related to this, there are many error messages in the .nextflow.log file. All look like this:

```
Jun-12 09:51:40.245 [Thread-2] DEBUG nextflow.Session - For input string: "3673366590"
java.lang.NumberFormatException: For input string: "3673366590"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.codehaus.groovy.runtime.StringGroovyMethods.toInteger(StringGroovyMethods.java:3312)
	at nextflow.trace.TraceRecord.parseTraceFile(TraceRecord.groovy:402)
	at nextflow.trace.TraceRecord$parseTraceFile.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nextflow.processor.TaskHandler.getTraceRecord(TaskHandler.groovy:179)
	at nextflow.executor.LocalTaskHandler.super$2$getTraceRecord(LocalExecutor.groovy)
	at sun.reflect.GeneratedMethodAccessor281.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:152)
	at nextflow.executor.LocalTaskHandler.getTraceRecord(LocalExecutor.groovy:250)
	at nextflow.trace.TraceFileObserver.onProcessComplete(TraceFileObserver.groovy:258)
	at nextflow.Session.notifyTaskComplete(Session.groovy:689)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:443)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:394)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:340)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
	at nextflow.processor.TaskPollingMonitor$_start_closure6.doCall(TaskPollingMonitor.groovy:319)
	at nextflow.processor.TaskPollingMonitor$_start_closure6.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.lang.Thread.run(Thread.java:745)
```

Thanks for looking into this!

**Comment by pditommaso** [comment]
Oops, it looks `Integer` is too small

**Comment by pditommaso** [comment]
But something weird is happening, because that number is supposed to be the mem or cpu usage percentage. So it should be in the range 0..100. 

Could you check in the work dir for one of the task for which that values are not reported (eg `79/a5b94d`) and upload here the file `.command.trace`  ?

**Comment by zichner** [comment]
Here is the trace file belonging to `79/a5b94d`:
[.command.trace](https://github.com/nextflow-io/nextflow/files/1068108/command.trace.txt)

**Comment by pditommaso** [comment]
Any chance to find the `.command.trace` containing the number `3673366590` ?

**Comment by zichner** [comment]
Here you go:
[.command.trace](https://github.com/nextflow-io/nextflow/files/1068243/command.trace.txt)

**Comment by pditommaso** [comment]
That number should not be there. Could please copy here the output of the commands `ps -o pid=,pcpu=,pmem=` and `ps -o pid= -o pcpu= -o pmem=` ?

**Comment by zichner** [comment]
```
> ps -o pid=,pcpu=,pmem=
,pcpu=,pmem=
        2719
       10974
```

```
> ps -o pid= -o pcpu= -o pmem=
 2735  0.0  0.0
10974  0.0  0.0
```

**Comment by pditommaso** [comment]
Could you change into the directory where you found the file with that number, execute the command below and report the output (it may be verbose)

```
NXF_DEBUG=3 bash .command.run
```

This will re-execute the task with debug information.

**Comment by zichner** [comment]
If found the problem:
Some of the Docker containers I use are based on the images `Alpine` and `r-base`. And these either don't have any `ps` command or not the usual one. This can be fixed by `apk --update add procps` in case of the `Alpine` container.

The mistake I did before, was to test the `ps` command on the host rather than inside Docker. Sorry about that.

Thanks for your support and pointing into the right direction!

**Comment by pditommaso** [comment]
gotcha!
