### ISSUE TITLE
Unhelpful error message when container is not provided on GCP

### ISSUE THREAD

**Issue by Puumanamana** [nextflow-io/nextflow#3746]
## Bug report 

Hello,

When running Nextflow on GCP (might be the same for AWS), if the container is not provided, the error message is the following:
```
Caused by:
   java.lang.NullPointerException
``` 
Would it be possible to check that before running and throw a dedicated error message?

### Expected behavior and actual behavior

Error message to let the user know he needs to provide a container image.

### Steps to reproduce the problem

**main.nf:**
```nextflow
nextflow.enable.dsl = 2

process P {
    output:
    path "*"

    script:
    """
    echo finished > log1.out
    """
}

workflow {
    P()
}
```

**nextflow.config:**
```
workDir = "gs://..."

google {
    project = "..."
    region = "us-central1"
    batch {
        bootDiskSize = 50.GB
        serviceAccountEmail = "..."
        spot = true
    }
}

process {
    executor = "google-batch"
}
```

### Program output 

```
Mar-13 12:52:42.684 [Task submitter] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=P; work-dir=gs://nf-tower-public/scratch/af/88620d34a727cbdf8a116af9413e12
  error [java.lang.NullPointerException]: java.lang.NullPointerException
Mar-13 12:52:42.695 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'P'

Caused by:
  java.lang.NullPointerException

java.lang.NullPointerException: null
        at com.google.cloud.batch.v1.Runnable$Container$Builder.setImageUri(Runnable.java:1430)
        at nextflow.cloud.google.batch.GoogleBatchTaskHandler.newSubmitRequest(GoogleBatchTaskHandler.groovy:163)
        at nextflow.cloud.google.batch.GoogleBatchTaskHandler.submit(GoogleBatchTaskHandler.groovy:132)
        at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:562)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:833)
Mar-13 12:52:42.701 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.NullPointerException
```

### Environment 

* Nextflow version: 23.02.1-edge build 5845
* Java version: 
```bash
$ java -version
openjdk version "17.0.3-internal" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17.0.3-internal+0-adhoc..src, mixed mode, sharing)
```
* Operating system: [macOS, Linux, etc]
```bash
$ uname -a
Linux nf-tower-main 5.15.0-1022-gcp #29~20.04.1-Ubuntu SMP Sat Oct 29 18:17:56 UTC 2022 x86_64 GNU/Linux
```
* Bash version: (use the command `$SHELL --version`): zsh 5.8 (x86_64-ubuntu-linux-gnu)

**Comment by pditommaso** [comment]
Good point. Thanks for reporting we'll look into it
