### ISSUE TITLE
ConcurrentModificationException when using `publishDir`

### ISSUE THREAD

**Issue by robsyme** [nextflow-io/nextflow#3768]
## Bug report 

A Seqera customer is intermittently seeing a java.util.ConcurrentModificationException that occurs during the publishing step of the FASTP process in nf-core/sarek.

The java.util.ConcurrentModificationException call is coming from the [addAll method in publishOutputs0 method in the TaskProcessor class](https://github.com/nextflow-io/nextflow/blob/v22.06.1-edge/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1298), when a collection of files `Collection<Path> value` is being appended to the `HashSet<Path> files`:

https://github.com/nextflow-io/nextflow/blob/2b518b53c7e9b28040c22cafbe204244ac37d892/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1284-L1306
### Steps to reproduce the problem

Unfortunately, this issue is difficult to reproduce reliably. The publishing task that caused the error often finishes without issue on resume.

### Program output 

```
Feb-24 16:18:10.603 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_SAREK:SAREK:FASTP (39994-L6)'

Caused by:
  java.util.ConcurrentModificationException

java.util.ConcurrentModificationException: null
    at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
    at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
    at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
    at java_util_Set$addAll$2.call(Unknown Source)
    at nextflow.processor.TaskProcessor.publishOutputs0(TaskProcessor.groovy:1298)
    at nextflow.processor.TaskProcessor.publishOutputs(TaskProcessor.groovy:1280)
    at jdk.internal.reflect.GeneratedMethodAccessor630.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
    at nextflow.processor.TaskProcessor.finalizeTask0(TaskProcessor.groovy:2185)
    at jdk.internal.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
    at nextflow.processor.TaskProcessor.finalizeTask(TaskProcessor.groovy:2156)
    at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:619)
    at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:534)
    at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:409)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
    at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
    at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
    at groovy.lang.Closure.run(Closure.java:493)
    at java.base/java.lang.Thread.run(Thread.java:829)
```
The full log is available in ticket 2676 on the internal ticketing system (not included publicly here)

### Environment 

* Nextflow version: 22.06.1-edge
* Java version: unknown
* Operating system: Linux
* Bash version: unknown

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
I think the problem is caused by this `sort` made in the `FAST.out.reads`

https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/workflows/sarek.nf#L453-L465

By default, `sort` is mutable i.e. modify the source collection instead of creating a new one, and therefore it modifies the same collection used during the publishDir phase.

I believe changing the above snippet to `read_files = reads.sort(false) { .. }.collate(2)` should solve the problem. Tagging @maxulysse 


Said that nextflow should not expose the process's internal list structure. I'll also patch on nextflow side

**Comment by robsyme** [comment]
Ah, great catch! I hadn't appreciated that modification of those variables affected the Nextflow internals. Another option might be use `toSorted` which also returns a new collection:

```groovy
read_files = reads.toSorted { a,b -> 
  a.getName().tokenize('.')[0] <=> b.getName().tokenize('.')[0] 
}
```

**Comment by pditommaso** [comment]
Solved by 38762080. I'd advice to patch sarek as well as to prevent the problem with old versions of nextflow

**Comment by amizeranschi** [comment]
Hi @pditommaso 

I am now getting the same error ('java.util.ConcurrentModificationException') when running FASTP in nf-core/sarek, with the exact same stack trace as in the original post above. 

I am running a joint variant calling analysis in sarek 3.1.2, using nextflow 23.04.0, on an HTCondor cluster with NFS storage.

The relevant part of the log is here: https://pastebin.com/YGDN3Uxa

**Comment by FriederikeHanssen** [comment]
Hi! The patch is available in dev but not released yet.

**Comment by amizeranschi** [comment]
Thanks @FriederikeHanssen for looking into this. I replaced '-r 3.1.2' with '-r dev' and got a different error (which never came up with sarek 3.1.2):

```
ERROR ~ Cannot invoke method minus() on null object

 -- Check script '/data/share/.nextflow/assets/nf-core/sarek/./workflows/sarek.nf' at line: 305 or see '.nextflow.log' file for more details
```

This is line 305 in `/data/share/.nextflow/assets/nf-core/sarek/./workflows/sarek.nf`: 

```
    snpeff_info = params.snpeff_cache ? [] : Channel.of([ [ id:params.snpeff_db ], params.snpeff_genome, params.snpeff_db.minus("${params.snpeff_genome}.") ])
```

And this is the full .nextflow.log: https://pastebin.com/raw/WVCwf6PF

The exact command that I am running is the following:

```
nextflow run nf-core/sarek -r dev -c custom.config --input sample-sheet.csv --outdir sarek-out -profile docker --max_time '336.h' --max_cpus '64' --max_memory '256.GB' \
--fasta /data/share/simona-marc/Bos_taurus.ARS-UCD1.2-chr.fa --fasta_fai /data/share/simona-marc/Bos_taurus.ARS-UCD1.2-chr.fa.fai --dbsnp /data/share/simona-marc/bos_taurus.vcf.gz \
--vep_cache /data/share/simona-marc/bos_taurus --igenomes_ignore --genome null --joint_germline --tools haplotypecaller,manta,tiddit,cnvkit,vep
```

It's a bit strange that the error mentions snpeff, even though I'm not using it in this particular scenario.

**Comment by FriederikeHanssen** [comment]
Let's take it to the sarek slack channel or github repo. can you repost in either?
