### ISSUE TITLE
Method stripIndent is only supported on Java 15 an later 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3787]
The method `String.stripIndent` requires Java 15 or later. When using an old JBm the following error is reported 

```
java.lang.NoSuchMethodError: 'java.lang.String java.lang.String.stripIndent()'
        at io.seqera.wave.plugin.WaveClient.condaRecipeToDockerFile(WaveClient.groovy:424)
        at io.seqera.wave.plugin.WaveClient.resolveAssets0(WaveClient.groovy:337)
        at io.seqera.wave.plugin.WaveClient.memoizedMethodPriv$resolveAssetsTaskRunString(WaveClient.groovy:314)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
        at io.seqera.wave.plugin.WaveClient$_closure2.doCall(WaveClient.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
```

A workaround consists in using the groovy version `String.stripIndent(boolean)`

**Comment by pditommaso** [comment]
Solved by 308eafe6
