### ISSUE TITLE
failOnMismatch error shown when the pipeline fails before the join

### ISSUE THREAD

**Issue by nvnieuwk** [nextflow-io/nextflow#3828]
### Expected behavior and actual behavior

When a pipeline fails before a `.join()` happens that contains the `failOnMismatch:true` check, the mismatch error is given. This has sometimes confused me because the problem wasn't an actual mismatch but a failure in an earlier step in the pipeline. 

### Steps to reproduce the problem

Following code reproduces the problem. The errors aren't shown in the stdout, but are visible in the logs. The error has ocassionally shown up in the stdout when running pipelines that failed before the join step
```
workflow {
    ch_1 = Channel.of(
        [1, "one"],
        [2, "two"],
        [3, "three"]
    )

    ch_2 = Channel.of(
        [1, "een"],
        [2, "twee"],
        [3, "drie"]
    )

    RETURNS_ERROR(ch_1)

    ch_2.join(RETURNS_ERROR.out, failOnMismatch:true, failOnDuplicate:true)
}

process RETURNS_ERROR {
    input:
    tuple val(number), val(full_number)

    output:
    tuple val(number), path("*.txt")

    script:
    """
    echo ${full_number} > ${full_number}.txt
    exit 1
    """
}
```

### Program output 

.nextflow.log:

```log
Apr-03 11:23:23.158 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Apr-03 11:23:23.225 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.0
Apr-03 11:23:23.250 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/nvnieuwk/.nextflow/plugins; core-plugins: nf-amazon@1.16.1,nf-azure@1.0.0,nf-codecommit@0.1.3,nf-console@1.0.5,nf-ga4gh@1.0.4,nf-google@1.7.2,nf-tower@1.5.11,nf-wave@0.8.1
Apr-03 11:23:23.260 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-03 11:23:23.261 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-03 11:23:23.266 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-03 11:23:23.276 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Apr-03 11:23:23.328 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Apr-03 11:23:23.339 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [exotic_ekeblad] DSL2 - revision: f3ebbc673e
Apr-03 11:23:23.340 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Apr-03 11:23:23.341 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Apr-03 11:23:23.351 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/nvnieuwk/.nextflow/secrets/store.json
Apr-03 11:23:23.360 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@3eba57a7] - activable => nextflow.secret.LocalSecretsProvider@3eba57a7
Apr-03 11:23:23.435 [main] DEBUG nextflow.Session - Session UUID: 1f48a955-9331-4361-a71e-94502651a27e
Apr-03 11:23:23.435 [main] DEBUG nextflow.Session - Run name: exotic_ekeblad
Apr-03 11:23:23.438 [main] DEBUG nextflow.Session - Executor pool size: 8
Apr-03 11:23:23.453 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=24; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Apr-03 11:23:23.485 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.04.0 build 5857
  Created: 01-04-2023 21:09 UTC (23:09 CEST)
  System: Linux 5.15.0-69-generic
  Runtime: Groovy 3.0.16 on OpenJDK 64-Bit Server VM 17.0.6+10-Ubuntu-0ubuntu120.04.1
  Encoding: UTF-8 (UTF-8)
  Process: 185112@Latitude-5420 [127.0.1.1]
  CPUs: 8 - Mem: 15.4 GB (1.2 GB) - Swap: 980 MB (946.7 MB)
Apr-03 11:23:23.508 [main] DEBUG nextflow.Session - Work-dir: /home/nvnieuwk/Documents/nextflow/issues/joins/work [ext2/ext3]
Apr-03 11:23:23.508 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/nvnieuwk/Documents/nextflow/issues/joins/bin
Apr-03 11:23:23.517 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Apr-03 11:23:23.531 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-03 11:23:23.557 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Apr-03 11:23:23.566 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Apr-03 11:23:23.636 [main] DEBUG nextflow.Session - Session start
Apr-03 11:23:24.121 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-03 11:23:24.198 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-03 11:23:24.199 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-03 11:23:24.203 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Apr-03 11:23:24.206 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=15.4 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Apr-03 11:23:24.283 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: RETURNS_ERROR
Apr-03 11:23:24.284 [main] DEBUG nextflow.Session - Igniting dataflow network (3)
Apr-03 11:23:24.284 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > RETURNS_ERROR
Apr-03 11:23:24.285 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Apr-03 11:23:24.285 [main] DEBUG nextflow.Session - Session await
Apr-03 11:23:24.404 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-03 11:23:24.407 [Task submitter] INFO  nextflow.Session - [cf/17d358] Submitted process > RETURNS_ERROR (3)
Apr-03 11:23:24.413 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-03 11:23:24.414 [Task submitter] INFO  nextflow.Session - [10/14ad5b] Submitted process > RETURNS_ERROR (1)
Apr-03 11:23:24.419 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-03 11:23:24.420 [Task submitter] INFO  nextflow.Session - [1a/545b83] Submitted process > RETURNS_ERROR (2)
Apr-03 11:23:24.446 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 3; name: RETURNS_ERROR (3); status: COMPLETED; exit: 1; error: -; workDir: /home/nvnieuwk/Documents/nextflow/issues/joins/work/cf/17d3580a6ac4e7efc0381d96edcc2a]
Apr-03 11:23:24.450 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=RETURNS_ERROR (3); work-dir=/home/nvnieuwk/Documents/nextflow/issues/joins/work/cf/17d3580a6ac4e7efc0381d96edcc2a
  error [nextflow.exception.ProcessFailedException]: Process `RETURNS_ERROR (3)` terminated with an error exit status (1)
Apr-03 11:23:24.467 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'RETURNS_ERROR (3)'

Caused by:
  Process `RETURNS_ERROR (3)` terminated with an error exit status (1)

Command executed:

  echo three > three.txt
  exit 1

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/nvnieuwk/Documents/nextflow/issues/joins/work/cf/17d3580a6ac4e7efc0381d96edcc2a

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
Apr-03 11:23:24.477 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `RETURNS_ERROR (3)` terminated with an error exit status (1)
Apr-03 11:23:24.491 [Task monitor] DEBUG nextflow.Session - The following nodes are still active:
  [operator] join

Apr-03 11:23:24.492 [main] DEBUG nextflow.Session - Session await > all processes finished
Apr-03 11:23:24.493 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-03 11:23:24.497 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: RETURNS_ERROR (1); status: COMPLETED; exit: 1; error: -; workDir: /home/nvnieuwk/Documents/nextflow/issues/joins/work/10/14ad5bfb892b7a1cb0e888ea36bc7e]
Apr-03 11:23:24.498 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=RETURNS_ERROR (1); work-dir=/home/nvnieuwk/Documents/nextflow/issues/joins/work/10/14ad5bfb892b7a1cb0e888ea36bc7e
  error [nextflow.exception.ProcessFailedException]: Process `RETURNS_ERROR (1)` terminated with an error exit status (1)
Apr-03 11:23:24.499 [Actor Thread 8] ERROR nextflow.extension.OperatorImpl - @unknown
nextflow.exception.AbortOperationException: Join mismatch for the following entries: 
- key=1 values= 
- key=2 values= 
- key=3 values=
	at nextflow.extension.JoinOp.checkForMismatch(JoinOp.groovy:290)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.extension.JoinOp$_handler_closure2.doCall(JoinOp.groovy:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.DataflowHelper$3.afterStop(DataflowHelper.groovy:254)
	at groovyx.gpars.dataflow.operator.DataflowProcessor.fireAfterStop(DataflowProcessor.java:324)
	at groovyx.gpars.dataflow.operator.DataflowProcessorActor.afterStop(DataflowProcessorActor.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1024)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1015)
	at groovyx.gpars.actor.Actor.callDynamic(Actor.java:369)
	at groovyx.gpars.actor.Actor.handleTermination(Actor.java:320)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:86)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Apr-03 11:23:24.506 [main] WARN  n.processor.TaskPollingMonitor - Killing running tasks (1)
Apr-03 11:23:24.510 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: RETURNS_ERROR (2); status: COMPLETED; exit: 1; error: -; workDir: /home/nvnieuwk/Documents/nextflow/issues/joins/work/1a/545b83c3496292db896dc1180e5303]
Apr-03 11:23:24.511 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=RETURNS_ERROR (2); work-dir=/home/nvnieuwk/Documents/nextflow/issues/joins/work/1a/545b83c3496292db896dc1180e5303
  error [nextflow.exception.ProcessFailedException]: Process `RETURNS_ERROR (2)` terminated with an error exit status (1)
Apr-03 11:23:24.511 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=2; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=1; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=35ms; cachedDuration=0ms;loadCpus=1; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Apr-03 11:23:24.678 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Apr-03 11:23:24.689 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

```

### Environment 

* Nextflow version: 22.10.6, 23.04.0 and possibly others
* Java version: 17.0.6
* Operating system: Ubuntu 20.04.6 LTS and RHEL 8
* Bash version: 5.0.17

**Comment by bentsherman** [comment]
From the stack trace it looks like the complete handler for the join operator is still being called:

https://github.com/nextflow-io/nextflow/blob/8a4348939949ce5532179cc8067350c9c2c598ef/modules/nextflow/src/main/groovy/nextflow/extension/DataflowHelper.groovy#L250-L260

From the GPars documentation:

```groovy
    /**
     * Invoked immediately after the operator terminates
     *
     * @param processor The reporting dataflow operator/selector
     */
    void afterStop(DataflowProcessor processor);

    /**
     * Invoked if an exception occurs.
     * If any of the listeners returns true, the operator will terminate.
     * Exceptions outside of the operator's body or listeners' messageSentOut() handlers will terminate the operator irrespective of the listeners' votes.
     *
     * @param processor The reporting dataflow operator/selector
     * @param e         The thrown exception
     * @return True, if the operator should terminate in response to the exception, false otherwise.
     */
    boolean onException(DataflowProcessor processor, Throwable e);
```

It seems like when the operator is terminated by session abort, it calls `afterStop()` but not `onException()`, so the complete handler is called even though it's in an error condition.

@pditommaso let me know how you would like to proceed here. I think the join operator is not being terminated properly but not sure how to fix it.

**Comment by nvnieuwk** [comment]
This issue is still happening in the latest stable version

**Comment by bentsherman** [comment]
Stepping back, I think the `failOnDuplicate` and `failOnMismatch` options should probably just be avoided. I think a better pattern is to join the channels with `remainder: true` and inspect the results in a subsequent operation, throwing an error if some value is missing. For example:

```groovy
    ch_12 = ch_1.join(ch_2, by: 0, remainder: true)
    ch_12.subscribe { id, en, nl ->
        if( !en || !nl )
            error("Combined tuple has null values: ($id, $en, $nl)")
    }
```

I would like to better understand when these `failOn` options are being used, I just feel like there is a more robust way to do the same thing.

**Comment by nvnieuwk** [comment]
I personally use this to catch potential bugs in the pipeline with channel mismatches, it has really helped a lot during development and bug hunting. I can however surely live with your proposed solution as this is more deterministic

**Comment by bentsherman** [comment]
Testing a bit more, it looks like the original example and my proposal (replacing `failOnMismatch` with `subscribe` + `error`) have the same behavior -- they both report the task failure and the downstream operator error

I think this is sufficient for now, as the task failure is quite prominent. Maybe it wasn't showing up in previous versions, I'm not sure.

See #903 for a further improvement being discussed -- a process `error:` section to capture domain errors and handle them explicitly in workflow logic
