### ISSUE TITLE
503 Slowdown request AWS S3 

### ISSUE THREAD

**Issue by Shahbaz-mahmood123** [nextflow-io/nextflow#3832]
## Bug report 

When running larger pipelines nextflow does not respect the AWS S3 limits. 

### Program output 

```
Mar-30 16:06:09.432 [PublishDir-3] WARN  nextflow.processor.PublishDir - Failed to publish file: s3://drna-sysbio/scratch/zhe/human_liver/rnaseq_1069/3d/7d68cceada0afa7deaa1f3efb15ba3/ERX2636513.splice_junction.pdf; to: s3://drna-sysbio/projects/zhe_2023/human_liver/rnaseq_1069/star_salmon/rseqc/junction_annotation/pdf/ERX2636513.splice_junction.pdf [copy] -- See log file for details
com.amazonaws.services.s3.model.AmazonS3Exception: Slow Down (Service: Amazon S3; Status Code: 503; Error Code: 503 Slow Down; Request ID: ZD90JEQ15RS43PR4; S3 Extended Request ID: CerFkttyhVenIJit1c0XLy/+wU4HGRaFtSzYwq/uk6/bW8fcqscXc5/mdWhHf7/kJZbyde/Ao4I=; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346)
	at com.upplication.s3fs.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:350)
	at com.upplication.s3fs.S3FileSystemProvider.copy(S3FileSystemProvider.java:612)
	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:960)
	at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:454)
	at nextflow.processor.PublishDir.processFile(PublishDir.groovy:365)
	at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:347)
	at jdk.internal.reflect.GeneratedMethodAccessor470.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.processor.PublishDir$_apply1_closure1.doCall(PublishDir.groovy:320)
	at nextflow.processor.PublishDir$_apply1_closure1.call(PublishDir.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Environment 

* Nextflow version: 22.10.7

### Additional context

Some additional log was added here but was requested to open a ticket:
https://github.com/nextflow-io/nextflow/blob/master/changelog.txt#L3

**Comment by bentsherman** [comment]
Nextflow 24.04 added automatic retries for publishing (see the [migration notes](https://nextflow.io/docs/latest/migrations/24-04.html#enhancements)), which should cover this case
