### ISSUE TITLE
FileAlreadyExistsException when using copyTo on a directory that already exists

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#3881]
Using `workflow.workDir.copyTo("/path/to/target/")` fails when the target exists with a `FileAlreadyExistsException` after re-running `nextflow run main.nf` a few times.

Likely this is an issue that [`Files.createDirectory`](https://github.com/nextflow-io/nextflow/blob/17fcc67814b6e8a5566469fc2873408fa476d262/modules/nf-commons/src/main/nextflow/file/CopyMoveHelper.java#L120) doesn't have a "replace existing" copy option, so we should check if the directory exists before copying...

<details>

<summary>main.nf:</summary>

```groovy
#!/usr/bin/env nextflow
nextflow.enable.dsl=2 

process sayHello {
  input: 
    val x
  output:
    stdout
  script:
    """
    echo '$x world!'
    """
}

workflow {
  Channel.of('Bonjour', 'Ciao', 'Hello', 'Hola') | sayHello | view
}

workflow.onComplete {
	targetDir = "/tmp/tmpDir/"
	workflow.workDir.copyTo(targetDir)
}
```
</details>

<details>

<summary>.nextflow.log</summary>

```
Apr-18 21:40:21.312 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Apr-18 21:40:21.433 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.0
Apr-18 21:40:21.565 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [grave_dijkstra] DSL2 - revision: 4530eea2ab
Apr-18 21:40:21.596 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/Users/nhomer/.nextflow/plugins; core-plugins: nf-amazon@1.7.1,nf-azure@0.13.1,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
Apr-18 21:40:21.598 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Apr-18 21:40:21.614 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-18 21:40:21.615 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-18 21:40:21.619 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-18 21:40:21.650 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Apr-18 21:40:21.743 [main] DEBUG nextflow.Session - Session uuid: 2ff1843c-836a-4fc9-ace3-1db7c9ed45e4
Apr-18 21:40:21.743 [main] DEBUG nextflow.Session - Run name: grave_dijkstra
Apr-18 21:40:21.745 [main] DEBUG nextflow.Session - Executor pool size: 10
Apr-18 21:40:21.802 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.04.0 build 5697
  Created: 23-04-2022 18:00 UTC (11:00 MDT)
  System: Mac OS X 12.5.1
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.15+10-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 48571@Nilss-MacBook-Pro.local [10.0.7.61]
  CPUs: 10 - Mem: 64 GB (333.4 MB) - Swap: 2 GB (1.4 GB)
Apr-18 21:40:21.824 [main] DEBUG nextflow.Session - Work-dir: /private/tmp/nextflow/work [Mac OS X]
Apr-18 21:40:21.824 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /private/tmp/nextflow/bin
Apr-18 21:40:21.835 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Apr-18 21:40:21.860 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-18 21:40:21.899 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Apr-18 21:40:21.913 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 11; maxThreads: 1000
Apr-18 21:40:21.976 [main] DEBUG nextflow.Session - Session start invoked
Apr-18 21:40:23.025 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-18 21:40:23.228 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-18 21:40:23.228 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-18 21:40:23.237 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Apr-18 21:40:23.243 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=10; memory=64 GB; capacity=10; pollInterval=100ms; dumpInterval=5m
Apr-18 21:40:23.520 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: sayHello
Apr-18 21:40:23.523 [main] DEBUG nextflow.Session - Ignite dataflow network (2)
Apr-18 21:40:23.526 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > sayHello
Apr-18 21:40:23.529 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Apr-18 21:40:23.529 [main] DEBUG nextflow.Session - Session await
Apr-18 21:40:23.949 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-18 21:40:23.957 [Task submitter] INFO  nextflow.Session - [00/734120] Submitted process > sayHello (4)
Apr-18 21:40:23.972 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-18 21:40:23.973 [Task submitter] INFO  nextflow.Session - [5e/02dd1e] Submitted process > sayHello (1)
Apr-18 21:40:23.985 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-18 21:40:23.986 [Task submitter] INFO  nextflow.Session - [f2/9abbf4] Submitted process > sayHello (2)
Apr-18 21:40:24.001 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-18 21:40:24.001 [Task submitter] INFO  nextflow.Session - [63/572652] Submitted process > sayHello (3)
Apr-18 21:40:24.167 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 4; name: sayHello (4); status: COMPLETED; exit: 0; error: -; workDir: /private/tmp/nextflow/work/00/7341200f39902e921b911aed447c23]
Apr-18 21:40:24.199 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: sayHello (1); status: COMPLETED; exit: 0; error: -; workDir: /private/tmp/nextflow/work/5e/02dd1e6730b6036860791b4d03dbc3]
Apr-18 21:40:24.210 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: sayHello (2); status: COMPLETED; exit: 0; error: -; workDir: /private/tmp/nextflow/work/f2/9abbf4b5cfd132ee6aa8160adaf85d]
Apr-18 21:40:24.216 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 3; name: sayHello (3); status: COMPLETED; exit: 0; error: -; workDir: /private/tmp/nextflow/work/63/5726529b3aac734d37a850e681f457]
Apr-18 21:40:24.233 [main] DEBUG nextflow.Session - Session await > all process finished
Apr-18 21:40:24.255 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-18 21:40:24.286 [main] ERROR nextflow.script.WorkflowMetadata - Failed to invoke `workflow.onComplete` event handler
java.nio.file.FileAlreadyExistsException: /tmp/tmpDir/work
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at nextflow.file.CopyMoveHelper$1.preVisitDirectory(CopyMoveHelper.java:154)
	at nextflow.file.CopyMoveHelper$1.preVisitDirectory(CopyMoveHelper.java:142)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2732)
	at nextflow.file.CopyMoveHelper.copyDirectory(CopyMoveHelper.java:174)
	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:931)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.extension.FilesEx.copyTo(FilesEx.groovy:184)
	at nextflow.extension.FilesEx$copyTo$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at nextflow.extension.FilesEx.copyTo(FilesEx.groovy:231)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:66)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_a4a91fed$_runScript_closure3.doCall(Script_a4a91fed:21)
	at Script_a4a91fed$_runScript_closure3.doCall(Script_a4a91fed)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowMetadata$_invokeOnComplete_closure4.doCall(WorkflowMetadata.groovy:389)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384)
	at nextflow.script.WorkflowMetadata.invokeOnComplete(WorkflowMetadata.groovy:387)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.script.WorkflowMetadata$_closure3.doCall(WorkflowMetadata.groovy:252)
	at nextflow.script.WorkflowMetadata$_closure3.call(WorkflowMetadata.groovy)
	at nextflow.Session.shutdown0(Session.groovy:675)
	at nextflow.Session.destroy(Session.groovy:625)
	at nextflow.script.ScriptRunner.terminate(ScriptRunner.groovy:222)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:122)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:334)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
Apr-18 21:40:24.309 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=4; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=401ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=4; peakCpus=4; peakMemory=0; ]
Apr-18 21:40:24.549 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Apr-18 21:40:24.587 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

</details>

**Comment by bentsherman** [comment]
The `copyTo` method does check if the target already exists:

https://github.com/xhejtman/nextflow/blob/78fea27f132c509ab42f2670d06a33e91afd54cc/modules/nf-commons/src/main/nextflow/extension/FilesEx.groovy#L168-L210

However it fails if the target is a file. Could that be the issue?

**Comment by nh13** [comment]
@bentsherman can you run the nextflow script and confirm it fails for you?

**Comment by bentsherman** [comment]
Whoops, forgot to look at your stack trace.

I had to run the example three times before I encountered the error. The first time, it copies the `work` directory to `tmpDir`. The second time, it copes the `work` directory to `tmpDir/work`. The third time, it tries to copy the `work` directory `tmpDir/work` and fails because `tmpDir/work` already exists.

Are you sure this is what you want? Even if it worked, you would be creating and endless recursion of `tmpDir/work/work/work/...` whereas I think you actually want to merge each work directory into the target.

**Comment by bentsherman** [comment]
I think you need to use `rsync`: https://unix.stackexchange.com/questions/149965/how-to-copy-merge-two-directories

**Comment by nh13** [comment]
Sure I could use rsync generally, but I’d like to use this an onError or onComplete block and use nextflow/Groovy to do so. I guess I am not following why it would create recursive directories when the target directory is always the same?

**Comment by nh13** [comment]
Try changing the `onComplete` block to be:
```
workflow.onComplete {
    targetDir = "/tmp/tmpDir/"
    log.info("workdir: ${workflow.workDir}")
    log.info("targetDir: ${targetDir}")
    workflow.workDir.copyTo(targetDir)
}
```

While I want it to _overwrite_ what's there, I don't see why `copyTo` would want to cause a recursive copy when it purports to be like `cp -r`:
https://github.com/nextflow-io/nextflow/blob/4343e333b749b748b57f65290443d2fc61c27b96/modules/nf-commons/src/main/nextflow/extension/FilesEx.groovy#L161

I think the recursive part may be a bug in the nextflow-io code?

**Comment by bentsherman** [comment]
You can use `rsync` in that workflow handler. In Groovy, you can call `execute()` on a string to execute it like a command:
```groovy
"rsync ${workflow.workDir} ${targetDir}".execute()
```

The `copyTo()` method does mimic the behavior of `cp -r`, which includes recursive copying of a directory. But you have to think about how the existence of the target affects the behavior:
- if the target doesn't exist, the source directory *becomes* the target directory
- if the target exists as a file, the copy fails
- if the target exists as a directory, the source directory is copied *into* the target directory
  - if a file or directory with the same name as the source already exists in the target directory, the copy fails

I think you will find the same behavior whether you use `copyTo()` or `cp -r`. You should either explicitly delete the target directory before you copy, or use `rsync` if you want to merge the directories.
