### ISSUE TITLE
ERROR - java.nio.file.attribute.BasicWithKeyFileAttributeView

### ISSUE THREAD

**Issue by lescai** [nextflow-io/nextflow#3911]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Running normal test profile for Sarek with command:

```
nextflow run nf-core/sarek -c ~/configs/eos_nf.config -profile eos,test --outdir .
```
works without any issues (expected behaviour), while running a full test profile
```
nextflow run nf-core/sarek -c ~/configs/eos_nf.config -profile eos,test_full --outdir .
```

runs into the following error:

```
Downloading plugin nf-amazon@1.16.2
ERROR ~ Not a valid S3 file system provider file attribute view: java.nio.file.attribute.BasicWithKeyFileAttributeView
```

I've had this issue with both nextflow version 22.10.6 (recipe in conda) and plugin nf-amazon@1.11.3 as well as version 23.04.1 and plugin nf-amazon@1.16.2

nf-core/rnaseq works fine with test profile (like sarek), but haven't tried the test_full.

### Steps to reproduce the problem

The config profile is the same in both case, but just reporting it here for reproducibility:

```
profiles {
    eos {
        process{
            executor = 'slurm'
        }
    singularity.enabled = true
    singularity.autoMounts = true
    }
}
```

to reproduce the problem it should be sufficient to run

```
nextflow run nf-core/sarek -profile test_full --outdir .
```

### Program output 

Log is this 

```
------------------------------------------------------
May-03 16:06:05.373 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: 1.16.2
May-03 16:06:05.378 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-amazon@1.16.2
May-03 16:06:12.441 [main] INFO  org.pf4j.util.FileUtils - Expanded plugin zip 'nf-amazon-1.16.2.zip' in 'nf-amazon-1.16.2'
May-03 16:06:12.476 [main] DEBUG nextflow.plugin.PluginUpdater - Failed atomic move for plugin /tmp/pf4j-update-downloader9583593209973655424/nf-amazon-1.16.2 -> /home/lescai/.nextflow/plugins/nf-amazon-1.16.2 - Reason: /tmp/pf4j-u
pdate-downloader9583593209973655424/nf-amazon-1.16.2 -> /home/lescai/.nextflow/plugins/nf-amazon-1.16.2: Invalid cross-device link - Fallback on safe move
May-03 16:06:13.309 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-amazon@1.16.2' resolved
May-03 16:06:13.310 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@1.16.2'
May-03 16:06:13.372 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@1.16.2
May-03 16:06:13.414 [main] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
May-03 16:06:13.415 [main] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/G1000_alleles_hg38.zip
May-03 16:06:13.444 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
May-03 16:06:13.459 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {max_error_retry=5}
May-03 16:06:14.822 [main] DEBUG com.upplication.s3fs.AmazonS3Client - Setting S3 glacierRetrievalTier=null
May-03 16:06:53.750 [main] DEBUG nextflow.Session - Session aborted -- Cause: Not a valid S3 file system provider file attribute view: java.nio.file.attribute.BasicWithKeyFileAttributeView
May-03 16:06:53.794 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.UnsupportedOperationException: Not a valid S3 file system provider file attribute view: java.nio.file.attribute.BasicWithKeyFileAttributeView
	at com.upplication.s3fs.S3FileSystemProvider.getFileAttributeView(S3FileSystemProvider.java:733)
	at java.base/java.nio.file.Files.getFileAttributeView(Files.java:1776)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:221)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:282)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:328)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2792)
	at nextflow.file.FileHelper.visitFiles(FileHelper.groovy:825)
	at nextflow.file.FileHelper$visitFiles$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
	at nextflow.Nextflow.fileNamePattern(Nextflow.groovy:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:249)
	at nextflow.Nextflow.file(Nextflow.groovy:120)
	at nextflow.Nextflow$file.callStatic(Unknown Source)
	at Script_662cb5ec.runScript(Script_662cb5ec:56)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:145)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:229)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:215)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:205)
	at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:151)
	at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
	at nextflow.script.IncludeDef$__clinit__closure2.doCall(IncludeDef.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
	at nextflow.script.IncludeDef.load0(IncludeDef.groovy:123)
	at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_c05744b2.runScript(Script_c05744b2:79)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:145)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:229)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:224)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:130)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
```

Given the error log, I've tried to download manually with aws-cli to exclude any issue related to my environment

```
aws s3 --no-sign-request --region eu-west-1 cp s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/G1000_alleles_hg38.zip .
download: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/G1000_alleles_hg38.zip to ./G1000_alleles_hg38.zip
```

which worked without any error.

### Environment 

* Nextflow version: 23.04.1
* Java version: 
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)

* Operating system: Rocky Linux release 8.7 (Green Obsidian)
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)

**Comment by pditommaso** [comment]
This is due to a non-official JVM. Install Java using [sdkman](https://sdkman.io/) instead. See here https://github.com/nextflow-io/nextflow/issues/2841#issuecomment-1114289022

**Comment by lescai** [comment]
thanks. nextflow was installed through conda, so the JVM is the dependency listed in the conda recipe I suppose :)

**Comment by pditommaso** [comment]
yeah, never understood why conda uses that broken version
