### ISSUE TITLE
Using tap with pipes in DSL2

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#3970]
### Discussed in https://github.com/nextflow-io/nextflow/discussions/3919

<div type='discussions-op-text'>

<sup>Originally posted by **glormph** May  5, 2023</sup>
Hi, I have tried and failed to use `tap` in DSL2 with pipes:
```
ch1
| SomeProcess
| tap { ch2 }
| AnotherProcess
```
This gets me an error message, `No such variable: ch2`. I have not been able to figure out if this is intended or not, since `.tap { ch2 }` works fine. Not a huge problem and easy enough to work around, but I do like the pipe syntax a lot :)</div>

**Comment by bentsherman** [comment]
I reproduced the error using the tap example from the operator docs. If you replace the dot notation with pipe notation, you get this error:
```
groovy.lang.MissingPropertyException: No such property: log1 for class: Script_943e124e
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at Script_943e124e$_runScript_closure1.doCall(Script_943e124e:2)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:363)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.tap(DefaultGroovyMethods.java:404)
	at org.codehaus.groovy.runtime.dgm$761.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:222)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at Script_943e124e.runScript(Script_943e124e:2)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:145)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:230)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:224)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:130)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:371)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
```

The `set` operator doesn't seem to have this problem, I can use `set` with a pipe and it works.

**Comment by pditommaso** [comment]
I believe is related to this https://github.com/nextflow-io/nextflow/issues/3378

**Comment by bskubi** [comment]
Just confirming that I get the same error using tap with pipes, and that the error goes away when I replace the pipes with dot notation.

**Comment by pa-beaufort** [comment]
> Just confirming that I get the same error using tap with pipes, and that the error goes away when I replace the pipes with dot notation.

Idem here

**Comment by Gullumluvl** [comment]
Hi there,

I think this issue in practice forbids the use of the `tap` operator, because it makes it too tricky to combine processes and operators in a single chain of operations including `tap`.

I was trying to figure out how I can chain my operations, so here are dummy configurations I tried, and the results:

```groovy
process process_x {
    input:
    val invalue

    output:
    val outvalue

    fair true

    exec:
    outvalue = invalue + 1
}

workflow {
    // works ok
    Channel.of(0, 10, 100) | map { it+1 } | process_x | view

    // tap after operators, all pipes: ERROR ~ No such variable: intermediate
    Channel.of(0, 10, 100) | map { it+1 } | tap { intermediate } | process_x | view

    // tap after operators, last preceded by dot: ERROR ~ No such variable: intermediate
    Channel.of(0, 10, 100) | map { it+1 }.tap { intermediate } | process_x | view

    // tap after operators, **only** preceded by dots: OK!
    Channel.of(0, 10, 100).map { it+1 }.tap { intermediate } | process_x | view

    // tap after process, only preceded by dots: ERROR ~ No such variable: process_x
    Channel.of(0, 10, 100).process_x.tap { intermediate } | view

    // tap after process, last preceded by dot: ERROR ~ No such variable: intermediate
    Channel.of(0, 10, 100) | process_x .tap { intermediate } | view

    // tap after parenthesized process, last preceded by dot: OK!
    (Channel.of(0, 10, 100) | process_x) .tap { intermediate } | view

    intermediate | view { "intermediate: $it" }
}
```

In particular, I want to highlight that *the whole preceding chain* must use dots. However processes must be chained via pipe, so in this case it breaks unless we parenthesize operations preceding `tap`. 

I am using Nextflow 24.04.4 (latest).

**Comment by bentsherman** [comment]
Thanks for the testing. I think this issue probably won't be solvable until we implement a more robust version of the pipe operator. Some deeper changes need to be made first, but they're in the works

**Comment by yinshiyi** [comment]
similar errors on using `tap`, `set` is working great though.
Thank you for your hard work. Looking forward to see if there is any guidance on this issue. Thanks!

**Comment by bentsherman** [comment]
Closing as not planned since [tap](https://nextflow.io/docs/latest/reference/operator.html#tap) is discouraged in favor of standard assignments
