### ISSUE TITLE
Better error message on join mismatch

### ISSUE THREAD

**Issue by asp8200** [nextflow-io/nextflow#4052]
## New feature

It would be so helpful if nextflow would report which join-operation is failing, like in which file and in which line. Currently, we just get, say, something like the following in the stdout

```
Join mismatch for the following entries:
- key=[patient:test, sample:test, sex:XX, status:0, id:test, data_type:fastq] values=
- key=[patient:test, sample:test, sex:XX, status:0, id:test] values=
```

with no information on which join-operation caused the mismatch.  Also, the error message in `.nextflow.log` isn't much more useful:
```
Jun-26 12:51:10.461 [Actor Thread 8] ERROR nextflow.extension.OperatorImpl - @unknown
nextflow.exception.AbortOperationException: Join mismatch for the following entries: 
- key=[patient:test, sample:test, sex:XX, status:0, id:test, data_type:fastq] values= 
- key=[patient:test, sample:test, sex:XX, status:0, id:test] values=
	at nextflow.extension.JoinOp.checkForMismatch(JoinOp.groovy:290)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.extension.JoinOp$_handler_closure2.doCall(JoinOp.groovy:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.DataflowHelper$3.afterStop(DataflowHelper.groovy:254)
	at groovyx.gpars.dataflow.operator.DataflowProcessor.fireAfterStop(DataflowProcessor.java:324)
	at groovyx.gpars.dataflow.operator.DataflowProcessorActor.afterStop(DataflowProcessorActor.java:59)
	at jdk.internal.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1024)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1015)
	at groovyx.gpars.actor.Actor.callDynamic(Actor.java:369)
	at groovyx.gpars.actor.Actor.handleTermination(Actor.java:320)
	at groovyx.gpars.actor.AbstractLoopingActor.terminate(AbstractLoopingActor.java:204)
	at groovyx.gpars.dataflow.operator.DataflowProcessor.terminate(DataflowProcessor.java:147)
	at groovyx.gpars.dataflow.operator.DataflowProcessorActor.checkPoison(DataflowProcessorActor.java:115)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:83)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Jun-26 12:51:10.468 [Actor Thread 8] DEBUG nextflow.Session - Session aborted -- Cause: Join mismatch for the following entries: 
- key=[patient:test, sample:test, sex:XX, status:0, id:test, data_type:fastq] values= 
- key=[patient:test, sample:test, sex:XX, status:0, id:test] values=
```

**Comment by bentsherman** [comment]
This is tricky because of how the pipeline is lazily executed. So the script is executed which produces the DAG, then the DAG is executed in a separate step. So information like line numbers is long gone.

There may be some way to preserve the line number associated with each operator call, then we could include the line number in the exception that is thrown (e.g. `AbortOperationException`). But I'm not sure on all the details, needs to be investigated further.

**Comment by asp8200** [comment]
> This is tricky because of how the pipeline is lazily executed. So the script is executed which produces the DAG, then the DAG is executed in a separate step. So information like line numbers is long gone.
> 
> There may be some way to preserve the line number associated with each operator call, then we could include the line number in the exception that is thrown (e.g. `AbortOperationException`). But I'm not sure on all the details, needs to be investigated further.

Thanks for your prompt reply, @bentsherman. I hope some solution can be found as I could see a solution for this particular error also being relevant for many other kinds of errors.

**Comment by xiangqing111** [comment]
***********************************************************************
  Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.

Work dir:
  /cluster/home/fanrong/projects/AK58/input/work/34/d385a832a8e4322a41e626ad559cfb

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
Join mismatch for the following entries: 
- key=[patient:patient1, sample:test_sample3, sex:NA, status:0, id:test_sample3, data_type:cram] values= 
- key=[patient:patient1, sample:test_sample4, sex:NA, status:0, id:test_sample4, data_type:cram] values=

I'm having the same problem, can you find the problem?

**Comment by bentsherman** [comment]
Closing as not planned, see my recommendation here: https://github.com/nextflow-io/nextflow/issues/3828#issuecomment-3530519270
