### ISSUE TITLE
Unable to start plugin 'nf-google'

### ISSUE THREAD

**Issue by AMCalejandro** [nextflow-io/nextflow#4124]
### Expected behavior and actual behavior

Nextflow pipeline manages to access data stored in google cloud bucket and run several processes

### Steps to reproduce the problem

Running .nf script from command line with a parameters file that looks like I show below
nextflow run workflows/main.nf -profile standard -params-file params.yml

```
---
# Input files
input: gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/geno-test/*.vcf
covarfile: gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/clinical/covars_netpdCorriell.tsv
phenofile: gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/clinical/updrspheno_netpdCorriell.tsv

#Variables names
pheno_name: updrs_part_iii_summary_score
study_col: study_arm
time_col: visit_name
covariates: "age_at_baseline sex PC1 PC2 PC3"

# Model variables
longitudinal_flag:  true
survival_flag:      false
linear_flag:        false
chunk_flag:         false

# Parameters for genetic QC
r2thres:             -9
minor_allele_freq:   0.05
minor_allele_ct:     20
kinship:             0.177
ancestry:            EUR
assembly:            hg38
chunk_size:          100000
plink_chunk_size:    100000

#Identifier for the input genotype files - useful to cache results
dataset:           "CHECK_GSUTIL_V2"

# Generate manhattan with result files
mh_plot:           true
```

### Program output 

```
xtflow run workflows/main.nf -profile standard -params-file params_toy.yml
N E X T F L O W  ~  version 23.04.2
Launching `workflows/main.nf` [golden_lattes] DSL2 - revision: ebf59684ef
 LONG-GWAS - GWAS P I P E L I N E
 ======================================
 Chunk size for genetic processing        : 100000
 Kinship matrix threshold                 : 0.177
 R2 threshold                             : -9
 MAF threshold                            : 0.05
 data ancestry                            : EUR
 genetic data assemble                    : hg38
 phenotype name                           : updrs_part_iii_summary_score
 covariates                               : age_at_baseline sex PC1 PC2 PC3
 analysis                                 : LMM_GALLOP
 outdir                                   : /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/LONGWAS-NF/tmp/files/longGWAS_pipeline/results/cache/CHECK_GSUTIL_V2

[-        ] process > DOQC:GENETICQC                -
[-        ] process > DOQC:GENETICQC                -
[-        ] process > DOQC:MERGER_SPLITS            -
[-        ] process > DOQC:GENETICQC                -
[-        ] process > DOQC:MERGER_SPLITS            -
[-        ] process > DOQC:MERGER_CHRS              -
[-        ] process > DOQC:GWASQC                   -
[-        ] process > GWASDATA_PREP:GETPHENOS       -
[-        ] process > GWASDATA_PREP:REMOVEOUTLIERS  -
[-        ] process > GWASDATA_PREP:COMPUTE_PCA     -
[-        ] process > GWASDATA_PREP:MERGE_PCA       -
[-        ] process > GWASDATA_PREP:GALLOPCOX_INPUT -
[-        ] process > GWASDATA_PREP:RAWFILE_EXPORT  -
[-        ] process > GWAS_RUN:GWASGALLOP           -
[-        ] process > SAVE_RESULTS:SAVEGWAS         -
[-        ] process > SAVE_RESULTS:MANHATTAN        -
Downloading plugin nf-google@1.7.3
WARN: Unable to start plugin 'nf-google' required by gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/geno-test/*.vcf
ERROR ~ Missing plugin 'nf-google' required to read file: gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/geno-test/*.vcf

 -- Check '.nextflow.log' file for details
Error executing process > 'GWASDATA_PREP:GETPHENOS'

Caused by:
  Missing plugin 'nf-google' required to read file: gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/clinical/covars_netpdCorriell.tsv
```

### Environment 

* Nextflow version: [23.04.2.5870] 
* Java version: [ "11.0.19" 2023-04-18]
* Operating system: [Linux on my HPC]
* Bash version: (use the command `$SHELL --version`) [GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)]

### Additional context

In $HOME, the plugins folder is properly created, and all plugins are downloaded

```
 ls -la ~/.nextflow/plugins/nf-google-1.7.3/
total 20
drwxrwxr-x 5 acarrasco acarrasco 4096 Jul 22 22:47 .
drwxrwxr-x 3 acarrasco acarrasco 4096 Jul 22 22:47 ..
drwxrwxr-x 4 acarrasco acarrasco 4096 Jul 22 22:47 classes
drwxrwxr-x 2 acarrasco acarrasco 4096 Jul 22 22:47 lib
drwxrwxr-x 2 acarrasco acarrasco 4096 Jul 22 22:47 META-INF
```

As I am running this on an HPC, I have also checked that this does not relate to a permission issue. 
I tried to rerun after giving chmod 777 to my $HOME, where .nextflow/ is maintained.
The issue persists.

In addition, I have managed to run thes exact same pipeline from other machine, using a slightly older version of nextflow.
I also tried running with the working nextflow version, but it did not solve the issue
```
 NXF_VER=22.10.7 nextflow run workflows/main.nf -profile standard -params-file par
ams_toy.yml
Downloading nextflow dependencies. It may require a few seconds, please wait ..
CAPSULE: Downloading dependency io.nextflow:nf-commons:jar:22.10.7
CAPSULE: Downloading dependency org.codehaus.groovy:groovy:jar:3.0.13
CAPSULE: Downloading dependency org.jsoup:jsoup:jar:1.14.3
CAPSULE: Downloading dependency org.yaml:snakeyaml:jar:1.30
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-nio:jar:3.0.13
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-templates:jar:3.0.13
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-xml:jar:3.0.13
CAPSULE: Downloading dependency io.nextflow:nf-httpfs:jar:22.10.7
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-json:jar:3.0.13
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:22.10.7
N E X T F L O W  ~  version 22.10.7
Launching `workflows/main.nf` [kickass_kowalevski] DSL2 - revision: ebf59684ef
 LONG-GWAS - GWAS P I P E L I N E
 ======================================
 Chunk size for genetic processing        : 100000
 Kinship matrix threshold                 : 0.177
 R2 threshold                             : -9
 MAF threshold                            : 0.05
 data ancestry                            : EUR
 genetic data assemble                    : hg38
 phenotype name                           : updrs_part_iii_summary_score
 covariates                               : age_at_baseline sex PC1 PC2 PC3
 analysis                                 : LMM_GALLOP
 outdir                                   : /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/LONGWAS-NF/tmp/files/longGWAS_pipeline/results/cache/CHECK_GSUTIL_V2

[-        ] process > DOQC:GENETICQC                -
[-        ] process > DOQC:MERGER_SPLITS            -
[-        ] process > DOQC:GENETICQC                -
[-        ] process > DOQC:MERGER_SPLITS            -
[-        ] process > DOQC:MERGER_CHRS              -
[-        ] process > DOQC:GENETICQC                -
[-        ] process > DOQC:MERGER_SPLITS            -
[-        ] process > DOQC:MERGER_CHRS              -
[-        ] process > DOQC:GWASQC                   -
[-        ] process > GWASDATA_PREP:GETPHENOS       -
[-        ] process > GWASDATA_PREP:REMOVEOUTLIERS  -
[-        ] process > GWASDATA_PREP:COMPUTE_PCA     -
[-        ] process > GWASDATA_PREP:MERGE_PCA       -
[-        ] process > GWASDATA_PREP:GALLOPCOX_INPUT -
[-        ] process > GWASDATA_PREP:RAWFILE_EXPORT  -
[-        ] process > GWAS_RUN:GWASGALLOP           -
[-        ] process > SAVE_RESULTS:SAVEGWAS         -
[-        ] process > SAVE_RESULTS:MANHATTAN        -
Downloading plugin nf-google@1.4.5
WARN: Unable to start plugin 'nf-google' required by gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/geno-test/*.vcf
Missing plugin 'nf-google' required to read file: gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/geno-test/*.vcf


Error executing process > 'GWASDATA_PREP:GETPHENOS'

Caused by:
  Missing plugin 'nf-google' required to read file: gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/clinical/covars_netpdCorriell.tsv
```

**Comment by pditommaso** [comment]
Please include the `.nextflow.log` file of the failed execution

**Comment by AMCalejandro** [comment]
Thanks for looking at this issue, Paolo.
Please, find the .nextflow.log attached.

[.nextflow.log](https://github.com/nextflow-io/nextflow/files/12139735/default.nextflow.log)

**Comment by pditommaso** [comment]
It looks like your file system does not support symbolic link creation 

```
Jul-23 18:47:39.266 [PathVisitor-2] WARN  nextflow.file.FileHelper - Unable to start plugin 'nf-google' required by gs://long-gwas/long-gwas/DATA/amc/netpdcorriell/geno-test/*.vcf
java.nio.file.FileSystemException: .nextflow/plr/f08e749d-b600-4be4-b624-914d9cdf413e/nf-google-1.7.3: Operation not supported
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:462)
	at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1059)
	at nextflow.plugin.LocalPluginManager.createLink0(LocalPluginManager.groovy:117)
	at nextflow.plugin.LocalPluginManager.createLinkFromPath(LocalPluginManager.groovy:110)
	at nextflow.plugin.LocalPluginManager.loadPluginFromPath(LocalPluginManager.groovy:96)
	at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:335)

```

**Comment by AMCalejandro** [comment]
Whereas my HPC does support symbolic link creation, my WD is on a mounted network drive. 
SSHing to the network drive, I could guarantee symbolic link creation is not allowed.

I wonder if it would be a sensible feature request allow nextflow to somehow work on external drives but that are ultimately using resources from the HPC they are mounted on.

Closing this for now, thanks for your help.

**Comment by bentsherman** [comment]
Fwiw, in this case Nextflow is trying to create a symbolic link at `$HOME/.nextflow` as part of downloading the nf-google plugin. If your home directory doesn't support symbolic links, you can change the location of this directory with the `NXF_HOME` environment variable.
