### ISSUE TITLE
ERROR ~ No such variable: foobar

### ISSUE THREAD

**Issue by kemin711** [nextflow-io/nextflow#4203]
Is there a limit on the number of output channels or the number of lines in the script section?
I saw the above error when my output has 5 channels, and 62 lines.  The the variable in my last channel is flagged as undefined, when in reality this variable is well defined just above the """ delimiter.  

The following is the stack track more likely to help the developers:
`groovy.lang.MissingPropertyException: Unknown variable 'deflatedRawQF'
   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
   at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
   at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
   at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:295)
   at nextflow.script.ProcessConfig.getProperty(ProcessConfig.groovy:278)
   at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
   at groovy.lang.Closure.getPropertyTryThese(Closure.java:320)
   at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:310)
   at groovy.lang.Closure.getProperty(Closure.java:296)
   at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
   at Script_de771b46$_runScript_closure22.doCall(Script_de771b46:552)
   at Script_de771b46$_runScript_closure22.doCall(Script_de771b46)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
   at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
   at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
   at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
   at groovy.lang.Closure.call(Closure.java:412)
   at groovy.lang.Closure.call(Closure.java:406)
   at nextflow.script.ProcessDef.initialize(ProcessDef.groovy:110)
   at nextflow.script.ProcessDef.run(ProcessDef.groovy:168)
   at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
   at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
   at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:102)
`
It turned out to be a typo:
output:
tuple ...
path(somefile)
... several more channels
// last one
....., emit blabal_ch
it is the last one that I missed the ':' semicolon
Hope this case may be used for the syntax checker to output more meaningful error messages.

**Comment by kemin711** [comment]
It is due to a typo. Hope some once can update the error message.

**Comment by bentsherman** [comment]
Hi @kemin711 can you give a more detailed script example? I tried to reproduce it with a simple pipeline but I get `Unknown variable 'emit'`
