### ISSUE TITLE
Capsule Exception caused by java.io.IOException

### ISSUE THREAD

**Issue by 18alia** [nextflow-io/nextflow#4206]
## Bug report 

Attempting to run nextflow causes a Capsule Exception. 

### Expected behavior and actual behavior
The expected bevaior would be initializing and running Nextflow. Instead, a Capsule Exception is thrown, and when I check it with a verbose log, it shows it is "caused by" a variety of Java errors that appear to stem from an IO Exception.

### Steps to reproduce the problem
The initial problem appears with any command that starts with 'nextflow'. Running 'nextflow -Dcapsule.log=verbose info' gets the mord detailed output seen below.

### Program output 
For 'nextflow':
`CAPSULE: Downloading dependency org.multiverse:multiverse-core:jar:0.7.0
CAPSULE: Downloading dependency org.apache.ivy:ivy:jar:2.5.1
CAPSULE: Downloading dependency org.slf4j:jul-to-slf4j:jar:1.7.36
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-templates:jar:3.0.16
CAPSULE: Downloading dependency org.slf4j:jcl-over-slf4j:jar:1.7.36
CAPSULE: Downloading dependency commons-io:commons-io:jar:2.11.0
CAPSULE: Downloading dependency org.codehaus.jsr166-mirror:jsr166y:jar:1.7.0
CAPSULE: Downloading dependency commons-codec:commons-codec:jar:1.15
CAPSULE: Downloading dependency com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava
CAPSULE: Downloading dependency ch.artecat.grengine:grengine:jar:3.0.0
CAPSULE: Downloading dependency com.beust:jcommander:jar:1.35
CAPSULE: Downloading dependency io.nextflow:nf-httpfs:jar:23.04.3
CAPSULE: Downloading dependency jline:jline:jar:2.9
CAPSULE: Downloading dependency io.nextflow:nf-commons:jar:23.04.3
CAPSULE: Downloading dependency ch.qos.logback:logback-core:jar:1.2.11
CAPSULE: Downloading dependency com.github.zafarkhaja:java-semver:jar:0.9.0
CAPSULE: Downloading dependency javax.mail:mail:jar:1.4.7
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-json:jar:3.0.16
CAPSULE: Downloading dependency org.eclipse.jgit:org.eclipse.jgit:jar:6.2.0.202206071550-r
CAPSULE: Downloading dependency com.google.code.findbugs:jsr305:jar:3.0.2
CAPSULE: Downloading dependency org.codehaus.groovy:groovy:jar:3.0.16
CAPSULE: Downloading dependency commons-lang:commons-lang:jar:2.6
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb-api:jar:0.12
CAPSULE: Downloading dependency org.codehaus.gpars:gpars:jar:1.2.1
CAPSULE: Downloading dependency ch.qos.logback:logback-classic:jar:1.2.11
CAPSULE: Downloading dependency org.jsoup:jsoup:jar:1.15.4
CAPSULE: Downloading dependency org.slf4j:log4j-over-slf4j:jar:1.7.36
CAPSULE: Downloading dependency com.google.guava:guava:jar:31.1-jre
CAPSULE: Downloading dependency org.objenesis:objenesis:jar:2.1
CAPSULE: Downloading dependency com.esotericsoftware.kryo:kryo:jar:2.24.0
CAPSULE: Downloading dependency org.slf4j:slf4j-api:jar:1.7.36
CAPSULE: Downloading dependency org.yaml:snakeyaml:jar:2.0
CAPSULE: Downloading dependency com.google.code.gson:gson:jar:2.10.1
CAPSULE: Downloading dependency com.google.errorprone:error_prone_annotations:jar:2.11.0
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-nio:jar:3.0.16
CAPSULE: Downloading dependency dev.failsafe:failsafe:jar:3.1.0
CAPSULE: Downloading dependency com.google.j2objc:j2objc-annotations:jar:1.3
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:23.04.3
CAPSULE: Downloading dependency javax.activation:activation:jar:1.1.1
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-xml:jar:3.0.16
CAPSULE: Downloading dependency org.pf4j:pf4j:jar:3.4.1
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb:jar:0.12
CAPSULE: Downloading dependency com.google.guava:failureaccess:jar:1.0.1
CAPSULE: Downloading dependency com.googlecode.javaewah:JavaEWAH:jar:1.1.13
CAPSULE: Downloading dependency org.checkerframework:checker-qual:jar:3.12.0
CAPSULE: Downloading dependency org.pf4j:pf4j-update:jar:2.3.0
CAPSULE EXCEPTION: Error resolving dependencies. while processing attribute Allow-Snapshots: false (for stack trace, run with -Dcapsule.log=verbose)
Unable to initialize nextflow environment`

For 'nextflow -Dcapsule.log=verbose info': (note: I had to truncate this output because it was too long to fit in my Command Prompt window):
`CAPSULE: Transfer failed: capsule.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.googlecode.javaewah:JavaEWAH:jar:1.1.13 from/to central (https://repo1.maven.org/maven2/): java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
capsule.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.googlecode.javaewah:JavaEWAH:jar:1.1.13 from/to central (https://repo1.maven.org/maven2/): java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at capsule.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
        at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at capsule.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at java.base/javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:263)
        at java.base/javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
        at capsule.org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:505)
        at capsule.org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:377)
        at capsule.org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
        at capsule.org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
        at capsule.org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at capsule.org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at capsule.org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at capsule.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at capsule.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at capsule.org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:158)
        at capsule.org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:318)
        at capsule.org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:274)
        at capsule.org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
        at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
        at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
        ... 4 more
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1901)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
        at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
        at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
        at capsule.org.eclipse.aether.transport.http.SslSocketFactory.getSocketFactory(SslSocketFactory.java:45)
        at capsule.org.eclipse.aether.transport.http.SslSocketFactory.<init>(SslSocketFactory.java:39)
        at capsule.org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:166)
        at capsule.org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:59)
        at capsule.org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:130)
        at capsule.org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:93)
        at capsule.org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:110)
        at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)        at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at capsule.org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
        at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at capsule.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:373)
        at capsule.DependencyManager.resolve0(DependencyManager.java:377)
        at capsule.DependencyManager.resolveDependencies(DependencyManager.java:314)
        at MavenCapsule.resolve0(MavenCapsule.java:224)
        at Capsule.resolve(Capsule.java:3375)
        at Capsule.resolve(Capsule.java:3389)
        at Capsule.buildJavaProcess(Capsule.java:2228)
        at Capsule.buildProcess0(Capsule.java:1530)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.prelaunch0(Capsule.java:1494)
        at Capsule.prelaunch(Capsule.java:1487)
        at NextflowLoader.prelaunch(NextflowLoader.java:42)
        at Capsule.prepareForLaunch(Capsule.java:1339)
        at Capsule.launch(Capsule.java:1268)
        at Capsule.main0(Capsule.java:399)
        at Capsule.main(Capsule.java:379)
Caused by: java.security.KeyStoreException: problem accessing trust store
        at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
        at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
        at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:1053)
        at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:1023)
        at java.base/sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1198)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.security.Provider.newInstanceUtil(Provider.java:154)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1894)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
        at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
        at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
        at capsule.org.eclipse.aether.transport.http.SslSocketFactory.getSocketFactory(SslSocketFactory.java:45)
        at capsule.org.eclipse.aether.transport.http.SslSocketFactory.<init>(SslSocketFactory.java:39)
        at capsule.org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:166)
        at capsule.org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:59)
        at capsule.org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:130)
        at capsule.org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:93)
        at capsule.org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:110)
        at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)        at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at capsule.org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
        at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at capsule.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at capsule.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
        at capsule.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
        at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
        at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
        at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
        at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at capsule.org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        at capsule.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
        ... 17 more
Caused by: java.io.IOException: toDerInputStream rejects tag type 35
        at java.base/sun.security.util.DerValue.toDerInputStream(DerValue.java:858)
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1974)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
        at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
        at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
        at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
        ... 55 more`
`CAPSULE: Cleanup
CAPSULE EXCEPTION: Error resolving dependencies. while processing attribute Allow-Snapshots: false
java.lang.RuntimeException: Error resolving dependencies.
        at capsule.DependencyManager.resolve0(DependencyManager.java:382)
        at capsule.DependencyManager.resolveDependencies(DependencyManager.java:314)
        at MavenCapsule.resolve0(MavenCapsule.java:224)
        at Capsule.resolve(Capsule.java:3375)
        at Capsule.resolve(Capsule.java:3389)
        at Capsule.buildJavaProcess(Capsule.java:2228)
        at Capsule.buildProcess0(Capsule.java:1530)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.buildProcess(Capsule.java:1521)
        at Capsule.prelaunch0(Capsule.java:1494)
        at Capsule.prelaunch(Capsule.java:1487)
        at NextflowLoader.prelaunch(NextflowLoader.java:42)
        at Capsule.prepareForLaunch(Capsule.java:1339)
        at Capsule.launch(Capsule.java:1268)
        at Capsule.main0(Capsule.java:399)
        at Capsule.main(Capsule.java:379)
Caused by: capsule.org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.multiverse:multiverse-core:jar:0.7.0
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:387)
        at capsule.DependencyManager.resolve0(DependencyManager.java:377)
        ... 16 more
Caused by: capsule.org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.multiverse:multiverse-core:jar:0.7.0
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
        ... 17 more
Caused by: capsule.org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.multiverse:multiverse-core:jar:0.7.0
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        ... 18 more
Caused by: capsule.org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.multiverse:multiverse-core:pom:0.7.0 from/to central (https://repo1.maven.org/maven2/): java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
        ... 25 more
Caused by: capsule.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.multiverse:multiverse-core:pom:0.7.0 from/to central (https://repo1.maven.org/maven2/): java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 28 more
Caused by: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:263)
        at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
        at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:505)
        at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:377)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:158)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:318)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:274)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)        ... 33 more
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at java.security.Provider$Service.newInstance(Provider.java:1901)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
        at org.eclipse.aether.transport.http.SslSocketFactory.getSocketFactory(SslSocketFactory.java:45)
        at org.eclipse.aether.transport.http.SslSocketFactory.<init>(SslSocketFactory.java:39)
        at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:166)
        at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:59)
        at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:130)
        at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:93)
        at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:110)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
        ... 29 more
Caused by: java.security.KeyStoreException: problem accessing trust store
        at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
        at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:1053)
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:1023)
        at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1198)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.security.Provider.newInstanceUtil(Provider.java:154)
        at java.security.Provider$Service.newInstance(Provider.java:1894)
        ... 45 more
Caused by: java.io.IOException: toDerInputStream rejects tag type 35
        at sun.security.util.DerValue.toDerInputStream(DerValue.java:858)
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1974)
        at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.security.KeyStore.load(KeyStore.java:1479)
        at sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
        at sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
        at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
        at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
        ... 55 more
Unable to initialize nextflow environment`

### Environment 

* Nextflow version: I can't check because 'nextflow -v' also throws the above error
* Java version: 11.0.13
* Operating system: Linux
* Bash version: 'command not found'

**Comment by bentsherman** [comment]
How did you install Java? Also could you share the entire output of `java -version`?

**Comment by 18alia** [comment]
The full output of java- version:
`openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)`

**Comment by bentsherman** [comment]
Looks like you are actually using Java 8, which Nextflow no longer supports. Need to use 11 or later

**Comment by pditommaso** [comment]
Solved by https://github.com/nextflow-io/nextflow/issues/2951
