### ISSUE TITLE
Permission denied while running nextflow on HTCondor

### ISSUE THREAD

**Issue by asvarvara** [nextflow-io/nextflow#4370]
## Bug report 

Nextflow newbie here, so please forgive me if the question could sound silly.
I am running nextflow in a Conda environment installed via bioconda, using HTCondor as a job scheduler.
Nextflow working smoothly if I am running it on command line but it throws permission issues if I am using condor_submit.
I have googled a but the issue and found out someone encountered it with other Job scheduler, but no solutions were provided.
Can you please advice me on how to fix the issue in order to run epi2me-labs/wf-human-variation via nextflow

### Program output 

```
mkdir: cannot create directory '/.nextflow': Permission denied
Warning: Couldn't create cached classpath folder: /.nextflow/tmp/launcher/nextflow-one_23.04.3/wn-gpu-7-8-32.recas.ba.infn.it -- Maybe NXF_HOME is not writable?
Exception in thread "main" java.lang.ExceptionInInitializerError
        at nextflow.cli.Launcher.init(Launcher.groovy:122)
        at nextflow.cli.Launcher.<init>(Launcher.groovy:83)
        at nextflow.cli.Launcher.main(Launcher.groovy:653)
Caused by: java.lang.IllegalStateException: Cannot create path '/.nextflow' -- check file system access permission
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at nextflow.Const.getHomeDir(Const.groovy:110)
        at nextflow.Const.<clinit>(Const.groovy:50)
        ... 3 more
```

### Environment 

* Nextflow version: 23.04.3.5875
* Java version: 17.0.8-internal
* Operating system: Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by twrightsman** [comment]
Just for those who stumble upon this later, I could work around this issue by defining `NXF_HOME` to something. Somehow Nextflow/Java resolves the home directory to `/` in certain environments (in my case, running Nextflow in Python's `subprocess.run`). No obvious problems jumped out to me in the resolving code (below) but I'm not a Java expert:

https://github.com/nextflow-io/nextflow/blob/5b61afe01fbf461f94df7c78d19b88492683816e/modules/nf-commons/src/main/nextflow/Const.groovy#L44-L67
