### ISSUE TITLE
Google: Capture data staging errors for retry

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4480]
From Slack thread [here](https://nextflow.slack.com/archives/C02TLU7U57F/p1698393948148659).

> Is there a way of gracefully handling GCS 503 errors (bucket temporarily overloaded)?
> With the 503 bucket error, there is an error message but it's not recognized as a process exit code that can be handled.

![image](https://github.com/nextflow-io/nextflow/assets/465550/e4de02ea-668c-4a6f-9d26-606247fbfc09)

Log file: [nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/13249020/nextflow.log.txt)

From @bentsherman:

> The AWS Java SDK has built-in retries for errors like these, and Nextflow has a retry strategy around Azure API calls, so we could do a similar thing for Google if the SDK isn't doing it

**Comment by pditommaso** [comment]
It should be possible to handle via Google storage retry settings 

https://cloud.google.com/storage/docs/samples/storage-configure-retries#storage_configure_retries-java

it could possibile to apply it here 

https://github.com/nextflow-io/nextflow/blob/4c6f2e8541afae3a3960b04e71aaa62f744c1866/plugins/nf-google/src/main/nextflow/cloud/google/util/GsPathFactory.groovy#L61-L70

**Comment by pditommaso** [comment]
Add the error stack trace for reference 

```
Caused by:
  503 Service Unavailable
POST https://storage.googleapis.com/upload/storage/v1/b/bii-nextflow/o?name=plan_relax_and_predict_scaffolds/5b/b624d329120d870890a09f6d6f6f9c/.command.sh&uploadType=resumable
Service Unavailable

com.google.api.client.http.HttpResponseException: 503 Service Unavailable
POST https://storage.googleapis.com/upload/storage/v1/b/bii-nextflow/o?name=plan_relax_and_predict_scaffolds/5b/b624d329120d870890a09f6d6f6f9c/.command.sh&uploadType=resumable
Service Unavailable
	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.open(HttpStorageRpc.java:1000)
	at com.google.cloud.storage.ResumableMedia.lambda$null$0(ResumableMedia.java:37)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.Retrying.run(Retrying.java:54)
	at com.google.cloud.storage.ResumableMedia.lambda$startUploadForBlobInfo$1(ResumableMedia.java:34)
	at com.google.cloud.storage.BlobWriteChannel$Builder.build(BlobWriteChannel.java:315)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:609)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:579)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:101)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newWriteChannel(CloudStorageFileSystemProvider.java:467)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFileSystemProvider.java:299)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.write(Files.java:3425)
	at nextflow.executor.BashWrapperBuilder.write0(BashWrapperBuilder.groovy:356)
	at nextflow.executor.BashWrapperBuilder.build(BashWrapperBuilder.groovy:340)
	at nextflow.cloud.google.batch.GoogleBatchTaskHandler.submit(GoogleBatchTaskHandler.groovy:128)
	at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:195)
	at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:561)
	at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:386)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1047)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1132)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
