### ISSUE TITLE
Azure Storage Params File cannot be provided

### ISSUE THREAD

**Issue by mouzkolit** [nextflow-io/nextflow#4494]
## Bug report 

I would like to use a params file mounted at azure storage for configuration of my pipeline. 

### Expected behavior and actual behavior

The expected behaviour would be that the file is loaded and the actual behavior is that the Nextflow Session is missing Error

### Steps to reproduce the problem

(Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)

### Program output 

Nov-08 15:49:45.410 [main] DEBUG nextflow.Session - Session aborted -- Cause: No signature of method: static nextflow.script.ScriptBinding.readParams() is applicable for argument types: (String) values: [az://ont-vc-testdata/05887d8b4de9d2ec95eb43fcecc85217de7e4493dfb34fa5ae79d3e77ce007f7/params_sheet.yaml]
Possible solutions: getParams(), setParams(java.util.Map)
Nov-08 15:49:45.414 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingMethodException: No signature of method: static nextflow.script.ScriptBinding.readParams() is applicable for argument types: (String) values: [az://ont-vc-testdata/05887d8b4de9d2ec95eb43fcecc85217de7e4493dfb34fa5ae79d3e77ce007f7/params_sheet.yaml]
Possible solutions: getParams(), setParams(java.util.Map)
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1570)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1556)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1010)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
	at nextflow.script.ScriptBinding$ParamsMap.methodMissing(ScriptBinding.groovy)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:948)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1333)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1256)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_c8b2a99dab1427a0.runScript(Script_c8b2a99dab1427a0:2)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:144)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:236)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:242)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:137)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:372)
	at nextflow.cli.Launcher.run(Launcher.groovy:499)
	at nextflow.cli.Launcher.main(Launcher.groovy:670)

### Environment 

* Nextflow version: [?] 
* Java version: [?]
* Linux Ubuntu 20:03
* Bash version: (use the command `$SHELL --version`)

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
This error looks strange. Can you show me how you are loading this params file?

**Comment by mouzkolit** [comment]
This is how I would start my pipeline.: 
`nextflow run main.nf -c conf/azure.config -params-file az://ont-vc-testdata/05887d8b4de9d2ec95eb43fcecc85217de7e4493dfb34fa5ae79d3e77ce007f7/params.yaml
`
I can confirm that hte pipeline is running when the params file is accessible locally.

**Comment by bentsherman** [comment]
Which Nextflow version are you using?

**Comment by mouzkolit** [comment]
This is my nextflow version with additional system information:

  Version: 23.10.0 build 5889
  Created: 15-10-2023 15:07 UTC (17:07 CEST)
  System: Mac OS X 14.0
  Runtime: Groovy 3.0.19 on Java HotSpot(TM) 64-Bit Server VM 20.0.2+9-78
  Encoding: UTF-8 (UTF-8)

**Comment by bentsherman** [comment]
This error message is confusing me:
```
groovy.lang.MissingMethodException: No signature of method: static nextflow.script.ScriptBinding.readParams() is applicable for argument types: (String) values: [az://ont-vc-testdata/05887d8b4de9d2ec95eb43fcecc85217de7e4493dfb34fa5ae79d3e77ce007f7/params_sheet.yaml]
```

There is no `readParams()` method anywhere in the codebase (I asked about the version in case you were using an older version). I have no idea where this method call is coming from

Your command line looks correct. Are you trying to load params anywhere in your config or pipeline code? Any special params logic when importing modules (e.g. `addParams`)?

**Comment by mouzkolit** [comment]
Actually not, and I mean otherwise wouldn't this disturb also the loading from a local param-file?

**Comment by mouzkolit** [comment]
Hey I would like to ask if there is any update on this? Thank you very much:)
