### ISSUE TITLE
google-batch workflow interruptions with "UNKNOWN: channel closed"

### ISSUE THREAD

**Issue by Puumanamana** [nextflow-io/nextflow#4546]
## Bug report 

When running large workflows, the main process gets interrupted with the error `UNKNOWN: channel closed`.  

### Expected behavior and actual behavior

Expected: Normal execution of the workflow or more feedback about what the actual issue is.
Actual: Workflow interrupted

### Steps to reproduce the problem

Unable to reproduce, but happened a few times on large scale runs (custom RNA-seq pipeline)

### Program output 

The issue occurred for both the 1st and resumed run (~20,000 samples).

Here are the relevant parts of the log file:

**Beginning of log file**
```
Nov-27 12:46:24.677 [main] DEBUG nextflow.cli.Launcher - $> nextflow run 'https://github.com/Rome-Tx/nf-rome-quant.git' -resume -latest -r main -profile gcp --samplesheet samplesheet.csv --outdir 'gs://rome-quant-data/PPMI'
Nov-27 12:46:24.814 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.11.0-edge
Nov-27 12:46:24.852 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/cedric/.nextflow/plugins; core-plugins: nf-amazon@2.2.0,nf-azure@1.4.0,nf-cloudcache@0.3.1,nf-codecommit@0.1.6,nf-console@1.0.7,nf-ga4gh@1.1.1,nf-google@1.9.0,nf-tower@1.7.0,nf-wave@1.1.0
Nov-27 12:46:24.875 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Nov-27 12:46:24.877 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Nov-27 12:46:24.885 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.10.0 in 'deployment' mode
Nov-27 12:46:24.920 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Nov-27 12:46:24.960 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/cedric/.nextflow/scm
Nov-27 12:46:26.147 [main] DEBUG nextflow.scm.ProviderConfig - Detected SCM config: [providers:[github:[user:Puumanamana, password:ghp****]]]
Nov-27 12:46:26.187 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Nov-27 12:46:26.271 [main] DEBUG nextflow.scm.RepositoryFactory - Git url=nextflow.scm.GitUrl(https, null, github.com, Rome-Tx/nf-rome-quant) -> config=ProviderConfig[name: github, platform: github, server: https://github.com]
Nov-27 12:46:26.272 [main] DEBUG nextflow.scm.AssetManager - Repository URL: https://github.com/Rome-Tx/nf-rome-quant.git; Project: Rome-Tx/nf-rome-quant; Hub provider: github
Nov-27 12:46:26.789 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/cedric/.nextflow/assets/Rome-Tx/nf-rome-quant/.git/config; branch: master; remote: origin; url: https://github.com/Rome-Tx/nf-rome-quant.git
Nov-27 12:46:26.791 [main] INFO  nextflow.cli.CmdRun - Pulling Rome-Tx/nf-rome-quant ...
Nov-27 12:46:26.792 [main] DEBUG nextflow.scm.AssetManager - Pull pipeline Rome-Tx/nf-rome-quant  -- Using local path: /home/cedric/.nextflow/assets/Rome-Tx/nf-rome-quant
Nov-27 12:46:28.132 [main] INFO  nextflow.cli.CmdRun -  Already-up-to-date
Nov-27 12:46:28.160 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/cedric/.nextflow/assets/Rome-Tx/nf-rome-quant/nextflow.config
Nov-27 12:46:28.162 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/cedric/.nextflow/assets/Rome-Tx/nf-rome-quant/nextflow.config
Nov-27 12:46:28.184 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `gcp`
Nov-27 12:46:29.181 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [geo, test_stub, gcp, test_geo, test_hs]
Nov-27 12:46:29.260 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Nov-27 12:46:29.262 [main] INFO  nextflow.cli.CmdRun - Launching `https://github.com/Rome-Tx/nf-rome-quant` [curious_nightingale] DSL2 - revision: ef4a87899c [main]
Nov-27 12:46:29.263 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[nf-google@1.9.0]
Nov-27 12:46:29.263 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-google@1.9.0]
Nov-27 12:46:29.263 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-google version: 1.9.0
Nov-27 12:46:29.283 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-google@1.9.0' resolved
Nov-27 12:46:29.284 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-google@1.9.0'
Nov-27 12:46:29.353 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-google@1.9.0
Nov-27 12:46:29.369 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/cedric/.nextflow/secrets/store.json
Nov-27 12:46:29.374 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@61d60e38] - activable => nextflow.secret.LocalSecretsProvider@61d60e38
Nov-27 12:46:29.547 [main] DEBUG nextflow.Session - Session UUID: 3a9c6e86-ce88-46f6-8304-c34dfbb22322
Nov-27 12:46:29.548 [main] DEBUG nextflow.Session - Run name: curious_nightingale
Nov-27 12:46:29.549 [main] DEBUG nextflow.Session - Executor pool size: 8
Nov-27 12:46:29.820 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Nov-27 12:46:29.830 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=24; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Nov-27 12:46:29.885 [main] DEBUG nextflow.cli.CmdRun -
  Version: 23.11.0-edge build 5891
  Created: 24-11-2023 20:24 UTC
  System: Linux 5.15.0-1027-gcp
  Runtime: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 11.0.20.1+1-post-Ubuntu-0ubuntu120.04
  Encoding: UTF-8 (UTF-8)
  Process: 1810553@nf-tower-main [10.128.0.2]
  CPUs: 8 - Mem: 62.8 GB (51 GB) - Swap: 0 (0)
Nov-27 12:46:29.927 [main] DEBUG nextflow.file.FileHelper - Can't check if specified path is NFS (1): gs://nxf-work/romequant/cedric

Nov-27 12:46:29.927 [main] DEBUG nextflow.Session - Work-dir: gs://nxf-work/romequant/cedric [null]
Nov-27 12:46:29.928 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/cedric/.nextflow/assets/Rome-Tx/nf-rome-quant/bin
Nov-27 12:46:29.972 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[GoogleLifeSciencesExecutor, GoogleBatchExecutor]
Nov-27 12:46:29.997 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Nov-27 12:46:30.095 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Nov-27 12:46:30.114 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Nov-27 12:46:30.440 [main] DEBUG nextflow.Session - Session start
Nov-27 12:46:30.463 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow started -- trace file: /home/cedric/runs/ROME-datasets/Neuro/PPMI/trace-20231127-45990004.txt
Nov-27 12:46:30.481 [main] DEBUG nextflow.Session - Using default localLib path: /home/cedric/.nextflow/assets/Rome-Tx/nf-rome-quant/lib
Nov-27 12:46:30.488 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/cedric/.nextflow/assets/Rome-Tx/nf-rome-quant/lib
Nov-27 12:46:32.545 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
```

**Error**
```
Nov-27 16:14:33.705 [Task submitter] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=ROME_QUANT_HS:ALUEM_QUANT (PPMI-Phase2-IR1.3066.V02.0003445770.5104-SL-3015.L003); work-dir=gs://nxf-work/romequant/cedric/d4/02dd19cfcb226f03dcec4534c78fe7
  error [com.google.api.gax.rpc.UnknownException]: io.grpc.StatusRuntimeException: UNKNOWN: channel closed
Nov-27 16:14:33.709 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=ROME_QUANT_HS:SALMON_QUANT (PPMI-Phase2-IR1.3968.V02.0003443442.5104-SL-2900.L002); work-dir=gs://nxf-work/romequant/cedric/e3/a44f5803d2823e02badbf944576e0e                                                                            error [com.google.api.gax.rpc.UnknownException]: io.grpc.StatusRuntimeException: UNKNOWN: channel closed
Nov-27 16:14:33.733 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'ROME_QUANT_HS:ALUEM_QUANT (PPMI-Phase2-IR1.3066.V02.0003445770.5104-SL-3015.L003)'
Caused by:
  UNKNOWN: channel closed

com.google.api.gax.rpc.UnknownException: io.grpc.StatusRuntimeException: UNKNOWN: channel closed                                                                                                                                                            at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:119)
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)                                                                                                                                                          at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)                                                                                                                                                          at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
        at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
        at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:568)                                                                                                                                                                           at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)                                                                                                                                                 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                                                                       [115/440]
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
                at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
                at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
                at com.google.cloud.batch.v1.BatchServiceClient.createJob(BatchServiceClient.java:316)
                at com.google.cloud.batch.v1.BatchServiceClient.createJob(BatchServiceClient.java:248)
                at nextflow.cloud.google.batch.client.BatchClient.submitJob(BatchClient.groovy:85)
                at nextflow.cloud.google.batch.GoogleBatchTaskHandler.submit(GoogleBatchTaskHandler.groovy:136)
                at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:196)
                at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:565)
                at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:390)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
                at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1042)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1128)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
                at groovy.lang.Closure.call(Closure.java:427)
                at groovy.lang.Closure.call(Closure.java:406)
                at groovy.lang.Closure.run(Closure.java:498)
                ... 1 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: channel closed
        at io.grpc.Status.asRuntimeException(Status.java:537)
        ... 14 common frames omitted
Caused by: java.nio.channels.ClosedChannelException: null                                                                                                                                                                                   [86/440]
        at io.grpc.netty.shaded.io.grpc.netty.Utils.statusFromThrowable(Utils.java:275)
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.onConnectionError(NettyClientHandler.java:507)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:654)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$1.operationComplete(DefaultHttp2ConnectionEncoder.java:535)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$1.operationComplete(DefaultHttp2ConnectionEncoder.java:530)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:386)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryFailure(Http2CodecUtil.java:306)
        at io.grpc.netty.shaded.io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
        at io.grpc.netty.shaded.io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:57)
        at io.grpc.netty.shaded.io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:877)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:845)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:800)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.flush(SslHandler.java:781)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
        at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.flush(WriteQueue.java:143)
        at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.access$000(WriteQueue.java:35)
        at io.grpc.netty.shaded.io.grpc.netty.WriteQueue$1.run(WriteQueue.java:47)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted
Caused by: io.grpc.netty.shaded.io.netty.channel.StacklessClosedChannelException: null                                                                                                                                                      [31/440]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: sendAddress(..) failed: Connection reset by peer
Nov-27 16:14:33.748 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: io.grpc.StatusRuntimeException: UNKNOWN: channel closed
Nov-27 16:14:33.755 [Task submitter] DEBUG nextflow.Session - The following nodes are still active:
```

### Environment 

* Nextflow version: `23.11.0-edge build 5891`
* Java version: `openjdk version "11.0.20.1" 2023-08-24`
* Operating system: `Linux nf-tower-main 5.15.0-1027-gcp #34~20.04.1-Ubuntu SMP Mon Jan 9 18:40:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Bash version: `zsh 5.8 (x86_64-ubuntu-linux-gnu)`

**Comment by sbthandras** [comment]
Has there been an update on this?

**Comment by bentsherman** [comment]
Tentatively closing. We made a bunch of improvements to the error handling in the google batch executor in 24.10 and 25.04, and I suspect this error is also addressed. Feel free to re-open if the issue persists
