### ISSUE TITLE
AZURE_STORAGE_SAS_TOKEN is not propagated from the environment

### ISSUE THREAD

**Issue by alberto-miranda** [nextflow-io/nextflow#4605]
### Expected behavior and actual behavior

While rewriting some testing pipelines for Fusion using an Azure backend we hit a nextflow error (`ERROR ~ Missing AZURE_STORAGE_ACCOUNT_KEY or AZURE_STORAGE_SAS_TOKEN`) despite `AZURE_STORAGE_SAS_TOKEN` being properly exported to the environment.

### Steps to reproduce the problem

The commands below reproduce the problem with the `hello` pipeline: 
```shell
$ export AZURE_STORAGE_ACCOUNT_NAME=<redacted>
$ export AZURE_STORAGE_SAS_TOKEN=<redacted>
$ nextflow run hello -profile azure                                                                                     
```

Note that an `azure` profile exists in `nextflow.config` with the following contents:

```groovy
profiles {
  azure {
    workDir = 'az://' + (System.getenv("AZURE_BUCKET") ?: 'fusion-develop')  + '/scratch'
    docker {
        enabled = true
        envWhitelist = 'AZURE_BATCH_ACCOUNT_KEY,AZURE_BATCH_ACCOUNT_NAME,AZURE_STORAGE_ACCOUNT_KEY,AZURE_STORAGE_ACCOUNT_NAME,AZURE_STORAGE_SAS_TOKEN,FUSION_LOG_OUTPUT,FUSION_LOG_LEVEL,FUSION_CHUNK_SIZE,FUSION_USE_SUID'
    }
  }
}
```

### Program output 

The configuration above generates the following output:

```shell
N E X T F L O W  ~  version 23.10.0
ERROR ~ Missing AZURE_STORAGE_ACCOUNT_KEY or AZURE_STORAGE_SAS_TOKEN

 -- Check '.nextflow.log' file for details
```

And the following `.nextflow.log`:

```
Dec-19 20:32:22.860 [main] DEBUG nextflow.cli.Launcher - $> nextflow run hello -profile azure
Dec-19 20:32:22.979 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.10.0
Dec-19 20:32:22.992 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/amiranda/.nextflow/plugins; core-plugins: nf-amazon@2.1.4,nf-azure@1.3.2,nf-cloudcache@0.3.0,nf-codecommit@0.1.5,nf-console@1.0.6,nf-ga4gh@1.1.0,nf-google@1.8.3,nf-tower@1.6.3,nf-wave@1.0.0
Dec-19 20:32:22.998 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Dec-19 20:32:22.999 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Dec-19 20:32:23.001 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Dec-19 20:32:23.008 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Dec-19 20:32:23.027 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/amiranda/.nextflow/scm
Dec-19 20:32:23.035 [main] DEBUG nextflow.scm.AssetManager - Listing projects in folder: /home/amiranda/.nextflow/assets
Dec-19 20:32:23.398 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/amiranda/.nextflow/assets/nextflow-io/helloworld/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
Dec-19 20:32:23.423 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Dec-19 20:32:23.433 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/amiranda/.nextflow/assets/nextflow-io/helloworld/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
Dec-19 20:32:27.312 [main] INFO  nextflow.scm.AssetManager - NOTE: Your local project version looks outdated - a different revision is available in the remote repository [7588c46ffe]
Dec-19 20:32:27.322 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/amiranda/.nextflow/assets/nextflow-io/helloworld/nextflow.config
Dec-19 20:32:27.323 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/amiranda/dev/fusionfs/nextflow.config
Dec-19 20:32:27.323 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/amiranda/.nextflow/assets/nextflow-io/helloworld/nextflow.config
Dec-19 20:32:27.323 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/amiranda/dev/fusionfs/nextflow.config
Dec-19 20:32:27.331 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `azure`
Dec-19 20:32:27.344 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `azure`
Dec-19 20:32:27.501 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [aws_ci, coverage, no_privileged, minio, google, aws, azure]
Dec-19 20:32:27.516 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Dec-19 20:32:27.517 [main] INFO  nextflow.cli.CmdRun - Launching `https://github.com/nextflow-io/helloworld` [determined_mahavira] DSL2 - revision: 1d71f857bb [master]
Dec-19 20:32:27.518 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[nf-azure@1.3.2]
Dec-19 20:32:27.518 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-azure@1.3.2, nf-wave@1.0.0]
Dec-19 20:32:27.518 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-azure version: 1.3.2
Dec-19 20:32:27.524 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-azure@1.3.2' resolved
Dec-19 20:32:27.525 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-azure@1.3.2'
Dec-19 20:32:27.541 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-azure@1.3.2
Dec-19 20:32:27.560 [main] DEBUG nextflow.file.FileHelper - > Added 'AzFileSystemProvider' to list of installed providers [az]
Dec-19 20:32:27.560 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-wave version: 1.0.0
Dec-19 20:32:27.561 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-wave@1.0.0' resolved
Dec-19 20:32:27.561 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-wave@1.0.0'
Dec-19 20:32:27.566 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-wave@1.0.0
Dec-19 20:32:27.571 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/amiranda/.nextflow/secrets/store.json
Dec-19 20:32:27.573 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@61191222] - activable => nextflow.secret.LocalSecretsProvider@61191222
Dec-19 20:32:27.613 [main] DEBUG nextflow.Session - Session UUID: e2b769d9-2dcc-4e0e-bb0b-62b6892d216e
Dec-19 20:32:27.613 [main] DEBUG nextflow.Session - Run name: determined_mahavira
Dec-19 20:32:27.614 [main] DEBUG nextflow.Session - Executor pool size: 12
Dec-19 20:32:27.619 [main] DEBUG n.cloud.azure.file.AzPathFactory - Creating Azure path factory
Dec-19 20:32:27.636 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: AzFileSystemProvider
Dec-19 20:32:27.636 [main] ERROR nextflow.cli.Launcher - Missing AZURE_STORAGE_ACCOUNT_KEY or AZURE_STORAGE_SAS_TOKEN
java.lang.IllegalArgumentException: Missing AZURE_STORAGE_ACCOUNT_KEY or AZURE_STORAGE_SAS_TOKEN
	at nextflow.cloud.azure.nio.AzFileSystemProvider.newFileSystem0(AzFileSystemProvider.groovy:223)
	at nextflow.cloud.azure.nio.AzFileSystemProvider.newFileSystem(AzFileSystemProvider.groovy:181)
	at nextflow.cloud.azure.nio.AzFileSystemProvider.newFileSystem(AzFileSystemProvider.groovy)
	at nextflow.file.FileHelper$_getOrCreateFileSystemFor_closure8.doCall(FileHelper.groovy:679)
	at nextflow.file.FileHelper$_getOrCreateFileSystemFor_closure8.call(FileHelper.groovy)
	at nextflow.extension.Bolts.withLock(Bolts.groovy:337)
	at nextflow.extension.Bolts.withLock(Bolts.groovy)
	at nextflow.file.FileHelper.getOrCreateFileSystemFor(FileHelper.groovy:673)
	at nextflow.cloud.azure.file.AzPathFactory.getFileSystem(AzPathFactory.groovy:81)
	at nextflow.cloud.azure.file.AzPathFactory.parseUri(AzPathFactory.groovy:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.file.FileSystemPathFactory$_parse_closure1.doCall(FileSystemPathFactory.groovy:76)
	at nextflow.file.FileSystemPathFactory$_parse_closure1.call(FileSystemPathFactory.groovy)
	at nextflow.file.FileSystemPathFactory.lookup0(FileSystemPathFactory.groovy:104)
	at nextflow.file.FileSystemPathFactory.parse(FileSystemPathFactory.groovy:76)
	at nextflow.file.FileHelper.asPath0(FileHelper.groovy:301)
	at nextflow.file.FileHelper.asPath(FileHelper.groovy:297)
	at nextflow.extension.Bolts.asType(Bolts.groovy:438)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1024)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1015)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:603)
	at nextflow.Session.create(Session.groovy:366)
	at nextflow.Session.<init>(Session.groovy:295)
	at nextflow.script.ScriptRunner.<init>(ScriptRunner.groovy:78)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:343)
	at nextflow.cli.Launcher.run(Launcher.groovy:499)
	at nextflow.cli.Launcher.main(Launcher.groovy:670)
```

### Environment 

* Nextflow version: 23.10.0
* Java version: 21.0.1 (Temurin)
* Operating system: Linux
* Bash version: zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

**Comment by alberto-miranda** [comment]
Assuming filtering the propagation is not the intended behavior, the problem seems to come from the following code in [plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzStorageOpts.groovy](https://github.com/nextflow-io/nextflow/blob/58937831ee789c32160c79c94ace97ff89e322ce/plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzStorageOpts.groovy#L44):

```groovy
        this.accountKey = config.accountKey ?: sysEnv.get('AZURE_STORAGE_ACCOUNT_KEY')
        this.accountName = config.accountName ?: sysEnv.get('AZURE_STORAGE_ACCOUNT_NAME')
        this.sasToken = config.sasToken
```

While `AZURE_STORAGE_ACCOUNT_KEY` and `AZURE_STORAGE_ACCOUNT_NAME` are read from the process environment if available, the SAS Token is only read from the configuration.
