### ISSUE TITLE
Nextflow config fails to parse some environment variables

### ISSUE THREAD

**Issue by alexdhill** [nextflow-io/nextflow#4665]
## Bug report 

Nextflow config files cannot access environment variables unless specified in the `nextflow run` command.

### Expected behavior and actual behavior

Utilization of environment variable `UID` and `GID` in the nextflow.config file. This is being passed to the docker.runOptions to specify a container user to prevent the work directory being generated by nobody:nogroup.

When run using `nextflow run ...`, nextflow cannot parse the config file (see error below).

When run as `UID=$UID nextflow run ...` the config file is able to utilize the UID variable as expected.

### Steps to reproduce the problem

Create a dummy nextflow workflow. Add the docker.runOptions="-u=$UID" in nextflow.config. Attempt to run both commands above. 

### Program output 

`ERROR ~ Unknown config attribute `UID` -- check config file`

Nextflow Log:
```
Jan-16 13:57:48.607 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf -resume -with-tower -w test_work
Jan-16 13:57:49.282 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.2
Jan-16 13:57:49.334 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.3
Jan-16 13:57:49.415 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jan-16 13:57:49.431 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jan-16 13:57:49.438 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jan-16 13:57:49.517 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jan-16 13:57:49.565 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /path/to/nextflow.config
Jan-16 13:57:49.567 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /path/to/nextflow.config
Jan-16 13:57:49.627 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jan-16 13:57:51.041 [main] DEBUG nextflow.config.ConfigBuilder - In the following config snippet the attribute `UID` is empty:
  docker {
  	enabled=false
  	runOptions=[-u="[:]:[:]", '--pull=always']
  }

Jan-16 13:57:51.052 [main] ERROR nextflow.cli.Launcher - Unknown config attribute `UID` -- check config file: /path/to/nextflow.config
nextflow.exception.ConfigParseException: Unknown config attribute `UID` -- check config file: /path/to/nextflow.config
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:461)
	at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:448)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:422)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:371)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:316)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:803)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:816)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:321)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)

```

### Environment 

* Nextflow version: 23.04.2 
* Java version: openjdk 17.0.3-internal 2022-04-19
* Operating system: Linux ubuntu:22.04.02
* Bash version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Comment by bentsherman** [comment]
You have to escape the dollar sign, otherwise it will be interpreted as a variable in the config:
```groovy
docker.runOptions="-u=\$UID"
```
