### ISSUE TITLE
Add retry capability to publishDir

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#480]
I ran into a situation where a few files failed to get copied to my results directory by `publishDir`.  The errors were recorded in the `.nextflow.log` and I was able to recover the files, but it would be nice if we could add retry capability to `publishDir` as well.  This is similar to https://github.com/nextflow-io/nextflow/issues/295.

If it helps, here is the exception:
```
Oct-11 08:18:05.412 [pool-3-thread-114] WARN  nextflow.processor.PublishDir - Failed to publish file: /mnt/efs/nextflow/run.f08ced71-c74b-4ffb-b5b4-c0d3a86dff53/work/04/84092dd634745a1477f6a7df64f0be/part-r-04226-6a9f1652-4e4e-4081-a96a-df81b52f802c_ipr.json.gz; to: /sgi-pipeline-dev/deeplearning/data/1610_nervanaProcessed/interproscan/val_results/part-r-04226-6a9f1652-4e4e-4081-a96a-df81b52f802c_ipr.json.gz [copy] -- See log file for details
java.io.IOException: Failed to put data into Amazon S3 object
        at com.upplication.s3fs.S3OutputStream.putObject(S3OutputStream.java:694)
        at com.upplication.s3fs.S3OutputStream.putObject(S3OutputStream.java:669)
        at com.upplication.s3fs.S3OutputStream.close(S3OutputStream.java:504)
        at java.nio.file.Files.copy(Files.java:3028)
        at nextflow.file.CopyMoveHelper.copyFile(CopyMoveHelper.java:127)
        at nextflow.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:208)
        at nextflow.file.FileHelper.copyPath(FileHelper.groovy:830)
        at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:306)
        at nextflow.processor.PublishDir.processFile(PublishDir.groovy:281)
        at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:267)
        at sun.reflect.GeneratedMethodAccessor362.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
        at nextflow.processor.PublishDir$_apply_closure2.doCall(PublishDir.groovy:240)
        at nextflow.processor.PublishDir$_apply_closure2.call(PublishDir.groovy)
        at groovy.lang.Closure.run(Closure.java:495)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.ResetException: Failed to reset the request input stream;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)
        at com.amazonaws.http.AmazonHttpClient.resetRequestInputStream(AmazonHttpClient.java:1001)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:827)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:723)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:475)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:437)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:386)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3999)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1573)
        at com.upplication.s3fs.S3OutputStream.putObject(S3OutputStream.java:692)
        ... 27 common frames omitted
Caused by: java.io.IOException: Resetting to invalid mark
        at java.io.BufferedInputStream.reset(BufferedInputStream.java:448)
        at com.amazonaws.internal.SdkBufferedInputStream.reset(SdkBufferedInputStream.java:106)
        at com.amazonaws.internal.SdkFilterInputStream.reset(SdkFilterInputStream.java:102)
        at com.amazonaws.event.ProgressInputStream.reset(ProgressInputStream.java:139)
        at com.amazonaws.internal.SdkFilterInputStream.reset(SdkFilterInputStream.java:102)
        at com.amazonaws.http.AmazonHttpClient.resetRequestInputStream(AmazonHttpClient.java:999)
        ... 35 common frames omitted
```

**Comment by zichner** [comment]
I have the same problem. In my case caused by an `Unable to execute HTTP request: Socket is closed` error.

<details><summary>Full error message</summary>

```
Caused by:
  Unable to execute HTTP request: Socket is closed

java.io.IOException: Failed to put data into Amazon S3 object
        at com.upplication.s3fs.S3OutputStream.putObject(S3OutputStream.java:560)
        at com.upplication.s3fs.S3OutputStream.putObject(S3OutputStream.java:535)
        at com.upplication.s3fs.S3OutputStream.close(S3OutputStream.java:373)
        at java.nio.file.Files.write(Files.java:3300)
        at sun.reflect.GeneratedMethodAccessor1017.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at nextflow.executor.BashWrapperBuilder.build(BashWrapperBuilder.groovy:576)
        at nextflow.executor.BashWrapperBuilder$build$0.call(Unknown Source)
        at nextflow.cloud.aws.batch.AwsBatchTaskHandler.createTaskWrapper(AwsBatchTaskHandler.groovy:304)
        at nextflow.cloud.aws.batch.AwsBatchTaskHandler.submit(AwsBatchTaskHandler.groovy:283)
        at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:210)
        at nextflow.processor.ParallelPollingMonitor.submit0(ParallelPollingMonitor.groovy:68)
        at nextflow.processor.ParallelPollingMonitor$1.invoke(ParallelPollingMonitor.groovy:77)
        at nextflow.util.ThrottlingExecutor$Recoverable.call(ThrottlingExecutor.groovy:433)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Socket is closed
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1755)
        at com.upplication.s3fs.S3OutputStream.putObject(S3OutputStream.java:558)
        ... 23 common frames omitted
Caused by: java.net.SocketException: Socket is closed
        at java.net.Socket.setSoTimeout(Socket.java:1137)
        at sun.security.ssl.BaseSSLSocketImpl.setSoTimeout(BaseSSLSocketImpl.java:633)
        at sun.security.ssl.SSLSocketImpl.setSoTimeout(SSLSocketImpl.java:2565)
        at org.apache.http.impl.BHttpConnectionBase.fillInputBuffer(BHttpConnectionBase.java:346)
        at org.apache.http.impl.BHttpConnectionBase.awaitInput(BHttpConnectionBase.java:354)
        at org.apache.http.impl.DefaultBHttpClientConnection.isResponseAvailable(DefaultBHttpClientConnection.java:130)
        at org.apache.http.impl.conn.CPoolProxy.isResponseAvailable(CPoolProxy.java:150)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:219)
        at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1238)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
        ... 33 common frames omitted
```

</details>
<p>
  
</p>  
  
It might also be useful if one could specify a waiting period between two `publishDir` attempts.
