### ISSUE TITLE
Nextflow console is broken using version 24.01.0-edge

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#4805]
## Bug report 

When running the console command the following error is reported 

```
Mar-09 12:17:14.332 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.NoClassDefFoundError: com/github/javaparser/ast/nodeTypes/modifiers/NodeWithPublicModifier
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3429)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2608)
	at org.codehaus.groovy.reflection.CachedClass$2.lambda$initValue$4(CachedClass.java:68)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.codehaus.groovy.reflection.CachedClass.doPrivileged(CachedClass.java:160)
	at org.codehaus.groovy.reflection.CachedClass.access$000(CachedClass.java:45)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:73)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:63)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:50)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:37)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:276)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:232)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:242)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:166)
	at groovy.runtime.metaclass.CustomMetaClassCreationHandle.createNormalMetaClass(CustomMetaClassCreationHandle.java:56)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:156)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:139)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:271)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:314)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:269)
	at org.codehaus.groovy.vmplugin.v8.Selector$InitSelector.getMetaClass(Selector.java:406)
	at org.codehaus.groovy.vmplugin.v8.Selector$MethodSelector.setCallSiteTarget(Selector.java:1020)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fallback(IndyInterface.java:360)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.access$000(IndyInterface.java:50)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface$FallbackSupplier.get(IndyInterface.java:282)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.lambda$fromCache$1(IndyInterface.java:304)
	at org.codehaus.groovy.vmplugin.v8.CacheableCallSite.getAndPut(CacheableCallSite.java:70)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.lambda$fromCache$2(IndyInterface.java:301)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.doWithCallSite(IndyInterface.java:376)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:298)
	at nextflow.ui.console.ConsoleRunner.run(ConsoleRunner.groovy:57)
	at nextflow.cli.CmdConsole.run(CmdConsole.groovy:50)
	at nextflow.cli.Launcher.run(Launcher.groovy:500)
	at nextflow.cli.Launcher.main(Launcher.groovy:672)
Caused by: java.lang.ClassNotFoundException: com.github.javaparser.ast.nodeTypes.modifiers.NodeWithPublicModifier
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:144)
	... 35 common frames omitted

```

**Comment by pditommaso** [comment]
Solved by baf29110
