### ISSUE TITLE
Specific Singularity container not working when running inside of Nextflow

### ISSUE THREAD

**Issue by marchoeppner** [nextflow-io/nextflow#5132]
### Expected behavior and actual behavior

I have encountered an odd issue where a very specific singularity-converted Docker container will happily work outside of Nextflow, but throws an error when running inside of Nextflow. I can reproduce this insofar as running the .command.sh script inside the container works, but running .command.run will produce the same error. So presumably it has something to do with the many flags and exports that are happening in the run file (?). 

[Dockerhub](https://hub.docker.com/layers/biocontainers/ncbi-datasets-cli/16.22.1_cv1/images/sha256-3535d6bc909dbee0e72abfa9ca079a422b08b03dced4bbf7e0affae2a0118e9e?context=explore)

Interestingly, there is an [alterantive](https://hub.docker.com/layers/staphb/ncbi-datasets/16.22.1/images/sha256-b7a7e5f8e2eea019ddebac2003682962b61cc1ea35bfd1a49a876030e345e9e9?context=explore) Dockerhub project - and that container produces the exact same error. So it isn't specifically that one container, but more likely the software package that gets "broken" by how Nextflow wraps the singularity execution.

The package works fine when running it via Conda (or, as mentioned, with Singularity outside of Nextflow). 

### Steps to reproduce the problem

Inside versus outside of Nextflow, with Singularity:

```BASH
datasets download genome accession GCF_900085275.1 --include gff3,genome,seq-report --filename GCF_900085275.1.zip
```
### Program output 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xada83e]

goroutine 1 [running]:
datasets_cli/v2/datasets.pagePtrWithRetryFor[...](0x1?, {0xde5c40?, 0xc00000e478})
        apps/public/Datasets/v2/datasets/datasets/PageProcessor.go:268 +0x1be
datasets_cli/v2/datasets.ProcessPages[...]({0xdea950, 0xc0002207b0}, {0xde5c40, 0xc00000e478}, {0xdea340, 0xc000073180?}, 0x7fffffffffffffff, 0x0)
        apps/public/Datasets/v2/datasets/datasets/PageProcessor.go:398 +0x136
datasets_cli/v2/datasets.(*GenomeDownloader).setAssemblyAccsForRequest(0xc000030c60, 0xc000212ea0)
        apps/public/Datasets/v2/datasets/datasets/GenomeDownloader.go:35 +0x1a6
datasets_cli/v2/datasets.GenomeWithAccessions.func1(0xc00018fc40?)
        apps/public/Datasets/v2/datasets/datasets/GenomeDownloader.go:120 +0x4f
datasets_cli/v2/datasets.NewGenomeDownloader(0xc000073160, {0xc00000cae0, 0xc00000caf8, 0xc00000cb10, 0xc00000cb28, 0xc00000cb40, 0xc00000cb58, 0xc00019f440, 0xc00019f470, 0xc00000cb70, ...})
        apps/public/Datasets/v2/datasets/datasets/GenomeDownloader.go:177 +0x148
datasets_cli/v2/datasets.createDownloadGenomeAccessionCmd.func1(0xc0001f9500?, {0xc00007ed70?, 0x1?, 0x5?})
        apps/public/Datasets/v2/datasets/datasets/DownloadGenomeAccession.go:46 +0x318
github.com/spf13/cobra.(*Command).execute(0xc0001f9500, {0xc00007ed20, 0x5, 0x5})
        external/com_github_spf13_cobra/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x133df00)
        external/com_github_spf13_cobra/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        external/com_github_spf13_cobra/command.go:992
datasets_cli/v2/datasets.Execute()
        apps/public/Datasets/v2/datasets/datasets/root.go:482 +0x25
main.main()
        apps/public/Datasets/v2/cmd/datasets/main.go:10 +0x17
``` 

### Environment 

* Nextflow version: 23.10.0, 24.04.3 
* Java version: 11.0.23
* Operating system: Linux (AlmaLinux 9.4)
* Bash version: 5.1.8
* Singularity version: 4.1.3

### Additional context

You are also welcome to run the pipeline test, but will have to install the references first (which may take a while, or fail - still under development). 

```BASH
nextflow run marchoeppner/gabi -profile singularity --build_references --reference_base /path/to/local/refs --run_name build -r dev
nextflow run marchoeppner/gabi -profile singularity,test --reference_base /path/to/local/refs  -r dev
```

**Comment by marchoeppner** [comment]
Right - so the cause of this was that Nextflow strips away environment variables from the host, including, apparently, HTTP_PROXY and HTTPS_PROXY. Using singularity.envWhitelist = "HTTP_PROXY,HTTPS_PROXY", seems to have fixed this.
