### ISSUE TITLE
nextflow creates wrong number of instances in a cluster when there is a trailing whitespace in the subnetId field

### ISSUE THREAD

**Issue by gnetsanet** [nextflow-io/nextflow#518]
https://groups.google.com/d/msg/nextflow/A6Po2cNsE-A/0RbmA_WQBQAJ

```
cloud {
 imageId = 'ami-b069d4ca'
 instanceType = 'm4.xlarge'
 subnetId = 'subnet-e838108d '
 sharedStorageId = 'fs-1803efd1'
 sharedStorageMount = '/mnt/efs'
 spotPrice = 0.06
 keyName = 'nextflow-pem'
 userName = 'ec2-user'


}
```

```
Nov-10 17:25:07.273 [main] DEBUG nextflow.cloud.aws.AmazonCloudDriver - AWS submitting launch request for 1 SPOT instances; config: imageId=ami-b069d4ca, instanceType=m4.xlarge, spotPrice=0.06
Nov-10 17:25:09.550 [main] ERROR nextflow.cli.Launcher - @unknown
com.amazonaws.services.ec2.model.AmazonEC2Exception: An internal error has occurred (Service: AmazonEC2; Status Code: 500; Error Code: InternalError; Request ID: d3d74b5b-0279-4fbf-a972-24f296dd193f)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:13930)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:13906)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeRequestSpotInstances(AmazonEC2Client.java:12901)
	at com.amazonaws.services.ec2.AmazonEC2Client.requestSpotInstances(AmazonEC2Client.java:12877)
	at nextflow.cloud.aws.AmazonCloudDriver.launchSpotInstances0(AmazonCloudDriver.groovy:479)
	at nextflow.cloud.aws.AmazonCloudDriver.launchInstances(AmazonCloudDriver.groovy:461)
	at nextflow.cloud.CloudDriver$launchInstances$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at nextflow.cli.CmdCloud.addNodes0(CmdCloud.groovy:288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:82)
	at nextflow.cli.CmdCloud.this$dist$invoke$2(CmdCloud.groovy)
	at nextflow.cli.CmdCloud$CreateCluster.methodMissing(CmdCloud.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:939)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1262)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at nextflow.cli.CmdCloud$CreateCluster.apply(CmdCloud.groovy:511)
	at nextflow.cli.CmdCloud$SubCmd$apply.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nextflow.cli.CmdCloud.run(CmdCloud.groovy:181)
	at nextflow.cli.Launcher.run(Launcher.groovy:415)
	at nextflow.cli.Launcher.main(Launcher.groovy:569)
```

**Comment by pditommaso** [comment]
My understanding is that providing an invalid request field, the AWS client misinterprets and the related error condition, trying to execute it multiple times. Hence the execution of more instance than the requested ones. Ultimately it's a AWS client error. 

However it's user role provide a valid input request.
