### ISSUE TITLE
Caused by: java.nio.file.FileAlreadyExistsException: /tmp

### ISSUE THREAD

**Issue by daichengxin** [nextflow-io/nextflow#5459]
Hi all, suddenly there's this error when performing `nextflow run test.nf`. How do I fix this?

test.nf:
print(11111)

Nov-01 17:04:31.145 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.ExceptionInInitializerError: null
        at nextflow.util.LoggerHelper$RollOnStartupPolicy.isTriggeringEvent(LoggerHelper.groovy:658)
        at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:245)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:85)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:426)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
        at ch.qos.logback.classic.Logger.debug(Logger.java:487)
        at nextflow.cli.Launcher.run(Launcher.groovy:491)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)
Caused by: java.nio.file.FileAlreadyExistsException: /tmp

**Comment by pditommaso** [comment]
Unable to replicate
