### ISSUE TITLE
500 K8sResponseException (tunnel disconnect) from k8s Pod status request

### ISSUE THREAD

**Issue by alanbchristie** [nextflow-io/nextflow#5574]
### Expected behavior and actual behavior

Nextflow receives a 500 error from the kubernetes API but it would be nice to retry (as I think the error is transient). We are using `maxErrorRetry` and nextflow `22.10.8` but this does not appear to help.

### Steps to reproduce the problem

We run our workflow and it fails with this error regularly, at almost exactly the same time each day ... `00:33:31`.

### Program output 

```
Dec-05 00:33:23.490 [Task submitter] INFO  nextflow.Session - [b7/61f70d] Submitted process > fragment (1184)
Dec-05 00:33:31.834 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'fragment (820)'

Caused by:
  Request GET /api/v1/namespaces/fragmentor/pods/nf-c309da8f60a5670ff3446695f8b85664/status returned an error code=500 -- error trying to reach service: tunnel disconnect

nextflow.k8s.client.K8sResponseException: Request GET /api/v1/namespaces/fragmentor/pods/nf-c309da8f60a5670ff3446695f8b85664/status returned an error code=500 -- error trying to reach service: tunnel disconnect
	at nextflow.k8s.client.K8sClient.makeRequestCall(K8sClient.groovy:670)
	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:626)
	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy)
	at nextflow.k8s.client.K8sClient.get(K8sClient.groovy:679)
	at nextflow.k8s.client.K8sClient.podStatus(K8sClient.groovy:317)
	at nextflow.k8s.client.K8sClient.podStatus0(K8sClient.groovy:328)
	at nextflow.k8s.client.K8sClient.podState(K8sClient.groovy:461)
	at nextflow.k8s.K8sTaskHandler.getState(K8sTaskHandler.groovy:323)
	at nextflow.k8s.K8sTaskHandler.checkIfCompleted(K8sTaskHandler.groovy:393)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:610)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:534)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:409)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:293)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.lang.Thread.run(Thread.java:829)
Dec-05 00:33:31.840 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Request GET /api/v1/namespaces/fragmentor/pods/nf-c309da8f60a5670ff3446695f8b85664/status returned an error code=500 -- error trying to reach service: tunnel disconnect
```

### Environment 

* Nextflow version: `22.10.8` 
* Java version: `openjdk 11.0.25 2024-10-15`
* Operating system: `Debian GNU/Linux 11 (bullseye)`
* Bash version: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`

### Additional context

Running in an OpenStack kubernetes cluster (v1.30) and the following nextflow config: -

```
process {
  pod = [
    nodeSelector: 'informaticsmatters.com/purpose-fragmentor=yes',
    imagePullPolicy: 'Always'
  ]
}
executor {
    name = 'k8s'
    queueSize = 400
}
k8s {
    httpConnectTimeout = '120s'
    httpReadTimeout = '120s'
    maxErrorRetry = '8'
    serviceAccount = 'fragmentor'
    storageClaimName = 'work'
    storageMountPath = '/work'
}
```

**Comment by bentsherman** [comment]
22.10 is very old, the latest version should have retry logic for 500 responses

**Comment by alanbchristie** [comment]
Yes, understand - it's legacy code and we're assessing the impact of also moving to DSL2 as I think that was removed in `22.12.0-edge`. We're also investigating where our nightly network errors are coming from. For now we're sort of stuck on DSL1.

**Comment by alanbchristie** [comment]
Understand ... we're assessing the impact of migrating to DSL2. If we do we'll report whether it helps with this peculiar k8s 500 error.

**Comment by pditommaso** [comment]
Closing as likely solved in recent versions
