### ISSUE TITLE
Is maxErrorRetry applied to K8sResponseException 500 (tunnel disconnect)?

### ISSUE THREAD

**Issue by alanbchristie** [nextflow-io/nextflow#5604]
## Bug report 

> This issue was originally raised as #5574 against NF `22.10.8` but having re-written the process for DSL2 and running with NF `24.10.2` it persists, so I'm (re-)raising a new issue here

### Expected behavior and actual behavior

Nextflow receives a 500 error from the kubernetes API but it would be nice to retry (as I think the error is transient). We are using `maxErrorRetry` and NF `24.10.2` but this does not appear to help.

### Steps to reproduce the problem

We run our workflow and it fails with this error regularly, at almost exactly the same time each day ... `00:33:31`. In the exception last night it occurred again at `00:33:31`. Although we are trying to determine the cause of the underlying disconnect it would be nice if NF could comply with `maxErrorRetry`. If it is there's no evidence in the log.

### Program output 

```
Dec-13 00:33:31.980 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=fragment:fragment_mols (888); work-dir=/work/nextflow/0b/2286d5f91a1bb1f5a67b9c8d3ada45
  error [nextflow.k8s.client.K8sResponseException]: Request GET /api/v1/namespaces/fragmentor/pods/nf-0b2286d5f91a1bb1f5a67b9c8d3ada45-c297d/status returned an error code=500 -- error trying to reach service: tunnel disconnect
Dec-13 00:33:31.997 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'fragment:fragment_mols (888)'

Caused by:
  Request GET /api/v1/namespaces/fragmentor/pods/nf-0b2286d5f91a1bb1f5a67b9c8d3ada45-c297d/status returned an error code=500 -- error trying to reach service: tunnel disconnect


nextflow.k8s.client.K8sResponseException: Request GET /api/v1/namespaces/fragmentor/pods/nf-0b2286d5f91a1bb1f5a67b9c8d3ada45-c297d/status returned an error code=500 -- error trying to reach service: tunnel disconnect
	at nextflow.k8s.client.K8sClient.makeRequestCall(K8sClient.groovy:674)
	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:630)
	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy)
	at nextflow.k8s.client.K8sClient.get(K8sClient.groovy:683)
	at nextflow.k8s.client.K8sClient.podStatus(K8sClient.groovy:319)
	at nextflow.k8s.client.K8sClient.podStatus0(K8sClient.groovy:330)
	at nextflow.k8s.client.K8sClient.podState(K8sClient.groovy:463)
	at nextflow.k8s.K8sTaskHandler.getState(K8sTaskHandler.groovy:343)
	at nextflow.k8s.K8sTaskHandler.checkIfCompleted(K8sTaskHandler.groovy:413)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:651)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:573)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:443)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1333)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:82)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.doCall(TaskPollingMonitor.groovy:318)
	at nextflow.processor.TaskPollingMonitor$_start_closure2.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:505)
	at java.base/java.lang.Thread.run(Thread.java:829)
Dec-13 00:33:32.005 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Request GET /api/v1/namespaces/fragmentor/pods/nf-0b2286d5f91a1bb1f5a67b9c8d3ada45-c297d/status returned an error code=500 -- error trying to reach service: tunnel disconnect
```

### Environment 

* Nextflow version: `24.10.2`
* Java version: `openjdk 11.0.25 2024-10-15`
* Operating system: `Debian GNU/Linux 11 (bullseye)`
* Bash version: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`

### Additional context

Running in an OpenStack kubernetes cluster (v1.30) and the following nextflow config: -

```
process {
  pod = [
    nodeSelector: 'informaticsmatters.com/purpose-fragmentor=yes',
    imagePullPolicy: 'Always'
  ]
}
executor {
    name = 'k8s'
    queueSize = 400
}
k8s {
    httpConnectTimeout = '120s'
    httpReadTimeout = '120s'
    maxErrorRetry = '8'
    serviceAccount = 'fragmentor'
    storageClaimName = 'work'
    storageMountPath = '/work'
}
```

**Comment by bentsherman** [comment]
If it's returning a 500 error code then Nextflow should be retrying it: https://github.com/nextflow-io/nextflow/blob/0aa76affe22c35fc5bc6a4b609fa9b78528859a9/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L629-L639

I wonder if it is retrying but the tunnel disconnect lasts longer than the duration of the 8 retries. Seems plausible if it is a regular outage. Can you see the "API request threw socket exception..." messages in your log?

**Comment by alanbchristie** [comment]
There are no such messages so it looks like `maxRetries` is not being set as expected?

Can I know whether nextflow is reading the `maxErrorRetry = '8'` value from `$HOME/.nextflow/config` file?

In case it's significant, I am also starting nextflow with an explicit `-c` command (to a file that is empty) ... but I understand that configurations are **merged** so using an empty file will not disturb anything read from `$HOME/.nextflow/config`? After all - it must be reading the config described otherwise it wouldn't know to use a Kubernetes executor?

The `$HOME/.nextflow/config` is shown in the **Additional Context** in the initial issue text above.

**Comment by alanbchristie** [comment]
OK, thanks. It does look like it's picking up my configuration...

```bash
# nextflow config
process {
   pod = [nodeSelector:'informaticsmatters.com/purpose-fragmentor=yes', imagePullPolicy:'Always']
}

executor {
   name = 'k8s'
   queueSize = 600
}

k8s {
   httpConnectTimeout = '120s'
   httpReadTimeout = '120s'
   maxErrorRetry = '8'
   serviceAccount = 'fragmentor'
   storageClaimName = 'work'
   storageMountPath = '/work'
}
```

**Comment by alanbchristie** [comment]
The other thing that might be of interest is that the 'base' nextflow (as I am running it in a container) may not be `24.10.2` but it is running in an environment where `NXF_VER=24.10.2` (and the log clearly indicates `24.10.2` is the version that is running).

**Comment by crossthet** [comment]
> If it's returning a 500 error code then Nextflow should be retrying it:
> 
> [nextflow/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy](https://github.com/nextflow-io/nextflow/blob/0aa76affe22c35fc5bc6a4b609fa9b78528859a9/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L629-L639)
> 
> Lines 629 to 639 in [0aa76af](/nextflow-io/nextflow/commit/0aa76affe22c35fc5bc6a4b609fa9b78528859a9)
>  try { 
>      return makeRequestCall( method, path, body ) 
>  } catch ( K8sResponseException | SocketException | SocketTimeoutException e ) { 
>      if ( e instanceof K8sResponseException && e.response.code != 500 ) 
>          throw e 
>      if ( ++attempt > maxRetries ) 
>          throw e 
>      log.debug "[K8s] API request threw socket exception: $e.message for $method $path - Retrying request (attempt=$attempt)" 
>      final long delay = (Math.pow(3, attempt - 1) as long) * 250 
>      sleep( delay ) 
>  } 
> 
> I wonder if it is retrying but the tunnel disconnect lasts longer than the duration of the 8 retries. Seems plausible if it is a regular outage. Can you see the "API request threw socket exception..." messages in your log?

@bentsherman, apologies if this should be raised a separate question/issue but this issue and conversation seem to be closely related to question/issue I am having. 

I am running in a cluster that sometimes under heavy load does return temporary 503 errors and this causes nextflow to terminate and this can be seen in the logs:

```
`Request GET /api...returned an error code=503...`
```

I seems that similar codes have been switched to retryable for AWS Batch #4709.

I am using nextflow `24.04.3` and when the 503 occurs and the workflow exits the running processes are not terminated.  Testing with `24.12.0-edge` that has fix #5561 resolves that and terminates running processes even if 503 occurs.

My question is essentially is there a reason why 503 is not also added as a retryable exit code as for AWS Batch? 

Is this something that could potentially be added or a `k8s` setting that would allow the user to specify which errors to treat as retryable `k8s.retryable_errors = [500, 502, 503 ]`?
