### ISSUE TITLE
Nextflow ends before moving the files

### ISSUE THREAD

**Issue by nephantes** [nextflow-io/nextflow#622]
In Nextflow.nf file, we have the following command at the end of the file: `workflow.onComplete { file('work').deleteDir() }`
However we received an error that is shown below.
It is deleting the file before publishDir finalize its operation. How can we get around this? When the files big, it takes time to copy but nextflow thinks its complete.

Log.txt
```
N E X T F L O W  ~  version 0.24.0
Launching `/share/garberlab/yukseleo/nextflowruns/singleCell/run273/nextflow.nf` [furious_meitner] - revision: bb4fb7bcd2
[warm up] executor > local
[5f/9aed8d] Submitted process > rsync_basespace
WARN: Failed to publish file: /share/garberlab/yukseleo/nextflowruns/singleCell/run273/work/5f/9aed8d0dc6c3be812dba702e75c5cc/VitiligoTest_11_9_17; to: /share/garberlab/yukseleo/nextflowruns/singleCell/VitiligoTest_11_9_17 [move] -- See log file for details
```

.Nexflow.log file:
```
Feb-22 18:03:08.035 [main] DEBUG nextflow.cli.Launcher - $> /usr/bin/nextflow /share/garberlab/yukseleo/nextflowruns/singleCell/run273/nextflow.nf --brun /share/garberlab/gellatlk/pretend_basespace/Files --wdir VitiligoTest_11_9_17 -with-trace
Feb-22 18:03:08.414 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.24.0
Feb-22 18:03:08.448 [main] INFO  nextflow.cli.CmdRun - Launching `/share/garberlab/yukseleo/nextflowruns/singleCell/run273/nextflow.nf` [furious_meitner] - revision: bb4fb7bcd2
Feb-22 18:03:08.563 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: nextflow.config
Feb-22 18:03:08.566 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /share/garberlab/yukseleo/nextflowruns/singleCell/run273/nextflow.config
Feb-22 18:03:09.471 [main] DEBUG nextflow.config.ConfigBuilder - Setting config profile: 'standard'
Feb-22 18:03:09.647 [main] DEBUG nextflow.Session - Session uuid: 75ca5fbb-d8fa-4262-9a56-8e99f3cb5c09
Feb-22 18:03:09.648 [main] DEBUG nextflow.Session - Run name: furious_meitner
Feb-22 18:03:09.653 [main] DEBUG nextflow.Session - Executor pool size: 4
Feb-22 18:03:09.694 [main] DEBUG nextflow.cli.CmdRun -
  Version: 0.24.0 build 4235
  Modified: 20-03-2017 08:39 UTC
  System: Linux 3.13.0-106-generic
  Runtime: Groovy 2.4.10 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11
  Encoding: UTF-8 (UTF-8)
  Process: 6199@master [172.31.36.141]
  CPUs: 4 - Mem: 14.4 GB (162.4 MB) - Swap: 0 (0)
Feb-22 18:03:09.781 [main] DEBUG nextflow.Session - Work-dir: /share/garberlab/yukseleo/nextflowruns/singleCell/run273/work [ext2/ext3]
Feb-22 18:03:09.782 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /share/garberlab/yukseleo/nextflowruns/singleCell/run273/bin
Feb-22 18:03:10.077 [main] DEBUG nextflow.Session - Session start invoked
Feb-22 18:03:10.086 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Feb-22 18:03:10.088 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /share/garberlab/yukseleo/nextflowruns/singleCell/run273/trace.txt
Feb-22 18:03:10.116 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Feb-22 18:03:10.472 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Feb-22 18:03:10.777 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: local
Feb-22 18:03:10.777 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Feb-22 18:03:10.799 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Feb-22 18:03:10.802 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Feb-22 18:03:10.820 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=4; memory=14.4 GB; capacity=4; pollInterval=100ms; dumpInterval=5m
Feb-22 18:03:10.827 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Feb-22 18:03:10.828 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Feb-22 18:03:10.833 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Feb-22 18:03:11.021 [main] DEBUG nextflow.Session - >>> barrier register (process: rsync_basespace)
Feb-22 18:03:11.061 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > rsync_basespace -- maxForks: 4
Feb-22 18:03:11.135 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Feb-22 18:03:11.135 [main] DEBUG nextflow.Session - Session await
Feb-22 18:03:11.221 [Actor Thread 2] DEBUG nextflow.processor.TaskProcessor - <rsync_basespace> Poison pill arrived
Feb-22 18:03:11.229 [Actor Thread 1] DEBUG nextflow.processor.StateObj - <rsync_basespace> State before poison: StateObj[submitted: 1; completed: 0; poisoned: false ]
Feb-22 18:03:11.500 [Actor Thread 3] INFO  nextflow.Session - [5f/9aed8d] Submitted process > rsync_basespace
Feb-22 18:03:11.518 [Actor Thread 2] DEBUG nextflow.processor.TaskProcessor - <rsync_basespace> After stop
Feb-22 18:07:03.460 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <rsync_basespace> Sending poison pills and terminating process
Feb-22 18:07:03.465 [Actor Thread 1] DEBUG nextflow.Session - <<< barrier arrive (process: rsync_basespace)
Feb-22 18:07:03.469 [main] DEBUG nextflow.Session - Session await > all process finished
Feb-22 18:07:03.479 [pool-3-thread-1] WARN  nextflow.processor.PublishDir - Failed to publish file: /share/garberlab/yukseleo/nextflowruns/singleCell/run273/work/5f/9aed8d0dc6c3be812dba702e75c5cc/VitiligoTest_11_9_17; to: /share/garberlab/yukseleo/nextflowruns/singleCell/VitiligoTest_11_9_17 [move] -- See log file for details
java.nio.file.DirectoryNotEmptyException: /share/garberlab/yukseleo/nextflowruns/singleCell/VitiligoTest_11_9_17/VitiligoTest_11_9_17
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:445)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at nextflow.file.FileHelper.movePath(FileHelper.groovy:794)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
        at nextflow.extension.FilesEx.moveTo(FilesEx.groovy:267)
        at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:303)
        at nextflow.processor.PublishDir.processFile(PublishDir.groovy:281)
        at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:267)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
        at nextflow.processor.PublishDir$_apply_closure2.doCall(PublishDir.groovy:240)
        at nextflow.processor.PublishDir$_apply_closure2.call(PublishDir.groovy)
        at groovy.lang.Closure.run(Closure.java:495)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Feb-22 18:07:03.486 [Thread-1] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Feb-22 18:07:03.505 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-22 18:07:15.029 [main] DEBUG nextflow.trace.TraceFileObserver - Flow completing -- flushing trace file
Feb-22 18:07:15.056 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Feb-22 18:07:15.098 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

**Comment by pditommaso** [comment]
Not sure the problem is the `deleteDir()` because the exception says `DirectoryNotEmptyException: /share/garberlab/yukseleo/nextflowruns/singleCell/VitiligoTest_11_9_17/VitiligoTest_11_9_17` 

Can try the following things:
* remove the `workflow.onComplete { file('work').deleteDir() }` and repeat the execution 
* upgrade to the latest version and repeat the execution

**Comment by nephantes** [comment]
It works pretty well when I removed that line. We need to remove work directory upon successful completion. However, what I observed is nextflow doesn't wait to copy the files. It thinks the run is completed and executes onComplete command.

**Comment by pditommaso** [comment]
I'm not able to replicate the issue with the following test case. 

```
process foo {
  publishDir '.', saveAs: { println "before publish"; sleep 15_000; println "after publish"; return it }
  output:
  file 'x' 
  script:
  """
  touch x
  """
}
```

**Comment by nephantes** [comment]
I guess, this was machine specific. We changed the machine, it started working. Thanks for your help.

**Comment by nephantes** [comment]
Hi Paolo,
We recreated the problem in this nextflow file below;
Before all the index files copied, it deletes the folder with 
workflow.onComplete { file('work').deleteDir() } 
So, I first copied the next flow file we used and the error log comes after that.

#BuildIndex.nf
```
params.outdir = '/project/umw_biocore/dolphinnext/buildtest1'  
params.genome ="" 
g_11_genome = file(params.genome) 
process Build_Index {
publishDir params.outdir, mode: 'copy',
	saveAs: {filename ->
	if (filename =~ /genome.index/) "index/$filename"
}
input:
 file genome from g_11_genome

output:
 file 'genome.index*' into g_0_genome_index

"""
bowtie2-build ${genome} genome.index
"""
}
workflow.onComplete { file('work').deleteDir() } 
```
##########

When I run, it gives these warnings;
```
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.2.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.2.bt2 [copy] -- See log file for details
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.3.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.3.bt2 [copy] -- See log file for details
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.rev.1.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.rev.1.bt2 [copy] -- See log file for details
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.rev.2.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.rev.2.bt2 [copy] -- See log file for details
```
I copied the error log;
```
Mar-01 10:19:48.635 [pool-3-thread-1] WARN  nextflow.processor.PublishDir - Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.2.bt2; to: /project/umw_biocore
/dolphinnext/buildtest1/index/genome.index.2.bt2 [copy] -- See log file for details
java.nio.file.NoSuchFileException: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.2.bt2
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:828)
	at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:306)
	at nextflow.processor.PublishDir.processFile(PublishDir.groovy:281)
	at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
	at nextflow.processor.PublishDir$_apply_closure2.doCall(PublishDir.groovy:240)
	at nextflow.processor.PublishDir$_apply_closure2.call(PublishDir.groovy)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
