### ISSUE TITLE
Before all the files copied, nextflow deletes the folder 

### ISSUE THREAD

**Issue by nephantes** [nextflow-io/nextflow#626]
Hi Paolo,
We recreated the problem in this nextflow file below;
Before all the index files copied, it deletes the folder with 
workflow.onComplete { file('work').deleteDir() } 

Here there are multiple files bowtie-build generates and nextflow satisfies when only one of them copied.

So, I first copied the next flow file we used and the error log comes after that.

#BuildIndex.nf
```
params.outdir = '/project/umw_biocore/dolphinnext/buildtest1'  
params.genome ="" 
g_11_genome = file(params.genome) 
process Build_Index {
publishDir params.outdir, mode: 'copy',
	saveAs: {filename ->
	if (filename =~ /genome.index/) "index/$filename"
}
input:
 file genome from g_11_genome

output:
 file 'genome.index*' into g_0_genome_index

"""
bowtie2-build ${genome} genome.index
"""
}
workflow.onComplete { file('work').deleteDir() } 
```
##########

When I run, it gives these warnings;
```
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.2.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.2.bt2 [copy] -- See log file for details
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.3.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.3.bt2 [copy] -- See log file for details
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.rev.1.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.rev.1.bt2 [copy] -- See log file for details
WARN: Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.rev.2.bt2; to: /project/umw_biocore/dolphinnext/buildtest1/index/genome.index.rev.2.bt2 [copy] -- See log file for details
```
I copied the error log;
```
Mar-01 10:19:48.635 [pool-3-thread-1] WARN  nextflow.processor.PublishDir - Failed to publish file: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.2.bt2; to: /project/umw_biocore
/dolphinnext/buildtest1/index/genome.index.2.bt2 [copy] -- See log file for details
java.nio.file.NoSuchFileException: /project/umw_biocore/dolphinnext/buildtest1/run235/work/19/69ef47fca5d60e4e895b9fba3f8a0f/genome.index.2.bt2
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:828)
	at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:306)
	at nextflow.processor.PublishDir.processFile(PublishDir.groovy:281)
	at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
	at nextflow.processor.PublishDir$_apply_closure2.doCall(PublishDir.groovy:240)
	at nextflow.processor.PublishDir$_apply_closure2.call(PublishDir.groovy)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by pditommaso** [comment]
Yes, I think there's a condition in which it can happen. I would advice to not delete the workdir using the `onComplete` handler until this issue is fixed, and maybe just use a trivial bash wrapper to delete that folder when the execution complete.

**Comment by nephantes** [comment]
Is there a possibility to check copy or move process rather than file there to fire onComplete event. We are creating a generic nextflow builder that's why this functionality is critical for us to remove all intermediate files upon completion.

**Comment by pditommaso** [comment]
This is supposed to be fixed. Above I was proposing a temporary workaround.

**Comment by pditommaso** [comment]
This can be more tricky than expected to solve. I think it makes more sense to add built-in feature to cleanup the workflow work dir, see #649. This allows also a better control on the deleted folder.
