### ISSUE TITLE
A HTTP access error is raised when the URL contains a ? character

### ISSUE THREAD

**Issue by chdem** [nextflow-io/nextflow#634]
Hi everybody !

I'm trying to get json from an URL with the HTTP files nextflow integration :
```
def mygene_info_query_url = 'http://mygene.info/v3/query?species=human&fields=symbol&q=refseq:NM_001082.3'
def mygene_info_answer = file(mygene_info_query_url)
```

This is throwing the following error :
```
mars-12 15:11:51.835 [main] DEBUG nextflow.file.FileHelper - Path matcher not defined by 'XFileSystem' file system -- using default default strategy
mars-12 15:11:52.606 [main] DEBUG nextflow.Session - Session aborted -- Cause: Unable to access path: /v3
mars-12 15:11:52.859 [main] ERROR nextflow.cli.Launcher - Unable to access path: /v3
java.io.IOException: Unable to access path: /v3
        at nextflow.file.http.XFileSystemProvider.readAttributes(XFileSystemProvider.groovy:363)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at nextflow.file.FileHelper.visitFiles(FileHelper.groovy:723)
        at nextflow.file.FileHelper$visitFiles$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
        at nextflow.Nextflow.fileNamePattern(Nextflow.groovy:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222)
        at nextflow.Nextflow.file(Nextflow.groovy:163)
```

On the other hand, the following code works (not a connexion/configuration problem) :
```
def mygene_info_query_url = 'http://mygene.info/v3/query?species=human&fields=symbol&q=refseq:NM_001082.3'
def jsonSlurper = new JsonSlurper()
def url = new URL(mygene_info_query_url)
def jsonDoc = jsonSlurper.parseText(url.text)
```

Let me know if I can help you with anything else about this issue.

**Comment by pditommaso** [comment]
Yes, here there's a bug the problem is that it parses `?` as a glob wildcard and tries to traverse the path as directory structures. As as temporary workaround specify `glob:false` eg. 

```
def f = file('http://mygene.info/v3/query?species=human&fields=symbol&q=refseq:NM_001082.3', glob:false)

println f.text
```

**Comment by pditommaso** [comment]
Version 0.28.1
