### ISSUE TITLE
Channel.fromPath throws an exception when curly brackets pattern is specified 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#64]
When `Channel.fromPath` argument is a non-default file system including a curly brackets glob pattern an exception is raised. For example: 

    Channel.fromPath('s3:///cbcrg-eu/nmdpflow-data/raw/**_R1*{fastq,fq,fastq.gz,fq.gz}') 

It throws: 

	java.lang.IllegalArgumentException: Illegal character in path at index 39: s3:///cbcrg-eu/nmdpflow-data/raw/**_R1*{fastq,fq,fastq.gz,fq.gz}
		at java.net.URI.create(URI.java:852) ~[na:1.8.0_40]
		at nextflow.file.FileHelper.asPath(FileHelper.groovy:241) ~[nxf-commons-0.15.1.jar:na]
		at nextflow.extension.Bolts.asType(Bolts.groovy:340) ~[nxf-commons-0.15.1.jar:na]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
		at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
		at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:51) ~[groovy-2.3.11.jar:2.3.11]
		at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54) ~[groovy-2.3.11.jar:2.3.11]
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[groovy-2.3.11.jar:2.3.11]
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206) ~[groovy-2.3.11.jar:2.3.11]
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015) ~[groovy-2.3.11.jar:2.3.11]
		at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:73) ~[nextflow-0.15.1.jar:na]
		at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:889) ~[groovy-2.3.11.jar:2.3.11]
		at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:880) ~[groovy-2.3.11.jar:2.3.11]
		at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:166) ~[groovy-2.3.11.jar:2.3.11]
		at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:589) ~[groovy-2.3.11.jar:2.3.11]
		at nextflow.Channel.fromPath(Channel.groovy:163) ~[nextflow-0.15.1.jar:na]
		at nextflow.Channel.fromPath(Channel.groovy) ~[nextflow-0.15.1.jar:na]
		at nextflow.Channel$fromPath.call(Unknown Source) ~[na:na]
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-2.3.11.jar:2.3.11]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) ~[groovy-2.3.11.jar:2.3.11]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-2.3.11.jar:2.3.11]
		at main.run(main.nf:35) ~[na:na]
		at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:290) ~[nextflow-0.15.1.jar:na]
		at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:142) ~[nextflow-0.15.1.jar:na]
		at nextflow.cli.CmdRun.run(CmdRun.groovy:183) ~[nextflow-0.15.1.jar:na]
		at nextflow.cli.Launcher.run(Launcher.groovy:377) [nextflow-0.15.1.jar:na]
		at nextflow.cli.Launcher.main(Launcher.groovy:520) [nextflow-0.15.1.jar:na]
	Caused by: java.net.URISyntaxException: Illegal character in path at index 39: s3:///cbcrg-eu/nmdpflow-data/raw/**_R1*{fastq,fq,fastq.gz,fq.gz}
		at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_40]
		at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_40]
		at java.net.URI$Parser.parseHierarchical(URI.java:3105) ~[na:1.8.0_40]
		at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_40]
		at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_40]
		at java.net.URI.create(URI.java:850) ~[na:1.8.0_40]

**Comment by pditommaso** [comment]
Fixed in version `0.15.2`
