### ISSUE TITLE
Add -offline flag when no internet access is available

### ISSUE THREAD

**Issue by mfoll** [nextflow-io/nextflow#665]
When using nextflow an a machine without internet access and pipelines hosted on GitHub (but previously pulled locally), nextflow hangs for a couple of minutes before successfully completing the pipeline. The following error is in the `.nextflow.log` file:
```
Apr-25 16:53:09.446 [main] DEBUG nextflow.scm.AssetManager - WARN: Failed to check remote Git revision
org.eclipse.jgit.api.errors.TransportException: https://github.com/nextflow-io/hello.git: cannot open git-upload-pack
    at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:222)
    at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:160)
    at nextflow.scm.AssetManager.getRemoteCommitId(AssetManager.groovy:884)
    at nextflow.scm.AssetManager.checkRemoteStatus0(AssetManager.groovy:895)
    at nextflow.scm.AssetManager.checkRemoteStatus(AssetManager.groovy:913)
    at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:293)
    at nextflow.cli.CmdRun.run(CmdRun.groovy:198)
    at nextflow.cli.Launcher.run(Launcher.groovy:428)
    at nextflow.cli.Launcher.main(Launcher.groovy:582)
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/nextflow-io/hello.git: cannot open git-upload-pack
    at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:566)
    at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:326)
    at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:199)
    ... 8 common frames omitted
Caused by: java.net.ConnectException: Connection timed out (Connection timed out) github.com
    at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:210)
    at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:504)
    ... 10 common frames omitted
```
Adding an `-offline` flag to prevent nextflow to check the remote version would be useful.

**Comment by wbszhu** [comment]
Hi,
I have a simliar problem like you:

```
module load Singularity/3.1.1
nextflow run nf-core/atacseq  --input $1 -profile singularity  --fasta ~/22.genome/susScr11_xy/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa  --gtf ~/22.genome/susScr11_xy/Sus_scrofa.Sscrofa11.1.101.chr.gtf --outdir /public/home/luzhang/06.pig-eqtl/02.results/atac-seq/$2 
```
and got this

```
N E X T F L O W  ~  version 22.04.0
Pulling nf-core/atacseq ...
https://github.com/nf-core/atacseq.git: cannot open git-upload-pack
```
Hope to get your help.
Lu Zhang
