### ISSUE TITLE
K8s client fails to connect the cluster when client key nor certificate is specified

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#692]
The following exception is throw when trying to connect to a K8s cluster using a context only specifying the user `token` and providing client key not the client certificate: 

```
java.lang.IllegalArgumentException: no SSLSocketFactory specified
    at javax.net.ssl.HttpsURLConnection.setSSLSocketFactory(HttpsURLConnection.java:357)
    at nextflow.k8s.client.K8sClient.setupHttpsConn(K8sClient.groovy:282)
    at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:310)
    at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy)
    at nextflow.k8s.client.K8sClient.get(K8sClient.groovy:337)
    at nextflow.k8s.client.K8sClient.volumeClaimRead(K8sClient.groovy:387)
    at nextflow.k8s.client.K8sClient$volumeClaimRead.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
    at nextflow.k8s.K8sDriverLauncher.validateClaimNames(K8sDriverLauncher.groovy:162)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
    at nextflow.k8s.K8sDriverLauncher.checkStorageAndPaths(K8sDriverLauncher.groovy:182)
    at nextflow.k8s.K8sDriverLauncher.run(K8sDriverLauncher.groovy:133)
    at nextflow.cli.CmdKubeRun.run(CmdKubeRun.groovy:69)
    at nextflow.cli.Launcher.run(Launcher.groovy:428)
    at nextflow.cli.Launcher.main(Launcher.groovy:582)
```

**Comment by pditommaso** [comment]
Released in version `0.29.1`.
