### ISSUE TITLE
An exception is thrown when an output folder contains a circular symlink path

### ISSUE THREAD

**Issue by arnaudceol** [nextflow-io/nextflow#701]
My nextlow pipeline is broken, probably because of a combination of recursive search for output files and backward link in the output directory.

This is probably less a problem with nextflow than a problem with the output and the filter, but I'm creating anyway an new issue: At worst it may be useful for other users having the same problem. I first describe the problem as it occurs in my case (with bcl2fastq), because I've seen it happened to others, but you can also find a small script to reproduce it at the end of this message.

My nextflow pipeline is demultiplexing single cell sequencing data with 10X genomics cellranger software, which is based on bcl2fastq:

```
process demultiplex {
    cpus 16
    publishDir "${params.tmpDir}/${params.runID}"
   
   
    output:
    file "**R[1-2]_[0-9][0-9][0-9]*.fastq.gz" into fastq_channel mode flatten
    file "Stats"
    file "Reports"
   
    script:
   
        """
        cellranger mkfastq --localcores=16 --run ${params.runDir}/${params.runID}/ --id ${params.runID} --csv ${params.runDir}/${params.runID}/chromium.csv --output-dir .
        """
   }
```

The output of this process looks like:

```
ls -lht  work/76/30d4088435f083caaeb194a63e70b9/180308_A00302_0015_AH5VMHDMXX/outs/
total 224K
lrwxrwxrwx 1 ieo3004 dpt  64 May 14 21:54 fastq_path -> /hpcnfs/scratch/CRU/demux/work/76/30d4088435f083caaeb194a63e70b9
-rw-r--r-- 1 ieo3004 dpt 28K May 14 20:51 qc_summary.json
drwxr-xr-x 2 ieo3004 dpt  37 May 14 19:49 interop_path
-rw-r--r-- 1 ieo3004 dpt 308 May 14 16:58 input_samplesheet.csv
```

And the error message is :

```
May-14 21:55:13.499 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 14299.hpcfe01; id: 1; name: demultiplex; status: COMPLETED; exit: 0; error: -; workDir: /hpcnfs/scratch/CRU/demux/work/76/30d4088435f083caaeb194a63e70b9 started: 1526309887914; exited: 2018-05-14T19:55:09.246134Z; ]
May-14 21:55:13.542 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'demultiplex'

Caused by:
  /hpcnfs/scratch/CRU/demux/work/76/30d4088435f083caaeb194a63e70b9/180308_A00302_0015_AH5VMHDMXX/outs/fastq_path

java.nio.file.FileSystemLoopException: /hpcnfs/scratch/CRU/demux/work/76/30d4088435f083caaeb194a63e70b9/180308_A00302_0015_AH5VMHDMXX/outs/fastq_path
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:294)

        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
        at java.nio.file.Files.walkFileTree(Files.java:2706)
        at nextflow.file.FileHelper.visitFiles(FileHelper.groovy:723)
        at nextflow.file.FileHelper$visitFiles$3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)

....

```

It looks like the process itself went fine, but the error comes later, probably while preparing the output for the next step.

I'm not sure if this is really a nextflow problem, and I can fix it by removing the link at the end of the process.

Anyway, it can be reproduced with the following script:

```
#!/usr/bin/env nextflow

process testlinks {

   
    output:
    file "**R[1-2]_[0-9][0-9][0-9]*.fastq.gz" into
fastq_channel mode flatten
   
    script:
        """
        mkdir -p RUNID/outs/
        ln -s . RUNID/outs/fastq_path
        mkdir RUNID/outs/fastq_path/fastqs/
        touch RUNID/outs/fastq_path/fastqs/sample1_R1_000.fastq.gz
        touch RUNID/outs/fastq_path/fastqs/sample1_R2_000.fastq.gz
        """
}    


process checkQuality {
   
    input:
    file fastq from fastq_channel
   
    """
    echo  ${fastq}    
    """
   
}

```

**Comment by pditommaso** [comment]
Thanks for the test case. This is very useful.

**Comment by pditommaso** [comment]
I've published a beta version including this patch. You may want to give it a try using the following command: 

```
NXF_VER=0.30.0-BETA1 nextflow run .. etc
```

**Comment by arnaudceol** [comment]
The test case is working, I'll check with real data and let you know.
Thanks a lot.

On Thu, May 17, 2018 at 10:16 AM, Paolo Di Tommaso <notifications@github.com
