### ISSUE TITLE
Add support for K8s pod securityContext

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#707]
Was working with Paolo on testing the K8S support and hit a problem with using containers that do not run as the root user (which is strongly preferable for security reasons).
The nextflow/nextflow container that executes the workflow runs as root (this should not really be needed) and creates the directories in the work dir that are owned by root.
Then when the containers that run the processes execute they need to be able to write to those directories, but as they are not running as root they do no have permissions.
When running with Docker I work around this by using a before script of `beforeScript 'chmod g+w .'` to set the group write permissions of the directory, and now the user in the conainer executing the process can write to that directly (as by convention we make that user belong to group 0).
With the K8S executor this does not seem to be working.

Try the attached example. 
[example.zip](https://github.com/nextflow-io/nextflow/files/2017006/example.zip)
Run it like this:
`oc create -f nf-pod.yml`
That works as the container configured in `nextflow.config` runs as root. But if your change the image to `informaticsmatters/smog:latest` which runs as non-privileged user the workflow fails.

This example is set up in the ~/pv-nextflow/nf-0001 directory in our test environment.

Ideally both the `nextflow/nextflow` container and all containers executing the processes should be able to run as different non-root users.

**Comment by pditommaso** [comment]
Can you please include the `.nextflow.log` for a failed run?

**Comment by tdudgeon** [comment]
```
May-18 14:11:05.901 [main] DEBUG nextflow.cli.Launcher - $> /usr/local/bin/nextflow run main.nf
May-18 14:11:06.125 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.29.1
May-18 14:11:06.160 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [grave_mendel] - revision: 2305d62c54
May-18 14:11:06.195 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: nextflow.config
May-18 14:11:06.198 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /workspace/nextflow.config
May-18 14:11:06.320 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
May-18 14:11:06.920 [main] DEBUG nextflow.Session - Session uuid: 78cfd720-55ca-4cec-aab0-f6bbd3acf1b7
May-18 14:11:06.920 [main] DEBUG nextflow.Session - Run name: grave_mendel
May-18 14:11:06.921 [main] DEBUG nextflow.Session - Executor pool size: 8
May-18 14:11:06.942 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 0.29.1 build 4804
  Modified: 10-05-2018 07:47 UTC (07:47 GMT)
  System: Linux 3.10.0-693.21.1.el7.x86_64
  Runtime: Groovy 2.4.15 on OpenJDK 64-Bit Server VM 1.8.0_151-b12
  Encoding: UTF-8 (UTF-8)
  Process: 1@nf-runner-zbscw [10.128.6.145]
  CPUs: 8 - Mem: 15.5 GB (7.2 GB) - Swap: 0 (0)
May-18 14:11:07.581 [main] DEBUG nextflow.Session - Work-dir: /workspace/work [nfs]
May-18 14:11:07.583 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /workspace/bin
May-18 14:11:10.878 [main] DEBUG nextflow.Session - Session start invoked
May-18 14:11:10.886 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
May-18 14:11:10.887 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
May-18 14:11:11.120 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
May-18 14:11:11.336 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: k8s
May-18 14:11:11.336 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'k8s'
May-18 14:11:11.347 [main] DEBUG nextflow.executor.Executor - Initializing executor: k8s
May-18 14:11:11.350 [main] INFO  nextflow.executor.Executor - [warm up] executor > k8s
May-18 14:11:11.361 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'k8s' > capacity: 100; pollInterval: 5s; dumpInterval: 5m 
May-18 14:11:11.364 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: TaskPollingMonitor
May-18 14:11:11.365 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: k8s)
May-18 14:11:11.373 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: k8s
May-18 14:11:11.383 [main] DEBUG nextflow.k8s.client.ConfigDiscovery - K8s config file does not exist: /root/.kube/config
May-18 14:11:11.405 [main] DEBUG nextflow.k8s.K8sExecutor - [K8s] API client config=ClientConfig[ server=172.30.0.1:443, namespace=nextflow, token=eyJhbGciOiJ.., sslCert=LS0tLS1CRUd.., clientCert=-, clientKey=-, verifySsl=false, fromFile=true ]
May-18 14:11:11.496 [main] DEBUG nextflow.Session - >>> barrier register (process: splitter)
May-18 14:11:11.500 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > splitter -- maxForks: 8
May-18 14:11:11.800 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: k8s
May-18 14:11:11.800 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'k8s'
May-18 14:11:11.800 [main] DEBUG nextflow.executor.Executor - Initializing executor: k8s
May-18 14:11:11.803 [main] DEBUG nextflow.Session - >>> barrier register (process: smog_scoring)
May-18 14:11:11.804 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > smog_scoring -- maxForks: 8
May-18 14:11:11.884 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: k8s
May-18 14:11:11.886 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'k8s'
May-18 14:11:11.888 [main] DEBUG nextflow.executor.Executor - Initializing executor: k8s
May-18 14:11:11.890 [main] DEBUG nextflow.Session - >>> barrier register (process: joiner)
May-18 14:11:11.890 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > joiner -- maxForks: 8
May-18 14:11:11.906 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: k8s
May-18 14:11:11.906 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'k8s'
May-18 14:11:11.907 [main] DEBUG nextflow.executor.Executor - Initializing executor: k8s
May-18 14:11:11.910 [main] DEBUG nextflow.Session - >>> barrier register (process: metrics_meta)
May-18 14:11:11.915 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > metrics_meta -- maxForks: 8
May-18 14:11:11.917 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
May-18 14:11:11.917 [main] DEBUG nextflow.Session - Session await
May-18 14:11:14.235 [Task submitter] INFO  nextflow.Session - [ac/550cdf] Submitted process > splitter
May-18 14:11:31.631 [Task monitor] DEBUG nextflow.k8s.K8sTaskHandler - [K8s] Cannot read exitstatus for task: `splitter`
java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.exitcode
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at org.codehaus.groovy.runtime.NioGroovyMethods.newReader(NioGroovyMethods.java:1311)
	at org.codehaus.groovy.runtime.NioGroovyMethods.getText(NioGroovyMethods.java:422)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1845)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3773)
	at groovy.lang.DelegatingMetaClass.getProperty(DelegatingMetaClass.java:130)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:195)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassGetPropertySite.getProperty(PojoMetaClassGetPropertySite.java:36)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
	at nextflow.k8s.K8sTaskHandler.readExitFile(K8sTaskHandler.groovy:293)
	at nextflow.k8s.K8sTaskHandler.checkIfCompleted(K8sTaskHandler.groovy:280)
	at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:526)
	at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:454)
	at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
	at nextflow.processor.TaskPollingMonitor$_start_closure4.doCall(TaskPollingMonitor.groovy:285)
	at nextflow.processor.TaskPollingMonitor$_start_closure4.call(TaskPollingMonitor.groovy)
	at groovy.lang.Closure.run(Closure.java:499)
	at java.lang.Thread.run(Thread.java:748)
May-18 14:11:31.640 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: splitter; status: COMPLETED; exit: -; error: -; workDir: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080]
May-18 14:11:31.661 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.command.out
May-18 14:11:31.664 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.command.err
May-18 14:11:31.666 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.command.log
May-18 14:11:31.667 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'splitter'

Caused by:
  Process `splitter` terminated for an unknown reason -- Likely it has been terminated by the external system

Command executed:

  python -m pipelines_utils_rdkit.filter -i ligands.data.gz -c 25 -l 0 -d 4 -o ligand_part -of sdf --meta

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /workspace/work/ac/550cdfa075e9ac12cc11522cd99080

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
May-18 14:11:31.682 [Actor Thread 3] DEBUG nextflow.Session - <<< barrier arrive (process: splitter)
May-18 14:11:31.687 [Actor Thread 6] DEBUG nextflow.Session - <<< barrier arrive (process: metrics_meta)
May-18 14:11:31.688 [Actor Thread 7] DEBUG nextflow.Session - <<< barrier arrive (process: smog_scoring)
May-18 14:11:31.688 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `splitter` terminated for an unknown reason -- Likely it has been terminated by the external system
May-18 14:11:31.695 [Actor Thread 7] DEBUG nextflow.Session - <<< barrier arrive (process: joiner)
May-18 14:11:31.695 [main] DEBUG nextflow.Session - Session await > all process finished
May-18 14:11:31.721 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.command.err
May-18 14:11:31.721 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.command.out
May-18 14:11:31.727 [main] DEBUG nextflow.Session - Session await > all barriers passed
May-18 14:11:31.728 [main] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.command.err
May-18 14:11:31.729 [main] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /workspace/work/ac/550cdfa075e9ac12cc11522cd99080/.command.out
May-18 14:11:31.737 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: k8s)
May-18 14:11:31.757 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=1; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms]
May-18 14:11:31.998 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
May-18 14:11:32.083 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

**Comment by tdudgeon** [comment]
p.s. much of this probably also applies to the Docker executor too.

**Comment by pditommaso** [comment]
I think there's some problem with the file system configuration and/or file system permission. 

The issue is raised because the job pod is not able to write in the job working directory mounted with the PVC. 

I've made some test with the following pod: 

```
apiVersion: v1
kind: Pod
metadata:
  name: nauseous-watson
  namespace: nextflow
spec:
  restartPolicy: Never
  containers:
  - name: nauseous-watson
    image: informaticsmatters/smog:latest
    command: [/bin/bash, -c, 'echo "who am i: $(whoami)"; echo hello > /workspace/hello.txt; touch /workspace/paolo/x.txt; touch /workspace/paolo/work/x.txt']
    volumeMounts:
    - {name: vol-1, mountPath: /workspace}
  volumes:
  - name: vol-1
    persistentVolumeClaim: {claimName: nf-0001}
```

It returns the following output: 

```
$ oc logs nauseous-watson
who am i: smog
touch: cannot touch '/workspace/paolo/x.txt': Permission denied
touch: cannot touch '/workspace/paolo/work/x.txt': Permission denied
```

Therefore it can write in the `/workspace` path but not in any subdirectory.  

This is the listing of that folders:

```
ls -la /workspace
total 660
drwxrwxrwx.  6 nobody nogroup   4096 May 19 08:08 .
drwxr-xr-x. 18 root   root       286 May 19 08:24 ..
drwxr-xr-x.  3 nobody nogroup   4096 May 18 14:11 .nextflow
-rw-r--r--.  1 nobody nogroup  12057 May 18 14:11 .nextflow.log
-rw-rw-r--.  1 rdkit     1000 317440 May 18 13:01 all.tar
-rw-rw-r--.  1 rdkit     1000 150397 May  8 10:08 docking.zip
-rw-r--r--.  1 smog   nogroup      6 May 19 08:24 hello.txt
-rw-r--r--.  1 rdkit     1000 120508 May  1 14:05 ligands.data.gz
-rw-r--r--.  1 rdkit     1000     53 May  1 14:05 ligands.metadata
-rw-rw-r--.  1 rdkit     1000   2278 May 17 10:35 main.nf
-rwxr-xr-x.  1 rdkit     1000    270 May 18 14:09 nextflow.config
-rw-rw-r--.  1 rdkit     1000    496 May 17 10:37 nf-pod.yml
drwxr-xr-x.  4 nobody nogroup   4096 May 19 08:15 paolo
drwxr-xr-x.  3 nobody nogroup   4096 May 19 08:08 projects
-rw-r--r--.  1 rdkit     1000  27271 May  1 14:05 protein.pdb.gz
drwxr-xr-x.  3 nobody nogroup   4096 May 18 14:11 work
```

```
ls -la /workspace/paolo
total 56
drwxr-xr-x.  4 nobody nogroup  4096 May 19 08:15 .
drwxrwxrwx.  6 nobody nogroup  4096 May 19 08:08 ..
drwxr-xr-x.  3 nobody nogroup  4096 May 19 08:15 .nextflow
-rw-r--r--.  1 nobody nogroup 15561 May 19 08:15 .nextflow.log
-rw-r--r--.  1 nobody nogroup 11825 May 19 08:10 .nextflow.log.1
-rw-r--r--.  1 nobody nogroup  7059 May 19 08:09 .nextflow.log.2
-rw-r--r--.  1 nobody nogroup   236 May 19 08:14 nextflow.config
drwxr-xr-x. 14 nobody nogroup  4096 May 19 08:15 work
```

As you see the `paolo` folder belong to `nobody nogroup`, then I guess `smog` user cannot write there.

**Comment by tdudgeon** [comment]
This is what the ownerships and permisssions look like on the NFS server:
```
# ls -al
total 664
drwxrwxrwx. 6 nfsnobody nfsnobody   4096 May 19 08:08 .
drwxr-xr-x. 8 root      root        4096 May  8 09:42 ..
-rw-rw-r--. 1 centos    centos    317440 May 18 13:01 all.tar
-rw-rw-r--. 1 centos    centos    150397 May  8 10:08 docking.zip
-rw-r--r--. 1      1001 nfsnobody      6 May 19 08:33 hello.txt
-rw-r--r--. 1 centos    centos    120508 May  1 14:05 ligands.data.gz
-rw-r--r--. 1 centos    centos        53 May  1 14:05 ligands.metadata
-rw-rw-r--. 1 centos    centos      2278 May 17 10:35 main.nf
drwxr-xr-x. 3 nfsnobody nfsnobody   4096 May 18 14:11 .nextflow
-rwxr-xr-x. 1 centos    centos       270 May 18 14:09 nextflow.config
-rw-r--r--. 1 nfsnobody nfsnobody  12057 May 18 14:11 .nextflow.log
-rw-rw-r--. 1 centos    centos       496 May 17 10:37 nf-pod.yml
drwxr-xr-x. 4 nfsnobody nfsnobody   4096 May 19 09:06 paolo
drwxr-xr-x. 3 nfsnobody nfsnobody   4096 May 19 08:08 projects
-rw-r--r--. 1 centos    centos     27271 May  1 14:05 protein.pdb.gz
drwxr-xr-x. 3 nfsnobody nfsnobody   4096 May 18 14:11 work
```
The NFS export was created using the `root_squash` option, which is recommended as it maps the remote root user to nfsnobody. Thus the `work` and `paolo` directories that get created by the `nextflow/nextflow` container running as `root` are owned by `nfsnobody.nfsnobody`, which when mounter in a container without that user and group appear as `nobody` and `nogroup`.
Note that the directory itself has world write permissions, but the `work` and `paolo` directories that are created do not, hence which you can't write to them from a different user.

Seems like NF needs to either be told what user the containers will run as, or to specify which user they should be run as,in which case it can set the permissions accordingly,  or to set world read/write access to all directories it created, which is obviously a security risk.

The best situation would be if you run the `nextflow/nextflow` container as a specific non-root user id (e.g. 1000), and specify that the process containers also run as that user id.

**Comment by pditommaso** [comment]
Not sure this problem can be managed on NF side.

**Comment by tdudgeon** [comment]
The user a container runs as can be specified (in OpenShift at least) using the `pod.spec.containers.securityContext.runAsUser` property:
```
$ oc explain pod.spec.containers.securityContext.runAsUser
FIELD: runAsUser <integer>

DESCRIPTION:
     The UID to run the entrypoint of the container process. Defaults to user
     specified in image metadata if unspecified. May also be set in
     PodSecurityContext. If set in both SecurityContext and PodSecurityContext,
     the value specified in SecurityContext takes precedence.
```

**Comment by pditommaso** [comment]
I've added the ability to specify the user to run the container eg. 

```
process {
  pod = [runAsUser: 1000]
}
```

or 

```
k8s {
  pod = [runAsUser: 1000]
}
```

If you test it make sure to use the latest NF docker image snapshot tagged as 

```
0.31.0-SNAPSHOT: digest: sha256:e0f3edb6b7e93c074ff7428a6315cec6c13353ddc0d085070f4f40acae97f896 size: 2620
```

and to use the latest NF snapshot running the following command the very first time: 

```
NXF_VER=0.31.0-SNAPSHOT CAPSULE_RESET=1 nextflow info 
```
