### ISSUE TITLE
Add opt-in support for GitLab deprecated v3 API protocol

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#751]
As of release 0.30.2, something has broken with nextflow access to gitlab.  This call:

`nextflow run SGI-Pipelines/nextflow_transcriptomics -hub gitlab -resume -params-file params.yml -latest -r 1.3.0`

(where the gitlab server is correctly specified in the nextflow `scm` file) works for 0.29.0 but fails with version 0.30.2.  There error we see is:

```
asdf@xyz:/asdf/assets/txp_pe $ nextflow run SGI-Pipelines/nextflow_transcriptomics -hub gitlab -resume -params-file params.yml -latest -r 1.3.0
CAPSULE: Downloading dependency org.multiverse:multiverse-core:pom:0.7.0
CAPSULE: Downloading dependency org.multiverse:multiverse:pom:0.7.0
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb-api:pom:0.7
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb-project:pom:0.7
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-kms:pom:1.11.324
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-pom:pom:1.11.324
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-core:pom:1.11.324
CAPSULE: Downloading dependency joda-time:joda-time:pom:2.8.1
CAPSULE: Downloading dependency com.beust:jcommander:pom:1.35
CAPSULE: Downloading dependency org.sonatype.oss:oss-parent:pom:3
CAPSULE: Downloading dependency com.sun.activation:javax.activation:pom:1.2.0
CAPSULE: Downloading dependency com.sun.activation:all:pom:1.2.0
CAPSULE: Downloading dependency net.java:jvnet-parent:pom:1
CAPSULE: Downloading dependency com.amazonaws:jmespath-java:pom:1.11.324
CAPSULE: Downloading dependency org.jsoup:jsoup:pom:1.11.2
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-nio:pom:2.4.15
CAPSULE: Downloading dependency javax.mail:mail:pom:1.4.7
CAPSULE: Downloading dependency com.sun.mail:all:pom:1.4.7
CAPSULE: Downloading dependency org.slf4j:jcl-over-slf4j:pom:1.7.21
CAPSULE: Downloading dependency org.slf4j:slf4j-parent:pom:1.7.21
CAPSULE: Downloading dependency io.nextflow:nxf-s3fs:pom:1.0.3
CAPSULE: Downloading dependency org.apache.httpcomponents:httpcore:pom:4.4.9
CAPSULE: Downloading dependency org.apache.httpcomponents:httpcomponents-core:pom:4.4.9
CAPSULE: Downloading dependency org.apache.httpcomponents:httpcomponents-parent:pom:9
CAPSULE: Downloading dependency org.apache:apache:pom:18
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-core:pom:2.6.7
CAPSULE: Downloading dependency com.fasterxml.jackson:jackson-parent:pom:2.6.2
CAPSULE: Downloading dependency com.fasterxml:oss-parent:pom:24
CAPSULE: Downloading dependency org.codehaus.gpars:gpars:pom:1.2.1
CAPSULE: Downloading dependency io.nextflow:nxf-httpfs:pom:0.30.2
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-templates:pom:2.4.15
CAPSULE: Downloading dependency com.esotericsoftware.kryo:kryo:pom:2.24.0
CAPSULE: Downloading dependency org.sonatype.oss:oss-parent:pom:7
CAPSULE: Downloading dependency io.nextflow:nxf-commons:pom:0.30.2
CAPSULE: Downloading dependency org.apache.ivy:ivy:pom:2.3.0
CAPSULE: Downloading dependency org.apache:apache:pom:7
CAPSULE: Downloading dependency com.googlecode.javaewah:JavaEWAH:pom:1.1.6
CAPSULE: Downloading dependency org.sonatype.oss:oss-parent:pom:5
CAPSULE: Downloading dependency com.jcraft:jsch:pom:0.1.54
CAPSULE: Downloading dependency org.sonatype.oss:oss-parent:pom:6
CAPSULE: Downloading dependency ch.qos.logback:logback-classic:pom:1.1.10
CAPSULE: Downloading dependency ch.qos.logback:logback-parent:pom:1.1.10
CAPSULE: Downloading dependency ch.grengine:grengine:pom:1.2.1
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-xml:pom:2.4.15
CAPSULE: Downloading dependency io.nextflow:nextflow:pom:0.30.2
CAPSULE: Downloading dependency com.google.guava:guava:pom:16.0.1
CAPSULE: Downloading dependency com.google.guava:guava-parent:pom:16.0.1
CAPSULE: Downloading dependency ch.qos.logback:logback-core:pom:1.1.10
CAPSULE: Downloading dependency org.codehaus.jsr166-mirror:jsr166y:pom:1.7.0
CAPSULE: Downloading dependency org.apache.httpcomponents:httpclient:pom:4.5.5
CAPSULE: Downloading dependency org.apache.httpcomponents:httpcomponents-client:pom:4.5.5
CAPSULE: Downloading dependency org.apache.httpcomponents:httpcomponents-parent:pom:10
CAPSULE: Downloading dependency org.slf4j:log4j-over-slf4j:pom:1.7.21
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-s3:pom:1.11.324
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-ec2:pom:1.11.324
CAPSULE: Downloading dependency com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:pom:2.6.7
CAPSULE: Downloading dependency org.codehaus.groovy:groovy:pom:2.4.15
CAPSULE: Downloading dependency javax.activation:activation:pom:1.1
CAPSULE: Downloading dependency commons-lang:commons-lang:pom:2.6
CAPSULE: Downloading dependency org.apache.commons:commons-parent:pom:17
CAPSULE: Downloading dependency software.amazon.ion:ion-java:pom:1.0.2
CAPSULE: Downloading dependency org.eclipse.jgit:org.eclipse.jgit:pom:4.8.0.201706111038-r
CAPSULE: Downloading dependency org.eclipse.jgit:org.eclipse.jgit-parent:pom:4.8.0.201706111038-r
CAPSULE: Downloading dependency org.objenesis:objenesis:pom:2.1
CAPSULE: Downloading dependency org.objenesis:objenesis-parent:pom:2.1
CAPSULE: Downloading dependency org.yaml:snakeyaml:pom:1.18
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb:pom:0.7
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-batch:pom:1.11.324
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-json:pom:2.4.15
CAPSULE: Downloading dependency org.slf4j:jul-to-slf4j:pom:1.7.21
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-databind:pom:2.6.7.1
CAPSULE: Downloading dependency org.slf4j:slf4j-api:pom:1.7.22
CAPSULE: Downloading dependency org.slf4j:slf4j-parent:pom:1.7.22
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-annotations:pom:2.6.0
CAPSULE: Downloading dependency com.fasterxml.jackson:jackson-parent:pom:2.6.1
CAPSULE: Downloading dependency com.fasterxml:oss-parent:pom:23
CAPSULE: Downloading dependency commons-codec:commons-codec:pom:1.10
CAPSULE: Downloading dependency org.apache.commons:commons-parent:pom:35
CAPSULE: Downloading dependency org.apache:apache:pom:15
CAPSULE: Downloading dependency org.multiverse:multiverse-core:jar:0.7.0
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb-api:jar:0.7
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-kms:jar:1.11.324
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-core:jar:1.11.324
CAPSULE: Downloading dependency joda-time:joda-time:jar:2.8.1
CAPSULE: Downloading dependency com.beust:jcommander:jar:1.35
CAPSULE: Downloading dependency com.sun.activation:javax.activation:jar:1.2.0
CAPSULE: Downloading dependency com.amazonaws:jmespath-java:jar:1.11.324
CAPSULE: Downloading dependency org.jsoup:jsoup:jar:1.11.2
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-nio:jar:2.4.15
CAPSULE: Downloading dependency javax.mail:mail:jar:1.4.7
CAPSULE: Downloading dependency org.slf4j:jcl-over-slf4j:jar:1.7.21
CAPSULE: Downloading dependency io.nextflow:nxf-s3fs:jar:1.0.3
CAPSULE: Downloading dependency org.apache.httpcomponents:httpcore:jar:4.4.9
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-core:jar:2.6.7
CAPSULE: Downloading dependency org.codehaus.gpars:gpars:jar:1.2.1
CAPSULE: Downloading dependency io.nextflow:nxf-httpfs:jar:0.30.2
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-templates:jar:2.4.15
CAPSULE: Downloading dependency com.esotericsoftware.kryo:kryo:jar:2.24.0
CAPSULE: Downloading dependency io.nextflow:nxf-commons:jar:0.30.2
CAPSULE: Downloading dependency org.apache.ivy:ivy:jar:2.3.0
CAPSULE: Downloading dependency com.googlecode.javaewah:JavaEWAH:jar:1.1.6
CAPSULE: Downloading dependency com.jcraft:jsch:jar:0.1.54
CAPSULE: Downloading dependency ch.qos.logback:logback-classic:jar:1.1.10
CAPSULE: Downloading dependency ch.grengine:grengine:jar:1.2.1
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-xml:jar:2.4.15
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:0.30.2
CAPSULE: Downloading dependency com.google.guava:guava:jar:16.0.1
CAPSULE: Downloading dependency ch.qos.logback:logback-core:jar:1.1.10
CAPSULE: Downloading dependency org.codehaus.jsr166-mirror:jsr166y:jar:1.7.0
CAPSULE: Downloading dependency org.apache.httpcomponents:httpclient:jar:4.5.5
CAPSULE: Downloading dependency org.slf4j:log4j-over-slf4j:jar:1.7.21
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-s3:jar:1.11.324
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-ec2:jar:1.11.324
CAPSULE: Downloading dependency com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7
CAPSULE: Downloading dependency org.codehaus.groovy:groovy:jar:2.4.15
CAPSULE: Downloading dependency javax.activation:activation:jar:1.1
CAPSULE: Downloading dependency commons-lang:commons-lang:jar:2.6
CAPSULE: Downloading dependency software.amazon.ion:ion-java:jar:1.0.2
CAPSULE: Downloading dependency org.eclipse.jgit:org.eclipse.jgit:jar:4.8.0.201706111038-r
CAPSULE: Downloading dependency org.objenesis:objenesis:jar:2.1
CAPSULE: Downloading dependency org.yaml:snakeyaml:jar:1.18
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb:jar:0.7
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-batch:jar:1.11.324
CAPSULE: Downloading dependency org.codehaus.groovy:groovy-json:jar:2.4.15
CAPSULE: Downloading dependency org.slf4j:jul-to-slf4j:jar:1.7.21
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-databind:jar:2.6.7.1
CAPSULE: Downloading dependency org.slf4j:slf4j-api:jar:1.7.22
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0
CAPSULE: Downloading dependency commons-codec:commons-codec:jar:1.10
N E X T F L O W  ~  version 0.30.2
Pulling SGI-Pipelines/nextflow_transcriptomics ...
ERROR ~ Unable to determine the current character, it is not a string, number, array, or object

The current character read is '<' with an int value of 60
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
<!DOCTYPE html>
^

 -- Check '.nextflow.log' file for details
```
And here is the exception found in .nextflow.log:

```
 at groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:206)
  at groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:157)
  at groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:46)
  at groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:384)
  at groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:112)
  at groovy.json.JsonSlurper.parseText(JsonSlurper.java:205)
  at nextflow.scm.RepositoryProvider.memoizedMethodPriv$invokeAndParseResponseString(RepositoryProvider.groovy:175)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
  at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
  at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
  at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
  at nextflow.scm.RepositoryProvider$_closure1.doCall(RepositoryProvider.groovy)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
  at groovy.lang.Closure.call(Closure.java:418)
  at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:134)
  at groovy.lang.Closure.call(Closure.java:434)
  at nextflow.scm.RepositoryProvider.invokeAndParseResponse(RepositoryProvider.groovy)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
  at nextflow.scm.GitlabRepositoryProvider.getDefaultBranch(GitlabRepositoryProvider.groovy:60)
  at nextflow.scm.GitlabRepositoryProvider.getContentUrl(GitlabRepositoryProvider.groovy:71)
  at nextflow.scm.GitlabRepositoryProvider.readBytes(GitlabRepositoryProvider.groovy:96)
  at nextflow.scm.RepositoryProvider.validateFor(RepositoryProvider.groovy:202)
  at nextflow.scm.AssetManager.checkValidRemoteRepo(AssetManager.groovy:346)
  at nextflow.scm.AssetManager.download(AssetManager.groovy:550)
  at nextflow.scm.AssetManager.download(AssetManager.groovy)
  at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:292)
  at nextflow.cli.CmdRun.run(CmdRun.groovy:207)
  at nextflow.cli.Launcher.run(Launcher.groovy:428)
  at nextflow.cli.Launcher.main(Launcher.groovy:586)
```
After seeing this failure, if we start the pipeline in 0.29.0, stop it, and then run it with 0.30.2 the pipeline works.  This tells me the problem is really just with how the project gets pulled from gitlab.

**Comment by pditommaso** [comment]
Are you using a private GitLab server right? This it is caused by #734. In a nutshell, GitLab API v3 has been discontinued, latest version of NF uses GitLab API v4.

**Comment by msmootsgi** [comment]
Wow, this is really unfortunate.  Just because v3 of the API has been discontinued by _new_ installations of gitlab doesn't mean it's now unused by existing installations.  Upgrading gitlab is highly non-trivial since it's such a foundational resource in our stack.  The changes in https://github.com/nextflow-io/nextflow/issues/734 don't seem that bad - can we support both versions?  Maybe as a config option (or options)?

**Comment by pditommaso** [comment]
That should be possible. What about having a env var `NXF_GITLAB_LEGACY` ?

**Comment by msmootsgi** [comment]
I think an env var would be great!

**Comment by msmootsgi** [comment]
Sorry, didn't see this comment.  An option in the config file would probably be fine too. 

That being said, we've now upgraded our Gitlab server so we're also using V4 of the API.  It turns out that several other people wanted the upgrade as well, so it got bumped in priority.  If no one else complains about gitlab, you can probably close this ticket.

**Comment by pditommaso** [comment]
👍
