### ISSUE TITLE
Unable to initialize nextflow environment

### ISSUE THREAD

**Issue by TainVelasco-Luquez** [nextflow-io/nextflow#770]
# The problem
Hello.
I am running Ubuntu 18.04 and when downloading Nextflow using ``wget -qO- https://get.nextflow.io | bash`` to install it it throws me a lot of `CAPSULE: Transfer failed:...` errors. By looking at other threads (<https://groups.google.com/forum/#!searchin/nextflow/Unable$20to$20initialize$20nextflow$20environment|sort:date/nextflow/x1EvTWwYAG8/tClskDJZCAAJ> and <https://groups.google.com/forum/#!topic/nextflow/gomqlcZXsQQ/discussion>) I tried setting up the correct java version (as I was running java 11) and downloading the self-contained executable `wget -O nextflow http://www.nextflow.io/releases/v0.14.3/nextflow-0.14.3-all` which also throws me the same error (the verbose output is in the file [self_contained_verbose.txt](https://github.com/nextflow-io/nextflow/files/2137736/self_contained_verbose.txt)).

What do you think could be rising the issues?

>**Note:** I am not running behind any proxy

Some useful information:
 ```java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

 ```sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                         Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1101      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1101      manual mode
* 2            /usr/lib/jvm/java-8-oracle/jre/bin/java       1081      manual mode 
```
***
# Solution
After reading carefully the output of the verbose what I did was
```
wget -qO- https://get.nextflow.io | bash
```
To create the `.nextflow/` dir, which contains the `capsule/` folder mentioned in the output of verbose. 
Then (following @pditommaso in <https://groups.google.com/forum/#!topic/nextflow/gomqlcZXsQQ/discussion>)

```
wget -O nextflow http://www.nextflow.io/releases/v0.14.3/nextflow-0.14.3-all
chmod 777 nextflow 
nextflow run tutorial.nf 
```
And now the verbose output looks like 
[new_self_contained_verbose.txt](https://github.com/nextflow-io/nextflow/files/2137824/new_self_contained_verbose.txt) and no `Unable to initialize nextflow environment` message is shown.

All fine after all, however, I would like to know why the normal installation did not work properly the first time?

**Comment by pditommaso** [comment]
It's very strange is trying to download version `0.14.3` and not the latest one. What's the output of ?

```
env | grep NXF
```

**Comment by TainVelasco-Luquez** [comment]
Thanks for the fast reply. After the update, the output of  `env` is (there is no NXF)

```
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_MEASUREMENT=en_GB.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_PAPER=en_GB.UTF-8
LC_MONETARY=en_GB.UTF-8
TERMINATOR_UUID=urn:uuid:a44c9035-25c9-4407-9ea5-4d47b5b87671
XDG_MENU_PREFIX=gnome-
LANG=en_GB.UTF-8
DISPLAY=:0
GNOME_SHELL_SESSION_MODE=ubuntu
COLORTERM=truecolor
USERNAME=tain
JAVA_HOME=/usr/lib/jvm/java-8-oracle
J2SDKDIR=/usr/lib/jvm/java-8-oracle
XDG_VTNR=2
GIO_LAUNCHED_DESKTOP_FILE_PID=25662
SSH_AUTH_SOCK=/run/user/1001/keyring/ssh
LC_NAME=en_GB.UTF-8
XDG_SESSION_ID=39
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
USER=tain
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
PWD=/home/tain
HOME=/home/tain
TEXTDOMAIN=im-config
J2REDIR=/usr/lib/jvm/java-8-oracle/jre
SSH_AGENT_PID=25274
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
TERMINATOR_DBUS_NAME=net.tenshu.Terminator20x1a6021154d881c
XDG_SESSION_DESKTOP=ubuntu
LC_ADDRESS=en_GB.UTF-8
GJS_DEBUG_OUTPUT=stderr
LC_NUMERIC=en_GB.UTF-8
GTK_MODULES=gail:atk-bridge
TERMINATOR_DBUS_PATH=/net/tenshu/Terminator2
PAPERSIZE=a4
WINDOWPATH=2
TERM=xterm-256color
VTE_VERSION=5202
SHELL=/bin/bash
QT_IM_MODULE=xim
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1001/gnupg/S.gpg-agent:0:1
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/terminator.desktop
SHLVL=1
XDG_SEAT=seat0
LANGUAGE=en_GB:en
LC_TELEPHONE=en_GB.UTF-8
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=tain
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
XDG_RUNTIME_DIR=/run/user/1001
XAUTHORITY=/run/user/1001/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/home/tain/miniconda3/bin:/home/tain/.local/bin:/home/tain/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
LC_IDENTIFICATION=en_GB.UTF-8
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/052EFCI174038:@/tmp/.ICE-unix/25181,unix/052EFCI174038:/tmp/.ICE-unix/25181
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
LC_TIME=en_GB.UTF-8
OLDPWD=/home/tain/bin
_=/usr/bin/env
```

**Comment by pditommaso** [comment]
Can you copy and paste the output of 

```
curl  -fsSL https://get.nextflow.io | bash 
```

**Comment by TainVelasco-Luquez** [comment]
The same as using `wget -qO- https://get.nextflow.io | bash`. The complete output is 
[curl_output.txt](https://github.com/nextflow-io/nextflow/files/2137901/curl_output.txt)

**Comment by pditommaso** [comment]
Are you behind a proxy?

**Comment by TainVelasco-Luquez** [comment]
No, at least not apparently. After checking the `env` there is no proxy info at all. Furthermore, checking it using [what is my ip](https://www.whatismyip.com/proxy-check/?iref=home) further confirm that there is no proxy:
![screenshot from 2018-06-26 11-23-02](https://user-images.githubusercontent.com/15576215/41925848-5e4a1470-7933-11e8-9638-ac3975b8dce1.png)

**Comment by pditommaso** [comment]
If  so try the following and copy here the output 

```
nextflow -Dcapsule.log=verbose info 
```

**Comment by TainVelasco-Luquez** [comment]
It is a very long output to comment it out here, so -> [default_installation_verbose.txt](https://github.com/nextflow-io/nextflow/files/2138032/default_installation_verbose.txt)

**Comment by pditommaso** [comment]
OK, it's problem with the Java security certificates. 

```
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at capsule.org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
	at capsule.org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
	at capsule.org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at capsule.org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at capsule.org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at capsule.org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at capsule.org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at capsule.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at capsule.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at capsule.org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:158)
	at capsule.org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:318)
	at capsule.org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:274)
	at capsule.org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
	at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at capsule.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 33 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)
	at sun.security.validator.Validator.getInstance(Validator.java:179)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	... 49 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
	... 61 more
``` 

Frankly I've never seen before. Try to ask to your sysadmin or google for it. Please update this issue as you have solved it.

**Comment by TainVelasco-Luquez** [comment]
Ok. Thank you anyway for the quick response and help. 

# Solution
After reading carefully the output of the verbose what I did was
```
wget -qO- https://get.nextflow.io | bash
```
To create the `.nextflow/` dir, which contains the `capsule/` folder mentioned in the output of verbose. 
Then (following @pditommaso in <https://groups.google.com/forum/#!topic/nextflow/gomqlcZXsQQ/discussion>)

```
wget -O nextflow http://www.nextflow.io/releases/v0.14.3/nextflow-0.14.3-all
chmod 777 nextflow 
nextflow run tutorial.nf 
```
And now the output is 

```
N E X T F L O W  ~  version 0.14.3
Launching tutorial.nf
[warm up] executor > local
[41/15c074] Submitted process > splitLetters (1)
[5c/e3b845] Submitted process > convertToUpper (2)
[2d/b1748a] Submitted process > convertToUpper (1)
WORLD!
HELLO
```
And the verbose output looks like 
[new_self_contained_verbose.txt](https://github.com/nextflow-io/nextflow/files/2137824/new_self_contained_verbose.txt) and no `Unable to initialize nextflow environment` message is shown.

everybody is happy =)

**Comment by huguesfontenelle** [comment]
In short, don't forget
```
chmod 777 nextflow 
```

**Comment by boutrys** [comment]
Hello, 

for me it did not worked 

nor the conda install, nor the install described here https://nf-co.re/docs/usage/installation


And this (from above )
wget -O nextflow http://www.nextflow.io/releases/v0.14.3/nextflow-0.14.3-all
chmod 777 nextflow 
nextflow run tutorial.nf 

Gave me this 
Error: cannot find Java or it's a wrong version -- please make sure that Java 7 or higher it's installed
Note: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /work/gr-fe/sboutry/tools/jdk-21.0.2/bin/java
 JAVA_HOME: /work/gr-fe/sboutry/tools/jdk-21.0.2
 
 but java -version give me this 
 java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

Anyone has an idea why it do not work for me ?

Thanks in advance, 

Simon

**Comment by anaellle** [comment]
Hello, 

I have the same problem as @boutrys, does anyone found a solution ?

Thanks
Anaëlle
