### ISSUE TITLE
Ignite executor fills up logs when node was disconnected from the topology

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#810]
## Bug report 

The ingite executor failed when it appeared that a node was disconnected from the topology.
This resulted in the error continually being written to the .node-nextflow.log file on that node and filling up the file system.

This was reported on the mailing list: https://groups.google.com/forum/#!topic/nextflow/YtjS3q6XZlM 
An example log file (up to the part where the same error keeps getting written) is here: https://gist.github.com/tdudgeon/de8e0702baf71e3bd9564ec38a283cb7

### Expected behavior and actual behavior

The error should be written to the log, but it should not continue to be written so that it fills up the file system.

### Environment 

* Nextflow version: 0.30.2
* Java version: 1.8.0_171
* Operating system: Linux

**Comment by pditommaso** [comment]
The relevant error stack trace is the following: 

```
Jul-20 22:41:55.411 [scheduler-agent] ERROR nextflow.scheduler.SchedulerAgent - === Unexpected scheduler agent error
javax.cache.CacheException: Failed to process query request (grid is stopping).
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.query(IgniteCacheProxyImpl.java:618)
	at org.apache.ignite.internal.processors.cache.GatewayProtectedCacheProxy.query(GatewayProtectedCacheProxy.java:368)
	at nextflow.scheduler.SchedulerAgent$AgentProcessor.processPendingTasks(SchedulerAgent.groovy:284)
	at nextflow.scheduler.SchedulerAgent$AgentProcessor.run(SchedulerAgent.groovy:149)
Caused by: org.apache.ignite.IgniteCheckedException: Failed to process query request (grid is stopping).
	at org.apache.ignite.internal.processors.query.GridQueryProcessor.executeQuery(GridQueryProcessor.java:2578)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.query(IgniteCacheProxyImpl.java:372)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.query(IgniteCacheProxyImpl.java:610)
	... 3 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to process query request (grid is stopping).
	at org.apache.ignite.internal.processors.cache.query.GridCacheQueryManager.scanQueryLocal(GridCacheQueryManager.java:1405)
	at org.apache.ignite.internal.processors.cache.query.GridCacheQueryAdapter.executeScanQuery(GridCacheQueryAdapter.java:545)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl$1.applyx(IgniteCacheProxyImpl.java:375)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl$1.applyx(IgniteCacheProxyImpl.java:373)
	at org.apache.ignite.internal.util.lang.IgniteOutClosureX.apply(IgniteOutClosureX.java:36)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor.executeQuery(GridQueryProcessor.java:2555)
	... 5 common frames omitted
```
