### ISSUE TITLE
Nextflow stops execution reporting input channel has been used twice as an input by process and another operator

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#819]
## Bug report 

Nextflow stops execution with error:
```
nextflow.dag.MultipleInputChannelException: Channel `inputChannelS3` has been used twice as an input by process `newtest` and another operator
```

This error shouln't be raised _after_ adding the configuration line for dumpInterval - as this introduces the error. Without the line the workflow finishes successfully.

### Expected behavior and actual behavior

Nextflow should execute the code without any error even if dumpInterval is set.

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block.
Whenever possible upload the `.nextflow.log` file.)
```
Jul-31 21:51:32.654 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: awsbatch)
Jul-31 21:51:32.657 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: awsbatch
Jul-31 21:51:32.755 [main] INFO  n.cloud.aws.batch.AwsBatchExecutor - Uploading local `bin` scripts folder to s3://test/work/sum-4b80cac7-6c39-437c-b602-f5b73029e73a/t
mp/c2/ff058a5a70eeba5896bb5d393e673f/bin
Jul-31 21:51:52.680 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:52:02.682 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:52:12.683 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:52:22.684 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:52:32.686 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:52:42.688 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:52:52.690 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:53:02.691 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:53:12.693 [Task monitor] DEBUG n.processor.TaskPollingMonitor - No more task to compute -- Execution may be stalled
Jul-31 21:53:20.233 [main] DEBUG nextflow.Session - >>> barrier register (process: newtest)
Jul-31 21:53:20.235 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > newtest -- maxForks: 8
Jul-31 21:53:20.250 [main] DEBUG nextflow.Session - Session aborted -- Cause: Channel `inputChannelS3` has been used twice as an input by process `newtest` and another operator
Jul-31 21:53:20.255 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: awsbatch)
Jul-31 21:53:20.276 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.dag.MultipleInputChannelException: Channel `inputChannelS3` has been used twice as an input by process `newtest` and another operator
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:266)
        at nextflow.dag.DAG.inbound(DAG.groovy:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at nextflow.dag.DAG$_addVertex_closure1.doCall(DAG.groovy:131)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
        at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:90)
        at nextflow.dag.DAG.addVertex(DAG.groovy:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
        at nextflow.dag.DAG.addProcessNode(DAG.groovy:89)
        at nextflow.dag.NodeMarker.addProcessNode(NodeMarker.groovy:54)
        at nextflow.dag.NodeMarker$addProcessNode$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
        at nextflow.processor.TaskProcessor.createOperator(TaskProcessor.groovy:621)
        at nextflow.processor.TaskProcessor.run(TaskProcessor.groovy:519)
        at nextflow.processor.TaskProcessor$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at nextflow.script.BaseScript.process(BaseScript.groovy:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at _nf_script_4a03c016.run(_nf_script_4a03c016:10)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:379)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:168)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:235)
        at nextflow.cli.Launcher.run(Launcher.groovy:432)
        at nextflow.cli.Launcher.main(Launcher.groovy:590)

```

### Steps to reproduce the problem

Use given files config/aws.config and main.tf
### aws.config
```
process.executor = 'awsbatch'
process.queue = 'spotce'
process.container = 'job-definition://container:14'
aws {
        aws.region = 'region-tbd'
        aws.accessKey = 'key'
        aws.secretKey = 'key'
        client {
                storageEncryption = 'AES256'
        }
}

executor {
      dumpInterval = '1 sec'
}

```

### main.nf
```
#!/usr/bin/env nextflow

params.s3datadir = "s3://test/test/*p*aaa.aaa.gz"

Channel
        .fromPath(params.s3datadir)
        .map { file -> tuple (file, file.size()) }
        .set { inputChannelS3 }

process newtest{
        input:
        set file(inp_file), fsize from inputChannelS3

        """
        echo \$(hostname)
        """
}

```

### Environment 

  Version: 0.31.1-SNAPSHOT build 4890
  Modified: 30-07-2018 13:50 UTC
  System: Linux 4.14.42-52.37.amzn1.x86_64
  Runtime: Groovy 2.4.15 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_171-b11

**Comment by pditommaso** [comment]
I'm unable to replicate it. Please upload the `.nextflow.log` file.

**Comment by tbugfinder** [comment]
log file:
[bug819.error.nextflow.log](https://github.com/nextflow-io/nextflow/files/2251315/bug819.error.nextflow.log)

**Comment by pditommaso** [comment]
Have you stopped this manually or it crashed on its own after a while?

**Comment by tbugfinder** [comment]
It crashes on its own.

**Comment by pditommaso** [comment]
Still not able to replicate the problem. Is this a Amazon Ec2 instance right? any change to share it?

**Comment by tbugfinder** [comment]
as mentioned in #799 I was able to get rid of this error by removing all temp files and folders (.nextflow ...).
Will try to figure out which one of those is specific.

**Comment by tbugfinder** [comment]
It's EC2 maybe I could make it available somehow.

**Comment by tbugfinder** [comment]
I'm still ending up in this error if I do not start within an empty "workspace".
Today NF should run the 3rd time within the workspace and NF ends up in that error. All three executions should were created by NF `version 18.10.1`. 

Would there be any trace option available which could bring us closer to it. I'm preparing a public instance. Which public ssh key would you use to login?

**Comment by pditommaso** [comment]
This error is generally a side effect of some other exception. What do you mean by "empty workspace"? Is maybe related to #916 ?

You can produce a more detailed logging using: 

```
nextflow -trace nextflow run .. etc
```

Upload the resulting log when done (note: `-trace` option is *before* `run`).

**Comment by tbugfinder** [comment]
I refered to an empty workspace by cleaning up the .nextflow folder and any trace file which was created before in the current working directory. Luckily I also run into the issue and will collect trace files.

**Comment by pditommaso** [comment]
Closing this. If you have more evidence feel free to re-open it.

**Comment by monfortm** [comment]
Hello,

@pditommaso Could you elborate on your comment above:

> This error is generally a side effect of some other exception. 

I have a similar issue where I am sure my channel is not used by another process or operator.
The error I hit is:

```
nextflow.dag.MultipleInputChannelException: Channel `Clustering_ch` has been used as an input by more than a process or an operator
```

**Comment by pditommaso** [comment]
The error message is misleading, there's a patch in the current master. I should release early next week.

**Comment by Cynthia1012** [comment]
Hello,
@pditommaso  I have a similar issue where I am sure my channel is not used by another process or operator.
The error I hit is:
Channel `conbine_qcstat_ch` has been used as an input by more than a process or an operator

But if you run it again without making any changes, it will succeed. 
nextflow version 20.10.0.5430

**Comment by levin8023** [comment]
`a_done = Channel.value()
b_done = Channel.value()
c_done = Channel.value()

process c {

    input:
    val a_done from a_done
    val b_done from b_done

    output:
    val done into c_done

    script:
    done = true
    """
    sleep 1
    """
}

process b {

    input:
    val a_done from a_done

    output:
    val done into b_done

    script:
    done = true
    """
    sleep 1
    """
}

process a {

    output:
    val done into a_done

    script:
    done = true
    """
    sleep 1
    """
}
`
Could you help me to figure out why the code bellow can't work, here's the error: 
Channel `a_done` has been used twice as an output by process `a` and another operator, 
and if i change the place of process 'a' before process 'c', it will work successfully.

In some cases, our workflow is very complicated, we can't know where it should be in order
