### ISSUE TITLE
The AWS Batch execution hangs when running on 1 cpu machine 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#825]
## Bug report 

The AWS Batch executor hangs and do not submit any job when running on a 1 cpu machine. 

The threads dump reveal deadlock: 

```
"AWSBatch-executor-1" #22 prio=5 os_prio=0 tid=0x0000000001178bf0 nid=0x6265 waiting on condition [0x00007f3a3120a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e1cd7048> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:244)
	at nextflow.util.ThrottlingExecutor.doInvoke1(ThrottlingExecutor.groovy:680)

 "AWSBatch-executor-2" #23 prio=5 os_prio=0 tid=0x000000000117a540 nid=0x6266 waiting on condition [0x00007f3a3110b000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000ed5bfb70> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at java_util_concurrent_locks_Lock$lock.call(Unknown Source)
	at nextflow.cloud.aws.batch.AwsBatchTaskHandler.resolveJobDefinition(AwsBatchTaskHandler.groovy:347)


"AWSBatch-executor-3" #24 prio=5 os_prio=0 tid=0x000000000117da80 nid=0x6267 waiting on condition [0x00007f3a3100a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000ed5bfb70> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at java_util_concurrent_locks_Lock$lock.call(Unknown Source)
	at nextflow.cloud.aws.batch.AwsBatchTaskHandler.resolveJobDefinition(AwsBatchTaskHandler.groovy:347)

 "AWSBatch-executor-4" #25 prio=5 os_prio=0 tid=0x000000000117ed10 nid=0x6268 waiting on condition [0x00007f3a30f09000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000ed5bfb70> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at java_util_concurrent_locks_Lock$lock.call(Unknown Source)
	at nextflow.cloud.aws.batch.AwsBatchTaskHandler.resolveJobDefinition(AwsBatchTaskHandler.groovy:347)          


"AWSBatch-executor-5" #26 prio=5 os_prio=0 tid=0x0000000001180110 nid=0x6269 waiting on condition [0x00007f3a30e08000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000ed5bfb70> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at java_util_concurrent_locks_Lock$lock.call(Unknown Source)
	at nextflow.cloud.aws.batch.AwsBatchTaskHandler.resolveJobDefinition(AwsBatchTaskHandler.groovy:347)    
```

This happens because the job submit request tries to make another remote request (`resolveJobDefinition`) which tries to use another thread form the pool. 

The problem can be replicated with the example in [this repository](https://github.com/pditommaso/nf-issue-825).

### Environment 

* Nextflow version: 0.31.0  
* Java version: any 
* Operating system: Amazon Linux

**Comment by pditommaso** [comment]
Fixed `0.31.1-SNAPSHOT.4891`
