### ISSUE TITLE
Apache Ignite - Node is out of Topology (probably due to short-time network problems)

### ISSUE THREAD

**Issue by aresDeathscythe** [nextflow-io/nextflow#830]
Hi,

I am creating a nextflow cluster via: nextflow cloud create <name of cluster> -c <number of nodes> via my own nextflow.config e.g:

cloud {
    imageId = 'ami-000f09a50620477fa'
    sharedStorageId = 'fs-2b8f4972'
    sharedStorageMount = '<name of storage mount>'
    instanceRole = '<name of role>'
    instanceType = 'm4.10xlarge'
    spotPrice = 0.64
    securityGroup = 'sg-1e5cf672'
    subnetId = 'subnet-bd07ffc0'
    userName = 'ubuntu'
    keyName = '<name of key>'
}

So far so good cluster is starting up and I can execute my nextflow workflow without any problems.
Now I want to analyse big amount of data with my workflow and the master is perfectly communicating with the workers and processing my workflow.

Now if I have a big amount of data and after running ~20 minutes I get the following error:

Aug-09 08:32:26.139 [tcp-comm-worker-#1%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished node ping [nodeId=0023b2f2-e756-401e-b0db-db94fa9e9351, res=true, time=6ms]
Aug-09 08:32:26.144 [tcp-disco-srvr-#3%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - TCP discovery accepted incoming connection [rmtAddr=/10.0.0.9, rmtPort=54161]
Aug-09 08:32:26.144 [tcp-disco-srvr-#3%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - TCP discovery spawning a new thread for connection [rmtAddr=/10.0.0.9, rmtPort=54161]
Aug-09 08:32:26.144 [tcp-disco-sock-reader-#9%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Started serving remote node connection [rmtAddr=/10.0.0.9:54161, rmtPort=54161]
Aug-09 08:32:26.150 [tcp-disco-msg-worker-#2%nextflow%] WARN  o.a.i.s.d.tcp.TcpDiscoverySpi - Node is out of topology (probably, due to short-time network problems).
Aug-09 08:32:26.150 [tcp-disco-sock-reader-#9%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished serving remote node connection [rmtAddr=/10.0.0.9:54161, rmtPort=54161
Aug-09 08:32:26.152 [disco-event-worker-#123%nextflow%] WARN  o.a.i.i.m.d.GridDiscoveryManager - Local node SEGMENTED: TcpDiscoveryNode [id=027780ec-d3a9-424b-bffa-d34b2abe1453, addrs=[0:0:0:0:0:0:0:1%lo, 10.0.0.61, 127.0.0.1, 172.17.0.1], sockAddrs=[ip-10-0-0-61.eu-central-1.compute.internal/10.0.0.61:47500, ip-172-17-0-1.eu-central-1.compute.internal/172.17.0.1:47500, /0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500], discPort=47500, order=4, intOrder=4, lastExchangeTime=1533803546142, loc=true, ver=2.4.0#20180305-sha1:aa342270, isClient=false]
Aug-09 08:32:26.163 [disco-event-worker-#123%nextflow%] WARN  o.a.i.i.m.d.GridDiscoveryManager - Stopping local node according to configured segmentation policy.
Aug-09 08:32:26.164 [disco-event-worker-#123%nextflow%] WARN  o.a.i.i.m.d.GridDiscoveryManager - Node FAILED: TcpDiscoveryNode [id=a441908a-5a31-4f85-a29c-cf72bdcbfc91, addrs=[0:0:0:0:0:0:0:1%lo, 10.0.0.9, 127.0.0.1, 172.17.0.1], sockAddrs=[ip-172-17-0-1.eu-central-1.compute.internal/172.17.0.1:47500, ip-10-0-0-9.eu-central-1.compute.internal/10.0.0.9:47500, /0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500], discPort=47500, order=1, intOrder=1, lastExchangeTime=1533801206351, loc=false, ver=2.4.0#20180305-sha1:aa342270, isClient=false]
Aug-09 08:32:26.166 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager - Topology snapshot [ver=5, servers=3, clients=0, CPUs=120, offheap=94.0GB, heap=80.0GB]
Aug-09 08:32:26.166 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager - Data Regions Configured:
Aug-09 08:32:26.166 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager -   ^-- default [initSize=256.0 MiB, maxSize=31.5 GiB, persistenceEnabled=false]
Aug-09 08:32:26.173 [Thread-4] INFO  o.a.i.i.p.r.p.t.GridTcpRestProtocol - Command protocol successfully stopped: TCP binary
Aug-09 08:32:26.185 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.p.c.d.d.p.GridDhtPartitionsExchangeFuture - Finish exchange future [startVer=AffinityTopologyVersion [topVer=5, minorTopVer=0], resVer=null, err=class org.apache.ignite.internal.IgniteInterruptedCheckedException: Node is stopping: nextflow]
Aug-09 08:32:26.193 [disco-event-worker-#123%nextflow%] WARN  o.a.i.i.m.d.GridDiscoveryManager - Node FAILED: TcpDiscoveryNode [id=39614955-3940-45a0-adad-93fcfebe7df7, addrs=[0:0:0:0:0:0:0:1%lo, 10.0.0.211, 127.0.0.1, 172.17.0.1], sockAddrs=[ip-172-17-0-1.eu-central-1.compute.internal/172.17.0.1:47500, /0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500, ip-10-0-0-211.eu-central-1.compute.internal/10.0.0.211:47500], discPort=47500, order=2, intOrder=2, lastExchangeTime=1533801206351, loc=false, ver=2.4.0#20180305-sha1:aa342270, isClient=false]
Aug-09 08:32:26.193 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager - Topology snapshot [ver=6, servers=2, clients=0, CPUs=80, offheap=63.0GB, heap=53.0GB]
Aug-09 08:32:26.193 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager - Data Regions Configured:
Aug-09 08:32:26.193 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager -   ^-- default [initSize=256.0 MiB, maxSize=31.5 GiB, persistenceEnabled=false]
Aug-09 08:32:26.195 [disco-event-worker-#123%nextflow%] WARN  o.a.i.i.m.d.GridDiscoveryManager - Node FAILED: TcpDiscoveryNode [id=0023b2f2-e756-401e-b0db-db94fa9e9351, addrs=[0:0:0:0:0:0:0:1%lo, 10.0.0.183, 127.0.0.1, 172.17.0.1], sockAddrs=[ip-10-0-0-183.eu-central-1.compute.internal/10.0.0.183:47500, ip-172-17-0-1.eu-central-1.compute.internal/172.17.0.1:47500, /0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500], discPort=47500, order=3, intOrder=3, lastExchangeTime=1533801206372, loc=false, ver=2.4.0#20180305-sha1:aa342270, isClient=false]
Aug-09 08:32:26.195 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager - Topology snapshot [ver=7, servers=1, clients=0, CPUs=40, offheap=31.0GB, heap=27.0GB]
Aug-09 08:32:26.195 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager - Data Regions Configured:
Aug-09 08:32:26.195 [disco-event-worker-#123%nextflow%] INFO  o.a.i.i.m.d.GridDiscoveryManager -   ^-- default [initSize=256.0 MiB, maxSize=31.5 GiB, persistenceEnabled=false]
Aug-09 08:32:26.327 [scheduler-agent] ERROR nextflow.scheduler.SchedulerAgent - === Unexpected scheduler agent error
javax.cache.CacheException: class org.apache.ignite.internal.NodeStoppingException: Operation has been cancelled (node is stopping).
	at org.apache.ignite.internal.processors.cache.GridCacheUtils.convertToCacheException(GridCacheUtils.java:1294)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.cacheException(IgniteCacheProxyImpl.java:1673)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.getAndRemove(IgniteCacheProxyImpl.java:1176)
	at org.apache.ignite.internal.processors.cache.GatewayProtectedCacheProxy.getAndRemove(GatewayProtectedCacheProxy.java:1054)
	at nextflow.scheduler.SchedulerAgent$AgentProcessor.processPendingTasks(SchedulerAgent.groovy:299)
	at nextflow.scheduler.SchedulerAgent$AgentProcessor.run(SchedulerAgent.groovy:149)
Caused by: org.apache.ignite.internal.NodeStoppingException: Operation has been cancelled (node is stopping).
	at org.apache.ignite.internal.processors.cache.GridCacheMvccManager.stopError(GridCacheMvccManager.java:408)
	at org.apache.ignite.internal.processors.cache.GridCacheMvccManager.onStop(GridCacheMvccManager.java:371)
	at org.apache.ignite.internal.processors.cache.GridCacheProcessor.onKernalStop(GridCacheProcessor.java:950)
	at org.apache.ignite.internal.IgniteKernal.stop0(IgniteKernal.java:2144)
	at org.apache.ignite.internal.IgniteKernal.stop(IgniteKernal.java:2092)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.stop0(IgnitionEx.java:2545)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.stop(IgnitionEx.java:2508)
	at org.apache.ignite.internal.IgnitionEx.stop(IgnitionEx.java:365)
	at org.apache.ignite.Ignition.stop(Ignition.java:224)
	at org.apache.ignite.internal.managers.discovery.GridDiscoveryManager$10.run(GridDiscoveryManager.java:2381)
	at java.lang.Thread.run(Thread.java:748)
Aug-09 08:32:26.327 [scheduler-thread] DEBUG nextflow.scheduler.Scheduler - +++ Can't process received message
javax.cache.CacheException: class org.apache.ignite.internal.NodeStoppingException: Operation has been cancelled (node is stopping).
	at org.apache.ignite.internal.processors.cache.GridCacheUtils.convertToCacheException(GridCacheUtils.java:1294)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.cacheException(IgniteCacheProxyImpl.java:1673)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.put(IgniteCacheProxyImpl.java:1029)
	at org.apache.ignite.internal.processors.cache.GatewayProtectedCacheProxy.put(GatewayProtectedCacheProxy.java:886)
	at nextflow.scheduler.Scheduler.schedule0(Scheduler.groovy:319)
	at nextflow.scheduler.Scheduler.access$0(Scheduler.groovy)
	at nextflow.scheduler.Scheduler$_schedule_closure5.doCall(Scheduler.groovy:307)
	at nextflow.scheduler.Scheduler$_schedule_closure5.call(Scheduler.groovy)
	at nextflow.scheduler.Scheduler$_createEventProcessor_closure2.doCall(Scheduler.groovy:189)
	at nextflow.scheduler.Scheduler$_createEventProcessor_closure2.call(Scheduler.groovy)
	at groovy.lang.Closure.run(Closure.java:499)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ignite.internal.NodeStoppingException: Operation has been cancelled (node is stopping).
	at org.apache.ignite.internal.processors.cache.GridCacheMvccManager.stopError(GridCacheMvccManager.java:408)
	at org.apache.ignite.internal.processors.cache.GridCacheMvccManager.onStop(GridCacheMvccManager.java:371)
	at org.apache.ignite.internal.processors.cache.GridCacheProcessor.onKernalStop(GridCacheProcessor.java:950)
	at org.apache.ignite.internal.IgniteKernal.stop0(IgniteKernal.java:2144)
	at org.apache.ignite.internal.IgniteKernal.stop(IgniteKernal.java:2092)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.stop0(IgnitionEx.java:2545)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.stop(IgnitionEx.java:2508)
	at org.apache.ignite.internal.IgnitionEx.stop(IgnitionEx.java:365)
	at org.apache.ignite.Ignition.stop(Ignition.java:224)
	at org.apache.ignite.internal.managers.discovery.GridDiscoveryManager$10.run(GridDiscoveryManager.java:2381)
	... 1 common frames omitted
Aug-09 08:32:26.328 [scheduler-thread] DEBUG nextflow.scheduler.Scheduler - +++ Node failed: [i-0655a78ba3916993a] a441908a-5a31-4f85-a29c-cf72bdcbfc91
Aug-09 08:32:26.330 [Thread-4] INFO  o.a.i.i.p.cache.GridCacheProcessor - Stopped cache [cacheName=nextflow.cache.pendingtasks]
Aug-09 08:32:26.331 [Thread-4] INFO  o.a.i.i.p.cache.GridCacheProcessor - Stopped cache [cacheName=allSessions]
Aug-09 08:32:26.332 [Thread-4] INFO  o.a.i.i.p.cache.GridCacheProcessor - Stopped cache [cacheName=ignite-sys-cache]
Aug-09 08:32:26.332 [Thread-4] INFO  o.a.i.i.p.cache.GridCacheProcessor - Stopped cache [cacheName=igfs-internal-igfs-meta]
Aug-09 08:32:26.332 [Thread-4] INFO  o.a.i.i.p.cache.GridCacheProcessor - Stopped cache [cacheName=igfs-internal-igfs-data]
Aug-09 08:32:26.342 [scheduler-agent] ERROR nextflow.scheduler.SchedulerAgent - === Unexpected scheduler agent error
java.lang.IllegalStateException: class org.apache.ignite.internal.processors.cache.CacheStoppedException: Failed to perform cache operation (cache is stopped): nextflow.cache.pendingtasks
	at org.apache.ignite.internal.processors.cache.GridCacheGateway.enter(GridCacheGateway.java:164)
	at org.apache.ignite.internal.processors.cache.GatewayProtectedCacheProxy.onEnter(GatewayProtectedCacheProxy.java:1684)
	at org.apache.ignite.internal.processors.cache.GatewayProtectedCacheProxy.query(GatewayProtectedCacheProxy.java:365)
	at nextflow.scheduler.SchedulerAgent$AgentProcessor.processPendingTasks(SchedulerAgent.groovy:284)
	at nextflow.scheduler.SchedulerAgent$AgentProcessor.run(SchedulerAgent.groovy:149)
Caused by: org.apache.ignite.internal.processors.cache.CacheStoppedException: Failed to perform cache operation (cache is stopped): nextflow.cache.pendingtasks
	... 5 common frames omitted

etc.

I have read now about a lot what to do like increasing failureDetectionTimeout or set SegmentationPolicy to RESTART_JVM etc. but I don't have any clue how and where to set those options or if there exists any other solution.

Thanks for helping!

### Environment 

* Nextflow version: 0.30.2
* Java version: 8
* Operating system: Ubuntu 16.04

**Comment by pditommaso** [comment]
The setting `failureDetectionTimeout` is now available in version `0.31.x`, see #820.

**Comment by eugenemiretsky** [comment]
@aresDeathscythe : Did you manage to resolve this? 

We are facing the same issue. Will try to increase failureDetectionTimeout, but the default of 10s seems very reasonable to me. We don't have any long gc pauses, so before increasing it blindly I want to understand the root cause.

**Comment by pditommaso** [comment]
It could be useful inspect the GC activity. Also I've updated Ignite libraries to version 2.6 in the current snapshot `0.32.0-SNAPSHOT`

**Comment by aresDeathscythe** [comment]
@eugenemiretsky sry I was on holiday. Nope I could not get it running, it seems there are a way more problems included with this problem. Unfortunately I could not dig deeper in this because I had time constraints due to my projects. I will update if I find out something.

**Comment by aresDeathscythe** [comment]
@pditommaso so the 0.32.0 snapshot is now installed if I install the 0.31.1 version?

**Comment by pditommaso** [comment]
No, you need to set the `NXF_VER` env var, for example: 

```
NXF_VER=0.32.0-SNAPSHOT nextflow run .. etc
``` 

or export explicitly in your environment.

**Comment by aresDeathscythe** [comment]
I have updated now everything to 0.32.0 and still remains the same problem (set failureDetectionTimeout on a higher value) and get now following output:

```
Oct-03 11:21:28.439 [tcp-disco-srvr-#3%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - TCP discovery spawning a new thread for connection [rmtAddr=/10.0.0.154, rmtPort=33532]
Oct-03 11:21:28.442 [tcp-disco-srvr-#3%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - TCP discovery accepted incoming connection [rmtAddr=/10.0.0.154, rmtPort=36360]
Oct-03 11:21:28.442 [tcp-disco-srvr-#3%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - TCP discovery spawning a new thread for connection [rmtAddr=/10.0.0.154, rmtPort=36360]
Oct-03 11:21:28.442 [tcp-disco-sock-reader-#7%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Started serving remote node connection [rmtAddr=/10.0.0.154:33532, rmtPort=33532]
Oct-03 11:21:28.442 [tcp-disco-sock-reader-#6%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Received ping request from the remote node [rmtNodeId=aab6d253-dbe3-43c4-8693-a12ba08cb3bb, rmtAddr=/10.0.0.154:40125, rmtPort=40125]
Oct-03 11:21:28.442 [tcp-disco-sock-reader-#7%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Received ping request from the remote node [rmtNodeId=aab6d253-dbe3-43c4-8693-a12ba08cb3bb, rmtAddr=/10.0.0.154:33532, rmtPort=33532]
Oct-03 11:21:28.442 [tcp-disco-sock-reader-#8%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Started serving remote node connection [rmtAddr=/10.0.0.154:36360, rmtPort=36360]
Oct-03 11:21:28.443 [tcp-disco-sock-reader-#7%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished writing ping response [rmtNodeId=aab6d253-dbe3-43c4-8693-a12ba08cb3bb, rmtAddr=/10.0.0.154:33532, rmtPort=33532]
Oct-03 11:21:28.443 [tcp-disco-sock-reader-#6%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished writing ping response [rmtNodeId=aab6d253-dbe3-43c4-8693-a12ba08cb3bb, rmtAddr=/10.0.0.154:40125, rmtPort=40125]
Oct-03 11:21:28.443 [tcp-disco-sock-reader-#7%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished serving remote node connection [rmtAddr=/10.0.0.154:33532, rmtPort=33532
Oct-03 11:21:28.443 [tcp-disco-sock-reader-#6%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished serving remote node connection [rmtAddr=/10.0.0.154:40125, rmtPort=40125
Oct-03 11:21:28.468 [tcp-disco-msg-worker-#2%nextflow%] WARN  o.a.i.s.d.tcp.TcpDiscoverySpi - Node is out of topology (probably, due to short-time network problems).
Oct-03 11:21:28.469 [tcp-disco-sock-reader-#8%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished serving remote node connection [rmtAddr=/10.0.0.154:36360, rmtPort=36360
Oct-03 11:21:28.469 [disco-event-worker-#183%nextflow%] WARN  o.a.i.i.m.d.GridDiscoveryManager - Local node SEGMENTED: TcpDiscoveryNode [id=24c0e6a1-4c20-4630-b77a-3bcb625b1b03, addrs=[0:0:0:0:0:0:0:1%lo, 10.0.0.215, 127.0.0.1, 172.17.0.1], sockAddrs=[ip-10-0-0-215.eu-central-1.compute.internal/10.0.0.215:47500, ip-172-17-0-1.eu-central-1.compute.internal/172.17.0.1:47500, /0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500], discPort=47500, order=7, intOrder=5, lastExchangeTime=1538565688461, loc=true, ver=2.6.0#20180710-sha1:669feacc, isClient=false]
Oct-03 11:21:28.473 [tcp-disco-srvr-#3%nextflow%] ERROR ROOT - Critical system error detected. Will be handled accordingly to configured handler [hnd=class o.a.i.failure.StopNodeOrHaltFailureHandler, failureCtx=FailureContext [type=SYSTEM_WORKER_TERMINATION, err=java.lang.IllegalStateException: Thread tcp-disco-srvr-#3%nextflow% is terminated unexpectedly.]]
java.lang.IllegalStateException: Thread tcp-disco-srvr-#3%nextflow% is terminated unexpectedly.
        at org.apache.ignite.spi.discovery.tcp.ServerImpl$TcpServer.body(ServerImpl.java:5686)
        at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:62)
Oct-03 11:21:28.474 [tcp-disco-srvr-#3%nextflow%] ERROR ROOT - JVM will be halted immediately due to the failure: [failureCtx=FailureContext [type=SYSTEM_WORKER_TERMINATION, err=java.lang.IllegalStateException: Thread tcp-disco-srvr-#3%nextflow% is terminated unexpectedly.]]
```

Maybe it is an Apache Ignite problem?

**Comment by nephantes** [comment]
I get the same error. It starts without any problem. Add all the nodes. Starts running however, while writing from multiple nodes, EFS becomes extremely slow. This might be the problem why the nodes cannot communicate. 
I put all the logs below;
https://galaxyweb.umassmed.edu/logs/test5/.nextflow.log
Do you think it is a storage issue or something else? Why do you think EFS become extremely slow while running multiple jobs?

**Comment by pditommaso** [comment]
@nephantes actually it looks even worst, initially seems a node is failing

```
Oct-26 00:34:33.745 [tcp-disco-sock-reader-#8%nextflow%] INFO  o.a.i.s.d.tcp.TcpDiscoverySpi - Finished serving remote node connection [rmtAddr=/172.31.15.218:58523, rmtPort=58523
Oct-26 00:34:33.749 [tcp-comm-worker-#1%nextflow%] ERROR o.a.i.s.c.tcp.TcpCommunicationSpi - Failed to send message: class o.a.i.IgniteCheckedException: Failed to send message (connection was closed): GridSelectorNioSessionImpl [worker=DirectNioClientWorker [super=AbstractNioClientWorker [idx=0, bytesRcvd=96138, bytesSent=417770, bytesRcvd0=2981, bytesSent0=3045, select=true, super=GridWorker [name=grid-nio-worker-tcp-comm-0, igniteInstanceName=nextflow, finished=false, hashCode=1174729239, interrupted=false, runner=grid-nio-worker-tcp-comm-0-#41%nextflow%]]], writeBuf=java.nio.DirectByteBuffer[pos=0 lim=32768 cap=32768], readBuf=java.nio.DirectByteBuffer[pos=0 lim=32768 cap=32768], inRecovery=GridNioRecoveryDescriptor [acked=1440, resendCnt=0, rcvCnt=1471, sentCnt=1466, reserved=true, lastAck=1440, nodeLeft=false, node=TcpDiscoveryNode [id=80158b7b-4ee3-42f3-8dee-ebd2316df39a, addrs=[172.31.4.153], sockAddrs=[ip-172-31-4-153.ec2.internal/172.31.4.153:47500], discPort=47500, order=2, intOrder=2, lastExchangeTime=1540513969884, loc=false, ver=2.6.0#20180710-sha1:669feacc, isClient=false], connected=true, connectCnt=0, queueLimit=4096, reserveCnt=1, pairedConnections=false], outRecovery=GridNioRecoveryDescriptor [acked=1440, resendCnt=0, rcvCnt=1471, sentCnt=1466, reserved=true, lastAck=1440, nodeLeft=false, node=TcpDiscoveryNode [id=80158b7b-4ee3-42f3-8dee-ebd2316df39a, addrs=[172.31.4.153], sockAddrs=[ip-172-31-4-153.ec2.internal/172.31.4.153:47500], discPort=47500, order=2, intOrder=2, lastExchangeTime=1540513969884, loc=false, ver=2.6.0#20180710-sha1:669feacc, isClient=false], connected=true, connectCnt=0, queueLimit=4096, reserveCnt=1, pairedConnections=false], super=GridNioSessionImpl [locAddr=/172.31.3.29:47100, rmtAddr=/172.31.4.153:42176, createTime=1540513971243, closeTime=1540514017819, bytesSent=417770, bytesRcvd=96138, bytesSent0=3045, bytesRcvd0=2981, sndSchedTime=1540513971243, lastSndTime=1540514017557, lastRcvTime=1540514017819, readsPaused=false, filterChain=FilterChain[filters=[GridNioCodecFilter [parser=o.a.i.i.util.nio.GridDirectParser@4b41be48, directMode=true], GridConnectionBytesVerifyFilter], accepted=true]]
org.apache.ignite.IgniteCheckedException: Failed to send message (connection was closed): GridSelectorNioSessionImpl [worker=DirectNioClientWorker [super=AbstractNioClientWorker [idx=0, bytesRcvd=96138, bytesSent=417770, bytesRcvd0=2981, bytesSent0=3045, select=true, super=GridWorker [name=grid-nio-worker-tcp-comm-0, igniteInstanceName=nextflow, finished=false, hashCode=1174729239, interrupted=false, runner=grid-nio-worker-tcp-comm-0-#41%nextflow%]]], writeBuf=java.nio.DirectByteBuffer[pos=0 lim=32768 cap=32768], readBuf=java.nio.DirectByteBuffer[pos=0 lim=32768 cap=32768], inRecovery=GridNioRecoveryDescriptor [acked=1440, resendCnt=0, rcvCnt=1471, sentCnt=1466, reserved=true, lastAck=1440, nodeLeft=false, node=TcpDiscoveryNode [id=80158b7b-4ee3-42f3-8dee-ebd2316df39a, addrs=[172.31.4.153], sockAddrs=[ip-172-31-4-153.ec2.internal/172.31.4.153:47500], discPort=47500, order=2, intOrder=2, lastExchangeTime=1540513969884, loc=false, ver=2.6.0#20180710-sha1:669feacc, isClient=false], connected=true, connectCnt=0, queueLimit=4096, reserveCnt=1, pairedConnections=false], outRecovery=GridNioRecoveryDescriptor [acked=1440, resendCnt=0, rcvCnt=1471, sentCnt=1466, reserved=true, lastAck=1440, nodeLeft=false, node=TcpDiscoveryNode [id=80158b7b-4ee3-42f3-8dee-ebd2316df39a, addrs=[172.31.4.153], sockAddrs=[ip-172-31-4-153.ec2.internal/172.31.4.153:47500], discPort=47500, order=2, intOrder=2, lastExchangeTime=1540513969884, loc=false, ver=2.6.0#20180710-sha1:669feacc, isClient=false], connected=true, connectCnt=0, queueLimit=4096, reserveCnt=1, pairedConnections=false], super=GridNioSessionImpl [locAddr=/172.31.3.29:47100, rmtAddr=/172.31.4.153:42176, createTime=1540513971243, closeTime=1540514017819, bytesSent=417770, bytesRcvd=96138, bytesSent0=3045, bytesRcvd0=2981, sndSchedTime=1540513971243, lastSndTime=1540514017557, lastRcvTime=1540514017819, readsPaused=false, filterChain=FilterChain[filters=[GridNioCodecFilter [parser=org.apache.ignite.internal.util.nio.GridDirectParser@4b41be48, directMode=true], GridConnectionBytesVerifyFilter], accepted=true]]
	at org.apache.ignite.internal.util.nio.GridNioServer.send0(GridNioServer.java:587)
	at org.apache.ignite.internal.util.nio.GridNioServer.sendSystem(GridNioServer.java:643)
	at org.apache.ignite.internal.util.nio.GridNioServer.sendSystem(GridNioServer.java:609)
	at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi$CommunicationWorker.processIdle(TcpCommunicationSpi.java:4271)
	at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi$CommunicationWorker.body(TcpCommunicationSpi.java:4212)
	at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:62)

```

Then also the master node terminates abruptly: 

```
Oct-26 00:34:33.994 [tcp-disco-srvr-#3%nextflow%] ERROR ROOT - Critical system error detected. Will be handled accordingly to configured handler [hnd=class o.a.i.failure.StopNodeOrHaltFailureHandler, failureCtx=FailureContext [type=SYSTEM_WORKER_TERMINATION, err=java.lang.IllegalStateException: Thread tcp-disco-srvr-#3%nextflow% is terminated unexpectedly.]]
java.lang.IllegalStateException: Thread tcp-disco-srvr-#3%nextflow% is terminated unexpectedly.
	at org.apache.ignite.spi.discovery.tcp.ServerImpl$TcpServer.body(ServerImpl.java:5686)
	at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:62)
Oct-26 00:34:33.994 [tcp-disco-srvr-#3%nextflow%] ERROR ROOT - JVM will be halted immediately due to the failure: [failureCtx=FailureContext [type=SYSTEM_WORKER_TERMINATION, err=java.lang.IllegalStateException: Thread tcp-disco-srvr-#3%nextflow% is terminated unexpectedly.]]
``` 

Could it be a that you are using a spot instance for the master node and it get retired?

**Comment by nephantes** [comment]
No I am not using spot instance. And this is repeatable. Every time I run something, it fails.

**Comment by pditommaso** [comment]
Any chance to retrieve the `.node-nextflow.log` file in the crashing instances? (in that case please open a separate issue).

**Comment by aresDeathscythe** [comment]
@nephantes thanks for this hint, I always tried to run the operation on the EFS. If I have time I will try out running it on S3 or a local volume.

**Comment by aresDeathscythe** [comment]
Sorry for my absence, was a lot of other stuff to do.

I updated now everything on the latest release, created AMI & docker images:
Ubuntu 18.04
docker 18.06.1-ce
nextflow 18.10.1.5003
java sdk 1.8.0_191

+ latest releases on bioinformatic tools (fastqc, trimmomatic, spades, kraken, ...)

What I changed is that I write the tmp files on S3 and not on the EFS, maybe this workload caused the troubles.

I tested the things with a cluster consisting of 3 m4.16xlarge machines and everything runs through without any problems (Executor Apache Ignite). I hope the issue is somehow solved now if anything appears again I will open a new thread. Thanks for helping guys.
