### ISSUE TITLE
RejectedExecutionException on successive Console executions 

### ISSUE THREAD

**Issue by chdem** [nextflow-io/nextflow#906]
## Bug report 

I have to launch ```nextflow console``` for each code execution as I'm encountering an execption after each second run.

### Expected behavior and actual behavior

Nextflow console should be able to run many run attempts.

### Program output 

This is the ```nextflow console``` output after the second attempt :
```bash
groovy> test = Channel.fromPath('*.docx').map{ file -> tuple(file.baseName,file)} 
groovy> test.subscribe {  println "Got: $it"  } 
ERROR ~ Task java.util.concurrent.CompletableFuture$UniRun@2bea071c rejected from java.util.concurrent.ThreadPoolExecutor@22db22f5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]

 -- Check '.nextflow-console.log' file for details
```

This is the .nextflow-console.log : 
```bash
oct.-24 18:27:34.333 [AWT-EventQueue-0] DEBUG nextflow.Session - Session uuid: f7fabd19-31af-4753-9402-faff88294793
oct.-24 18:27:34.337 [AWT-EventQueue-0] DEBUG nextflow.Session - Run name: angry_pauling
oct.-24 18:27:34.337 [AWT-EventQueue-0] DEBUG nextflow.Session - Executor pool size: 4
oct.-24 18:27:34.464 [AWT-EventQueue-0] DEBUG nextflow.Session - Work-dir: /mnt/isilon_data_cifs/BIO_INFO/Christophe/DOCUMENTS/work [smb2]
oct.-24 18:27:34.783 [Thread-4] DEBUG nextflow.Session - Session start invoked
oct.-24 18:27:34.792 [Thread-4] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
oct.-24 18:27:35.556 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: ./; pattern: *.docx; options: [:]
oct.-24 18:27:35.686 [Thread-4] DEBUG nextflow.Session - Session await
oct.-24 18:27:35.687 [Thread-4] DEBUG nextflow.Session - Session await > all process finished
oct.-24 18:27:35.687 [Thread-4] DEBUG nextflow.Session - Session await > all barriers passed
oct.-24 18:27:35.697 [Thread-4] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=
0ms]
oct.-24 18:27:35.721 [Thread-4] DEBUG nextflow.CacheDB - Closing CacheDB done
oct.-24 18:27:39.810 [AWT-EventQueue-0] DEBUG nextflow.Session - Session uuid: 0c5dfada-b256-4113-b71c-1680b406c765
oct.-24 18:27:39.811 [AWT-EventQueue-0] DEBUG nextflow.Session - Run name: grave_goodall
oct.-24 18:27:39.811 [AWT-EventQueue-0] DEBUG nextflow.Session - Executor pool size: 4
oct.-24 18:27:39.820 [AWT-EventQueue-0] DEBUG nextflow.Session - Work-dir: /mnt/isilon_data_cifs/BIO_INFO/Christophe/DOCUMENTS/work [smb2]
oct.-24 18:27:39.998 [Thread-5] DEBUG nextflow.Session - Session start invoked
oct.-24 18:27:39.999 [Thread-5] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
oct.-24 18:27:40.043 [Thread-5] ERROR nextflow.Channel - Task java.util.concurrent.CompletableFuture$UniRun@2bea071c rejected from java.util.concurrent.ThreadPoolExecutor@22db22f5[Terminated, pool size = 0, active threads 
= 0, queued tasks = 0, completed tasks = 1]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$UniRun@2bea071c rejected from java.util.concurrent.ThreadPoolExecutor@22db22f5[Terminated, pool size = 0, active threads = 0, que
ued tasks = 0, completed tasks = 1]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:703)
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
        at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:720)
        at java.util.concurrent.CompletableFuture.thenRunAsync(CompletableFuture.java:2019)
        at nextflow.file.PathVisitor.applyAsync(PathVisitor.groovy:75)
        at nextflow.Channel.fromPath0(Channel.groovy:214)
        at nextflow.Channel.fromPath(Channel.groovy:202)
        at nextflow.Channel.fromPath(Channel.groovy)
        at nextflow.Channel$fromPath.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at ConsoleScript1.run(ConsoleScript1:1)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:264)
        at groovy.lang.GroovyShell.run(GroovyShell.java:373)
        at groovy.lang.GroovyShell.run(GroovyShell.java:352)
        at groovy.lang.GroovyShell.run(GroovyShell.java:172)
        at groovy.lang.GroovyShell$run$0.call(Unknown Source)
        at groovy.ui.Console$_runScriptImpl_closure22.doCall(Console.groovy:1158)
        at groovy.ui.Console$_runScriptImpl_closure22.doCall(Console.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.run(Closure.java:492)
        at java.lang.Thread.run(Thread.java:748)
oct.-24 18:27:40.051 [Thread-5] DEBUG nextflow.Session - Session aborted -- Cause: Task java.util.concurrent.CompletableFuture$UniRun@2bea071c rejected from java.util.concurrent.ThreadPoolExecutor@22db22f5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
oct.-24 18:27:40.065 [Thread-5] DEBUG nextflow.Session - Session await
oct.-24 18:27:40.066 [Thread-5] DEBUG nextflow.Session - Session await > all process finished
oct.-24 18:27:40.066 [Thread-5] DEBUG nextflow.Session - Session await > all barriers passed
oct.-24 18:27:40.066 [Thread-5] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms]
oct.-24 18:27:40.076 [Thread-5] DEBUG nextflow.CacheDB - Closing CacheDB done
```

### Steps to reproduce the problem

1. launch ```nextflow console```
2. run any command as a first attempt
3. run the same command (or another one) as the second attempt

### Environment 

* Nextflow version: [18.10.1] 
* Java version: [1.8.0_181]
* Operating system: [ubuntu 18.10]

**Comment by chadisaad** [comment]
same issue here !

**ENV:**
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)

**LOG:**
oct.-24 18:06:23.245 [Thread-2] DEBUG nextflow.Session - Session start invoked
oct.-24 18:06:23.245 [Thread-2] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
oct.-24 18:06:23.265 [Thread-2] ERROR nextflow.Channel - Task java.util.concurrent.CompletableFuture$UniRun@2d50dba8 rejected from java.util.concurrent
.ThreadPoolExecutor@3cb5d24[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$UniRun@2d50dba8 rejected from java.util.concurrent.ThreadP
oolExecutor@3cb5d24[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2080)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:832)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
        at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:813)
        at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
        at java.base/java.util.concurrent.CompletableFuture.thenRunAsync(CompletableFuture.java:2130)
        at nextflow.file.PathVisitor.applyAsync(PathVisitor.groovy:75)
        at nextflow.Channel.fromPath0(Channel.groovy:214)
        at nextflow.Channel.fromPath(Channel.groovy:202)
        at nextflow.Channel.fromPath(Channel.groovy)
        at nextflow.Channel$fromPath.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at ConsoleScript1.run(ConsoleScript1:1)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:264)
        at groovy.lang.GroovyShell.run(GroovyShell.java:373)
        at groovy.lang.GroovyShell.run(GroovyShell.java:352)
        at groovy.lang.GroovyShell.run(GroovyShell.java:172)
        at groovy.lang.GroovyShell$run$0.call(Unknown Source)
:

**Comment by pditommaso** [comment]
This will be included in next release.
