### ISSUE TITLE
Error when using `file.size()` to request memory for job on cluster 

### ISSUE THREAD

**Issue by PhilPalmer** [nextflow-io/nextflow#922]
### Expected behavior and actual behavior

For [nf-core/deepvariant dev branch](https://github.com/nf-core/deepvariant/tree/dev) 
memory is set as follows in `base.config`:
```nextflow
memory = { bam.size() < 1000000000 ? 4.GB : check_max( ( bam.size()/1024/1024/1024) * 10.GB * task.attempt, 'memory')}
```

When the pipeline is run on a computing cluster the job fails to submit despite the requested resources being within the limits. (The requested node, has a max of 28 cores, 48hours of wall time and 128GB RAM per node). 

### Program output 

```
Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  qsub -N nf-make_example .command.run

Command exit status:
  168

Command output:
  qsub: submit error (Illegal attribute or resource value for Resource_List.mem)

Work dir:
  /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/d7/78ed3a18fda374310837f6ce93b9e7

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
Execution cancelled -- Finishing pending tasks before exit
```

Requested resources from .command.run:
```
#PBS -N nf-make_example
#PBS -o /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/d7/78ed3a18fda374310837f6ce93b9e7/.command.log
#PBS -j oe
#PBS -q short
#PBS -l nodes=1:ppn=20
#PBS -l walltime=10:00:00
#PBS -l mem=57.4gb
cd /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/d7/78ed3a18fda374310837f6ce93b9e7
```

Issue only appeared after using `file.size()` to set memory, see [here](https://github.com/nf-core/deepvariant/issues/5) for original issue/thread
### Steps to reproduce the problem

@apeltzer please feel free to add more information such as any steps & environment if possible, thanks

### Environment 

* Nextflow version: [?] 
* Java version: [?]
* Operating system: [macOS, Linux, etc]

**Comment by rsuchecki** [comment]
Not convinced this is a NF issue. Can men be a float on PBS?

**Comment by apeltzer** [comment]
Nextflow Version is 18.10.1, Java 8u152, Linux (CentOS7). 

Never had that issue before and PBS was fine with jobs being submitted and this just came up with that specific feature. According to https://www.osc.edu/supercomputing/batch-processing-at-osc/pbs-directives-summary , one can submit either in bytes, MB or GB mode. 

Not sure whether we can have 57.4GB though...

**Comment by pditommaso** [comment]
What executor is this? PBS or SGE ?

**Comment by apeltzer** [comment]
PBS/Torque

**Comment by pditommaso** [comment]
Somehow is expected because the result of the dyn rule you have specified is taken as it is. 

https://github.com/nextflow-io/nextflow/blob/0dc25480bb745424d9e0eb6e12e7be008b438d17/src/main/groovy/nextflow/executor/PbsExecutor.groovy#L61

Maybe NF should use always MiB to avoid the decimal. For now you should round to giga units.

**Comment by apeltzer** [comment]
`.toGiga()` works for that I suppose?

**Comment by pditommaso** [comment]
I think the problem is this `(bam.size()/1024/1024/1024)` that returns a decimal, if you replace with `bam.size() >> 30` (shift operation) should work.

**Comment by PhilPalmer** [comment]
I couldn't get `bam.size() >> 30` to work but realised I had made a mistake. No `.toInt()` doesn't exist, I was hoping you may know of a similar method but it doesn't matter now. Thanks

**Comment by PhilPalmer** [comment]
## Bug report 
### Expected behavior and actual behavior

Hi I'm trying to use the shift operation you recommend `bam.size() >> 30` however it doesn't seem to be working. I'm not sure I understand exactly what the right shift is doing. In the above example is it just dividing the `bam.size()` by 30?

Below is an examle I tried running on the Nextflow REPL console
Expected behaviour should return 50GB
Actual behaviour get an error 

### Program output 

```
groovy.lang.MissingMethodException: No signature of method: java.lang.Integer.rightShift() is applicable for argument types: (nextflow.util.MemoryUnit) values: [50 GB]
Possible solutions: rightShift(java.lang.Number), leftShift(java.lang.Number)
	at ConsoleScript11.run(ConsoleScript11:2)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

### Steps to reproduce the problem
```nextflow
bamSize = 5
bamSize >> 5 * 10.GB
```

### Environment 

* Nextflow version: [18.11.0-edge.5016] 
* Java version: [?]
* Operating system: [macOS]

Any help would be much appreciated, thanks in advance

**Comment by PhilPalmer** [comment]
## Bug report 
### Expected behavior and actual behavior

Hi I'm trying to use the shift operation you recommend `bam.size() >> 30` however it doesn't seem to be working. I'm not sure I understand exactly what the right shift is doing. In the above example is it just dividing the `bam.size()` by 30?

Below is an examle I tried running on the Nextflow REPL console
Expected behaviour should return 50GB
Actual behaviour get an error 

### Program output 

```
groovy.lang.MissingMethodException: No signature of method: java.lang.Integer.rightShift() is applicable for argument types: (nextflow.util.MemoryUnit) values: [50 GB]
Possible solutions: rightShift(java.lang.Number), leftShift(java.lang.Number)
	at ConsoleScript11.run(ConsoleScript11:2)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

### Steps to reproduce the problem
```nextflow
bamSize = 5
bamSize >> 5 * 10.GB
```

### Environment 

* Nextflow version: [18.11.0-edge.5016] 
* Java version: [?]
* Operating system: [macOS]

@pditommaso Any help would be much appreciated, thanks in advance
