### ISSUE TITLE
SLURM "Failed to submit" error when jobs were successfully submitted

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#970]
### Expected behavior and actual behavior

Expected: Tasks are submitted as sbatch jobs to the SLURM cluster

Actual: Sporadically, Nextflow reports that tasks failed to submit to the cluster, despite the tasks actually being submitted and completing successfullly

### Steps to reproduce the problem

Not possible to reproduce the problem manually, it happens randomly during (long) pipeline execution.

### Program output 

Nextflow stdout messages:
```
[f4/92c717] NOTE: Error submitting process 'eval_pair_vcf (SampleID.MuTect2)' for execution -- Execution is retried (1)
ERROR ~ Error executing process > 'eval_pair_vcf (SampleID.MuTect2)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch job submission failed: Socket timed out on send/recv operation

Work dir:
  /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
WARN: Killing pending tasks (9)
WARN: [SLURM] queue (cpu_medium) status cannot be fetched > exit status: 1
```

section from `.nextflow.log`

```

Dec-13 08:57:52.263 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor slurm > tasks to be completed: 10 -- pending tasks are shown below
~> TaskHandler[jobId: 541317; id: 141; name: fastqc (SampleID1); status: SUBMITTED; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/0c/55355a669fb71db5592d41b1ddde38 started: -; exited: -; ]
~> TaskHandler[jobId: 541323; id: 147; name: samtools_flagstat (SampleID2); status: SUBMITTED; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/c6/f5d4dbe2b8d0792dc152d527180d08 started: -; exited: -; ]
~> TaskHandler[jobId: 541352; id: 174; name: gatk_AnalyzeCovariates (NTC-2-H2O); status: SUBMITTED; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/cf/7e607c5a85ee83ccc98b4a96926c97 started: -; exited: -; ]
~> TaskHandler[jobId: 542110; id: 449; name: gatk_CallableLoci (SampleID3); status: SUBMITTED; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/d0/dc3178bd916cc05cbdde8e6ccb2de6 started: -; exited: -; ]
~> TaskHandler[jobId: 542111; id: 450; name: qc_target_reads_gatk_pad500 (SampleID3.pad500); status: SUBMITTED; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/ee/e59982e5925dda309e9e27cc94ffac started: -; exited: -; ]
~> TaskHandler[jobId: 543491; id: 1141; name: mutect2 (SampleID4.chr1.MuTect2); status: RUNNING; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/04/84b348954caff88de62c981d63fb3d started: 1544694263985; exited: -; ]
~> TaskHandler[jobId: 543592; id: 1241; name: mutect2 (SampleID5.chr1.MuTect2); status: RUNNING; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/d2/2c99b059c637b517be4f6666655180 started: 1544699679977; exited: -; ]
~> TaskHandler[jobId: 543598; id: 1252; name: mutect2 (SampleID5.chr17.MuTect2); status: RUNNING; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/b0/7c9c8766f7450243d4febfa0eafc4b started: 1544699880042; exited: -; ]
~> TaskHandler[jobId: 543614; id: 1262; name: mutect2 (SampleID5.chr6.MuTect2); status: RUNNING; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/0a/eac462157a8f3d5049cb8a90259a3f started: 1544700465095; exited: -; ]
~> TaskHandler[jobId: 543629; id: 1282; name: mutect2 (SampleID6.chr12.MuTect2); status: RUNNING; exit: -; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/36/a18b183ef9e68503f5b55febb6e9ff started: 1544701940325; exited: -; ]
Dec-13 08:58:12.278 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 543629; id: 1282; name: mutect2 (SampleID6.chr12.MuTect2); status: COMPLETED; exit: 0; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/36/a18b183ef9e68503f5b55febb6e9ff started: 1544701940325; exited: 2018-12-13T13:58:09.277641Z; ]
Dec-13 08:58:12.359 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SLURM] submitted process eval_pair_vcf (SampleID6.chr12.MuTect2) > jobId: 545028; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/e1/c1f51ef137fb4800bc02c2676b6618
Dec-13 08:58:12.359 [Task submitter] INFO  nextflow.Session - [e1/c1f51e] Submitted process > eval_pair_vcf (SampleID6.chr12.MuTect2)
Dec-13 09:02:12.331 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 543598; id: 1252; name: mutect2 (SampleID5.chr17.MuTect2); status: COMPLETED; exit: 0; error: -; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/b0/7c9c8766f7450243d4febfa0eafc4b started: 1544699880042; exited: 2018-12-13T14:02:10.15151Z; ]
Dec-13 09:02:22.391 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - Failed to submit process eval_pair_vcf (SampleID5.chr17.MuTect2) > exit: 1; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f4/92c71756c2e1364a97072dc57ec529
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation


Dec-13 09:02:22.392 [Task submitter] INFO  nextflow.processor.TaskProcessor - [f4/92c717] NOTE: Error submitting process 'eval_pair_vcf (SampleID5.chr17.MuTect2)' for execution -- Execution is retried (1)
Dec-13 09:02:32.430 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - Failed to submit process eval_pair_vcf (SampleID5.chr17.MuTect2) > exit: 1; workDir: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation


Dec-13 09:02:32.523 [Task submitter] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'eval_pair_vcf (SampleID5.chr17.MuTect2)' -- Cause: java.nio.file.NoSuchFileException: /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1/.command.log
Dec-13 09:02:32.524 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'eval_pair_vcf (SampleID5.chr17.MuTect2)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch job submission failed: Socket timed out on send/recv operation

Work dir:
  /gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
Dec-13 09:02:32.539 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: Error submitting process 'eval_pair_vcf (SampleID5.chr17.MuTect2)' for execution
Dec-13 09:02:32.554 [Task submitter] DEBUG nextflow.Session - The following nodes are still active:
[process] samtools_flagstat_table
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] update_coverage_tables
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] eval_pair_vcf
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] annotate_pairs
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] collect_annotation_tables
  status=ACTIVE
  port 0: (value) OPEN  ; channel: t*
  port 1: (cntrl) -     ; channel: $

[process] callable_loci_table
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] calculate_tmb
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] custom_analysis_report
  status=ACTIVE
  port 0: (value) OPEN  ; channel: items
  port 1: (queue) OPEN  ; channel: -
  port 2: (cntrl) -     ; channel: $

[process] custom_sample_report
  status=ACTIVE
  port 0: (value) OPEN  ; channel: items
  port 1: (queue) OPEN  ; channel: -
  port 2: (cntrl) -     ; channel: $

[process] multiqc
  status=ACTIVE
  port 0: (value) OPEN  ; channel: all_vals
  port 1: (queue) OPEN  ; channel: output_dir
  port 2: (cntrl) -     ; channel: $

Dec-13 09:02:32.556 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Dec-13 09:02:32.557 [main] DEBUG nextflow.Session - Session await > all process finished
Dec-13 09:02:32.558 [main] DEBUG nextflow.Session - Session await > all barriers passed
Dec-13 09:02:32.585 [Actor Thread 2691] DEBUG nextflow.file.SortFileCollector - FileCollector temp dir not removed: null
Dec-13 09:02:32.660 [Actor Thread 2686] DEBUG nextflow.sort.BigSort - Sort completed -- entries: 27; slices: 1; internal sort time: 0.1 s; external sort time: 0.001 s; total time: 0.101 s
Dec-13 09:02:32.674 [Actor Thread 2686] DEBUG nextflow.file.FileCollector - Saved collect-files list to: /tmp/1805e9766f8faf0c93808aee5ebcbd7d.collect-file
Dec-13 09:02:32.676 [Actor Thread 2686] DEBUG nextflow.file.FileCollector - Deleting file collector temp dir: /tmp/nxf-7617786495365134702
Dec-13 09:02:32.680 [Actor Thread 2689] DEBUG nextflow.sort.BigSort - Sort completed -- entries: 262; slices: 1; internal sort time: 0.075 s; external sort time: 0.019 s; total time: 0.094 s
Dec-13 09:02:32.764 [Actor Thread 2689] DEBUG nextflow.file.FileCollector - Saved collect-files list to: /tmp/c3e9340285543cc64aff8277510b25d5.collect-file
Dec-13 09:02:32.778 [Actor Thread 2689] DEBUG nextflow.file.FileCollector - Deleting file collector temp dir: /tmp/nxf-1596197134643021174
Dec-13 09:02:32.782 [Actor Thread 2682] DEBUG nextflow.sort.BigSort - Sort completed -- entries: 83; slices: 1; internal sort time: 0.197 s; external sort time: 0.003 s; total time: 0.2 s
Dec-13 09:02:32.828 [Actor Thread 2682] DEBUG nextflow.file.FileCollector - Saved collect-files list to: /tmp/7925d62d2e1e1837eefa3f42086512f6.collect-file
Dec-13 09:02:32.832 [Actor Thread 2682] DEBUG nextflow.file.FileCollector - Deleting file collector temp dir: /tmp/nxf-4599005268754770488
Dec-13 09:02:32.858 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (9)
Dec-13 09:02:37.400 [Task monitor] WARN  n.executor.AbstractGridExecutor - [SLURM] queue (cpu_medium) status cannot be fetched > exit status: 1

Dec-13 09:02:37.401 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: slurm)
Dec-13 09:02:42.905 [main] DEBUG nextflow.Session - Failed to execute shutdown hook:
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'BatchCleanup[
' with class 'java.lang.String' to class 'java.lang.StringBuilder'
 at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:414)
 at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:328)
 at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:242)
 at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:617)
 at nextflow.executor.BatchCleanup.toString(BatchCleanup.groovy:112)
 at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:659)
 at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:148)
 at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:547)
 at groovy.lang.GString.writeTo(GString.java:197)
 at groovy.lang.GString.toString(GString.java:153)
 at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:55)
 at nextflow.processor.TaskPollingMonitor.cleanup(TaskPollingMonitor.groovy:664)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
 at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
 at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
 at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
 at nextflow.processor.TaskPollingMonitor$_start_closure1.doCall(TaskPollingMonitor.groovy:297)
 at nextflow.processor.TaskPollingMonitor$_start_closure1.call(TaskPollingMonitor.groovy)
 at nextflow.Session.shutdown0(Session.groovy:647)
 at nextflow.Session.destroy(Session.groovy:602)
 at nextflow.script.ScriptRunner.terminate(ScriptRunner.groovy:383)
 at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:166)
 at nextflow.cli.CmdRun.run(CmdRun.groovy:240)
 at nextflow.cli.Launcher.run(Launcher.groovy:428)
 at nextflow.cli.Launcher.main(Launcher.groovy:586)
Dec-13 09:02:42.907 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=1630; failedCount=14; ignoredCount=0; cachedCount=0; succeedDuration=64d 23h 21m 11s; failedDuration=0ms; cachedDuration=0ms]
Dec-13 09:02:42.907 [main] DEBUG nextflow.trace.TraceFileObserver - Flow completing -- flushing trace file
Dec-13 09:02:42.959 [main] DEBUG nextflow.trace.ReportObserver - Flow completing -- rendering html report
```

**However**, the task in question that was reported as failing to submit actually did submit successfully, and even completed successfully too:

```


kellys04@bigpurple-ln4:/gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1$ lt
total 356K
drwx--S--- 14 kellys04 8.0K Dec 13 09:02 ..
-rw-------  1 kellys04  243 Dec 13 09:02 .command.sh
-rw-------  1 kellys04 3.5K Dec 13 09:02 .command.stub
-rw-------  1 kellys04 5.8K Dec 13 09:02 .command.run
-rw-------  1 kellys04    0 Dec 13 09:02 .command.begin
-rw-------  1 kellys04 5.9K Dec 13 09:02 .env.begin
-rw-------  1 kellys04  272 Dec 13 09:15 .command.out
-rw-------  1 kellys04 4.9K Dec 13 09:15 .command.err
-rw-------  1 kellys04  16K Dec 13 09:15 SampleID.MuTect2.eval.grp
-rw-------  1 kellys04  204 Dec 13 09:15 .command.trace
-rw-------  1 kellys04 5.5K Dec 13 09:15 .command.log
drwx--S---  2 kellys04 8.0K Dec 13 09:15 .
-rw-------  1 kellys04    1 Dec 13 09:15 .exitcode

[2018-12-13 11:52:24]
kellys04@bigpurple-ln4:/gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1$ cat .exitcode
0
[2018-12-13 11:52:54]
kellys04@bigpurple-ln4:/gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1$ head .command.log
USER:kellys04 SLURM_JOB_ID:545799 SLURM_JOB_NAME:nf-eval_pair_vcf_(SampleID.MuTect2) HOSTNAME:cn-0030 PWD:/gpfs/data/molecpathlab/production/NGS580/180316_NB501073_0036_AH3VFKBGX5/work/f7/55e93e2adce10c298b177ba56dfea1 NTHREADS:none
nxf-scratch-dir cn-0030:/tmp/nxf.4LyRxSmCip
INFO  14:02:57,419 HelpFormatter - ----------------------------------------------------------------------------------
INFO  14:02:57,422 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 2017/07/28 21:26:50
INFO  14:02:57,422 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute
INFO  14:02:57,423 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk
INFO  14:02:57,423 HelpFormatter - [Thu Dec 13 14:02:57 UTC 2018] Executing on Linux 3.10.0-693.17.1.el7.x86_64 amd64
INFO  14:02:57,423 HelpFormatter - OpenJDK 64-Bit Server VM 1.8.0_102-8u102-b14.1-1~bpo8+1-b14
INFO  14:02:57,426 HelpFormatter - Program Args: -T VariantEval -R genome.fa -o SampleID.MuTect2.eval.grp --dbsnp dbsnp_138.hg19.vcf --eval SampleID.MuTect2.filtered.vcf
INFO  14:02:57,438 HelpFormatter - Executing as kellys04@cn-0030 on Linux 3.10.0-693.17.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_102-8u102-b14.1-1~bpo8+1-b14.

```

### Environment 

* Nextflow version: version 18.10.1 build 5003

* Java version: 
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)
```

* Operating system: RHEL 7

* SLURM version: `slurm 17.11.7`

### Additional context

(Add any other context about the problem here)

**Comment by stevekm** [comment]
Is there a recommended way to deal with this error inside Nextflow? I think right now it just considers it a failed task and can retry it (?), but could it instead be set to detect that the task did not actually fail, instead the job failed to submit.

**Comment by pditommaso** [comment]
Unfortunately currently if job submission fails the execution it is stop. I agree that this should be handled as a job error and using a exponential backoff delay as suggested in #721. I'm closing this issue in favour of the latter.

**Comment by stevekm** [comment]
Thanks for the update. For anyone that finds this issue, the error stopped occurring after our admins tweaked the SLURM scheduler to allow more time for scheduling jobs, however this resulted in the issues reported in #981 instead
