### ISSUE TITLE
Interpolated strings in a from statement are misinterpreted

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#978]
### Expected behavior and actual behavior

Error is reported when running pipeline with `-resume`; 

```
[44/880c5b] Cached process > delly2 (...)
[5b/02da83] Cached process > sambamba_dedup (...)
[c4/4c5aa6] Cached process > gatk_BaseRecalibratorBQSR (...)
ERROR ~ Cannot get property 'outputDir' on null object

 -- Check script 'main.nf' at line: 2192 or see '.nextflow.log' file for more details
[06/466330] Cached process > delly2 (...)
[c5/2aedbe] Cached process > gatk_PrintReads (...)
[bd/5a9e77] Cached process > gatk_BaseRecalibratorBQSR (...)
```

### Steps to reproduce the problem

The error seems to reference this section of the pipeline:

```
process multiqc {
    // automatic reporting based on detected output; might take a while to parse and create report
    publishDir "${params.outputDir}/analysis/qc", overwrite: true // , mode: 'copy'

    input:
    val(all_vals) from all_done2.collect()
    file(output_dir) from Channel.fromPath("${params.outputDir}")

    output:
    file "multiqc_report.html" // into email_files
    file "multiqc_data"

    when:
    disable_multiqc != true

    script:
    """
    multiqc "${output_dir}"
    """
}

```

The weird thing is that `params.outputDir` is referenced in many places throughout the pipeline, but it only reports an error at this section, and only when running with `-resume`

### Program output 

```
Dec-18 10:15:59.739 [PathVisitor-3] ERROR nextflow.Channel - Cannot get property 'outputDir' on null object
java.lang.NullPointerException: Cannot get property 'outputDir' on null object
        at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGetProperty(GetEffectivePogoPropertySite.java:45)
        at _nf_script_121eedc3$_run_closure117$_closure442.doCall(_nf_script_121eedc3:2192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.GString.writeTo(GString.java:189)
        at groovy.lang.GString.toString(GString.java:153)
        at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:55)
        at nextflow.extension.Bolts.asType(Bolts.groovy:474)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:182)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:605)
        at nextflow.file.PathVisitor.apply(PathVisitor.groovy:69)
        at nextflow.file.PathVisitor$_applyAsync_closure1.doCall(PathVisitor.groovy:75)
        at nextflow.file.PathVisitor$_applyAsync_closure1.call(PathVisitor.groovy)
        at groovy.lang.Closure.run(Closure.java:492)
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

### Environment 

* Nextflow version: 18.10.1
* Java version:

```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)
```

* Operating system: RHEL 7

**Comment by pditommaso** [comment]
umm, `Channel.fromPath("${params.outputDir}")` is suspicious. It should be `Channel.fromPath(params.outputDir)` (why string interpolation?).

**Comment by stevekm** [comment]
Sorry the string interpolation is just a habit I guess, I changed it to create the channel outside of the process like normal instead and that fixed it. `params.outputDir` is a string so I was not aware that interpolation of it inside the process while creating the channel was bad. Not sure what's going on under the hood with processes but it seemed like `Channel.fromPath("${params.outputDir}")` was being evaluated in a different environment than the parent script?

**Comment by pditommaso** [comment]
In principle it should. However I was not able to replicate the issue to debug it. If you are to isolate it, re-open the issue including a non-working example.

**Comment by pditommaso** [comment]
The issue can be replicated by this snippet 

```
foo = 1

process foo {
  input:
  val x from "$foo"
  
  script:
  """
  echo $x
  """
}
```
