### ISSUE TITLE
TraceFileObsever throws an exception when access task context metadata on task completion

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#98]
When declaring dynamic directives in the configuration file that access to task runtime properties as shown below: 

    process {
        container = { "grape/mapping:${task.tool.toLowerCase()}-${task.version}" }
    }

and the script is run with *trace* feature enabled, an exception similar to the following one is thrown:
 
    ERROR nextflow.processor.TaskDispatcher - No signature of method: groovy.util.ConfigObject.toLowerCase() is applicable for argument types: () values: []
    groovy.lang.MissingMethodException: No signature of method: groovy.util.ConfigObject.toLowerCase() is applicable for argument types: () values: []
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58) ~[groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:52) ~[groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-2.4.5.jar:2.4.5]
        at nextflow$_run_closure2$_closure8$_closure10.doCall(nextflow.config:30) ~[na:na]
        at nextflow$_run_closure2$_closure8$_closure10.doCall(nextflow.config) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.5.jar:2.4.5]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) [groovy-2.4.5.jar:2.4.5]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.5.jar:2.4.5]
        at groovy.lang.Closure.call(Closure.java:426) [groovy-2.4.5.jar:2.4.5]
        at groovy.lang.Closure.call(Closure.java:420) [groovy-2.4.5.jar:2.4.5]
        at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy:423) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.LazyMap.resolve(TaskConfig.groovy:383) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.LazyMap.get(TaskConfig.groovy:447) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.TaskConfig.get(TaskConfig.groovy:81) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.TaskConfig.getProperty(TaskConfig.groovy:76) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50) ~[groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307) [groovy-2.4.5.jar:2.4.5]
        at nextflow.processor.TaskRun.isContainerExecutable(TaskRun.groovy:526) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.TaskRun.getContainer(TaskRun.groovy:495) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.5.jar:2.4.5]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76) ~[groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGroovyObjectGetProperty(GetEffectivePogoPropertySite.java:68) ~[groovy-2.4.5.jar:2.4.5]
        at nextflow.processor.TaskHandler.getTraceRecord(TaskHandler.groovy:147) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.trace.TraceFileObserver.onProcessComplete(TraceFileObserver.groovy:266) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.trace.TraceObserver$onProcessComplete$1.call(Unknown Source) ~[na:na]
        at nextflow.processor.TaskDispatcher.notifyComplete(TaskDispatcher.groovy:206) ~[nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.TaskDispatcher$notifyComplete$5.call(Unknown Source) [nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.TaskPollingMonitor.checkTaskStatus(TaskPollingMonitor.groovy:473) [nextflow-0.16.6-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166) [groovy-2.4.5.jar:2.4.5]
        at nextflow.processor.TaskPollingMonitor.checkAllTasks(TaskPollingMonitor.groovy:382) [nextflow-0.16.6-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158) [groovy-2.4.5.jar:2.4.5]
        at nextflow.processor.TaskPollingMonitor.pollLoop(TaskPollingMonitor.groovy:330) [nextflow-0.16.6-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.5.jar:2.4.5]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384) [groovy-2.4.5.jar:2.4.5]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154) [groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158) [groovy-2.4.5.jar:2.4.5]
        at nextflow.processor.TaskPollingMonitor$_start_closure8.doCall(TaskPollingMonitor.groovy:306) [nextflow-0.16.6-SNAPSHOT.jar:na]
        at nextflow.processor.TaskPollingMonitor$_start_closure8.doCall(TaskPollingMonitor.groovy) [nextflow-0.16.6-SNAPSHOT.jar:na]
        :

**Comment by pditommaso** [comment]
Fixed in version `0.17.0`
